class DKUpgrade_Skill_MementoMori extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Memento Mori: "Remember, you must die." Each wave survived strengthens the Reaper's
// connection to the afterlife. Permanent max health gain at wave end:
// +HealPerWave max HP per wave survived this life (resets on death).

var config array<int> HealPerWave;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HealPerWave[0] = 2;
		default.HealPerWave[1] = 4;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function WaveEnd(int upgLevel, KFPlayerController KFPC)
{
	local DKUpgrade_Skill_MementoMori_Helper UPG;
	local WMPerk WMP;
	local int Gain;

	if (KFPC != None && KFPC.Pawn != None && KFPC.Pawn.Health > 0)
	{
		UPG = GetHelper(KFPawn(KFPC.Pawn));
		if (UPG != None)
		{
			UPG.IncrementWave();

			// DK FIX: converted from a wave-end heal to a PERMANENT max
			// health stack. The stack lives on the pawn-owned helper and is
			// applied inside DKPerk.ModifyHealth, so it survives every ZR
			// health recompute and resets naturally on death.
			Gain = default.HealPerWave[upgLevel - 1];
			UPG.PermanentHealthBonus += Gain;

			// Recompute max health now (includes the new stack), then grant
			// the gained HP so current health rises with the cap.
			WMP = WMPerk(KFPC.CurrentPerk);
			if (WMP != None)
			{
				WMP.ModifyHealth(KFPC.Pawn.HealthMax);
				KFPC.Pawn.Health = Min(KFPC.Pawn.Health + Gain, KFPC.Pawn.HealthMax);
			}
		}
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_MementoMori_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_MementoMori_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_MementoMori_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_MementoMori_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_MementoMori_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_MementoMori_Helper', UPG)
		{
			return UPG;
		}

		UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_MementoMori_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_MementoMori_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_MementoMori_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_MementoMori]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_MementoMori"

	UpgradeName="Memento Mori"
	UpgradeDescription(0)="<font color=\"#CC0000\">Memento Mori:</font> Gain <font color=\"#FFFFFF\">+2 permanent Max Health</font> at the end of every <font color=\"#FFAA00\">wave survived</font>. <font color=\"#66FF66\">Stacks each wave</font>; resets on death."
	UpgradeDescription(1)="<font color=\"#CC0000\">Memento Mori:</font> Gain <font color=\"#FFFFFF\">+4 permanent Max Health</font> at the end of every <font color=\"#FFAA00\">wave survived</font>. <font color=\"#66FF66\">Stacks each wave</font>; resets on death."

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_MementoMori'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_MementoMori_Deluxe'

	Name="Default__DKUpgrade_Skill_MementoMori"
}
