class DKUpgrade_Skill_NoSurrender extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// No Surrender
// Below critical HP threshold: melee kills heal and you gain massive damage resistance
// Normal: below 5% HP, Deluxe: below 10% HP

var config array<float> HPThreshold;       // 0.05 and 0.10
var config array<int> HealPerKill;         // HP healed per melee kill while below threshold
var config array<float> Resistance;        // Damage resistance while below threshold
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HPThreshold[0] = 0.05f;
		default.HPThreshold[1] = 0.10f;
		default.HealPerKill[0] = 25;
		default.HealPerKill[1] = 40;
		default.Resistance[0] = 0.50f;
		default.Resistance[1] = 0.70f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	if (OwnerPawn != None && OwnerPawn.Health > 0 && OwnerPawn.Health <= int(float(OwnerPawn.HealthMax) * default.HPThreshold[upgLevel - 1]))
	{
		InDamage -= Round(float(DefaultDamage) * default.Resistance[upgLevel - 1]);
		if (InDamage < 1)
			InDamage = 1;
	}
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (DamageType != None && static.IsMeleeDamageType(DamageType)
		&& MyKFPM != None && MyKFPM.IsAliveAndWell() && (MyKFPM.Health - InDamage) <= 0
		&& DamageInstigator != None && DamageInstigator.Pawn != None
		&& DamageInstigator.Pawn.Health > 0
		&& DamageInstigator.Pawn.Health <= int(float(DamageInstigator.Pawn.HealthMax) * default.HPThreshold[upgLevel - 1]))
	{
		// Melee kill while below threshold: heal
		DamageInstigator.Pawn.HealDamage(default.HealPerKill[upgLevel - 1], DamageInstigator, class'KFDT_Healing');
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_NoSurrender]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_NoSurrender"

	UpgradeName="No Surrender"

	UpgradeDescription(0)="<font color=\"#edb82a\">No Surrender</font> When below <font color=\"#DC143C\">5% HP</font>:  <font color=\"#4169E1\">+50% Damage Resistance</font>  Melee kills <font color=\"#32CD32\">heal 25 HP</font> <font color=\"#AAAAAA\">They'll have to kill you twice.</font>"
	UpgradeDescription(1)="<font color=\"#edb82a\">No Surrender</font> When below <font color=\"#DC143C\">10% HP</font>:  <font color=\"#4169E1\">+70% Damage Resistance</font>  Melee kills <font color=\"#32CD32\">heal 40 HP</font> <font color=\"#AAAAAA\">They'll have to kill you twice.</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_NoSurrender'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_NoSurrender_Deluxe'

	Name="Default__DKUpgrade_Skill_NoSurrender"
}
