class DKUpgrade_Skill_CascadingMassacre extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DamagePerStack;
var config int MaxStacks;
var config float StackDuration;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamagePerStack[0] = 0.08f;
		default.DamagePerStack[1] = 0.15f;
		default.MaxStacks = 5;
		default.StackDuration = 2.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_CascadingMassacre_Helper UPG;
    local int CurrentStacks;
    
    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;
    
    UPG = GetHelper(DamageInstigator.Pawn);
    if (UPG == None)
        return;
    
    // Apply damage bonus based on current stacks
    CurrentStacks = UPG.GetCurrentStacks();
    if (CurrentStacks > 0)
    {
        InDamage += Round(float(DefaultDamage) * default.DamagePerStack[upgLevel - 1] * float(CurrentStacks));
    }
    
    // Check if this will kill and track it
    if (MyKFPM != None && MyKFPM.IsAliveAndWell() && (MyKFPM.Health - InDamage) <= 0)
    {
        UPG.RegisterKill();
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_CascadingMassacre_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CascadingMassacre_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_CascadingMassacre_Helper', OwnerPawn);
            UPG.StackDuration = default.StackDuration;
            UPG.MaxStacks = default.MaxStacks;
        }
    }
}

static function DKUpgrade_Skill_CascadingMassacre_Helper GetHelper(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_CascadingMassacre_Helper UPG;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CascadingMassacre_Helper', UPG)
        {
            return UPG;
        }

        // Should have one
        UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_CascadingMassacre_Helper', OwnerPawn);
    }

    return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_CascadingMassacre_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CascadingMassacre_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_CascadingMassacre]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_CascadingMassacre"

    UpgradeName="Cascading Massacre"
    upgradeDescription(0)="Kills within <font color=\"#ffff00\">2 seconds</font> deal <font color=\"#66cc00\">escalating damage</font>: <font color=\"#ff3399\">+8%</font> per stack (max <font color=\"#ff3399\">5</font>, up to <font color=\"#ff3399\">+40%</font>)."
    upgradeDescription(1)="Kills within <font color=\"#ffff00\">2 seconds</font> deal <font color=\"#66cc00\">escalating damage</font>: <font color=\"#ff3399\">+15%</font> per stack (max <font color=\"#ff3399\">5</font>, up to <font color=\"#ff3399\">+75%</font>)."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CascadingMassacre'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CascadingMassacre_Deluxe'

    Name="Default__DKUpgrade_Skill_CascadingMassacre"
}
