class DKUpgrade_Skill_LastBreath extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Last Breath: When your health drops below a critical threshold, gain a massive
// temporary damage boost. Once per wave cooldown. A desperate last stand mechanic.

var config array<float> DamageBonus;
var config array<float> HealthThreshold;
var config array<float> BuffDuration;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageBonus[0] = 0.50f;
		default.DamageBonus[1] = 1.00f;
		default.HealthThreshold[0] = 0.30f;
		default.HealthThreshold[1] = 0.40f;
		default.BuffDuration[0] = 8.0f;
		default.BuffDuration[1] = 10.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_LastBreath_Helper UPG;

	if (OwnerPawn != None)
	{
		UPG = GetHelper(OwnerPawn);
		if (UPG != None && !UPG.bUsedThisWave && !UPG.bBuffActive)
		{
			// Check if this damage would bring us below threshold
			if (float(OwnerPawn.Health - InDamage) / float(OwnerPawn.HealthMax) <= default.HealthThreshold[upgLevel - 1])
				UPG.ActivateBuff(default.BuffDuration[upgLevel - 1]);
		}
	}
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_LastBreath_Helper UPG;

	if (DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		UPG = GetHelper(KFPawn(DamageInstigator.Pawn));
		if (UPG != None && UPG.bBuffActive)
			InDamage += Round(float(DefaultDamage) * default.DamageBonus[upgLevel - 1]);
	}
}

static function WaveEnd(int upgLevel, KFPlayerController KFPC)
{
	local DKUpgrade_Skill_LastBreath_Helper UPG;

	if (KFPC != None && KFPC.Pawn != None)
	{
		UPG = GetHelper(KFPawn(KFPC.Pawn));
		if (UPG != None)
			UPG.ResetForNewWave();
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_LastBreath_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_LastBreath_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_LastBreath_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_LastBreath_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_LastBreath_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_LastBreath_Helper', UPG)
		{
			return UPG;
		}

		UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_LastBreath_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_LastBreath_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_LastBreath_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_LastBreath]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_LastBreath"

	UpgradeName="Last Breath"
	UpgradeDescription(0)="<font color=\"#CC0000\">Last Breath:</font> When health drops below <font color=\"#FFFFFF\">30%</font>, gain <font color=\"#FFFFFF\">+50%</font> <font color=\"#FFD700\">damage</font> for <font color=\"#FFAA00\">8 seconds</font>. <font color=\"#666666\">Once per wave.</font>"
	UpgradeDescription(1)="<font color=\"#CC0000\">Last Breath:</font> When health drops below <font color=\"#FFFFFF\">40%</font>, gain <font color=\"#FFFFFF\">+100%</font> <font color=\"#FFD700\">damage</font> for <font color=\"#FFAA00\">10 seconds</font>. <font color=\"#666666\">Once per wave.</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_LastBreath'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_LastBreath_Deluxe'

	Name="Default__DKUpgrade_Skill_LastBreath"
}
