// Phoenix Prayer
// Healing allies accumulates divine favor, converted to bonus dosh at wave end
// Standard: 25% of HP healed → bonus dosh at wave end
// Deluxe: 50% of HP healed → bonus dosh at wave end
class DKUpgrade_Skill_PhoenixPrayer extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DoshConversion;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DoshConversion[0] = 0.25f;
		default.DoshConversion[1] = 0.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function HealingDamage(int upgLevel, int HealAmount, KFPawn HealedPawn, KFPawn InstigatorPawn, class<DamageType> DamageType)
{
	local DKUpgrade_Skill_PhoenixPrayer_Helper UPG;

	if (HealedPawn != None && InstigatorPawn != None && HealAmount > 0
		&& HealedPawn != InstigatorPawn && HealedPawn.GetHealthPercentage() < 1.0f)
	{
		UPG = GetHelper(InstigatorPawn);
		if (UPG != None)
			UPG.AddHealedHealth(Min(HealAmount, HealedPawn.HealthMax - HealedPawn.Health));
	}
}

static function WaveEnd(int upgLevel, KFPlayerController KFPC)
{
	local DKUpgrade_Skill_PhoenixPrayer_Helper UPG;
	local int BonusDosh;

	if (KFPC != None && KFPC.Pawn != None && KFPC.Pawn.IsAliveAndWell())
	{
		UPG = GetHelper(KFPawn(KFPC.Pawn));
		if (UPG != None)
		{
			BonusDosh = Round(float(UPG.HealthCounter) * default.DoshConversion[upgLevel - 1]);
			if (BonusDosh > 0 && KFPC.PlayerReplicationInfo != None)
				KFPlayerReplicationInfo(KFPC.PlayerReplicationInfo).AddDosh(BonusDosh, True);

			UPG.HealthCounter = 0;
		}
	}
}

static function DKUpgrade_Skill_PhoenixPrayer_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_PhoenixPrayer_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_PhoenixPrayer_Helper', UPG)
		{
			return UPG;
		}

		// Should have one
		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_PhoenixPrayer_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_PhoenixPrayer_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_PhoenixPrayer_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_PhoenixPrayer]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_PhoenixPrayer"

	UpgradeName="Phoenix Prayer"
	UpgradeDescription(0)="Healing allies accumulates divine favor. At wave end, <font color=\"#eeeeff\">25%</font> of HP healed is converted to <font color=\"#ffd700\">bonus dosh</font>"
	UpgradeDescription(1)="<font color=\"#ffd700\">Deluxe.</font> Healing allies accumulates divine favor. At wave end, <font color=\"#eeeeff\">50%</font> of HP healed is converted to <font color=\"#ffd700\">bonus dosh</font>"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PhoenixPrayer'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PhoenixPrayer_Deluxe'

	Name="Default__DKUpgrade_Skill_PhoenixPrayer"
}
