// ===================================================================
// DKUpgrade_Skill_RoyalFlush - Gambit Skill
//
// "Royal Flush" - Every Nth gambit completion triggers a ROYAL FLUSH,
// tripling the reward with a special sound effect.
//
// Standard: Every 5th completion.
// Deluxe:   Every 3rd completion.
//
// Pure signal skill -- all logic lives in the Gambit Helper.
// ===================================================================
class DKUpgrade_Skill_RoyalFlush extends DKUpgrade_Skill;

// Signal presence to Gambit Helper via ExtensionFuncInteger
// Returns upgLevel (1=standard, 2=deluxe) when queried with "GambitRoyalFlush"
static simulated function ExtensionFuncInteger(out int InValue, int DefaultValue, int upgLevel, string Identifier,
    KFWeapon MyKFW, KFPawn OwnerPawn, optional int InputInt, optional float InputFloat, optional name InputClassName,
    optional Object InputObject1, optional Object InputObject2, optional Object InputObject3)
{
    if (Identifier ~= "GambitRoyalFlush")
        InValue = upgLevel;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_RoyalFlush]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_RoyalFlush"

    UpgradeName="Royal Flush"
    upgradeDescription(0)="Every <font color=\"#FFFFFF\">5th</font> gambit completion triggers a <font color=\"#FFD700\">Royal Flush</font>, tripling the reward."
    upgradeDescription(1)="Every <font color=\"#FFFFFF\">3rd</font> gambit completion triggers a <font color=\"#FFD700\">Royal Flush</font>, tripling the reward."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_RoyalFlush'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_RoyalFlush_Deluxe'

    Name="Default__DKUpgrade_Skill_RoyalFlush"
}
