// Venomweave: Damage reduction scales with the number of nearby poisoned ZEDs.
// More poisoned enemies around you = more tanky you become.
// Rewards aggressive positioning in the thick of poisoned groups.
class DKUpgrade_Skill_Venomweave extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Damage reduction per poisoned ZED stack
var config array<float> DRPerStack;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DRPerStack[0] = 0.05f;
		default.DRPerStack[1] = 0.07f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_Venomweave_Helper UPG;
	local float DR;

	if (InDamage > 0)
	{
		UPG = GetHelper(OwnerPawn, upgLevel);
		if (UPG != None && UPG.PoisonedCount > 0)
		{
			DR = float(UPG.PoisonedCount) * default.DRPerStack[upgLevel - 1];
			DR = FMin(DR, 0.50f); // Hard cap at 50% damage reduction
			InDamage -= Round(float(InDamage) * DR);
			if (InDamage < 1)
				InDamage = 1;
		}
	}
}

static function DKUpgrade_Skill_Venomweave_Helper GetHelper(KFPawn OwnerPawn, int upgLevel)
{
	local DKUpgrade_Skill_Venomweave_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Venomweave_Helper', UPG)
		{
			// Refresh tier so a mid-game Standard -> Deluxe upgrade takes effect;
			// radius/cap derive from bDeluxe, which was previously only set on spawn.
			UPG.bDeluxe = (upgLevel > 1);
			return UPG;
		}

		UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_Venomweave_Helper', OwnerPawn);
		UPG.bDeluxe = (upgLevel > 1);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_Venomweave_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Venomweave_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Venomweave]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Venomweave"

	// 5% per stack (L1) or 7% per stack (L2)

	UpgradeDescription(0)="Gain <font color=\"#399c0e\">5% damage reduction</font> for each nearby <font color=\"#8fce00\">Poisoned</font> ZED. Max 50%."
	UpgradeDescription(1)="Gain <font color=\"#b346ea\">7% damage reduction</font> for each nearby <font color=\"#8fce00\">Poisoned</font> ZED. Max 50%."

	UpgradeName="Venomweave"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Venomweave'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Venomweave_Deluxe'

	Name="Default__DKUpgrade_Skill_Venomweave"
}
