class DKUpgrade_Skill_Shockwave extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Every Nth melee kill triggers a shockwave that knocks down and damages nearby zeds

var config array<int> KillThreshold;       // Kills needed per shockwave (5 / 3)
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.KillThreshold[0] = 5;
		default.KillThreshold[1] = 3;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_Shockwave_Helper UPG;

	if (DamageType != None && static.IsMeleeDamageType(DamageType)
		&& MyKFPM != None && MyKFPM.IsAliveAndWell() && (MyKFPM.Health - InDamage) <= 0
		&& DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		UPG = GetHelper(KFPawn(DamageInstigator.Pawn));
		if (UPG != None)
		{
			UPG.RegisterKill();
			if (UPG.KillCount >= default.KillThreshold[upgLevel - 1])
			{
				UPG.TriggerShockwave(upgLevel > 1);
			}
		}
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_Shockwave_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Shockwave_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			OwnerPawn.Spawn(class'DKUpgrade_Skill_Shockwave_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_Shockwave_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_Shockwave_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Shockwave_Helper', UPG)
		{
			return UPG;
		}

		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_Shockwave_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_Shockwave_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Shockwave_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Shockwave]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Shockwave"

	UpgradeName="Shockwave"

	UpgradeDescription(0)="<font color=\"#edb82a\">Shockwave</font> Every <font color=\"#FFFFFF\">5th</font> melee kill triggers a <font color=\"#FF6347\">shockwave</font>. Knocks down and damages all zeds within <font color=\"#FFFFFF\">5 meters</font>. <font color=\"#AAAAAA\">The ground shakes with every massacre.</font>"
	UpgradeDescription(1)="<font color=\"#edb82a\">Shockwave</font> Every <font color=\"#FFFFFF\">3rd</font> melee kill triggers a <font color=\"#FF6347\">shockwave</font>. Knocks down and damages all zeds within <font color=\"#FFFFFF\">7 meters</font>. <font color=\"#AAAAAA\">The ground shakes with every massacre.</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Shockwave'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Shockwave_Deluxe'

	Name="Default__DKUpgrade_Skill_Shockwave"
}
