class DKUpgrade_Skill_Liftboy extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> Bonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Bonus[0] = 5;
		default.Bonus[1] = 10;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ApplyWeightLimits(out int InWeightLimit, int DefaultWeightLimit, int upgLevel)
{
	InWeightLimit += default.Bonus[upgLevel - 1];
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Liftboy]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Liftboy"

    UpgradeName="Liftboy"
	upgradeDescription(0)="Increase your <font color=\"#ff3399\">Weight Limit</font> by <font color=\"#66cc00\">5</font>."
	upgradeDescription(1)="Increase your <font color=\"#ff3399\">Weight Limit</font> by <font color=\"#66cc00\">10</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Liftboy'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Liftboy_Deluxe'
    Name="Default__DKUpgrade_Skill_Liftboy"
}