class DKUpgrade_Skill_HippocraticOath extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Healing;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Healing[0] = 0.5f;
		default.Healing[1] = 1.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyHealAmount(out float InHealAmount, float DefaultHealAmount, int upgLevel)
{
	InHealAmount += DefaultHealAmount * (default.Healing[upgLevel - 1]);
}

defaultproperties
{    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_HippocraticOath]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_HippocraticOath"

    UpgradeName="Hippocratic Oath"
	upgradeDescription(0)="Increase <font color=\"#ff3399\">Healing</font> by <font color=\"#66cc00\">50%</font>."
    upgradeDescription(1)="Increase <font color=\"#ff3399\">Healing</font> by <font color=\"#66cc00\">100%</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HippocraticOath'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HippocraticOath_Deluxe'
    Name="Default__DKUpgrade_Skill_HippocraticOath"
}