class DKUpgrade_Weapon_Ricochet extends DKUpgrade_Weapon
	abstract;

var float RicochetChance;

// Only pistols are compatible
static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	return ClassIsChildOf(KFW, class'KFWeap_PistolBase');
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local KFPawn_Monster NearbyZed;
	local float RicochetRoll;
	local int RicochetDamage;
	local array<KFPawn_Monster> PotentialTargets;
	local int i;
	
	// Only ricochet on killing blow and if we have a valid monster target
	if (MyKFPM != None && MyKFPM.Health <= InDamage)
	{
		RicochetRoll = FRand();
		if (RicochetRoll <= (default.RicochetChance * upgLevel))
		{
			RicochetDamage = Round(float(InDamage) * 0.6); // 60% damage
			
			// Find nearby enemies within 500 units
			foreach MyKFPM.CollidingActors(class'KFPawn_Monster', NearbyZed, 500.0)
			{
				if (NearbyZed != MyKFPM && NearbyZed.IsAliveAndWell())
				{
					PotentialTargets.AddItem(NearbyZed);
				}
			}
			
			// Damage up to 2 random nearby enemies
			for (i = 0; i < Min(2, PotentialTargets.Length); i++)
			{
				if (PotentialTargets.Length > 0)
				{
					NearbyZed = PotentialTargets[Rand(PotentialTargets.Length)];
					if (NearbyZed != None && NearbyZed.IsAliveAndWell())
					{
						NearbyZed.TakeDamage(RicochetDamage, DamageInstigator, 
						                   NearbyZed.Location, vect(0,0,0), DamageType);
						PotentialTargets.RemoveItem(NearbyZed);
					}
				}
			}
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Weapon_Ricochet]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Weapon_Ricochet"

	RicochetChance=0.15f
	UpgradeName="Ricochet"
    UpgradeDescription(0)="Your <font color=\"#15d7fa\">killing shots</font> have a <font color=\"#77d914\">%x%%</font> chance to <font color=\"#15d7fa\">ricochet</font> to two extra targets for <font color=\"#77d914\">60%</font> damage."
	WeaponBonus=(baseValue=0, incValue=15, maxValue=-1)
    
	Name="Default__DKUpgrade_Weapon_Ricochet"
}