// ===================================================================
// DKUpgrade_Skill_CrimsonBond - Share Your Vampirism
// Healing a teammate establishes a blood bond. While bonded, your
// life steal also heals the bonded ally for a percentage of the
// amount. Bonds to the most recently healed player.
//
// Standard: 10s bond, bonded ally receives 50% of your life steal
// Deluxe:   15s bond, bonded ally receives 100% of your life steal
//
// Implementation:
//   HealingDamage establishes the bond via helper
//   AddVampireHealth passes heal to bonded ally via helper
// ===================================================================
class DKUpgrade_Skill_CrimsonBond extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> BondDuration;
var config array<float> LifeStealShare;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.BondDuration[0] = 10.0f;
		default.BondDuration[1] = 15.0f;
		default.LifeStealShare[0] = 0.50f;
		default.LifeStealShare[1] = 1.00f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// ===================================================================
// On Heal: Establish blood bond with healed player
// ===================================================================
static function HealingDamage(int upgLevel, int HealAmount, KFPawn HealedPawn,
	KFPawn InstigatorPawn, class<DamageType> DamageType)
{
	local DKUpgrade_Skill_CrimsonBond_Helper Helper;

	// Don't bond to self
	if (InstigatorPawn == None || HealedPawn == None || InstigatorPawn == HealedPawn)
		return;

	if (KFPawn_Human(HealedPawn) == None || KFPawn_Human(InstigatorPawn) == None)
		return;

	Helper = GetHelper(InstigatorPawn);
	if (Helper != None)
		Helper.EstablishBond(KFPawn_Human(HealedPawn), default.BondDuration[upgLevel - 1]);
}

// ===================================================================
// On Life Steal: Share healing with bonded ally
// ===================================================================
static function AddVampireHealth(out int InHealth, int DefaultHealth, int upgLevel,
	KFPlayerController KFPC, class<DamageType> DT)
{
	local DKUpgrade_Skill_CrimsonBond_Helper Helper;
	local int SharedHeal;

	if (KFPC == None || KFPC.Pawn == None)
		return;

	Helper = GetHelper(KFPC.Pawn);
	if (Helper != None && Helper.BondedAlly != None && Helper.bBondActive)
	{
		// Calculate shared heal
		SharedHeal = Max(1, Round(float(InHealth) * default.LifeStealShare[upgLevel - 1]));

		// Heal bonded ally
		if (Helper.BondedAlly.Health > 0 && Helper.BondedAlly.IsAliveAndWell())
			Helper.BondedAlly.HealDamage(SharedHeal, KFPC, class'KFDT_Healing');
	}
}

// ===================================================================
// Helper Management
// ===================================================================
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_CrimsonBond_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CrimsonBond_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			OwnerPawn.Spawn(class'DKUpgrade_Skill_CrimsonBond_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_CrimsonBond_Helper GetHelper(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_CrimsonBond_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CrimsonBond_Helper', UPG)
			return UPG;

		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_CrimsonBond_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_CrimsonBond_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CrimsonBond_Helper', UPG)
			UPG.Destroy();
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_CrimsonBond]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_CrimsonBond"

	UpgradeName="Crimson Bond"
	UpgradeDescription(0)="<font color=\"#B40028\">Crimson Bond:</font> Healing a teammate creates a <font color=\"#FFFFFF\">10s</font> blood bond. Your life steal also heals bonded ally for <font color=\"#FFFFFF\">50%</font>"
	UpgradeDescription(1)="<font color=\"#FFD700\">[DELUXE]</font> <font color=\"#B40028\">Crimson Bond:</font> Healing a teammate creates a <font color=\"#FFFFFF\">15s</font> blood bond. Your life steal also heals bonded ally for <font color=\"#FFFFFF\">100%</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CrimsonBond'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CrimsonBond_Deluxe'

	Name="Default__DKUpgrade_Skill_CrimsonBond"
}
