class DKUpgrade_Skill_AmmoSiphon extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Every N hits on a zed, transfer 1 round from spare ammo directly into the magazine
// Rewards sustained fire and accuracy - reduces dependence on reloading
// Uses the MagicBullet helper pattern for reliable ammo manipulation

var config array<int> HitsRequired;  // Number of hits needed to trigger a siphon
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HitsRequired[0] = 8;
		default.HitsRequired[1] = 5;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_AmmoSiphon_Helper UPG;

	if (MyKFPM != None && DamageInstigator != None && DamageInstigator.Pawn != None && MyKFW != None)
	{
		UPG = GetHelper(DamageInstigator.Pawn);
		if (UPG != None)
		{
			// Only count one hit per frame (handles shotgun pellets / multi-hit)
			if (UPG.LastHitTime != UPG.Player.WorldInfo.TimeSeconds)
			{
				UPG.LastHitTime = UPG.Player.WorldInfo.TimeSeconds;
				UPG.HitCounter++;

				if (UPG.HitCounter >= default.HitsRequired[upgLevel - 1])
				{
					UPG.HitCounter = 0;

					// Transfer 1 round from spare to magazine
					if (UPG.Player.WorldInfo.NetMode == NM_Standalone)
						UPG.StandaloneUpdateAmmo(1);
					else
						UPG.ServerUpdateAmmo(1);
				}
			}
		}
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_AmmoSiphon_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_AmmoSiphon_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_AmmoSiphon_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_AmmoSiphon_Helper GetHelper(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_AmmoSiphon_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_AmmoSiphon_Helper', UPG)
		{
			return UPG;
		}

		// Should have one
		UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_AmmoSiphon_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_AmmoSiphon_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_AmmoSiphon_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_AmmoSiphon]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_AmmoSiphon"

	UpgradeName="Ammo Siphon"

	UpgradeDescription(0)="<font color=\"#DAA520\">Ammo Siphon:</font> Every <font color=\"#FFFFFF\">8 hits</font> transfers <font color=\"#87CEEB\">1 round</font> from spare ammo directly into your magazine"
	UpgradeDescription(1)="<font color=\"#FFD700\">Ammo Siphon:</font> Every <font color=\"#FFFFFF\">5 hits</font> transfers <font color=\"#87CEEB\">1 round</font> from spare ammo directly into your magazine"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AmmoSiphon'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AmmoSiphon_Deluxe'

	Name="Default__DKUpgrade_Skill_AmmoSiphon"
}
