// Triage Expert
// Healing allies refills your ammo over a cumulative HP threshold
// Standard: Every 50 HP healed triggers ammo refill
// Deluxe: Every 25 HP healed triggers ammo refill
class DKUpgrade_Skill_TriageExpert extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config float AmmoDivider;
var config array<int> HealthThreshold;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.AmmoDivider = 30.0f;
		default.HealthThreshold[0] = 50;
		default.HealthThreshold[1] = 25;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function HealingDamage(int upgLevel, int HealAmount, KFPawn HealedPawn, KFPawn InstigatorPawn, class<DamageType> DamageType)
{
	local DKUpgrade_Skill_TriageExpert_Helper UPG;

	if (HealedPawn != None && InstigatorPawn != None && HealAmount > 0
		&& HealedPawn != InstigatorPawn && HealedPawn.GetHealthPercentage() < 1.0f)
	{
		UPG = GetHelper(InstigatorPawn);
		if (UPG != None)
		{
			UPG.AddHealedHealth(Min(HealAmount, HealedPawn.HealthMax - HealedPawn.Health));
			AddAmmunition(InstigatorPawn, UPG.GetAmmoMultiplier(default.HealthThreshold[upgLevel - 1]));
		}
	}
}

static function AddAmmunition(KFPawn Player, int Multiplier)
{
	local KFWeapon KFW;
	local byte i;
	local int ExtraAmmo;

	if (Player != None && Player.Health > 0 && Player.InvManager != None && Multiplier > 0)
	{
		foreach Player.InvManager.InventoryActors(class'KFWeapon', KFW)
		{
			for (i = 0; i < 2; ++i)
			{
				ExtraAmmo = Min(FCeil(float(KFW.GetMaxAmmoAmount(i)) / default.AmmoDivider) * Multiplier, KFW.GetMaxAmmoAmount(i) - KFW.GetTotalAmmoAmount(i));
				if (ExtraAmmo > 0)
				{
					if (i == 0)
						KFW.AddAmmo(ExtraAmmo);
					else
						KFW.AddSecondaryAmmo(ExtraAmmo);
				}
			}
		}
	}
}

static function DKUpgrade_Skill_TriageExpert_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_TriageExpert_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_TriageExpert_Helper', UPG)
		{
			return UPG;
		}

		// Should have one
		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_TriageExpert_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_TriageExpert_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_TriageExpert_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_TriageExpert]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_TriageExpert"

	UpgradeName="Triage Expert"
	UpgradeDescription(0)="Healing allies restores ammo to your weapons. Every <font color=\"#eeeeff\">50 HP</font> healed triggers a refill"
	UpgradeDescription(1)="<font color=\"#ffd700\">Deluxe.</font> Healing allies restores ammo to your weapons. Every <font color=\"#eeeeff\">25 HP</font> healed triggers a refill"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_TriageExpert'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_TriageExpert_Deluxe'

	Name="Default__DKUpgrade_Skill_TriageExpert"
}
