class DKUpgrade_Skill_FullMetalJacket extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Penetration;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Penetration[0] = 4.0f;
		default.Penetration[1] = 8.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function ModifyPenetrationPassive(out float penetrationFactor, int upgLevel)
{
	penetrationFactor += default.Penetration[upgLevel - 1];
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_FullMetalJacket]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_FullMetalJacket"

    UpgradeName="Full Metal Jacket"
	upgradeDescription(0)="Gain <font color=\"#ff3399\">400%</font> more <font color=\"#66cc00\">Penetration</font> for all weapons." 
   	upgradeDescription(1)="Gain <font color=\"#ff3399\">800%</font> more <font color=\"#66cc00\">Penetration</font> for all weapons."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FullMetalJacket'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FullMetalJacket_Deluxe'
    Name="Default__DKUpgrade_Skill_FullMetalJacket"
}