class DKUpgrade_Skill_WintersSwiftness extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> MovementSpeed;
var config array<float> WeaponSwitchSpeed;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MovementSpeed[0] = 0.10f;
		default.MovementSpeed[1] = 0.20f;
		default.WeaponSwitchSpeed[0] = 0.5f;
		default.WeaponSwitchSpeed[1] = 0.4f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// BUGFIX: both hooks previously overwrote the accumulated value from the
// DefaultX basis (InSpeed = DefaultSpeed * (1 + bonus)), which discarded
// every other speed contributor processed before this skill and could
// therefore LOWER the final value. Both now compose with the incoming
// value like every other WM/DK modifier.
static simulated function ModifySpeed(out float InSpeed, float DefaultSpeed, int upgLevel, KFPawn OwnerPawn)
{
	InSpeed += DefaultSpeed * default.MovementSpeed[upgLevel - 1];
}

static simulated function ModifyWeaponSwitchTime(out float InSwitchTime, float DefaultSwitchTime, int upgLevel, KFWeapon KFW)
{
	// Config value is a switch TIME multiplier (0.5 = twice as fast,
	// matching "100% weapon switch speed"). Multiply the incoming time
	// so prior contributors are preserved.
	InSwitchTime *= default.WeaponSwitchSpeed[upgLevel - 1];
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_WintersSwiftness]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_WintersSwiftness"

    UpgradeName="Winter's Swiftness"
    upgradeDescription(0)="Gain <font color=\"#87CEEB\">10%</font> <font color=\"#9966FF\">Movement Speed</font> and <font color=\"#15d7fa\">100%</font> <font color=\"#77d914\">Weapon Switch Speed</font>."
    upgradeDescription(1)="Gain <font color=\"#87CEEB\">20%</font> <font color=\"#9966FF\">Movement Speed</font> and <font color=\"#15d7fa\">150%</font> <font color=\"#77d914\">Weapon Switch Speed</font>."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_WintersSwiftness'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_WintersSwiftness_Deluxe'

    Name="Default__DKUpgrade_Skill_WintersSwiftness"
}
