// ===================================================================
// DKUpgrade_Skill_Wallhack - Active ability: see enemies through walls
// Standard: See enemies within 30m for 10s
// Deluxe: See enemies within 50m for 15s, also shows health bars
// Cooldown: 45s after effect ends
// ===================================================================
class DKUpgrade_Skill_Wallhack extends DKUpgrade_Skill;

// Called when skill is purchased - spawn the helper
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_Wallhack_Helper Helper;
	local DKPlayerController DKPC;
	local bool bFound;
	
	if (KFPawn_Human(OwnerPawn) == None || OwnerPawn.Role != Role_Authority)
		return;
	
	DKPC = DKPlayerController(OwnerPawn.Controller);
	if (DKPC == None)
	{
		`log("[DK_WALLHACK] ERROR - Player does not have DKPlayerController!");
		return;
	}
	
	// Check if helper already exists
	bFound = false;
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Wallhack_Helper', Helper)
	{
		bFound = true;
		Helper.SetTier(upgLevel);
		break;
	}
	
	// Spawn new helper if not found
	if (!bFound)
	{
		Helper = OwnerPawn.Spawn(class'DKUpgrade_Skill_Wallhack_Helper', OwnerPawn);
		if (Helper != None)
			Helper.Initialize(upgLevel, KFPawn_Human(OwnerPawn), DKPC);
	}
}

// Called when skill is removed - cleanup
static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_Wallhack_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Wallhack_Helper', Helper)
	{
		Helper.Cleanup();
		Helper.Destroy();
	}
}

// DrawOnHUD is called by WMPerk for purchased skills
static simulated function DrawOnHUD(int upgLevel, Canvas C, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_Wallhack_Helper Helper;
	local KFPawn_Monster KFPM;
	local vector ScreenPos, TargetLocation, CameraLocation;
	local rotator CameraRotation;
	local PlayerController PC;
	local float DistSq, MaxDistSq, HealthPercent;
	local bool bBehindWall, bShowHealthBars;
	local float DetectionRange;
	
	if (OwnerPawn == None || C == None)
		return;
	
	PC = PlayerController(OwnerPawn.Controller);
	if (PC == None)
		return;
	
	// Find the helper and check if active
	Helper = None;
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Wallhack_Helper', Helper)
	{
		break;
	}
	
	// If no helper or not active, don't draw
	if (Helper == None || !Helper.bActive)
		return;
	
	// Get settings from helper
	bShowHealthBars = (upgLevel >= 2);
	if (upgLevel >= 2)
		DetectionRange = 2500.0f; // 50m
	else
		DetectionRange = 1500.0f; // 30m
	
	MaxDistSq = Square(DetectionRange);
	
	// Get camera info
	PC.GetPlayerViewPoint(CameraLocation, CameraRotation);
	
	// Iterate all monsters
	foreach OwnerPawn.WorldInfo.AllPawns(class'KFPawn_Monster', KFPM)
	{
		if (KFPM == None || !KFPM.IsAliveAndWell())
			continue;
		
		// Check distance
		DistSq = VSizeSq(KFPM.Location - OwnerPawn.Location);
		if (DistSq > MaxDistSq)
			continue;
		
		// Get target location (above head)
		if (KFPM.bCrawler && KFPM.Floor.Z <= -0.7f && KFPM.Physics == PHYS_Spider)
		{
			TargetLocation = KFPM.Location + vect(0,0,-1) * KFPM.GetCollisionHeight() * 1.2f;
		}
		else
		{
			TargetLocation = KFPM.Location + vect(0,0,1) * KFPM.GetCollisionHeight() * 1.2f;
		}
		
		// Project to screen
		ScreenPos = C.Project(TargetLocation);
		
		// Check if on screen and in front of camera
		if (ScreenPos.Z <= 0)
			continue;
		
		if (ScreenPos.X < 0 || ScreenPos.X > C.SizeX || ScreenPos.Y < 0 || ScreenPos.Y > C.SizeY)
			continue;
		
		// Check if behind wall
		bBehindWall = !class'KFGameEngine'.static.FastTrace_PhysX(TargetLocation, CameraLocation);
		
		// Draw indicator - different color if behind wall
		if (bBehindWall)
			C.SetDrawColor(255, 100, 0, 200); // Orange for behind walls
		else
			C.SetDrawColor(0, 255, 255, 220); // Cyan for visible
		
		// Draw marker
		C.SetPos(ScreenPos.X - 6, ScreenPos.Y - 6);
		C.DrawRect(12, 12, Texture2D'EngineResources.WhiteSquareTexture');
		
		// Draw health bar if deluxe tier
		if (bShowHealthBars)
		{
			HealthPercent = FClamp(float(KFPM.Health) / float(KFPM.HealthMax), 0.0f, 1.0f);
			
			// Background
			C.SetDrawColor(0, 0, 0, 200);
			C.SetPos(ScreenPos.X - 20, ScreenPos.Y + 10);
			C.DrawRect(40, 6, Texture2D'EngineResources.WhiteSquareTexture');
			
			// Health fill
			C.SetDrawColor(237, 8, 0, 200);
			C.SetPos(ScreenPos.X - 19, ScreenPos.Y + 11);
			C.DrawRect(38 * HealthPercent, 4, Texture2D'EngineResources.WhiteSquareTexture');
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Wallhack]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Wallhack"

	UpgradeName="Wallhack"
	
	upgradeDescription(0)="Unlocks <font color=\"#66cc00\">Threat Scanner</font> active ability: <font color=\"#00ffff\">See enemies through walls</font> within <font color=\"#ffaa33\">30 meters</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">45 seconds</font>."
	
	upgradeDescription(1)="Unlocks <font color=\"#66cc00\">Threat Scanner (Deluxe)</font> active ability: <font color=\"#00ffff\">See enemies through walls</font> within <font color=\"#ffaa33\">50 meters</font> for <font color=\"#ffaa33\">15 seconds</font>. Also shows <font color=\"#ff0000\">health bars</font>. Cooldown: <font color=\"#ff9900\">45 seconds</font>."
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Wallhack'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Wallhack_Deluxe'
	
	Name="Default__DKUpgrade_Skill_Wallhack"
}