// ===================================================================
// DKUpgrade_Skill_TrophyShield - Trophies as Armor
//
// Gain damage reduction while holding 3+ trophies.
// Gain clot grab immunity at 5+ trophies.
// Normal: 15% DR at 3+ | Deluxe: 25% DR at 3+
//
// Tension: Hold trophies for defense vs. complete sets for bonuses.
// Scales in stacking phase (higher counts = always active).
// ===================================================================
class DKUpgrade_Skill_TrophyShield extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DamageReduction;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageReduction[0] = 0.15f;
		default.DamageReduction[1] = 0.25f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel,
    KFPawn OwnerPawn, optional class<DamageType> DamageType,
    optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    local DKUpgrade_Perk_Predator_Helper H;

    H = class'DKUpgrade_Perk_Predator'.static.GetHelper(OwnerPawn);
    if (H != None && H.TotalTrophies >= 3)
    {
        InDamage -= Round(float(DefaultDamage) * default.DamageReduction[upgLevel - 1]);
        if (InDamage < 0)
            InDamage = 0;
    }
}

static function bool CanNotBeGrabbed(int upgLevel, KFPawn OwnerPawn)
{
    local DKUpgrade_Perk_Predator_Helper H;

    H = class'DKUpgrade_Perk_Predator'.static.GetHelper(OwnerPawn);
    if (H != None && H.TotalTrophies >= 5)
        return True;

    return False;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_TrophyShield]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_TrophyShield"

    UpgradeName="Trophy Shield"
    UpgradeDescription(0)="<font color=\"#FFD700\">Trophy Shield:</font> <font color=\"#FFFFFF\">15%</font> <font color=\"#87CEEB\">damage reduction</font> with 3+ trophies. <font color=\"#FF6666\">Grab immunity</font> at 5+ trophies"
    UpgradeDescription(1)="<font color=\"#FFD700\">Trophy Shield:</font> <font color=\"#FFFFFF\">25%</font> <font color=\"#87CEEB\">damage reduction</font> with 3+ trophies. <font color=\"#FF6666\">Grab immunity</font> at 5+ trophies"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_TrophyShield'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_TrophyShield_Deluxe'

    Name="Default__DKUpgrade_Skill_TrophyShield"
}
