class DKUpgrade_Skill_FieryGambit extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Chance, Dosh;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Chance[0] = 0.01f;
		default.Chance[1] = 0.02f;
		default.Dosh[0] = 5;
		default.Dosh[1] = 10;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local KFPawn_Human KFPH;

    if(((DamageInstigator != none) && DamageInstigator.Pawn != none) && (DamageType != None && ClassIsChildOf(DamageType, class'KFDT_Fire')))
    {
        KFPH = KFPawn_Human(DamageInstigator.Pawn);
        
        if((KFPH != none) && KFPH.IsAliveAndWell())
        {
            if(((FRand() <= (default.Chance[upgLevel - 1]) && MyKFPM != none) && MyKFPM.IsAliveAndWell()) && (MyKFPM.Health - InDamage) <= 0)
            {
              KFPlayerReplicationInfo(DamageInstigator.PlayerReplicationInfo).AddDosh(default.Dosh[upgLevel - 1]);
            }
	    }
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_FieryGambit]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_FieryGambit"

    UpgradeName="Fiery Gambit"
	upgradeDescription(0)="When you kill a ZED with <font color=\"#ffa000\">Fire Damage</font>, you have a <font color=\"#66cc00\">1%</font> chance to gain <font color=\"#be4d25\">5 Dosh</font>."
	upgradeDescription(1)="When you kill a ZED with <font color=\"#ffa000\">Fire Damage</font>, you have a <font color=\"#66cc00\">2%</font> chance to gain <font color=\"#be4d25\">10 Dosh</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FieryGambit'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FieryGambit_Deluxe'

    Name="Default__DKUpgrade_Skill_FieryGambit"
}