class DKUpgrade_Skill_PainEcho extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// They hurt you, they hurt themselves
// Percentage of damage taken is reflected back at the attacker as true damage
// Reflection percentage scales with nearby enemy count (max at 5+)

var config array<float> BaseReflection;        // 10% / 15% base reflection
var config array<float> ReflectionPerEnemy;    // +5% / +8% per nearby enemy
var config array<int> MaxEnemyBonus;           // Up to 5 / 5 enemies count
var const float NearbyRadiusSQ;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.BaseReflection[0] = 0.10f;
		default.BaseReflection[1] = 0.15f;
		default.ReflectionPerEnemy[0] = 0.05f;
		default.ReflectionPerEnemy[1] = 0.08f;
		default.MaxEnemyBonus[0] = 5;
		default.MaxEnemyBonus[1] = 5;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local KFPawn_Monster AttackerPawn;
	local float ReflectPercent;
	local int ReflectDamage, NearbyCount;
	local KFPawn_Monster KFM;

	if (InDamage <= 0 || OwnerPawn == None || InstigatedBy == None)
		return;

	AttackerPawn = KFPawn_Monster(InstigatedBy.Pawn);
	if (AttackerPawn == None || !AttackerPawn.IsAliveAndWell())
		return;

	// Count nearby enemies
	NearbyCount = 0;
	foreach OwnerPawn.DynamicActors(class'KFPawn_Monster', KFM)
	{
		if (KFM.IsAliveAndWell() && VSizeSQ(OwnerPawn.Location - KFM.Location) <= default.NearbyRadiusSQ)
		{
			++NearbyCount;
			if (NearbyCount >= default.MaxEnemyBonus[upgLevel - 1])
				break;
		}
	}

	// Calculate reflection: base + per-enemy scaling
	ReflectPercent = default.BaseReflection[upgLevel - 1] + (default.ReflectionPerEnemy[upgLevel - 1] * float(Min(NearbyCount, default.MaxEnemyBonus[upgLevel - 1])));
	ReflectDamage = Round(float(DefaultDamage) * ReflectPercent);

	if (ReflectDamage > 0)
	{
		AttackerPawn.TakeDamage(ReflectDamage, OwnerPawn.Controller, AttackerPawn.Location, vect(0,0,0), class'KFDT_Bludgeon');
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_PainEcho]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_PainEcho"

	NearbyRadiusSQ=250000   // 500 UU = 5 meters, squared

	UpgradeName="Pain Echo"

	UpgradeDescription(0)="<font color=\"#edb82a\">Pain Echo</font> <font color=\"#FF4500\">Reflect 10%</font> of damage taken back at the attacker. <font color=\"#FFD700\">+5% reflection</font> per nearby enemy (max 5). At max enemies: <font color=\"#FFFFFF\">35% total reflection</font> <font color=\"#AAAAAA\">They hurt you, they hurt themselves.</font>"
	UpgradeDescription(1)="<font color=\"#edb82a\">Pain Echo</font> <font color=\"#FF4500\">Reflect 15%</font> of damage taken back at the attacker. <font color=\"#FFD700\">+8% reflection</font> per nearby enemy (max 5). At max enemies: <font color=\"#FFFFFF\">55% total reflection</font> <font color=\"#AAAAAA\">They hurt you, they hurt themselves.</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PainEcho'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PainEcho_Deluxe'

	Name="Default__DKUpgrade_Skill_PainEcho"
}
