class DKUpgrade_Skill_HighNoon extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Mod;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Mod[0] = 1.5f;
		default.Mod[1] = 3.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function GetZedTimeModifier(out float InModifier, int upgLevel, KFWeapon KFW)
{
	local name StateName;
	StateName = KFW.GetStateName();

	if (class'ZedternalReborn.WMWeaponStates'.static.IsWeaponReloadState(StateName) || class'ZedternalReborn.WMWeaponStates'.static.IsWeaponSwitchState(StateName))
		InModifier += default.Mod[upgLevel - 1];
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_HighNoon]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_HighNoon"

    UpgradeName="High Noon"
	upgradeDescription(0)="During <font color=\"#15d7fa\">ZED Time</font> you reload <font color=\"#77d914\">150%</font> faster."
	upgradeDescription(1)="During <font color=\"#15d7fa\">ZED Time</font> you reload <font color=\"#77d914\">300%</font> faster."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HighNoon'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HighNoon_Deluxe'

	Name="Default__DKUpgrade_Skill_HighNoon"
}

