class DKUpgrade_Skill_HoardersCache extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Theme: The Wendigo prepares thoroughly, stashing extra rounds before the hunt
var config array<float> MagBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MagBonus[0] = 0.15f;
		default.MagBonus[1] = 0.35f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function ModifyMagSizeAndNumberPassive(out float magazineCapacityFactor, int upgLevel)
{
	magazineCapacityFactor += default.MagBonus[upgLevel - 1];
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_HoardersCache]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_HoardersCache"

	UpgradeName="Hoarder's Cache"
	UpgradeDescription(0)="<font color=\"#4682B4\">Hoarder's Cache:</font> <font color=\"#FFFFFF\">+15%</font> <font color=\"#87CEEB\">magazine capacity</font> for all weapons"
	UpgradeDescription(1)="<font color=\"#4682B4\">Hoarder's Cache:</font> <font color=\"#FFFFFF\">+35%</font> <font color=\"#87CEEB\">magazine capacity</font> for all weapons"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HoardersCache'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HoardersCache_Deluxe'

	Name="Default__DKUpgrade_Skill_HoardersCache"
}
