class DKUpgrade_Skill_RavenousStrikes extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Theme: Killing a zed empowers your next shot - chain deliberate kills
var config array<float> Damage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Damage[0] = 0.25f;
		default.Damage[1] = 0.6f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_RavenousStrikes_Helper UPG;

	if (MyKFPM == None || DamageInstigator == None || DamageInstigator.Pawn == None)
		return;

	UPG = GetHelper(DamageInstigator.Pawn);
	if (UPG == None)
		return;

	// Apply buff if active (earned from a previous kill)
	if (UPG.bBuffActive)
	{
		InDamage += Round(float(DefaultDamage) * default.Damage[upgLevel - 1]);
		UPG.ConsumeBuff();
	}

	// If this shot kills the zed, activate buff for the next shot
	if (MyKFPM.IsAliveAndWell() && (MyKFPM.Health - InDamage) <= 0)
	{
		UPG.ActivateBuff();
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_RavenousStrikes_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_RavenousStrikes_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_RavenousStrikes_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_RavenousStrikes_Helper GetHelper(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_RavenousStrikes_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_RavenousStrikes_Helper', UPG)
		{
			return UPG;
		}

		// Should have one
		UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_RavenousStrikes_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_RavenousStrikes_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_RavenousStrikes_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_RavenousStrikes]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_RavenousStrikes"

	UpgradeName="Ravenous Strikes"
	UpgradeDescription(0)="<font color=\"#4682B4\">Ravenous Strikes:</font> Killing a zed grants <font color=\"#FFFFFF\">+25%</font> <font color=\"#87CEEB\">damage</font> to your next shot for <font color=\"#F0F8FF\">5 seconds</font>"
	UpgradeDescription(1)="<font color=\"#4682B4\">Ravenous Strikes:</font> Killing a zed grants <font color=\"#FFFFFF\">+60%</font> <font color=\"#87CEEB\">damage</font> to your next shot for <font color=\"#F0F8FF\">5 seconds</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_RavenousStrikes'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_RavenousStrikes_Deluxe'

	Name="Default__DKUpgrade_Skill_RavenousStrikes"
}
