// ===================================================================
// DKUpgrade_Skill_DeadEye - Active ability: temporary headshot damage boost
// Standard: +25% headshot damage for 10s
// Deluxe: +40% headshot damage for 10s
// Cooldown: 60s after effect ends
// ===================================================================
class DKUpgrade_Skill_DeadEye extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> HeadshotDamageBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HeadshotDamageBonus[0] = 0.25f;
		default.HeadshotDamageBonus[1] = 0.4f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_DeadEye_Helper Helper;
	local DKPlayerController DKPC;
	local bool bFound;
	
	if (KFPawn_Human(OwnerPawn) == None || OwnerPawn.Role != Role_Authority)
		return;
	
	DKPC = DKPlayerController(OwnerPawn.Controller);
	if (DKPC == None)
	{
		`log("DKUpgrade_Skill_DeadEye: ERROR - Player does not have DKPlayerController!");
		return;
	}
	
	bFound = false;
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_DeadEye_Helper', Helper)
	{
		bFound = true;
		Helper.SetTier(upgLevel);
		`log("DKUpgrade_Skill_DeadEye: Updated existing helper to tier" @ upgLevel);
		break;
	}
	
	if (!bFound)
	{
		Helper = OwnerPawn.Spawn(class'DKUpgrade_Skill_DeadEye_Helper', OwnerPawn);
		if (Helper != None)
		{
			Helper.Initialize(upgLevel, KFPawn_Human(OwnerPawn), DKPC);
			`log("DKUpgrade_Skill_DeadEye: Spawned helper for" @ OwnerPawn.PlayerReplicationInfo.PlayerName);
		}
		else
		{
			`log("DKUpgrade_Skill_DeadEye: ERROR - Failed to spawn helper!");
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_DeadEye_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_DeadEye_Helper', Helper)
	{
		Helper.Cleanup();
		Helper.Destroy();
		`log("DKUpgrade_Skill_DeadEye: Cleaned up helper");
	}
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
	optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
	optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
	optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_DeadEye_Helper Helper;
	local KFPawn OwnerPawn;
	
	if (DamageInstigator == None || DamageInstigator.Pawn == None)
		return;
	
	// Only apply to headshots (HitZoneIdx 0 = head in KF2)
	if (HitZoneIdx != 0)
		return;
	
	OwnerPawn = KFPawn(DamageInstigator.Pawn);
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_DeadEye_Helper', Helper)
	{
		if (Helper.bActive)
		{
			InDamage += Round(float(DefaultDamage) * default.HeadshotDamageBonus[upgLevel - 1]);
		}
		break;
	}
}

defaultproperties
{
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_DeadEye]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_DeadEye"

	UpgradeName="Dead Eye"
	
	upgradeDescription(0)="Unlocks <font color=\"#66cc00\">Dead Eye</font> active ability: <font color=\"#00ffff\">+25% headshot damage</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	upgradeDescription(1)="Unlocks <font color=\"#66cc00\">Dead Eye (Deluxe)</font> active ability: <font color=\"#00ffff\">+40% headshot damage</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_DeadEye'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_DeadEye_Deluxe'
	
	Name="Default__DKUpgrade_Skill_DeadEye"
}