// ===================================================================
// DKUpgrade_Skill_AnvilsEcho — Artificer Skill
//
// "Every Nth hit fires a phantom echo — an additional damage
//  instance. The weapon resonates with such perfection that
//  it strikes twice."
//
// Works with ALL weapons.
//
// Normal:  Every 5th hit deals +50% phantom bonus damage
// Deluxe:  Every 3rd hit deals +50% phantom bonus damage
//
// The counter persists across weapon switches (total hits tracked).
// No penalty for missing — purely additive.
//
// Hook: ModifyDamageGiven
// Helper: DKUpgrade_Skill_AnvilsEcho_Helper (tracks hit counter)
// ===================================================================
class DKUpgrade_Skill_AnvilsEcho extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> HitInterval;     // Every Nth hit triggers echo
var config float EchoDamage;           // +50% phantom damage on proc
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HitInterval[0] = 5;
		default.HitInterval[1] = 3;
		default.EchoDamage = 0.50f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_AnvilsEcho_Helper H;

    if (DamageInstigator == None || DamageInstigator.Pawn == None || MyKFPM == None || MyKFW == None)
        return;

    H = GetHelper(DamageInstigator.Pawn, upgLevel);
    if (H == None)
        return;

    H.OnHit(InDamage, DefaultDamage, upgLevel);
}

// ===================================================================
// HELPER MANAGEMENT
// ===================================================================

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == ROLE_Authority)
        GetHelper(OwnerPawn, upgLevel);
}

static function DKUpgrade_Skill_AnvilsEcho_Helper GetHelper(Pawn OwnerPawn, int upgLevel)
{
    local DKUpgrade_Skill_AnvilsEcho_Helper H;

    if (KFPawn_Human(OwnerPawn) == None)
        return None;

    foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_AnvilsEcho_Helper', H)
    {
        H.UpgradeLevel = upgLevel;
        return H;
    }

    // Spawn if not found
    if (OwnerPawn.Role == ROLE_Authority)
    {
        H = OwnerPawn.Spawn(class'DKUpgrade_Skill_AnvilsEcho_Helper', OwnerPawn);
        if (H != None)
            H.UpgradeLevel = upgLevel;
    }

    return H;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_AnvilsEcho_Helper H;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_AnvilsEcho_Helper', H)
        {
            H.Destroy();
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_AnvilsEcho]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_AnvilsEcho"

    UpgradeName="Anvil's Echo"
    UpgradeDescription(0)="Every <font color=\"#FFFFFF\">5th hit</font> fires a <font color=\"#FFD700\">phantom echo</font> dealing <font color=\"#FFFFFF\">+50%</font> bonus damage"
    UpgradeDescription(1)="Every <font color=\"#FFFFFF\">3rd hit</font> fires a <font color=\"#FFD700\">phantom echo</font> dealing <font color=\"#FFFFFF\">+50%</font> bonus damage"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AnvilsEcho'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AnvilsEcho_Deluxe'

    Name="Default__DKUpgrade_Skill_AnvilsEcho"
}
