// Wings of Mercy
// Gain movement speed when allies within range are below 50% health
// Speed bonus scales with how many hurt allies are nearby (up to 3)
// Standard: Up to +20% speed (3 hurt allies nearby)
// Deluxe: Up to +50% speed (3 hurt allies nearby)
class DKUpgrade_Skill_WingsOfMercy extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> MaxSpeedBonus;
var config float AllyRadiusSQ, HealthThreshold;
var config byte MaxHurtAllies;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MaxSpeedBonus[0] = 0.2f;
		default.MaxSpeedBonus[1] = 0.5f;
		default.AllyRadiusSQ = 640000.0f;
		default.HealthThreshold = 0.5f;
		default.MaxHurtAllies = 3;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function ModifySpeed(out float InSpeed, float DefaultSpeed, int upgLevel, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_WingsOfMercy_Helper UPG;

	UPG = GetHelper(OwnerPawn);
	if (UPG != None && UPG.HurtAllyCount > 0)
		InSpeed += DefaultSpeed * default.MaxSpeedBonus[upgLevel - 1] * (float(UPG.HurtAllyCount) / float(default.MaxHurtAllies));
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_WingsOfMercy_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_WingsOfMercy_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
		{
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_WingsOfMercy_Helper', OwnerPawn);
		}
	}
}

static simulated function DKUpgrade_Skill_WingsOfMercy_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_WingsOfMercy_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_WingsOfMercy_Helper', UPG)
		{
			return UPG;
		}

		// Should have one
		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_WingsOfMercy_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_WingsOfMercy_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_WingsOfMercy_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_WingsOfMercy]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_WingsOfMercy"

	UpgradeName="Wings of Mercy"
	UpgradeDescription(0)="Gain up to <font color=\"#eeeeff\">20%</font> <font color=\"#87ceeb\">movement speed</font> when allies within range are below 50% health"
	UpgradeDescription(1)="<font color=\"#ffd700\">Deluxe.</font> Gain up to <font color=\"#eeeeff\">50%</font> <font color=\"#87ceeb\">movement speed</font> when allies within range are below 50% health"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_WingsOfMercy'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_WingsOfMercy_Deluxe'

	Name="Default__DKUpgrade_Skill_WingsOfMercy"
}
