class DKUpgrade_Skill_FrozenHide extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Theme: The motionless predator becomes harder to hurt
var config array<float> Resistance;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Resistance[0] = 0.2f;
		default.Resistance[1] = 0.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	if (OwnerPawn != None && VSizeSq(OwnerPawn.Velocity) <= 0)
		InDamage -= Round(float(DefaultDamage) * default.Resistance[upgLevel - 1]);
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_FrozenHide]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_FrozenHide"

	UpgradeName="Frozen Hide"
	UpgradeDescription(0)="<font color=\"#4682B4\">Frozen Hide:</font> Take <font color=\"#FFFFFF\">20%</font> <font color=\"#87CEEB\">less damage</font> while <font color=\"#F0F8FF\">standing still</font>"
	UpgradeDescription(1)="<font color=\"#4682B4\">Frozen Hide:</font> Take <font color=\"#FFFFFF\">50%</font> <font color=\"#87CEEB\">less damage</font> while <font color=\"#F0F8FF\">standing still</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FrozenHide'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FrozenHide_Deluxe'

	Name="Default__DKUpgrade_Skill_FrozenHide"
}
