class DKUpgrade_Skill_Meltdown extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Meltdown: Increases rate of fire and melee attack speed.
// Standard: +15% fire rate / melee speed.
// Deluxe:   +35% fire rate / melee speed.

var config array<float> RateOfFire;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.RateOfFire[0] = 0.15f;
		default.RateOfFire[1] = 0.35f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function ModifyRateOfFirePassive(out float rateOfFireFactor, int upgLevel)
{
	rateOfFireFactor = 1.0f / (1.0f / rateOfFireFactor + default.RateOfFire[upgLevel - 1]);
}

static simulated function ModifyMeleeAttackSpeedPassive(out float durationFactor, int upgLevel)
{
	durationFactor = 1.0f / (1.0f / durationFactor + default.RateOfFire[upgLevel - 1]);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Meltdown]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Meltdown"

	UpgradeName="Meltdown"
	upgradeDescription(0)="<font color=\"#42e087\">Increase</font> <font color=\"#42e087\">rate of fire</font> and <font color=\"#42e087\">melee attack speed</font> by <font color=\"#84d6d0\">15%</font>."
	upgradeDescription(1)="<font color=\"#42e087\">Increase</font> <font color=\"#42e087\">rate of fire</font> and <font color=\"#42e087\">melee attack speed</font> by <font color=\"#84d6d0\">35%</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Meltdown'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Meltdown_Deluxe'

	Name="Default__DKUpgrade_Skill_Meltdown"
}
