class DKUpgrade_Skill_ReflectedFury extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DamageReflectMult;
var config float Cooldown;
var config float ExplosionRadius;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageReflectMult[0] = 0.50f;
		default.DamageReflectMult[1] = 1.00f;
		default.Cooldown = 10.0f;
		default.ExplosionRadius = 400.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_ReflectedFury_Helper UPG;
    local int ReflectedDamage;
    
    if (InDamage <= 0 || OwnerPawn == None)
        return;
    
    UPG = GetHelper(OwnerPawn, upgLevel);
    if (UPG == None)
        return;
    
    // Check if ready (cooldown expired)
    if (UPG.IsReady())
    {
        // Calculate reflected damage
        ReflectedDamage = Round(float(InDamage) * default.DamageReflectMult[upgLevel - 1]);
        
        // Trigger the reflection explosion
        UPG.TriggerReflection(ReflectedDamage, default.ExplosionRadius);
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_ReflectedFury_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ReflectedFury_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_ReflectedFury_Helper', OwnerPawn);
            UPG.Cooldown = default.Cooldown;
            UPG.bDeluxe = (upgLevel > 1);
        }
    }
}

static function DKUpgrade_Skill_ReflectedFury_Helper GetHelper(KFPawn OwnerPawn, int upgLevel)
{
    local DKUpgrade_Skill_ReflectedFury_Helper UPG;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ReflectedFury_Helper', UPG)
        {
            return UPG;
        }

        // Should have one
        UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_ReflectedFury_Helper', OwnerPawn);
        UPG.Cooldown = default.Cooldown;
        UPG.bDeluxe = (upgLevel > 1);
    }

    return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_ReflectedFury_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ReflectedFury_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_ReflectedFury]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_ReflectedFury"

    UpgradeName="Reflected Fury"
    upgradeDescription(0)="When hit, deal <font color=\"#ff3399\">50%</font> of damage taken to all enemies within <font color=\"#ffff00\">4 meters</font>. <font color=\"#aaaaaa\">10 second cooldown</font>."
    upgradeDescription(1)="When hit, deal <font color=\"#ff3399\">100%</font> of damage taken to all enemies within <font color=\"#ffff00\">4 meters</font>. <font color=\"#aaaaaa\">10 second cooldown</font>."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ReflectedFury'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ReflectedFury_Deluxe'

    Name="Default__DKUpgrade_Skill_ReflectedFury"
}
