class DKUpgrade_Skill_Giantsbane extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Damage;
var config array<float> MagSize;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Damage[0] = 0.20f;
		default.Damage[1] = 0.40f;
		default.MagSize[0] = 0.30f;
		default.MagSize[1] = 0.60f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional Class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    if((MyKFPM != none) && KFPawn_ZedScrake(MyKFPM) != none)
    {
            InDamage += Round((float(DefaultDamage) * default.Damage[upgLevel - 1]));           
    }
    else
    {
        if((MyKFPM != none) && KFPawn_ZedFleshpoundMini(MyKFPM) != none)
        {
            InDamage += Round((float(DefaultDamage) * default.Damage[upgLevel - 1]));            
        }
        else
        {
            if((MyKFPM != none) && KFPawn_ZedFleshpound(MyKFPM) != none)
            {
            InDamage += Round((float(DefaultDamage) * default.Damage[upgLevel - 1]));                   
            }
            else
            {
                if((MyKFPM != none) && WMPawn_ZedScrake_Tiny(MyKFPM) != none)
                {
            InDamage += Round((float(DefaultDamage) * default.Damage[upgLevel - 1]));       
                }
            }
        }
    }
}

static simulated function ModifyMagSizeAndNumber(out int InMagazineCapacity, int DefaultMagazineCapacity, int upgLevel, KFWeapon KFW, optional array< Class<KFPerk> > WeaponPerkClass, optional bool bSecondary, optional name WeaponClassName)
{
    InMagazineCapacity += Round((float(DefaultMagazineCapacity) * default.MagSize[upgLevel - 1]));
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Giantsbane]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Giantsbane"

    UpgradeName="Giantsbane"
	upgradeDescription(0)="You deal <font color=\"#15d7fa\">20%</font> more damage to <font color=\"#a0c1cb\">large ZEDs</font> and your <font color=\"#0bf1f1\">Magazine Size</font> is increased by <font color=\"#15d7fa\">30%</font>."
	upgradeDescription(1)="You deal <font color=\"#15d7fa\">40%</font> more damage to <font color=\"#a0c1cb\">large ZEDs</font> and your <font color=\"#0bf1f1\">Magazine Size</font> is increased by <font color=\"#15d7fa\">60%</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Giantsbane'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Giantsbane_Deluxe'

	Name="Default__DKUpgrade_Skill_Giantsbane"
}