class DKUpgrade_Skill_SurvivalInstinct extends DKUpgrade_Skill
	abstract
	config(ZedternalUnlimited);

var config array<float> HealthThreshold;
var config array<float> DamageBoost;
var config array<float> ReloadBoost;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HealthThreshold[0] = 0.35f;
		default.HealthThreshold[1] = 0.50f;
		default.DamageBoost[0] = 0.15f;
		default.DamageBoost[1] = 0.25f;
		default.ReloadBoost[0] = 0.20f;
		default.ReloadBoost[1] = 0.35f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local KFPawn_Human OwnerPawn;
	local float CurrentHealthPct;
	
	if (DamageInstigator == None || DamageInstigator.Pawn == None)
		return;
		
	OwnerPawn = KFPawn_Human(DamageInstigator.Pawn);
	if (OwnerPawn == None)
		return;
		
	CurrentHealthPct = float(OwnerPawn.Health) / float(OwnerPawn.HealthMax);
	
	if (CurrentHealthPct <= default.HealthThreshold[upgLevel - 1])
	{
		InDamage = Round(float(InDamage) * (1.0f + default.DamageBoost[upgLevel - 1]));
	}
}

static simulated function GetReloadRateScale(out float InReloadRateScale, int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local KFPawn_Human KFPawnHuman;
	local float CurrentHealthPct;
	
	if (OwnerPawn == None)
		return;
		
	KFPawnHuman = KFPawn_Human(OwnerPawn);
	if (KFPawnHuman == None)
		return;
		
	// Calculate current health percentage
	CurrentHealthPct = float(KFPawnHuman.Health) / float(KFPawnHuman.HealthMax);
	
	// Apply reload speed boost if health is below threshold
	if (CurrentHealthPct <= default.HealthThreshold[upgLevel - 1])
	{
		InReloadRateScale *= (1.0f + default.ReloadBoost[upgLevel - 1]);
	}
}


defaultproperties
{
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_SurvivalInstinct]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_SurvivalInstinct"

	UpgradeName="Survival Instinct"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SurvivalInstinct'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SurvivalInstinct_Deluxe'
	UpgradeDescription(0)="The symbiote triggers fight-or-flight response in danger. <font color='#00FF7F'>+15%</font> <font color='#9370DB'>damage</font> and <font color='#00FF7F'>+20%</font> <font color='#9370DB'>reload speed</font> when below <font color='#00FF7F'>35%</font> <font color='#9370DB'>health</font>."
	UpgradeDescription(1)="The symbiote enhances survival reflexes under stress. <font color='#00FF7F'>+25%</font> <font color='#9370DB'>damage</font> and <font color='#00FF7F'>+35%</font> <font color='#9370DB'>reload speed</font> when below <font color='#00FF7F'>50%</font> <font color='#9370DB'>health</font>."
	
	Name="Default__DKUpgrade_Skill_SurvivalInstinct"
}