class DKUpgrade_Skill_ToxicImmunity extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> PoisonResistance;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.PoisonResistance[0] = 0.5f;
		default.PoisonResistance[1] = 1.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    local KFPlayerController KFPC;
    
    // Check if this is poison damage
    if (DamageType != None && (ClassIsChildOf(DamageType, class'KFDT_Toxic') || ClassIsChildOf(DamageType, class'DKDT_Medusa_Poison')))
    {
        if (upgLevel == 1)
        {
            // Standard: 50% poison damage resistance
            InDamage = Round(float(InDamage) * (1.0f - default.PoisonResistance[0]));
        }
        else if (upgLevel == 2)
        {
            // Deluxe: Complete poison immunity + gain health when taking poison damage
            if (OwnerPawn != None && OwnerPawn.Health > 0 && OwnerPawn.Health < OwnerPawn.HealthMax)
            {
                // Heal for the damage that would have been taken
                OwnerPawn.HealDamage(InDamage, OwnerPawn.Controller, class'KFDT_Healing');
                
                // Show healing message
                KFPC = KFPlayerController(OwnerPawn.Controller);
                if (KFPC != None)
                {
                    KFPC.ClientMessage("Toxic Immunity: Poison healed +" $ InDamage $ " HP!", 'Event');
                }
            }
            
            // Negate all poison damage
            InDamage = 0;
        }
    }
}

defaultproperties
{
    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_ToxicImmunity]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_ToxicImmunity"

    UpgradeName="Toxic Immunity"
    UpgradeDescription(0)="<font color=\"#8B008B\">Toxic Immunity:</font> <font color=\"#FFFFFF\">50%</font> <font color=\"#00FF00\">poison damage resistance</font>."
    UpgradeDescription(1)="<font color=\"#8B008B\">Toxic Immunity (Deluxe):</font> <font color=\"#FFD700\">Complete poison immunity</font> + <font color=\"#00FF00\">gain health</font> when taking poison damage."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ToxicImmunity'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ToxicImmunity_Deluxe'
    
    Name="Default__DKUpgrade_Skill_ToxicImmunity"
}