// ===================================================================
// DKUpgrade_Skill_CardShark - Gambit Skill
//
// "Card Shark" - Failed gambits grant permanent damage stacks.
// Completing a gambit consumes all stacks for bonus dosh.
// The damage bonus persists until consumed by a completion.
//
// Standard: +2% damage per failure stack, 100 dosh per stack on cash-out.
// Deluxe:   +3% damage per failure stack, 150 dosh per stack on cash-out.
//
// ExtensionFuncInteger signals to helper (failure/cashout logic).
// ModifyDamageGiven applies the accumulated damage bonus.
// ===================================================================
class DKUpgrade_Skill_CardShark extends DKUpgrade_Skill;

// ===================================================================
// SIGNAL -- Tell helper this skill is active
// ===================================================================

static simulated function ExtensionFuncInteger(out int InValue, int DefaultValue, int upgLevel, string Identifier,
    KFWeapon MyKFW, KFPawn OwnerPawn, optional int InputInt, optional float InputFloat, optional name InputClassName,
    optional Object InputObject1, optional Object InputObject2, optional Object InputObject3)
{
    if (Identifier ~= "GambitCardShark")
        InValue = upgLevel;
}

// ===================================================================
// DAMAGE GIVEN -- Apply Card Shark accumulated damage bonus
// ===================================================================

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
    optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
    optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
    optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Perk_Gambit_Helper H;

    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;

    H = class'DKUpgrade_Perk_Gambit'.static.GetHelper(DamageInstigator.Pawn);
    if (H == None || H.CardSharkDamageBonus <= 0.0f)
        return;

    InDamage += Round(float(DefaultDamage) * H.CardSharkDamageBonus);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_CardShark]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_CardShark"

    UpgradeName="Card Shark"
    upgradeDescription(0)="Failed gambits grant permanent <font color=\"#FFD700\">+2%</font> damage stacks. Completing a gambit cashes out all stacks for <font color=\"#FFFFFF\">100 dosh</font> each."
    upgradeDescription(1)="Failed gambits grant permanent <font color=\"#FFD700\">+3%</font> damage stacks. Completing a gambit cashes out all stacks for <font color=\"#FFFFFF\">150 dosh</font> each."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CardShark'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CardShark_Deluxe'

    Name="Default__DKUpgrade_Skill_CardShark"
}
