class DKUpgrade_Skill_AcidicBlood extends DKUpgrade_Skill
	abstract
	config(ZedternalUnlimited);

var config array<float> RecoilReduction;
var config array<float> SpreadReduction;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.RecoilReduction[0] = 0.25f;
		default.RecoilReduction[1] = 0.40f;
		default.SpreadReduction[0] = 0.20f;
		default.SpreadReduction[1] = 0.35f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}



static simulated function ModifyRecoil(out float InRecoilModifier, float DefaultRecoilModifier, int upgLevel, KFWeapon KFW)
{
	// Reduce recoil due to enhanced circulation and steadier hands.
	// Convention across the codebase: recoil/spread reductions use -= so
	// the modifier shrinks. += would make the weapon WORSE — that was a bug.
	InRecoilModifier -= (DefaultRecoilModifier * (default.RecoilReduction[upgLevel - 1]));
}

static simulated function ModifySpread(out float InSpreadModifier, float DefaultSpreadModifier, int upgLevel, KFWeapon KFW)
{
	InSpreadModifier -= (DefaultSpreadModifier * (default.SpreadReduction[upgLevel - 1]));
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_AcidicBlood]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_AcidicBlood"

	UpgradeName="Acidic Blood"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AcidicBlood'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AcidicBlood_Deluxe'
	UpgradeDescription(0)="The symbiote's acidic blood enhances circulation and metabolism. Gain <font color='#00FF7F'>25%</font> less <font color='#FF6347'>Recoil</font> and <font color='#00FF7F'>20%</font> better <font color='#87CEEB'>Accuracy</font>."
	UpgradeDescription(1)="The symbiote's acidic blood enhances circulation and metabolism. Gain <font color='#00FF7F'>40%</font> less <font color='#FF6347'>Recoil</font> and <font color='#00FF7F'>35%</font> better <font color='#87CEEB'>Accuracy</font>."
	
	Name="Default__DKUpgrade_Skill_AcidicBlood"
}