// Necrosis: ALL your damage deals bonus damage to already-poisoned ZEDs.
// Encourages a two-step loop: poison first, then finish with heavy weapons.
class DKUpgrade_Skill_Necrosis extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> BonusDamage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.BonusDamage[0] = 0.20f;
		default.BonusDamage[1] = 0.50f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (MyKFPM != None && (MyKFPM.bIsPoisoned || ZedHasToxicDoT(MyKFPM)))
		InDamage += Round(float(DefaultDamage) * default.BonusDamage[upgLevel - 1]);
}

// True if the zed currently has an active toxic damage-over-time. KF2's
// bIsPoisoned is the toxic *affliction* flag (the green-screen/panic state),
// which a light DoT may never push over threshold -- so this skill (and
// Putrefaction / Venomweave) read false on zeds that were, in fact, taking
// poison damage. Scanning DamageOverTimeArray for a KFDT_Toxic DoT is the
// reliable "is poisoned" test.
static function bool ZedHasToxicDoT(KFPawn_Monster M)
{
	local int i;

	if (M == None)
		return false;

	for (i = 0; i < M.DamageOverTimeArray.Length; ++i)
	{
		if (M.DamageOverTimeArray[i].DamageType != None
			&& ClassIsChildOf(M.DamageOverTimeArray[i].DamageType, class'KFDT_Toxic'))
			return true;
	}

	return false;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Necrosis]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Necrosis"

	UpgradeDescription(0)="All your damage deals <font color=\"#399c0e\">20%</font> bonus damage to <font color=\"#8fce00\">Poisoned</font> ZEDs."
	UpgradeDescription(1)="All your damage deals <font color=\"#b346ea\">50%</font> bonus damage to <font color=\"#8fce00\">Poisoned</font> ZEDs."

	UpgradeName="Necrosis"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Necrosis'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Necrosis_Deluxe'

	Name="Default__DKUpgrade_Skill_Necrosis"
}
