class DKUpgrade_Skill_BattlefieldAwareness extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> ZedTimeExtensionAmount;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ZedTimeExtensionAmount[0] = 0.3f;
		default.ZedTimeExtensionAmount[1] = 0.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function GetZedTimeExtension(out float InExtension, float DefaultExtension, int upgLevel)
{
    // This skill extends zed time when kills are made during zed time
    // The actual extension logic is handled in ModifyDamageGiven when a kill occurs
    // This function just ensures the base extension capability exists
    InExtension += 0.1f; // Small base extension to enable the system
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local KFGameInfo KFGI;
    local float ExtensionTime;
    
    // Only process if this is a kill with a rifle weapon during zed time
    if (MyKFPM == None || MyKFW == None || MyKFPM.Health > InDamage || DamageInstigator == None)
        return;
    
    // Check if weapon is a rifle
    if (!IsRifleWeapon(MyKFW))
        return;
    
    // Check if we're in zed time
    KFGI = KFGameInfo(DamageInstigator.WorldInfo.Game);
    if (KFGI == None || !KFGI.IsZedTimeActive())
        return;
    
    // Extend zed time duration
    ExtensionTime = default.ZedTimeExtensionAmount[upgLevel - 1];
    KFGI.ZedTimeRemaining += ExtensionTime;
    
    // Clamp to reasonable maximum (don't let zed time go on forever - max 15 seconds)
    KFGI.ZedTimeRemaining = FMin(KFGI.ZedTimeRemaining, 15.0f);
}

// Helper function to determine if weapon is rifle-like
static function bool IsRifleWeapon(KFWeapon KFW)
{
    if (KFW == None)
        return False;
        
    // Check if weapon is in the assault rifle category (Commando weapons)
    if (IsWeaponOnSpecificPerk(KFW, class'KFGame.KFPerk_Commando'))
    {
        // Exclude SMGs and other non-rifle weapons by checking damage characteristics
        // Most rifles have higher damage per shot than SMGs
        return (KFW.InstantHitDamage[0] >= 35 || 
                KFW.default.FireInterval[0] >= 0.08);
    }
    
    // Also include weapons that might be rifle-like but under other categories
    return (InStr(PathName(KFW.Class), "Rifle") != INDEX_NONE ||
            InStr(PathName(KFW.Class), "rifle") != INDEX_NONE);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_BattlefieldAwareness]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_BattlefieldAwareness"

    // Level 1: 0.3 seconds extension per kill
    // Level 2: 0.5 seconds extension per kill
    
    UpgradeName="Battlefield Awareness"
    UpgradeDescription(0)="Each <font color=\"#15d7fa\">rifle kill</font> during <font color=\"#ff3399\">Zed Time</font> extends the duration by <font color=\"#77d914\">0.3 seconds</font>."
    UpgradeDescription(1)="Each <font color=\"#15d7fa\">rifle kill</font> during <font color=\"#ff3399\">Zed Time</font> extends the duration by <font color=\"#77d914\">0.5 seconds</font>."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BattlefieldAwareness'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BattlefieldAwareness_Deluxe'
    
    Name="Default__DKUpgrade_Skill_BattlefieldAwareness"
}