class DKUpgrade_Skill_PrimalRoar extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> Radius;
var config int KillThreshold;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Radius[0] = 360000;
		default.Radius[1] = 1000000;
		default.KillThreshold = 25;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_PrimalRoar_Helper UPG;

    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;

    // Check if this will kill
    if (MyKFPM != None && MyKFPM.IsAliveAndWell() && (MyKFPM.Health - InDamage) <= 0)
    {
        UPG = GetHelper(DamageInstigator.Pawn);
        if (UPG != None)
        {
            UPG.RegisterKill(default.KillThreshold, default.Radius[upgLevel - 1], upgLevel);
        }
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_PrimalRoar_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_PrimalRoar_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_PrimalRoar_Helper', OwnerPawn);
        }
    }
}

static function DKUpgrade_Skill_PrimalRoar_Helper GetHelper(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_PrimalRoar_Helper UPG;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_PrimalRoar_Helper', UPG)
        {
            return UPG;
        }

        UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_PrimalRoar_Helper', OwnerPawn);
    }

    return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_PrimalRoar_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_PrimalRoar_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_PrimalRoar]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_PrimalRoar"

    // Squared radii: 600^2 = 360000 (~6m), 1000^2 = 1000000 (~10m)

    UpgradeName="Primal Roar"
    upgradeDescription(0)="Every <font color=\"#ffff00\">25 kills</font> unleashes a shockwave that <font color=\"#00ffff\">stumbles</font> all enemies within <font color=\"#aaaaaa\">6 meters</font>."
    upgradeDescription(1)="Every <font color=\"#ffff00\">25 kills</font> unleashes a shockwave that <font color=\"#ff0000\">knocks down</font> all enemies within <font color=\"#aaaaaa\">10 meters</font>."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PrimalRoar'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PrimalRoar_Deluxe'

    Name="Default__DKUpgrade_Skill_PrimalRoar"
}
