class DKUpgrade_Skill_HouseEdge extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> SlotMachineTrigger;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.SlotMachineTrigger[0] = 30;
		default.SlotMachineTrigger[1] = 30;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_HouseEdge_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_HouseEdge_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_HouseEdge_Helper', OwnerPawn);
            UPG.bDeluxe = (upgLevel > 1);
            UPG.UpgradeLevel = upgLevel;
        }
    }
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_HouseEdge_Helper UPG;

    // Check if this damage will kill the target
    if (MyKFPM != None && MyKFPM.IsAliveAndWell() && 
        DamageInstigator != None && DamageInstigator.Pawn != None &&
        (MyKFPM.Health - InDamage) <= 0)
    {
        foreach DamageInstigator.Pawn.ChildActors(class'DKUpgrade_Skill_HouseEdge_Helper', UPG)
        {
            UPG.OnEnemyKilled();
            break;
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_HouseEdge_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_HouseEdge_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_HouseEdge]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_HouseEdge"

    UpgradeName="House Edge"
    
    upgradeDescription(0)="Every <font color=\"#ffaa33\">30th kill</font> triggers slot machine: <font color=\"#777777\">80% nothing</font>, <font color=\"#ffaa33\">15% +50 dosh</font>, <font color=\"#ff6600\">4% +150 dosh</font>, <font color=\"#ff0000\">1% +300 dosh</font>."
    upgradeDescription(1)="Every <font color=\"#ffaa33\">30th kill</font> triggers slot machine: <font color=\"#777777\">60% nothing</font>, <font color=\"#ffaa33\">25% +50 dosh</font>, <font color=\"#ff6600\">10% +150 dosh</font>, <font color=\"#ff0000\">5% +300 dosh</font>."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HouseEdge'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HouseEdge_Deluxe'

    Name="Default__DKUpgrade_Skill_HouseEdge"
}