class DKUpgrade_Skill_EndlessRampage extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> ZedTimeExtension;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ZedTimeExtension[0] = 0.50f;
		default.ZedTimeExtension[1] = 1.00f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function GetZedTimeExtension(out float InExtension, float DefaultExtension, int upgLevel)
{
    InExtension += DefaultExtension * default.ZedTimeExtension[upgLevel - 1];
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_EndlessRampage]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_EndlessRampage"

    UpgradeName="Endless Rampage"
    upgradeDescription(0)="<font color=\"#00ffff\">Zed Time</font> lasts <font color=\"#ffff00\">+50%</font> longer."
    upgradeDescription(1)="<font color=\"#00ffff\">Zed Time</font> lasts <font color=\"#ffff00\">+100%</font> longer."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_EndlessRampage'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_EndlessRampage_Deluxe'

    Name="Default__DKUpgrade_Skill_EndlessRampage"
}
