// ===================================================================
// DKUpgrade_Skill_ApexCharge - Detonator Skill
//
// "Apex Charge" - Bosses are special. Boss kills outside the active
// window instantly fill the counter and flip to active mode. Boss
// kills during the active window deal scaled detonation bonuses.
//
// Standard: Boss kill instantly fills the counter (auto-flip to
//           active). In-window detonations on bosses deal 1.5x damage
//           and 1.25x radius.
// Deluxe:   In-window detonations on bosses deal 2.5x damage and
//           1.5x radius. Boss kills outside the window also bank
//           +50% pre-charge for the cycle that starts after this
//           active window expires.
//
// Pure signal skill -- all logic lives in the Detonator helper.
// ===================================================================
class DKUpgrade_Skill_ApexCharge extends DKUpgrade_Skill;

// Signal presence to Detonator Helper via ExtensionFuncInteger.
// Returns upgLevel (1=standard, 2=deluxe) when queried with "DetonatorApexCharge".
static simulated function ExtensionFuncInteger(out int InValue, int DefaultValue, int upgLevel, string Identifier,
    KFWeapon MyKFW, KFPawn OwnerPawn, optional int InputInt, optional float InputFloat, optional name InputClassName,
    optional Object InputObject1, optional Object InputObject2, optional Object InputObject3)
{
    if (Identifier ~= "DetonatorApexCharge")
        InValue = upgLevel;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_ApexCharge]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_ApexCharge"

    UpgradeName="Apex Charge"
    upgradeDescription(0)="Boss kills <font color=\"#FFD700\">instantly fill</font> the counter. In-window boss detonations: <font color=\"#FF4444\">1.5x dmg, 1.25x radius</font>."
    upgradeDescription(1)="In-window boss detonations: <font color=\"#FF4444\">2.5x dmg, 1.5x radius</font>. Boss kills outside window also <font color=\"#77d914\">bank +50%</font> for the next cycle."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ApexCharge'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ApexCharge_Deluxe'

    Name="Default__DKUpgrade_Skill_ApexCharge"
}
