// ===================================================================
// DKUpgrade_Skill_FastHands - Active ability: temporary fire rate boost
// Standard: +40% fire rate for 10s
// Deluxe: +60% fire rate for 10s
// Cooldown: 60s after effect ends
//
// RENAMED from DKUpgrade_Skill_QuickDraw so the class/INI name matches the
// display name and no longer collides with ZR's WMUpgrade_Skill_QuickDraw on
// the same perk. The old class remains as a config stub for one release so
// admin-tuned values migrate; old SkillPath entries in the ZR skill list are
// rewritten automatically by the GameInfo boot migration.
// ===================================================================
class DKUpgrade_Skill_FastHands extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> FireRateBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		// Carry over admin tuning from the pre-rename section
		// [ZedternalRBPerkpackage.DKUpgrade_Skill_QuickDraw] if it exists,
		// otherwise seed the standard defaults.
		if (class'DKUpgrade_Skill_QuickDraw'.default.FireRateBonus.Length >= 2)
		{
			default.FireRateBonus[0] = class'DKUpgrade_Skill_QuickDraw'.default.FireRateBonus[0];
			default.FireRateBonus[1] = class'DKUpgrade_Skill_QuickDraw'.default.FireRateBonus[1];
		}
		else
		{
			default.FireRateBonus[0] = 0.4f;
			default.FireRateBonus[1] = 0.6f;
		}

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_FastHands_Helper Helper;
	local DKPlayerController DKPC;
	local bool bFound;
	
	if (KFPawn_Human(OwnerPawn) == None || OwnerPawn.Role != Role_Authority)
		return;
	
	DKPC = DKPlayerController(OwnerPawn.Controller);
	if (DKPC == None)
	{
		`log("DKUpgrade_Skill_FastHands: ERROR - Player does not have DKPlayerController!");
		return;
	}
	
	bFound = false;
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_FastHands_Helper', Helper)
	{
		bFound = true;
		Helper.SetTier(upgLevel);
		`log("DKUpgrade_Skill_FastHands: Updated existing helper to tier" @ upgLevel);
		break;
	}
	
	if (!bFound)
	{
		Helper = OwnerPawn.Spawn(class'DKUpgrade_Skill_FastHands_Helper', OwnerPawn);
		if (Helper != None)
		{
			Helper.Initialize(upgLevel, KFPawn_Human(OwnerPawn), DKPC);
			`log("DKUpgrade_Skill_FastHands: Spawned helper for" @ OwnerPawn.PlayerReplicationInfo.PlayerName);
		}
		else
		{
			`log("DKUpgrade_Skill_FastHands: ERROR - Failed to spawn helper!");
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_FastHands_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_FastHands_Helper', Helper)
	{
		Helper.Cleanup();
		Helper.Destroy();
		`log("DKUpgrade_Skill_FastHands: Cleaned up helper");
	}
}

static simulated function ModifyRateOfFire(out float InRate, float DefaultRate, int upgLevel, KFWeapon KFW)
{
	local DKUpgrade_Skill_FastHands_Helper Helper;
	local KFPawn OwnerPawn;
	
	if (KFW == None || KFW.Owner == None)
		return;
	
	OwnerPawn = KFPawn(KFW.Owner);
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_FastHands_Helper', Helper)
	{
		if (Helper.bActive)
		{
			// InRate is the fire INTERVAL (smaller = faster). Composed like
			// ZR's WMUpgrade_Weapon_RateOfFire so other contributors survive.
			InRate = DefaultRate / (DefaultRate / InRate + default.FireRateBonus[upgLevel - 1]);
		}
		break;
	}
}

defaultproperties
{
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_FastHands]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_FastHands"

	UpgradeName="Fast Hands"
	
	upgradeDescription(0)="Unlocks <font color=\"#66cc00\">Fast Hands</font> active ability: <font color=\"#00ffff\">+40% fire rate</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	upgradeDescription(1)="Unlocks <font color=\"#66cc00\">Fast Hands (Deluxe)</font> active ability: <font color=\"#00ffff\">+60% fire rate</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_QuickDraw'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_QuickDraw_Deluxe'
	
	Name="Default__DKUpgrade_Skill_FastHands"
}
