// ===================================================================
// DKUpgrade_Skill_EmpathicLink
// Pain is distributed across the hivemind's neural web - each blow
// is dampened as the collective absorbs the shock, leaving you
// standing when others would fall.
//
// Normal: 15% damage reduction
// Deluxe: 25% damage reduction
// ===================================================================
class DKUpgrade_Skill_EmpathicLink extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DamageReduction;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageReduction[0] = 0.15f;
		default.DamageReduction[1] = 0.25f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	InDamage -= Round(float(DefaultDamage) * default.DamageReduction[upgLevel - 1]);
	if (InDamage < 0)
		InDamage = 0;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_EmpathicLink]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_EmpathicLink"

	UpgradeName="Empathic Link"
	UpgradeDescription(0)="Pain is distributed across the <font color=\"#9370DB\">hivemind's neural web</font>. Take <font color=\"#00FF7F\">15% less damage</font> from all sources."
	UpgradeDescription(1)="Pain is distributed across the <font color=\"#9370DB\">hivemind's neural web</font>. Take <font color=\"#00FF7F\">25% less damage</font> from all sources."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_EmpathicLink'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_EmpathicLink_Deluxe'

	Name="Default__DKUpgrade_Skill_EmpathicLink"
}
