class DKUpgrade_Skill_PetrifyingPresence extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> PetrifyChance;
var config array<float> StumbleMultiplier;
var config array<float> DamageMultiplier;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.PetrifyChance[0] = 0.1f;
		default.PetrifyChance[1] = 0.2f;
		default.StumbleMultiplier[0] = 2.0f;
		default.StumbleMultiplier[1] = 2.0f;
		default.DamageMultiplier[0] = 0.0f;
		default.DamageMultiplier[1] = 0.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyStumblePowerPassive(out float stumblePowerFactor, int upgLevel)
{
    // Intentionally empty. Stumble is applied as a real, gated special-move on proc in
    // the helper (ApplyPetrificationEffects), not as a global passive scalar -- a
    // passive here would scale stumble on ALL hits/targets, not just petrified ones.
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_PetrifyingPresence_Helper PetrifyHelper;
    local float RandValue;
    local bool bPetrify;
    
    if (DamageInstigator == None || DamageInstigator.Pawn == None || MyKFPM == None) return;
    
    // Get helper to manage petrification effects
    PetrifyHelper = GetHelper(DamageInstigator.Pawn);
    if (PetrifyHelper == None) return;
    
    // Roll for petrification chance
    RandValue = FRand();
    bPetrify = (RandValue <= default.PetrifyChance[upgLevel - 1]);
    
    if (bPetrify)
    {
        // Apply petrification effect to the monster
        PetrifyHelper.PetrifyMonster(MyKFPM, upgLevel);
    }
    
    // Apply bonus damage if monster is petrified
    if (PetrifyHelper.IsMonsterPetrified(MyKFPM) && upgLevel == 2)
    {
        InDamage += Round(float(DefaultDamage) * default.DamageMultiplier[upgLevel - 1]);
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_PetrifyingPresence_Helper PetrifyHelper;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_PetrifyingPresence_Helper', PetrifyHelper)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            PetrifyHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_PetrifyingPresence_Helper', OwnerPawn);
            PetrifyHelper.UpgradeLevel = upgLevel;
        }
    }
}

static function DKUpgrade_Skill_PetrifyingPresence_Helper GetHelper(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_PetrifyingPresence_Helper PetrifyHelper;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_PetrifyingPresence_Helper', PetrifyHelper)
        {
            return PetrifyHelper;
        }

        // Create one if needed
        PetrifyHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_PetrifyingPresence_Helper', OwnerPawn);
    }

    return PetrifyHelper;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_PetrifyingPresence_Helper PetrifyHelper;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_PetrifyingPresence_Helper', PetrifyHelper)
        {
            PetrifyHelper.Destroy();
        }
    }
}

defaultproperties
{
    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_PetrifyingPresence]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_PetrifyingPresence"

    UpgradeName="Petrifying Presence"
    UpgradeDescription(0)="<font color=\"#8B008B\">Petrifying Presence:</font> Your attacks have <font color=\"#FFFFFF\">10% chance</font> to <font color=\"#FFD700\">petrify</font> enemies, <font color=\"#FF6666\">staggering</font> them. Giant ZEDs and bosses resist the stagger."
    UpgradeDescription(1)="<font color=\"#8B008B\">Petrifying Presence (Deluxe):</font> Your attacks have <font color=\"#FFFFFF\">20% chance</font> to <font color=\"#FFD700\">petrify</font> enemies, <font color=\"#FF6666\">staggering</font> them and making them take <font color=\"#66FF66\">+50% damage</font> from all sources. Giant ZEDs and bosses resist the stagger but still take the bonus damage."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PetrifyingPresence'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PetrifyingPresence_Deluxe'
    
    Name="Default__DKUpgrade_Skill_PetrifyingPresence"
}