Class DKUpgrade_Perk_Warlord extends DKUpgrade_Perk
	config(ZedternalUnlimited);

var config float RifleDamage, HeadshotDamage, ReloadSpeed, RecoilReduction, WeaponSwitchSpeed, AmmoCapacity;
var config int GrenadeCapacity;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.RifleDamage = 0.02f;
		default.HeadshotDamage = 0.02f;
		default.ReloadSpeed = 0.02f;
		default.RecoilReduction = 0.02f;
		default.WeaponSwitchSpeed = 0.02f;
		default.AmmoCapacity = 0.02f;
		default.GrenadeCapacity = 1;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (IsRifleWeapon(MyKFW))
	{
		// Base rifle damage bonus
		InDamage += Round(float(DefaultDamage) * default.RifleDamage * upgLevel);
		
		// Additional headshot damage bonus
		if (HitZoneIdx == HZI_HEAD)
			InDamage += Round(float(DefaultDamage) * default.HeadshotDamage * upgLevel);
	}
}

static simulated function GetReloadRateScalePassive(out float reloadRateFactor, int upgLevel)
{
	reloadRateFactor += default.ReloadSpeed * upgLevel;
}

static simulated function ModifyRecoilPassive(out float recoilFactor, int upgLevel)
{
	recoilFactor -= default.RecoilReduction * upgLevel;
}

static simulated function ModifyWeaponSwitchTimePassive(out float switchTimeFactor, int upgLevel)
{
	switchTimeFactor -= default.WeaponSwitchSpeed * upgLevel;
}

static simulated function ModifySpareAmmoAmountPassive(out float spareAmmoFactor, int upgLevel)
{
	spareAmmoFactor += default.AmmoCapacity * upgLevel;
}

static simulated function ModifyMagSizeAndNumberPassive(out float magazineCapacityFactor, int upgLevel)
{
	magazineCapacityFactor += default.AmmoCapacity * upgLevel;
}

static simulated function ModifySpareGrenadeAmount(out int SpareGrenade, int DefaultSpareGrenade, int upgLevel)
{
	if (upgLevel >= 5)
		SpareGrenade += default.GrenadeCapacity * (upgLevel / 5);
}

static function bool IsRifleWeapon(KFWeapon KFW)
{
	if (KFW == None)
		return False;
		
	if (IsWeaponOnSpecificPerk(KFW, class'KFGame.KFPerk_Commando'))
	{
		return (KFW.InstantHitDamage[0] >= 35 || 
				KFW.default.FireInterval[0] >= 0.08);
	}
	return (InStr(PathName(KFW.Class), "Rifle") != INDEX_NONE ||
			InStr(PathName(KFW.Class), "rifle") != INDEX_NONE);
}

defaultproperties
{
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Perk_Warlord]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Perk_Warlord"
    LocalizeDescriptionLineCount=7

	UpgradeName="Warlord"
	UpgradeDescription(0)="Increase <font color=\"#15d7fa\">Rifle Damage</font> by <font color=\"#77d914\">%x%%</font>."
	UpgradeDescription(1)="Increase <font color=\"#15d7fa\">Headshot Damage</font> with rifles by <font color=\"#77d914\">%x%%</font>."
	UpgradeDescription(2)="Increase <font color=\"#15d7fa\">Reload Speed</font> by <font color=\"#77d914\">%x%%</font>."
	UpgradeDescription(3)="Reduce <font color=\"#15d7fa\">Recoil</font> by <font color=\"#77d914\">%x%%</font>."
	UpgradeDescription(4)="Increase <font color=\"#15d7fa\">Weapon Switch Speed</font> by <font color=\"#77d914\">%x%%</font>."
	UpgradeDescription(5)="Increase <font color=\"#15d7fa\">Ammunition Capacity</font> by <font color=\"#77d914\">%x%%</font>."
	UpgradeDescription(6)="Increase <font color=\"#15d7fa\">Grenade Capacity</font> by <font color=\"#77d914\">+1</font> every <font color=\"#FFFFFF\">5 levels</font>."
	
	PerkBonus(0)=(baseValue=0, incValue=2, maxValue=-1)
	PerkBonus(1)=(baseValue=0, incValue=2, maxValue=-1)
	PerkBonus(2)=(baseValue=0, incValue=2, maxValue=-1)
	PerkBonus(3)=(baseValue=0, incValue=2, maxValue=-1)
	PerkBonus(4)=(baseValue=0, incValue=2, maxValue=-1)
	PerkBonus(5)=(baseValue=0, incValue=2, maxValue=-1)
	PerkBonus(6)=(baseValue=0, incValue=1, maxValue=-1)
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_0'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_1'
	UpgradeIcon(2)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_2'
	UpgradeIcon(3)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_3'
	UpgradeIcon(4)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_4'
	UpgradeIcon(5)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(6)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(7)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(8)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(9)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(10)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(11)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(12)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(13)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(14)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(15)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(16)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(17)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(18)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(19)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	UpgradeIcon(20)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	
	// Legacy (hand-made) artwork icons
	LegacyUpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_0'
	LegacyUpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_1'
	LegacyUpgradeIcon(2)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_2'
	LegacyUpgradeIcon(3)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_3'
	LegacyUpgradeIcon(4)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_4'
	LegacyUpgradeIcon(5)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(6)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(7)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(8)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(9)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(10)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(11)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(12)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(13)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(14)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(15)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(16)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(17)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(18)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(19)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'
	LegacyUpgradeIcon(20)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Warlord_Legacy_Rank_5'

	Name="Default__DKUpgrade_Perk_Warlord"
}