// ===================================================================
// DKUpgrade_Skill_DarkPact
//
// "Dark Pact"
// Your prophecy rewards are amplified, but so are your doom penalties.
// Every wave is higher stakes.
//
// Standard: +50% reward, +50% doom
// Deluxe:   +75% reward, +50% doom
// ===================================================================
class DKUpgrade_Skill_DarkPact extends DKUpgrade_Skill;

// --- Helper spawning ---
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_DarkPact_Helper H;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == ROLE_Authority)
    {
        bFound = false;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_DarkPact_Helper', H)
        {
            bFound = true;
            H.Initialize(upgLevel);
            break;
        }

        if (!bFound)
        {
            H = OwnerPawn.Spawn(class'DKUpgrade_Skill_DarkPact_Helper', OwnerPawn);
            if (H != None)
                H.Initialize(upgLevel);
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_DarkPact_Helper H;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_DarkPact_Helper', H)
        {
            H.Cleanup();
            H.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_DarkPact]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_DarkPact"

    UpgradeName="Dark Pact"
    UpgradeDescription(0)="Prophecy rewards are <font color=\"#15d7fa\">+50% stronger</font>, but doom penalties are also <font color=\"#ff0000\">+50% harsher</font>."
    UpgradeDescription(1)="Prophecy rewards are <font color=\"#15d7fa\">+75% stronger</font>, but doom penalties are also <font color=\"#ff0000\">+50% harsher</font>."

    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_DarkPact_Deluxe'

    Name="Default__DKUpgrade_Skill_DarkPact"
}
