// ===================================================================
// DKUpgrade_Skill_ShatterPoint — Artificer Skill
//
// "Your hits accumulate Stress Fractures on each target. When total
//  damage dealt to a single zed exceeds a threshold of its max HP,
//  your next hit finds the Shatter Point — dealing a massive burst
//  equal to a percentage of the target's maximum health.
//  The fracture tracker then resets and can trigger again."
//
// Works with ALL weapons.
//
// Normal:  Threshold = 30% of target's max HP dealt
//          Burst     = 15% of target's max HP as bonus damage
// Deluxe:  Threshold = 25% of target's max HP dealt
//          Burst     = 25% of target's max HP as bonus damage
//
// Against trash (low HP): procs almost instantly, essentially overkill.
// Against large zeds/bosses: a real investment → payoff cycle.
// Can trigger multiple times on the same target (e.g., boss fights).
//
// Hook: ModifyDamageGiven
// Helper: DKUpgrade_Skill_ShatterPoint_Helper (damage tracking per target)
// ===================================================================
class DKUpgrade_Skill_ShatterPoint extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DamageThreshold;   // % of max HP that must be dealt before Shatter triggers
var config array<float> BurstPercent;      // % of max HP dealt as bonus damage on Shatter
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageThreshold[0] = 0.30f;
		default.DamageThreshold[1] = 0.25f;
		default.BurstPercent[0] = 0.15f;
		default.BurstPercent[1] = 0.25f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_ShatterPoint_Helper H;

    if (DamageInstigator == None || DamageInstigator.Pawn == None || MyKFPM == None || MyKFW == None)
        return;

    H = GetHelper(DamageInstigator.Pawn, upgLevel);
    if (H == None)
        return;

    H.OnHit(MyKFPM, InDamage, DefaultDamage, upgLevel);
}

// ===================================================================
// HELPER MANAGEMENT
// ===================================================================

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == ROLE_Authority)
        GetHelper(OwnerPawn, upgLevel);
}

static function DKUpgrade_Skill_ShatterPoint_Helper GetHelper(Pawn OwnerPawn, int upgLevel)
{
    local DKUpgrade_Skill_ShatterPoint_Helper H;

    if (KFPawn_Human(OwnerPawn) == None)
        return None;

    foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ShatterPoint_Helper', H)
    {
        H.UpgradeLevel = upgLevel;
        return H;
    }

    // Spawn if not found
    if (OwnerPawn.Role == ROLE_Authority)
    {
        H = OwnerPawn.Spawn(class'DKUpgrade_Skill_ShatterPoint_Helper', OwnerPawn);
        if (H != None)
            H.UpgradeLevel = upgLevel;
    }

    return H;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_ShatterPoint_Helper H;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ShatterPoint_Helper', H)
        {
            H.Destroy();
        }
    }
}

defaultproperties
{


    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_ShatterPoint]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_ShatterPoint"

    UpgradeName="Shatter Point"
    UpgradeDescription(0)="Hits build <font color=\"#FFD700\">Stress Fractures</font>. After dealing <font color=\"#FFFFFF\">30%</font> of a target's max HP, trigger a <font color=\"#FFD700\">Shatter</font> for <font color=\"#FFFFFF\">15%</font> max HP bonus damage"
    UpgradeDescription(1)="Hits build <font color=\"#FFD700\">Stress Fractures</font>. After dealing <font color=\"#FFFFFF\">25%</font> of a target's max HP, trigger a <font color=\"#FFD700\">Shatter</font> for <font color=\"#FFFFFF\">25%</font> max HP bonus damage"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ShatterPoint'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ShatterPoint_Deluxe'

    Name="Default__DKUpgrade_Skill_ShatterPoint"
}
