// ===================================================================
// DKUpgrade_Skill_AcceleratedDecay - Time-Ravaged Wounds
// Theme: Accelerate time inside wounds. All DoT effects deal more
//        damage. Deluxe also boosts ground fire and napalm DoTs.
// Hooks: ModifyDoTScaler
// ===================================================================
class DKUpgrade_Skill_AcceleratedDecay extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DoTBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DoTBonus[0] = 0.4f;
		default.DoTBonus[1] = 0.8f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDoTScaler(out float InDoTScaler, float DefaultDotScaler, int upgLevel, optional class<KFDamageType> KFDT, optional bool bNapalmInfected)
{
	InDoTScaler += DefaultDotScaler * default.DoTBonus[upgLevel - 1];
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_AcceleratedDecay]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_AcceleratedDecay"

	UpgradeName="Accelerated Decay"
	upgradeDescription(0)="<font color=\"#9632ff\">Accelerate time inside wounds</font>. All damage-over-time effects deal <font color=\"#d8b0ff\">+40%</font> more damage."
	upgradeDescription(1)="<font color=\"#9632ff\">Accelerate time inside wounds</font>. All damage-over-time effects deal <font color=\"#d8b0ff\">+80%</font> more damage."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AcceleratedDecay'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AcceleratedDecay_Deluxe'

	Name="Default__DKUpgrade_Skill_AcceleratedDecay"
}
