class DKUpgrade_Skill_CorporateBailout extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> BailoutPercentage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.BailoutPercentage[0] = 0.25f;
		default.BailoutPercentage[1] = 0.50f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function PlayerDied(int upgLevel, KFPlayerController KFPC)
{
    // This triggers when ANY player dies - we need to check if the bailout provider is alive
    local KFPlayerController BailoutProvider;
    local KFPlayerReplicationInfo BailoutPRI, DeadPlayerPRI;
    local int BailoutAmount;
    local float BailoutRate;
    
    if (KFPC == None || upgLevel <= 0) return;
    
    DeadPlayerPRI = KFPlayerReplicationInfo(KFPC.PlayerReplicationInfo);
    if (DeadPlayerPRI == None) return;
    
    // Find a living player with this skill to provide the bailout
    foreach KFPC.WorldInfo.AllControllers(class'KFPlayerController', BailoutProvider)
    {
        if (BailoutProvider != KFPC && BailoutProvider.Pawn != None && 
            BailoutProvider.Pawn.IsAliveAndWell())
        {
            // Check if they have this skill
            if (HasCorporateBailoutSkill(BailoutProvider))
            {
                BailoutPRI = KFPlayerReplicationInfo(BailoutProvider.PlayerReplicationInfo);
                if (BailoutPRI != None && BailoutPRI.Score > 0)
                {
                    // Calculate bailout amount
                    BailoutRate = default.BailoutPercentage[GetBailoutSkillLevel(BailoutProvider) - 1];
                    BailoutAmount = int(BailoutPRI.Score * BailoutRate);
                    
                    if (BailoutAmount > 0)
                    {
                        // Give bailout to dead player
                        DeadPlayerPRI.AddDosh(BailoutAmount);
                        
                        // Notify both players
                        KFPC.ClientMessage("CORPORATE BAILOUT! Received " $ BailoutAmount $ " Dosh from " $ BailoutPRI.PlayerName, 'CriticalEvent');
                        BailoutProvider.ClientMessage("BAILOUT PROVIDED: Gave " $ BailoutAmount $ " Dosh to " $ DeadPlayerPRI.PlayerName, 'Event');
                        
                        break; // Only one bailout per death
                    }
                }
            }
        }
    }
}

// Helper function to check if player has this skill (simplified check)
static function bool HasCorporateBailoutSkill(KFPlayerController KFPC)
{
    // In a real implementation, you'd check the skill system
    // For now, we assume they have it if they're calling this function
    return true;
}

// Helper function to get skill level (simplified)
static function int GetBailoutSkillLevel(KFPlayerController KFPC)
{
    // In a real implementation, you'd check the actual skill level
    // For now, assume deluxe (level 2) - you'd integrate with skill system
    return 2;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_CorporateBailout]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_CorporateBailout"

    UpgradeName="Corporate Bailout"
    
    upgradeDescription(0)="When a teammate dies, they respawn with <font color=\"#ffaa33\">25%</font> of your current dosh as a <font color=\"#00ff00\">bonus</font> (you keep yours)."
    upgradeDescription(1)="When a teammate dies, they respawn with <font color=\"#ffaa33\">50%</font> of your current dosh as a <font color=\"#00ff00\">bonus</font> (you keep yours)."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CorporateBailout'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CorporateBailout_Deluxe'

    Name="Default__DKUpgrade_Skill_CorporateBailout"
}