class DKUpgrade_Skill_Wildfire extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> GroundFireDamage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.GroundFireDamage[0] = 0.50f;
		default.GroundFireDamage[1] = 1.20f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function bool CanSpreadNapalm(int upgLevel, KFPawn OwnerPawn)
{
	return True;
}

static simulated function bool IsGroundFireActive(int upgLevel, KFPawn OwnerPawn)
{
	return True;
}

static simulated function bool IsRangeActive(int upgLevel, KFPawn OwnerPawn)
{
	return (upgLevel > 1);
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (DamageType != None && ClassIsChildOf(DamageType, class'KFDT_Fire_Ground'))
		InDamage += Round(float(DefaultDamage) * default.GroundFireDamage[upgLevel - 1]);
}

static simulated function RevertUpgradeChanges(Pawn OwnerPawn)
{
	if (OwnerPawn != None && KFPlayerReplicationInfo(OwnerPawn.PlayerReplicationInfo) != None)
	{
		KFPlayerReplicationInfo(OwnerPawn.PlayerReplicationInfo).bSplashActive = False;
		KFPlayerReplicationInfo(OwnerPawn.PlayerReplicationInfo).bExtraFireRange = False;
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Wildfire]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Wildfire"

	UpgradeName="Wildfire"
	upgradeDescription(0)="Your <font color=\"#e80948\">Fire</font> spreads between ZEDs. Your weapons leave <font color=\"#e80948\">Ground Fire</font> that deals <font color=\"#e85009\">50%</font> more damage."
	upgradeDescription(1)="Your <font color=\"#e80948\">Fire</font> spreads between ZEDs. Your weapons leave <font color=\"#e80948\">Ground Fire</font> that deals <font color=\"#e85009\">120%</font> more damage. Increases your <font color=\"#e80948\">Fire Range</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Wildfire'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Wildfire_Deluxe'

	Name="Default__DKUpgrade_Skill_Wildfire"
}
