class DKUpgrade_Skill_DanceOfDeath extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Dance of Death: The Reaper deals more damage while in motion.
// Bonus scales from 0% (stationary) to max (full speed movement).
// Rewards aggressive, mobile play styles.

var config array<float> MaxDamageBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MaxDamageBonus[0] = 0.20f;
		default.MaxDamageBonus[1] = 0.50f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local KFPawn OwnerPawn;
	local float SpeedRatio, CurrentSpeed;

	if (DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		OwnerPawn = KFPawn(DamageInstigator.Pawn);
		if (OwnerPawn != None && OwnerPawn.GroundSpeed > 0)
		{
			// Use horizontal velocity only (ignore vertical/falling)
			CurrentSpeed = VSize2D(OwnerPawn.Velocity);

			// Minimum movement threshold to prevent tiny drift from giving bonus
			if (CurrentSpeed > 50.0f)
			{
				SpeedRatio = FMin(CurrentSpeed / OwnerPawn.GroundSpeed, 1.0f);
				InDamage += Round(float(DefaultDamage) * default.MaxDamageBonus[upgLevel - 1] * SpeedRatio);
			}
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_DanceOfDeath]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_DanceOfDeath"

	UpgradeName="Dance of Death"
	UpgradeDescription(0)="<font color=\"#CC0000\">Dance of Death:</font> Deal up to <font color=\"#FFFFFF\">+20%</font> <font color=\"#FFD700\">bonus damage</font> while moving. Bonus <font color=\"#66CCFF\">scales with speed</font>. Stand still and you're just a mortal."
	UpgradeDescription(1)="<font color=\"#CC0000\">Dance of Death:</font> Deal up to <font color=\"#FFFFFF\">+50%</font> <font color=\"#FFD700\">bonus damage</font> while moving. Bonus <font color=\"#66CCFF\">scales with speed</font>. Stand still and you're just a mortal."

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_DanceOfDeath'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_DanceOfDeath_Deluxe'

	Name="Default__DKUpgrade_Skill_DanceOfDeath"
}
