class DKUpgrade_Skill_InfernoRounds extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Inferno Rounds: Non-fire attacks have a chance to apply a fire DoT
// Probability scales with damage dealt (higher damage = higher chance, capped at MaxDamage)
// Normal: 20% DoT factor | Deluxe: 50% DoT factor

var const class<KFDamageType> InfernoDT;

var config float InfernoProbability;
var config float InfernoDamageCap;
var config array<float> DamageFactor;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.InfernoProbability = 1.0f;
		default.InfernoDamageCap = 75.0f;
		default.DamageFactor[0] = 0.2f;
		default.DamageFactor[1] = 0.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	// Only trigger on non-fire damage types (the inverse of Napalm's approach)
	if (DamageType != None
		&& DamageType != default.InfernoDT
		&& !ClassIsChildOf(DamageType, class'KFDT_Fire')
		&& DamageInstigator != None
		&& MyKFPM != None
		&& FRand() < (float(DefaultDamage) * default.InfernoProbability / default.InfernoDamageCap))
	{
		MyKFPM.ApplyDamageOverTime(int(float(DefaultDamage) * default.DamageFactor[upgLevel - 1]), DamageInstigator, default.InfernoDT);
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_InfernoRounds]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_InfernoRounds"

	InfernoDT=class'DKDT_InfernoRounds'

	UpgradeName="Inferno Rounds"
	UpgradeDescription(0)="Non-fire attacks have a chance to apply <font color=\"#e80948\">fire DoT</font>. Chance scales with damage dealt."
	UpgradeDescription(1)="Non-fire attacks have a higher chance to apply <font color=\"#e80948\">fire DoT</font> with <font color=\"#e85009\">increased</font> burn damage. Chance scales with damage dealt."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_InfernoRounds'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_InfernoRounds_Deluxe'

	Name="Default__DKUpgrade_Skill_InfernoRounds"
}
