// ===================================================================
// DKUpgrade_Skill_PocketDimension - Symbiotic Storage
// Theme: Fold space inside the Symbiote to carry more gear.
//        Deluxe also makes projectiles immune to duds.
// Hooks: ApplyWeightLimits, ModifySpareGrenadeAmount, ShouldNeverDud
// ===================================================================
class DKUpgrade_Skill_PocketDimension extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> WeightBonus;
var config array<int> GrenadeBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.WeightBonus[0] = 3;
		default.WeightBonus[1] = 5;
		default.GrenadeBonus[0] = 1;
		default.GrenadeBonus[1] = 2;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ApplyWeightLimits(out int InWeightLimit, int DefaultWeightLimit, int upgLevel)
{
	InWeightLimit += default.WeightBonus[upgLevel - 1];
}

static simulated function ModifySpareGrenadeAmount(out int SpareGrenade, int DefaultSpareGrenade, int upgLevel)
{
	SpareGrenade += default.GrenadeBonus[upgLevel - 1];
}

static simulated function bool ShouldNeverDud(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	return (upgLevel > 1);
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_PocketDimension]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_PocketDimension"

	UpgradeName="Pocket Dimension"
	upgradeDescription(0)="<font color=\"#9632ff\">Fold space within the Symbiote</font>. Carry capacity increased by <font color=\"#d8b0ff\">+3</font> weight blocks. Carry <font color=\"#d8b0ff\">+1</font> additional grenade."
	upgradeDescription(1)="<font color=\"#9632ff\">Fold space within the Symbiote</font>. Carry capacity increased by <font color=\"#d8b0ff\">+5</font> weight blocks. Carry <font color=\"#d8b0ff\">+2</font> additional grenades. Projectiles <font color=\"#FFFFFF\">never dud</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PocketDimension'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PocketDimension_Deluxe'

	Name="Default__DKUpgrade_Skill_PocketDimension"
}
