// ===================================================================
// DKUpgrade_Skill_SiphonCascade - Chain Reaction Siphoning
// When a siphoned enemy dies, a blood burst applies siphon to all
// enemies within a radius. Kill one tagged enemy in a crowd to tag
// the entire group. Creates chain-reaction siphon spreading.
//
// Standard: 5m burst radius on siphoned kill
// Deluxe:   8m burst radius on siphoned kill
//
// REQUIRES: DKUpgrade_Perk_Parasite_Helper must expose:
//   - IsSiphoned(KFPawn_Monster) : bool
//   - ApplySiphonToTarget(KFPawn_Monster) : void
//   - GetSiphonedEnemyCount() : int
//   - GetMaxSiphons() : int
// ===================================================================
class DKUpgrade_Skill_SiphonCascade extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> BurstRadius;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.BurstRadius[0] = 500.0f;
		default.BurstRadius[1] = 800.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// ===================================================================
// On Kill: If target was siphoned, spread siphon to nearby enemies
// ===================================================================
static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
	optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
	optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
	optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Perk_Parasite_Helper ParasiteHelper;
	local KFPawn_Monster KFPM;
	local float RadiusSq;

	if (DamageInstigator == None || DamageInstigator.Pawn == None || MyKFPM == None)
		return;

	// Check if this is a killing blow
	if (MyKFPM.Health - InDamage > 0)
		return;

	ParasiteHelper = GetParasiteHelper(DamageInstigator.Pawn);
	if (ParasiteHelper == None)
		return;

	// Only triggers on siphoned enemies
	if (!ParasiteHelper.IsSiphoned(MyKFPM))
		return;

	// Spread siphon to nearby enemies
	RadiusSq = default.BurstRadius[upgLevel - 1] ** 2;

	foreach DamageInstigator.Pawn.WorldInfo.AllPawns(class'KFPawn_Monster', KFPM)
	{
		// Skip the dying target
		if (KFPM == MyKFPM)
			continue;

		// Skip already dead
		if (KFPM.Health <= 0 || !KFPM.IsAliveAndWell())
			continue;

		// Skip already siphoned
		if (ParasiteHelper.IsSiphoned(KFPM))
			continue;

		// Check if at max siphons
		if (ParasiteHelper.GetSiphonedEnemyCount() >= ParasiteHelper.GetMaxSiphons())
			break;

		// Check range from dying enemy
		if (VSizeSq(KFPM.Location - MyKFPM.Location) <= RadiusSq)
			ParasiteHelper.ApplySiphonToTarget(KFPM);
	}
}

// ===================================================================
// Find Parasite Perk Helper
// ===================================================================
static function DKUpgrade_Perk_Parasite_Helper GetParasiteHelper(Pawn OwnerPawn)
{
	local DKUpgrade_Perk_Parasite_Helper PHelper;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Perk_Parasite_Helper', PHelper)
			return PHelper;
	}

	return None;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_SiphonCascade]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_SiphonCascade"

	UpgradeName="Siphon Cascade"
	UpgradeDescription(0)="<font color=\"#B40028\">Siphon Cascade:</font> Killing a <font color=\"#FF6464\">siphoned</font> enemy spreads siphon to all enemies within <font color=\"#FFFFFF\">5m</font>"
	UpgradeDescription(1)="<font color=\"#FFD700\">[DELUXE]</font> <font color=\"#B40028\">Siphon Cascade:</font> Killing a <font color=\"#FF6464\">siphoned</font> enemy spreads siphon to all enemies within <font color=\"#FFFFFF\">8m</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SiphonCascade'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SiphonCascade_Deluxe'

	Name="Default__DKUpgrade_Skill_SiphonCascade"
}
