class DKUpgrade_Skill_LuckySalvage extends DKUpgrade_Skill;

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_LuckySalvage_Helper Helper;
    
    // Only track kills (when damage would be fatal)
    if (MyKFPM != None && DamageInstigator != None && InDamage >= MyKFPM.Health && MyKFPM.IsAliveAndWell())
    {
        // Find existing helper
        foreach DamageInstigator.Pawn.ChildActors(class'ZedternalRBPerkpackage.DKUpgrade_Skill_LuckySalvage_Helper', Helper)
        {
            break;
        }
        
        if (Helper == None && DamageInstigator.Pawn != None)
        {
            Helper = DamageInstigator.Pawn.Spawn(class'ZedternalRBPerkpackage.DKUpgrade_Skill_LuckySalvage_Helper', DamageInstigator.Pawn);
        }
        
        if (Helper != None)
        {
            Helper.OnZedKilled(upgLevel);
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_LuckySalvage_Helper Helper;
    
    foreach OwnerPawn.ChildActors(class'ZedternalRBPerkpackage.DKUpgrade_Skill_LuckySalvage_Helper', Helper)
    {
        Helper.Destroy();
        break;
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_LuckySalvage]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_LuckySalvage"

    UpgradeName="Lucky Salvage"
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_LuckySalvage'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_LuckySalvage_Deluxe'
    
    UpgradeDescription(0)="1% chance per 100 kills to find a random weapon. Weapons spawn with reduced ammo"
    UpgradeDescription(1)="2% chance per 100 kills to find a random weapon. Weapons spawn with more ammo and higher tier weapons are more likely"
    
    Name="Default__DKUpgrade_Skill_LuckySalvage"
}