// ===================================================================
// DKUpgrade_Skill_ChronoCarapace - Temporal Exoskeleton
// Theme: Symbiote hardens into a temporal shell during ZED Time,
//        reducing damage taken. Deluxe: lingering protection for
//        3 seconds after ZED Time ends.
// Hooks: ModifyDamageTaken (ZED Time gated + helper for lingering)
// ===================================================================
class DKUpgrade_Skill_ChronoCarapace extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> ZedTimeDR;
var config float LingeringDR;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ZedTimeDR[0] = 0.3f;
		default.ZedTimeDR[1] = 0.5f;
		default.LingeringDR = 0.15f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_ChronoCarapace_Helper Helper;

	if (OwnerPawn == None)
		return;

	// Full damage reduction during ZED Time
	if (OwnerPawn.WorldInfo.TimeDilation < 1.0)
	{
		InDamage -= Round(float(DefaultDamage) * default.ZedTimeDR[upgLevel - 1]);
	}
	else if (upgLevel > 1)
	{
		// Deluxe: lingering damage reduction after ZED Time
		Helper = GetHelper(OwnerPawn);
		if (Helper != None && Helper.bLingeringProtection)
			InDamage -= Round(float(DefaultDamage) * default.LingeringDR);
	}
}

// ===================================================================
// Helper Management (only spawned for Deluxe)
// ===================================================================
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_ChronoCarapace_Helper UPG;
	local bool bFound;

	// Only spawn helper for Deluxe (lingering effect)
	if (upgLevel > 1 && KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ChronoCarapace_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			OwnerPawn.Spawn(class'DKUpgrade_Skill_ChronoCarapace_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_ChronoCarapace_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_ChronoCarapace_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ChronoCarapace_Helper', UPG)
		{
			return UPG;
		}
	}

	return None;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_ChronoCarapace_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ChronoCarapace_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_ChronoCarapace]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_ChronoCarapace"

	UpgradeName="Chrono-Carapace"
	upgradeDescription(0)="During <font color=\"#9632ff\">ZED Time</font>, take <font color=\"#d8b0ff\">30%</font> less damage from all sources."
	upgradeDescription(1)="During <font color=\"#9632ff\">ZED Time</font>, take <font color=\"#d8b0ff\">50%</font> less damage. <font color=\"#FFFFFF\">Lingering Protection</font>: take <font color=\"#d8b0ff\">15%</font> less damage for <font color=\"#d8b0ff\">3</font> seconds after ZED Time ends."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ChronoCarapace'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ChronoCarapace_Deluxe'

	Name="Default__DKUpgrade_Skill_ChronoCarapace"
}
