// ===================================================================
// DKUpgrade_Skill_PrimordialVigor
//
// "Each form strengthens the vessel."
//
// Gain damage resistance based on the number of active buffs.
// The more forms you embody, the tougher your body becomes.
// Scales beautifully with Mimicry progression — a late-game
// Shapeshifter becomes increasingly hard to kill.
//
// Note: Originally designed as +HP per buff, but ModifyHealth
// doesn't receive OwnerPawn so helper lookup is impossible.
// DR per buff is functionally equivalent (more effective HP)
// and works cleanly with ModifyDamageTaken.
//
// Standard: -1.5% damage taken per active buff (max -22.5% at 15)
// Deluxe:   -2.5% damage taken per active buff (max -37.5% at 15)
// ===================================================================
class DKUpgrade_Skill_PrimordialVigor extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DRPerBuff;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DRPerBuff[0] = 0.015f;
		default.DRPerBuff[1] = 0.025f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// Helper lookup - reuses the Shapeshifter perk's static GetHelper
static simulated function DKUpgrade_Perk_Shapeshifter_Helper GetShapeshifterHelper(Pawn OwnerPawn)
{
    return class'DKUpgrade_Perk_Shapeshifter'.static.GetHelper(OwnerPawn);
}

static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    local DKUpgrade_Perk_Shapeshifter_Helper Helper;
    local int BuffCount;
    local float Reduction;

    if (OwnerPawn == None) return;

    Helper = GetShapeshifterHelper(OwnerPawn);
    if (Helper == None) return;

    BuffCount = Helper.CountActiveBits(Helper.ReplicatedBuffMask);
    if (BuffCount <= 0) return;

    Reduction = default.DRPerBuff[upgLevel - 1] * float(BuffCount);
    InDamage -= Round(float(DefaultDamage) * Reduction);
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_PrimordialVigor]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_PrimordialVigor"

    UpgradeName="Primordial Vigor"
    UpgradeDescription(0)="Reduce <font color=\"#15d7fa\">Damage Taken</font> by <font color=\"#77d914\">1.5%</font> per active Shapeshifter buff."
    UpgradeDescription(1)="Reduce <font color=\"#15d7fa\">Damage Taken</font> by <font color=\"#77d914\">2.5%</font> per active Shapeshifter buff."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PrimordialVigor'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PrimordialVigor_Deluxe'

    Name="Default__DKUpgrade_Skill_PrimordialVigor"
}
