class DKUpgrade_Skill_Reaper extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> HealthGain;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HealthGain[0] = 1;
		default.HealthGain[1] = 2;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_Reaper_Helper UPG;
    local bool bFound;
    
    if(KFPawn_Human(OwnerPawn) != none && OwnerPawn.Role == ROLE_Authority)
    {
        bFound = false;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Reaper_Helper', UPG)
        {
            bFound = true;
            break;
        }
        
        if(!bFound)
        {
            UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_Reaper_Helper', OwnerPawn);
            UPG.UpgradeLevel = upgLevel;
        }
    }
}

static function DKUpgrade_Skill_Reaper_Helper GetHelper(KFPawn OwnerPawn, int upgLevel)
{
    local DKUpgrade_Skill_Reaper_Helper UPG;
    
    if(KFPawn_Human(OwnerPawn) != none)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Reaper_Helper', UPG)
        {
            return UPG;
        }
        
        if(OwnerPawn.Role == ROLE_Authority)
        {
            UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_Reaper_Helper', OwnerPawn);
            UPG.UpgradeLevel = upgLevel;
        }
    }
    
    return UPG;
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_Reaper_Helper UPG;
    local KFPawn PlayerPawn;
    
    if(MyKFPM != none && DamageInstigator != none && MyKFPM.IsAliveAndWell() && (MyKFPM.Health - InDamage) <= 0)
    {
        if(IsLargeZED(MyKFPM))
        {
            PlayerPawn = KFPawn(DamageInstigator.Pawn);
            if(PlayerPawn != none)
            {
                UPG = GetHelper(PlayerPawn, upgLevel);
                if(UPG != none)
                {
                    UPG.AddPermanentHealth();
                }
            }
        }
    }  
}

static function bool IsLargeZED(KFPawn_Monster KFPM)
{
    return (KFPM.IsA('KFPawn_ZedFleshpound') || 
            KFPM.IsA('KFPawn_ZedScrake') || 
            KFPM.IsA('KFPawn_ZedPatriarch') || 
            KFPM.IsA('KFPawn_ZedHans') || 
            KFPM.IsA('KFPawn_ZedMatriarch') || 
            KFPM.IsA('KFPawn_ZedFleshpoundKing') ||
            KFPM.IsA('KFPawn_ZedBloatKing') ||
            KFPM.IsA('KFPawn_ZedBloatKingSubspawn'));
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_Reaper_Helper UPG;
    
    if(OwnerPawn != none)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Reaper_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Reaper]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Reaper"

    UpgradeName="Reaper"
    upgradeDescription(0)="Gain <font color=\"#84d6d0\">1 Permanent Health</font> for every <font color=\"#962ab9\">Large ZED</font> you kill."
    upgradeDescription(1)="Gain <font color=\"#84d6d0\">2 Permanent Health</font> for every <font color=\"#962ab9\">Large ZED</font> you kill."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Reaper'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Reaper_Deluxe'
    Name="Default__DKUpgrade_Skill_Reaper"
}