// ===================================================================
// DKUpgrade_Skill_KarmicBalance
//
// "Karmic Balance"
// Your total accumulated negative stats (from dooms) boost your
// damage output. For every 1% total negative accumulation you
// carry, gain bonus damage.
//
// Standard: +0.4% damage per 1% total negative accumulation
// Deluxe:   +0.5% damage per 1% total negative accumulation
//
// Example: Player has -6% AccDamage, -4% AccDamageResist, -10% AccHS
//          Total negative = 20%, so bonus = 20 * 0.4% = +8% damage (standard)
// ===================================================================
class DKUpgrade_Skill_KarmicBalance extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config float DamagePerNegativePoint;        // Standard: 0.004 per 1% negative
var config float DamagePerNegativePointDeluxe;  // Deluxe: 0.005 per 1% negative
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamagePerNegativePoint = 0.004f;
		default.DamagePerNegativePointDeluxe = 0.005f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
    optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
    optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
    optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Perk_Omen_Helper OH;
    local float TotalNegative;
    local float BonusPerPoint;

    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;

    foreach DamageInstigator.Pawn.ChildActors(class'DKUpgrade_Perk_Omen_Helper', OH)
    {
        // Sum all negative accumulations (as positive magnitude in percentage points)
        TotalNegative = 0.0f;

        if (OH.AccDamage < 0.0f)
            TotalNegative += Abs(OH.AccDamage) * 100.0f;
        if (OH.AccHeadshotDamage < 0.0f)
            TotalNegative += Abs(OH.AccHeadshotDamage) * 100.0f;
        if (OH.AccDamageResist < 0.0f)
            TotalNegative += Abs(OH.AccDamageResist) * 100.0f;
        if (OH.AccReloadSpeed < 0.0f)
            TotalNegative += Abs(OH.AccReloadSpeed) * 100.0f;
        if (OH.AccMoveSpeed < 0.0f)
            TotalNegative += Abs(OH.AccMoveSpeed) * 100.0f;

        if (TotalNegative > 0.0f)
        {
            if (upgLevel >= 2)
                BonusPerPoint = default.DamagePerNegativePointDeluxe;
            else
                BonusPerPoint = default.DamagePerNegativePoint;

            InDamage += Round(float(DefaultDamage) * BonusPerPoint * TotalNegative);
        }
        break;
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_KarmicBalance]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_KarmicBalance"

    UpgradeName="Karmic Balance"
    UpgradeDescription(0)="For every <font color=\"#ff0000\">1% total negative accumulation</font> from dooms, gain <font color=\"#15d7fa\">+0.4% damage</font>."
    UpgradeDescription(1)="For every <font color=\"#ff0000\">1% total negative accumulation</font> from dooms, gain <font color=\"#15d7fa\">+0.5% damage</font>."

    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_KarmicBalance_Deluxe'

    Name="Default__DKUpgrade_Skill_KarmicBalance"
}
