class DKUpgrade_Skill_Overkill extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> ExcessCarryMult;
var config int MaxStoredDamage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ExcessCarryMult[0] = 0.50f;
		default.ExcessCarryMult[1] = 0.75f;
		default.MaxStoredDamage = 500;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_Overkill_Helper UPG;
    local int StoredDamage;
    local int ExcessDamage;
    
    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;
    
    UPG = GetHelper(DamageInstigator.Pawn);
    if (UPG == None)
        return;
    
    // First, add any stored damage from previous overkill
    StoredDamage = UPG.ConsumeStoredDamage();
    if (StoredDamage > 0)
    {
        InDamage += StoredDamage;
    }
    
    // Then, check if this will kill and calculate new excess
    if (MyKFPM != None && MyKFPM.IsAliveAndWell() && (MyKFPM.Health - InDamage) <= 0)
    {
        // Calculate excess damage (damage beyond what was needed to kill)
        ExcessDamage = InDamage - MyKFPM.Health;
        
        if (ExcessDamage > 0)
        {
            // Store a percentage of the excess for the next attack
            ExcessDamage = Round(float(ExcessDamage) * default.ExcessCarryMult[upgLevel - 1]);
            ExcessDamage = Min(ExcessDamage, default.MaxStoredDamage);
            
            UPG.StoreDamage(ExcessDamage);
        }
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_Overkill_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Overkill_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_Overkill_Helper', OwnerPawn);
        }
    }
}

static function DKUpgrade_Skill_Overkill_Helper GetHelper(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_Overkill_Helper UPG;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Overkill_Helper', UPG)
        {
            return UPG;
        }

        // Should have one
        UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_Overkill_Helper', OwnerPawn);
    }

    return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_Overkill_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Overkill_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Overkill]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Overkill"

    UpgradeName="Overkill"
    upgradeDescription(0)="<font color=\"#ff3399\">50%</font> of <font color=\"#ffff00\">excess damage</font> from kills carries over to your <font color=\"#66cc00\">next attack</font>. Max <font color=\"#aaaaaa\">500</font> stored."
    upgradeDescription(1)="<font color=\"#ff3399\">75%</font> of <font color=\"#ffff00\">excess damage</font> from kills carries over to your <font color=\"#66cc00\">next attack</font>. Max <font color=\"#aaaaaa\">500</font> stored."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Overkill'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Overkill_Deluxe'

    Name="Default__DKUpgrade_Skill_Overkill"
}
