class DKUpgrade_Skill_InsiderTrading extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> DoshPerZedType;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DoshPerZedType[0] = 10;
		default.DoshPerZedType[1] = 20;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_InsiderTrading_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_InsiderTrading_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_InsiderTrading_Helper', OwnerPawn);
            UPG.bDeluxe = (upgLevel > 1);
            UPG.UpgradeLevel = upgLevel;
        }
    }
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_InsiderTrading_Helper UPG;

    // Check if this damage will kill the target
    if (MyKFPM != None && MyKFPM.IsAliveAndWell() && 
        DamageInstigator != None && DamageInstigator.Pawn != None &&
        (MyKFPM.Health - InDamage) <= 0)
    {
        foreach DamageInstigator.Pawn.ChildActors(class'DKUpgrade_Skill_InsiderTrading_Helper', UPG)
        {
            UPG.OnEnemyKilled(MyKFPM);
            break;
        }
    }
}

static function WaveEnd(int upgLevel, KFPlayerController KFPC)
{
    local DKUpgrade_Skill_InsiderTrading_Helper UPG;
    
    if (KFPC != None && KFPC.Pawn != None)
    {
        foreach KFPC.Pawn.ChildActors(class'DKUpgrade_Skill_InsiderTrading_Helper', UPG)
        {
            UPG.PayoutWaveBonus();
            break;
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_InsiderTrading_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_InsiderTrading_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_InsiderTrading]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_InsiderTrading"

    UpgradeName="Insider Trading"
    
    upgradeDescription(0)="Gain <font color=\"#00ff00\">+10 dosh</font> for each different <font color=\"#ffaa33\">Zed type</font> killed this wave (resets each wave)."
    upgradeDescription(1)="Gain <font color=\"#00ff00\">+20 dosh</font> for each different <font color=\"#ffaa33\">Zed type</font> killed this wave (resets each wave)."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_InsiderTrading'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_InsiderTrading_Deluxe'

    Name="Default__DKUpgrade_Skill_InsiderTrading"
}