class DKUpgrade_Skill_FaminesTouch extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Theme: The Wendigo finishes off weakened prey with ruthless efficiency
var config array<float> Damage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Damage[0] = 0.2f;
		default.Damage[1] = 0.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (MyKFPM != None && MyKFPM.IsAliveAndWell() && MyKFPM.Health < (MyKFPM.HealthMax / 2))
		InDamage += Round(float(DefaultDamage) * default.Damage[upgLevel - 1]);
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_FaminesTouch]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_FaminesTouch"

	UpgradeName="Famine's Touch"
	UpgradeDescription(0)="<font color=\"#4682B4\">Famine's Touch:</font> Deal <font color=\"#FFFFFF\">+20%</font> <font color=\"#87CEEB\">damage</font> to zeds below <font color=\"#F0F8FF\">50% health</font>"
	UpgradeDescription(1)="<font color=\"#4682B4\">Famine's Touch:</font> Deal <font color=\"#FFFFFF\">+50%</font> <font color=\"#87CEEB\">damage</font> to zeds below <font color=\"#F0F8FF\">50% health</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FaminesTouch'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FaminesTouch_Deluxe'

	Name="Default__DKUpgrade_Skill_FaminesTouch"
}
