class DKUpgrade_Skill_IronFortress extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DamageReduction;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageReduction[0] = 0.15f;
		default.DamageReduction[1] = 0.25f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local KFWeapon HeldWeapon;

	if (OwnerPawn == None)
		return;

	HeldWeapon = KFWeapon(OwnerPawn.Weapon);
	if (!IsRifleWeapon(HeldWeapon))
		return;

	InDamage -= Round(float(DefaultDamage) * default.DamageReduction[upgLevel - 1]);
}

static function bool IsRifleWeapon(KFWeapon KFW)
{
	if (KFW == None)
		return False;

	if (IsWeaponOnSpecificPerk(KFW, class'KFGame.KFPerk_Commando'))
	{
		return (KFW.InstantHitDamage[0] >= 35 ||
				KFW.default.FireInterval[0] >= 0.08);
	}

	return (InStr(PathName(KFW.Class), "Rifle") != INDEX_NONE ||
			InStr(PathName(KFW.Class), "rifle") != INDEX_NONE);
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_IronFortress]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_IronFortress"

	UpgradeName="Iron Fortress"
	UpgradeDescription(0)="Take <font color=\"#77d914\">15%</font> <font color=\"#15d7fa\">less damage</font> while holding a <font color=\"#ff3399\">rifle</font>."
	UpgradeDescription(1)="Take <font color=\"#77d914\">25%</font> <font color=\"#15d7fa\">less damage</font> while holding a <font color=\"#ff3399\">rifle</font>."

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_IronFortress'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_IronFortress_Deluxe'

	Name="Default__DKUpgrade_Skill_IronFortress"
}
