class DKUpgrade_Skill_BottomlessReserves extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Holstered weapons slowly regenerate spare ammo over time
// Encourages carrying multiple weapons and rotating between them

var config array<float> RegenInterval; // Seconds between each regen tick
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.RegenInterval[0] = 8.0f;
		default.RegenInterval[1] = 4.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_BottomlessReserves_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_BottomlessReserves_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
		{
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_BottomlessReserves_Helper', OwnerPawn);
			UPG.StartTimer(default.RegenInterval[upgLevel - 1]);
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_BottomlessReserves_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_BottomlessReserves_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_BottomlessReserves]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_BottomlessReserves"

	UpgradeName="Bottomless Reserves"

	UpgradeDescription(0)="<font color=\"#DAA520\">Bottomless Reserves:</font> <font color=\"#FFFFFF\">Holstered</font> weapons passively <font color=\"#87CEEB\">regenerate 1 spare ammo</font> every <font color=\"#FFFFFF\">8</font> seconds"
	UpgradeDescription(1)="<font color=\"#FFD700\">Bottomless Reserves:</font> <font color=\"#FFFFFF\">Holstered</font> weapons passively <font color=\"#87CEEB\">regenerate 1 spare ammo</font> every <font color=\"#FFFFFF\">4</font> seconds"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BottomlessReserves'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BottomlessReserves_Deluxe'

	Name="Default__DKUpgrade_Skill_BottomlessReserves"
}
