class DKUpgrade_Skill_FleshWeaving extends DKUpgrade_Skill
	abstract
	config(ZedternalUnlimited);

var config array<float> HealChance;
var config array<int> HealAmount;
var config array<int> MinDamageToTrigger;
var config array<float> HealReceivedBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HealChance[0] = 0.10f;
		default.HealChance[1] = 0.20f;
		default.HealAmount[0] = 4;
		default.HealAmount[1] = 8;
		default.MinDamageToTrigger[0] = 10;
		default.MinDamageToTrigger[1] = 5;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
	if (default.MODEVERSION < 2)
	{
		default.HealReceivedBonus[0] = 0.05f;
		default.HealReceivedBonus[1] = 0.10f;

		default.MODEVERSION = 2;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local KFPawn_Human KFPawnHuman;
	local int HealingAmount;
	
	if (OwnerPawn == None)
		return;
		
	KFPawnHuman = KFPawn_Human(OwnerPawn);
	if (KFPawnHuman == None)
		return;
		
	// Only trigger on significant damage to prevent spam on tiny hits
	if (InDamage < default.MinDamageToTrigger[upgLevel - 1])
		return;
		
	// Don't trigger if already at full health
	if (KFPawnHuman.Health >= KFPawnHuman.HealthMax)
		return;
		
	// Roll for flesh weaving activation
	if (FRand() < default.HealChance[upgLevel - 1])
	{
		HealingAmount = default.HealAmount[upgLevel - 1];
		
		// Apply the healing
		KFPawnHuman.HealDamage(HealingAmount, KFPlayerController(KFPawnHuman.Controller), class'KFDT_Healing');
		
		if (upgLevel == 2) // Deluxe version
		{
			InDamage = Max(1, InDamage - 2); // Reduce damage by 2 points minimum 1
		}
	}
}

static function ModifyHealAmount(out float InHealAmount, float DefaultHealAmount, int upgLevel)
{
	InHealAmount += DefaultHealAmount * default.HealReceivedBonus[upgLevel - 1];
}

defaultproperties
{
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_FleshWeaving]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_FleshWeaving"

	UpgradeName="Flesh Weaving"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FleshWeaving'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FleshWeaving_Deluxe'
	UpgradeDescription(0)="The symbiote rapidly repairs tissue damage. <font color='#00FF7F'>10%</font> chance to heal <font color='#00FF7F'>4 HP</font> when taking <font color='#00FF7F'>10+</font> <font color='#9370DB'>damage</font>. <font color='#00FF7F'>+5%</font> <font color='#9370DB'>healing received</font>."
	UpgradeDescription(1)="The symbiote weaves flesh with enhanced efficiency. <font color='#00FF7F'>20%</font> chance to heal <font color='#00FF7F'>8 HP</font> when taking <font color='#00FF7F'>5+</font> <font color='#9370DB'>damage</font>. <font color='#00FF7F'>+10%</font> <font color='#9370DB'>healing received</font>. Reduces incoming damage by <font color='#00FF7F'>2</font>."
	
	Name="Default__DKUpgrade_Skill_FleshWeaving"
}
