// ===================================================================
// DKUpgrade_Skill_BreachingCharge - Active ability: temporary stumble power boost
// Standard: +50% stumble power for 10s
// Deluxe: +75% stumble power for 10s
// Cooldown: 60s after effect ends
// ===================================================================
class DKUpgrade_Skill_BreachingCharge extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> StumblePowerBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.StumblePowerBonus[0] = 0.5f;
		default.StumblePowerBonus[1] = 0.75f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_BreachingCharge_Helper Helper;
	local DKPlayerController DKPC;
	local bool bFound;
	
	if (KFPawn_Human(OwnerPawn) == None || OwnerPawn.Role != Role_Authority)
		return;
	
	DKPC = DKPlayerController(OwnerPawn.Controller);
	if (DKPC == None)
	{
		`log("DKUpgrade_Skill_BreachingCharge: ERROR - Player does not have DKPlayerController!");
		return;
	}
	
	bFound = false;
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_BreachingCharge_Helper', Helper)
	{
		bFound = true;
		Helper.SetTier(upgLevel);
		`log("DKUpgrade_Skill_BreachingCharge: Updated existing helper to tier" @ upgLevel);
		break;
	}
	
	if (!bFound)
	{
		Helper = OwnerPawn.Spawn(class'DKUpgrade_Skill_BreachingCharge_Helper', OwnerPawn);
		if (Helper != None)
		{
			Helper.Initialize(upgLevel, KFPawn_Human(OwnerPawn), DKPC);
			`log("DKUpgrade_Skill_BreachingCharge: Spawned helper for" @ OwnerPawn.PlayerReplicationInfo.PlayerName);
		}
		else
		{
			`log("DKUpgrade_Skill_BreachingCharge: ERROR - Failed to spawn helper!");
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_BreachingCharge_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_BreachingCharge_Helper', Helper)
	{
		Helper.Cleanup();
		Helper.Destroy();
		`log("DKUpgrade_Skill_BreachingCharge: Cleaned up helper");
	}
}

static function ModifyStumblePower(out float InStumblePower, float DefaultStumblePower, int upgLevel,
	optional KFPawn KFP, optional class<KFDamageType> DamageType, optional out float CooldownModifier,
	optional byte BodyPart, optional KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_BreachingCharge_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_BreachingCharge_Helper', Helper)
	{
		if (Helper.bActive)
		{
			InStumblePower += DefaultStumblePower * default.StumblePowerBonus[upgLevel - 1];
		}
		break;
	}
}

defaultproperties
{
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_BreachingCharge]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_BreachingCharge"

	UpgradeName="Breaching Charge"
	
	upgradeDescription(0)="Unlocks <font color=\"#66cc00\">Breaching Charge</font> active ability: <font color=\"#00ffff\">+50% stumble power</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	upgradeDescription(1)="Unlocks <font color=\"#66cc00\">Breaching Charge (Deluxe)</font> active ability: <font color=\"#00ffff\">+75% stumble power</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BreachingCharge'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BreachingCharge_Deluxe'
	
	Name="Default__DKUpgrade_Skill_BreachingCharge"
}