// ===================================================================
// DKUpgrade_Skill_MasterworkTechnique — Artificer Skill
//
// "Each mastery milestone on the current weapon grants additional
//  damage. Your refined technique makes every milestone count more."
//
// Works with ALL weapons (mastery-based).
// Requires Artificer perk to be active (reads its helper's MasteryData).
//
// Normal:  +1.5% damage per mastery milestone on current weapon
// Deluxe:  +3.0% damage per mastery milestone on current weapon
//
// This stacks with the Artificer perk's own mastery damage bonus,
// effectively making milestone investment more rewarding.
//
// Hook: ModifyDamageGiven
// Helper: None (reads DKUpgrade_Perk_Artificer_Helper)
// ===================================================================
class DKUpgrade_Skill_MasterworkTechnique extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DamagePerMilestone;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamagePerMilestone[0] = 0.015f;
		default.DamagePerMilestone[1] = 0.030f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Perk_Artificer_Helper ArtHelper;
    local string NormName;
    local int Milestones;
    local float Bonus;

    if (DamageInstigator == None || DamageInstigator.Pawn == None || MyKFW == None)
        return;

    // Find Artificer helper on this player
    ArtHelper = FindArtificerHelper(DamageInstigator.Pawn);
    if (ArtHelper == None)
        return;

    // Get milestones for current weapon
    NormName = class'DKUpgrade_Perk_Artificer'.static.NormalizeWeaponName(string(MyKFW.Class.Name));
    Milestones = ArtHelper.GetMilestonesCompleted(NormName);

    if (Milestones <= 0)
        return;

    // Apply bonus: milestones × damage per milestone
    Bonus = float(Milestones) * default.DamagePerMilestone[upgLevel - 1];
    InDamage += Round(float(DefaultDamage) * Bonus);
}

// ===================================================================
// ARTIFICER HELPER ACCESS
// ===================================================================

static function DKUpgrade_Perk_Artificer_Helper FindArtificerHelper(Pawn P)
{
    local DKUpgrade_Perk_Artificer_Helper H;

    if (P != None)
    {
        foreach P.ChildActors(class'DKUpgrade_Perk_Artificer_Helper', H)
        {
            return H;
        }
    }

    return None;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_MasterworkTechnique]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_MasterworkTechnique"

    UpgradeName="Masterwork Technique"
    UpgradeDescription(0)="Each <font color=\"#FFD700\">mastery milestone</font> on the current weapon grants <font color=\"#FFFFFF\">+1.5%</font> <font color=\"#FFD700\">additional damage</font>"
    UpgradeDescription(1)="Each <font color=\"#FFD700\">mastery milestone</font> on the current weapon grants <font color=\"#FFFFFF\">+3%</font> <font color=\"#FFD700\">additional damage</font>"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_MasterworkTechnique'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_MasterworkTechnique_Deluxe'

    Name="Default__DKUpgrade_Skill_MasterworkTechnique"
}
