class DKUpgrade_Skill_BulkPurchasing extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> RefundPercentage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.RefundPercentage[0] = 0.025f;
		default.RefundPercentage[1] = 0.04f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_BulkPurchasing_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_BulkPurchasing_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_BulkPurchasing_Helper', OwnerPawn);
            UPG.bDeluxe = (upgLevel > 1);
            UPG.UpgradeLevel = upgLevel;
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_BulkPurchasing_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_BulkPurchasing_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_BulkPurchasing]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_BulkPurchasing"

    UpgradeName="Bulk Purchasing"
    
    upgradeDescription(0)="Buying multiple items in one trader visit grants <font color=\"#00ff00\">2.5% dosh refund</font> per <font color=\"#ffaa33\">additional item</font>."
    upgradeDescription(1)="Buying multiple items in one trader visit grants <font color=\"#00ff00\">4% dosh refund</font> per <font color=\"#ffaa33\">additional item</font>."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BulkPurchasing'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BulkPurchasing_Deluxe'

    Name="Default__DKUpgrade_Skill_BulkPurchasing"
}