class DKUpgrade_Skill_Armory extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Armory: Increased spare ammo capacity and bonus starting grenades
// Normal: +15% spare ammo, +1 grenade | Deluxe: +35% spare ammo, +3 grenades

var config array<float> Ammo;
var config array<int> ExtraGrenades;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Ammo[0] = 0.15f;
		default.Ammo[1] = 0.35f;
		default.ExtraGrenades[0] = 1;
		default.ExtraGrenades[1] = 3;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function ModifySpareAmmoAmountPassive(out float spareAmmoFactor, int upgLevel)
{
	spareAmmoFactor += default.Ammo[upgLevel - 1];
}

static simulated function ModifySpareGrenadeAmount(out int SpareGrenade, int DefaultSpareGrenade, int upgLevel)
{
	SpareGrenade += default.ExtraGrenades[upgLevel - 1];
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Armory]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Armory"

	UpgradeName="Armory"
	UpgradeDescription(0)="Increase <font color=\"#e80948\">spare ammo</font> by <font color=\"#e85009\">15%</font> and gain <font color=\"#e85009\">+1</font> starting grenade."
	UpgradeDescription(1)="Increase <font color=\"#e80948\">spare ammo</font> by <font color=\"#e85009\">35%</font> and gain <font color=\"#e85009\">+3</font> starting grenades."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Armory'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Armory_Deluxe'

	Name="Default__DKUpgrade_Skill_Armory"
}
