// Envenomed Arsenal: Weapon swaps grant guaranteed poison procs on your next shots.
// Encourages rapid weapon juggling and constant rotation.
// Swap, fire guaranteed poison burst, swap back, repeat.
class DKUpgrade_Skill_EnvenomedArsenal extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> PoisonDamage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.PoisonDamage[0] = 10;
		default.PoisonDamage[1] = 20;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_EnvenomedArsenal_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_EnvenomedArsenal_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
		{
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_EnvenomedArsenal_Helper', OwnerPawn);
			UPG.bDeluxe = (upgLevel > 1);
		}

		if (UPG != None)
			UPG.WeaponSwapped(KFW);
	}
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_EnvenomedArsenal_Helper UPG;

	if (MyKFPM != None && DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		UPG = GetHelper(DamageInstigator.Pawn);
		if (UPG != None && UPG.ConsumeProc())
		{
			// Apply guaranteed poison regardless of Venomancer RNG
			MyKFPM.ApplyDamageOverTime(default.PoisonDamage[upgLevel - 1], DamageInstigator, class'KFDT_Toxic');
		}
	}
}

static function DKUpgrade_Skill_EnvenomedArsenal_Helper GetHelper(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_EnvenomedArsenal_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_EnvenomedArsenal_Helper', UPG)
		{
			return UPG;
		}
	}

	return None;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_EnvenomedArsenal_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_EnvenomedArsenal_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

// Also reduce weapon switch time to support the swap-heavy playstyle
static simulated function ModifyWeaponSwitchTime(out float InSwitchTime, float DefaultSwitchTime, int upgLevel, KFWeapon KFW)
{
	InSwitchTime -= DefaultSwitchTime * 0.25f;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_EnvenomedArsenal]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_EnvenomedArsenal"

	UpgradeDescription(0)="Weapon swaps grant <font color=\"#399c0e\">3 guaranteed Poison shots</font>. <font color=\"#ebd402\">25% faster weapon switch</font>."
	UpgradeDescription(1)="Weapon swaps grant <font color=\"#b346ea\">5 guaranteed Poison shots</font>. <font color=\"#ebd402\">25% faster weapon switch</font>."

	UpgradeName="Envenomed Arsenal"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_EnvenomedArsenal'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_EnvenomedArsenal_Deluxe'

	Name="Default__DKUpgrade_Skill_EnvenomedArsenal"
}
