class DKUpgrade_Skill_SurgicalPrecision extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Bonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Bonus[0] = 0.2f;
		default.Bonus[1] = 0.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (HitZoneIdx == HZI_HEAD && MyKFW != None && MyKFW.bUsingSights)
		InDamage += Round(float(DefaultDamage) * default.Bonus[upgLevel - 1]);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_SurgicalPrecision]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_SurgicalPrecision"

    UpgradeName="Surgical Precision"
	upgradeDescription(0)="When using Iron Sights, increase <font color=\"#ff3399\">Damage</font> with all weapons by <font color=\"#66cc00\">20%</font>."
    upgradeDescription(1)="When using Iron Sights, increase <font color=\"#ff3399\">Damage</font> with all weapons by <font color=\"#66cc00\">20%</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SurgicalPrecision'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SurgicalPrecision_Deluxe'
    Name="Default__DKUpgrade_Skill_SurgicalPrecision"
}