// ===================================================================
// DKUpgrade_Skill_Chronoshift - Active ability: trigger ZED time on demand
// Standard: 5 seconds of ZED time
// Deluxe: 8 seconds of ZED time
// Cooldown: 90 seconds
// ===================================================================
class DKUpgrade_Skill_Chronoshift extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Store duration values in defaultproperties
var config array<float> ZedTimeDurations;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ZedTimeDurations[0] = 5.0f;
		default.ZedTimeDurations[1] = 8.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// Called when skill is purchased - spawn the helper
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_Chronoshift_Helper Helper;
	local DKPlayerController DKPC;
	local bool bFound;
	
	if (KFPawn_Human(OwnerPawn) == None || OwnerPawn.Role != Role_Authority)
		return;
	
	DKPC = DKPlayerController(OwnerPawn.Controller);
	if (DKPC == None)
	{
		`log("DKUpgrade_Skill_Chronoshift: ERROR - Player does not have DKPlayerController!");
		return;
	}
	
	// Check if helper already exists
	bFound = false;
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Chronoshift_Helper', Helper)
	{
		bFound = true;
		// Update to new tier if upgrading Standard -> Deluxe
		Helper.SetTier(upgLevel);
		`log("DKUpgrade_Skill_Chronoshift: Updated existing helper to tier" @ upgLevel);
		break;
	}
	
	// Spawn new helper if not found
	if (!bFound)
	{
		Helper = OwnerPawn.Spawn(class'DKUpgrade_Skill_Chronoshift_Helper', OwnerPawn);
		if (Helper != None)
		{
			Helper.Initialize(upgLevel, KFPawn_Human(OwnerPawn), DKPC);
			`log("DKUpgrade_Skill_Chronoshift: Spawned helper for" @ OwnerPawn.PlayerReplicationInfo.PlayerName);
		}
		else
		{
			`log("DKUpgrade_Skill_Chronoshift: ERROR - Failed to spawn helper!");
		}
	}
}

// Called when skill is removed - cleanup
static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_Chronoshift_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Chronoshift_Helper', Helper)
	{
		Helper.Cleanup();
		Helper.Destroy();
		`log("DKUpgrade_Skill_Chronoshift: Cleaned up helper");
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Chronoshift]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Chronoshift"

	// Duration values stored in defaultproperties
	
	UpgradeName="Chronoshift"
	
	upgradeDescription(0)="Unlocks <font color=\"#66cc00\">Chronoshift</font> active ability: Instantly trigger <font color=\"#00ffff\">5 seconds</font> of <font color=\"#ffaa33\">ZED time</font> on demand. Cooldown: <font color=\"#ff9900\">90 seconds</font>."
	
	upgradeDescription(1)="Unlocks <font color=\"#66cc00\">Chronoshift (Deluxe)</font> active ability: Instantly trigger <font color=\"#00ffff\">8 seconds</font> of <font color=\"#ffaa33\">ZED time</font> on demand. Cooldown: <font color=\"#ff9900\">90 seconds</font>."
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Chronoshift'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Chronoshift_Deluxe'
	
	Name="Default__DKUpgrade_Skill_Chronoshift"
}