// ===================================================================
// DKUpgrade_Skill_FieldSurgery - Active ability: instant self-heal
// Standard: Heal 25 HP instantly
// Deluxe: Heal 50 HP instantly
// Cooldown: 60s after use
// ===================================================================
class DKUpgrade_Skill_FieldSurgery extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> HealAmount;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HealAmount[0] = 25;
		default.HealAmount[1] = 50;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_FieldSurgery_Helper Helper;
	local DKPlayerController DKPC;
	local bool bFound;
	
	if (KFPawn_Human(OwnerPawn) == None || OwnerPawn.Role != Role_Authority)
		return;
	
	DKPC = DKPlayerController(OwnerPawn.Controller);
	if (DKPC == None)
	{
		`log("DKUpgrade_Skill_FieldSurgery: ERROR - Player does not have DKPlayerController!");
		return;
	}
	
	bFound = false;
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_FieldSurgery_Helper', Helper)
	{
		bFound = true;
		Helper.SetTier(upgLevel);
		`log("DKUpgrade_Skill_FieldSurgery: Updated existing helper to tier" @ upgLevel);
		break;
	}
	
	if (!bFound)
	{
		Helper = OwnerPawn.Spawn(class'DKUpgrade_Skill_FieldSurgery_Helper', OwnerPawn);
		if (Helper != None)
		{
			Helper.Initialize(upgLevel, KFPawn_Human(OwnerPawn), DKPC);
			`log("DKUpgrade_Skill_FieldSurgery: Spawned helper for" @ OwnerPawn.PlayerReplicationInfo.PlayerName);
		}
		else
		{
			`log("DKUpgrade_Skill_FieldSurgery: ERROR - Failed to spawn helper!");
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_FieldSurgery_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_FieldSurgery_Helper', Helper)
	{
		Helper.Cleanup();
		Helper.Destroy();
		`log("DKUpgrade_Skill_FieldSurgery: Cleaned up helper");
	}
}

defaultproperties
{
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_FieldSurgery]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_FieldSurgery"

	UpgradeName="Field Surgery"
	
	upgradeDescription(0)="Unlocks <font color=\"#66cc00\">Field Surgery</font> active ability: <font color=\"#00ffff\">Heal 25 HP</font> instantly. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	upgradeDescription(1)="Unlocks <font color=\"#66cc00\">Field Surgery (Deluxe)</font> active ability: <font color=\"#00ffff\">Heal 50 HP</font> instantly. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FieldSurgery'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FieldSurgery_Deluxe'
	
	Name="Default__DKUpgrade_Skill_FieldSurgery"
}