class DKUpgrade_Skill_EternalForge extends DKUpgrade_Skill;

// Eternal Forge: After every wave, your weapons are forged stronger
// Damage bonus stacks infinitely
// Normal: +1% per wave | Deluxe: +2% per wave

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_EternalForge_Helper UPG;

	if (DamageInstigator != None)
	{
		UPG = GetHelper(KFPawn(DamageInstigator.Pawn), upgLevel);
		if (UPG != None && UPG.DamageBonus > 0.0f)
			InDamage += Round(float(DefaultDamage) * UPG.DamageBonus);
	}
}

static function WaveEnd(int upgLevel, KFPlayerController KFPC)
{
	local DKUpgrade_Skill_EternalForge_Helper UPG;

	if (KFPC.Pawn != None)
	{
		UPG = GetHelper(KFPawn(KFPC.Pawn), upgLevel);
		if (UPG != None)
			UPG.AddStack(upgLevel > 1);
	}
}

static function DKUpgrade_Skill_EternalForge_Helper GetHelper(KFPawn OwnerPawn, int upgLevel)
{
	local DKUpgrade_Skill_EternalForge_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_EternalForge_Helper', UPG)
		{
			return UPG;
		}

		// Should have one
		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_EternalForge_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_EternalForge_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_EternalForge_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_EternalForge]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_EternalForge"

	UpgradeName="Eternal Forge"
	UpgradeDescription(0)="After every wave, gain <font color=\"#e85009\">+1%</font> damage. <font color=\"#e80948\">Stacks infinitely</font>."
	UpgradeDescription(1)="After every wave, gain <font color=\"#e85009\">+2%</font> damage. <font color=\"#e80948\">Stacks infinitely</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_EternalForge'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_EternalForge_Deluxe'

	Name="Default__DKUpgrade_Skill_EternalForge"
}
