// Toxic Overload: Poisoned ZEDs explode on death, dealing AoE toxic damage.
// Uses two-hook approach:
//   ModifyDamageGiven -> caches target location + poisoned status on Helper
//   AddVampireHealth  -> fires on kill, triggers explosion via Helper
class DKUpgrade_Skill_ToxicOverload extends DKUpgrade_Skill;

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_ToxicOverload_Helper UPG;

	if (MyKFPM != None && DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		UPG = GetHelper(DamageInstigator.Pawn);
		if (UPG != None)
			UPG.UpdateTarget(MyKFPM);
	}
}

static function AddVampireHealth(out int InHealth, int DefaultHealth, int upgLevel, KFPlayerController KFPC, class<DamageType> DT)
{
	local DKUpgrade_Skill_ToxicOverload_Helper UPG;

	if (KFPC != None && KFPC.Pawn != None)
	{
		UPG = GetHelper(KFPC.Pawn);
		if (UPG != None)
			UPG.TriggerExplosion();
	}
}

static function DKUpgrade_Skill_ToxicOverload_Helper GetHelper(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_ToxicOverload_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ToxicOverload_Helper', UPG)
		{
			return UPG;
		}

		UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_ToxicOverload_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_ToxicOverload_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ToxicOverload_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_ToxicOverload]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_ToxicOverload"

	UpgradeDescription(0)="<font color=\"#8fce00\">Poisoned</font> ZEDs <font color=\"#399c0e\">explode on death</font>, dealing toxic AoE damage and poisoning nearby ZEDs."
	UpgradeDescription(1)="<font color=\"#8fce00\">Poisoned</font> ZEDs <font color=\"#b346ea\">explode on death</font>, dealing increased toxic AoE damage and poisoning nearby ZEDs."

	UpgradeName="Toxic Overload"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ToxicOverload'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ToxicOverload_Deluxe'

	Name="Default__DKUpgrade_Skill_ToxicOverload"
}
