class DKUpgrade_Skill_Windfall extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// At the end of each wave, all teammates receive a percentage of spare ammo
// Strong team utility skill that rewards surviving the wave

var config array<float> AmmoPercent;  // Percentage of max spare ammo granted to team
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.AmmoPercent[0] = 0.05f;
		default.AmmoPercent[1] = 0.12f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function WaveEnd(int upgLevel, KFPlayerController KFPC)
{
	local KFPlayerController PC;
	local KFPawn_Human Player;
	local Inventory Inv;
	local KFWeapon KFW;
	local int AmmoToAdd;

	if (KFPC == None || KFPC.WorldInfo == None)
		return;

	// Iterate all players in the game
	foreach KFPC.WorldInfo.AllControllers(class'KFPlayerController', PC)
	{
		Player = KFPawn_Human(PC.Pawn);
		if (Player != None && Player.Health > 0 && Player.InvManager != None)
		{
			// Iterate all weapons in this player's inventory
			for (Inv = Player.InvManager.InventoryChain; Inv != None; Inv = Inv.Inventory)
			{
				KFW = KFWeapon(Inv);
				if (KFW != None && KFW.SpareAmmoCapacity[0] > 0)
				{
					AmmoToAdd = Max(1, Round(float(KFW.SpareAmmoCapacity[0]) * default.AmmoPercent[upgLevel - 1]));
					KFW.SpareAmmoCount[0] = Min(KFW.SpareAmmoCount[0] + AmmoToAdd, KFW.SpareAmmoCapacity[0]);
				}
			}
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Windfall]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Windfall"

	UpgradeName="Windfall"

	UpgradeDescription(0)="<font color=\"#DAA520\">Windfall:</font> At the end of each wave, <font color=\"#00FF00\">all teammates</font> receive <font color=\"#87CEEB\">5%</font> <font color=\"#FFFFFF\">spare ammo</font> for all weapons"
	UpgradeDescription(1)="<font color=\"#FFD700\">Windfall:</font> At the end of each wave, <font color=\"#00FF00\">all teammates</font> receive <font color=\"#87CEEB\">12%</font> <font color=\"#FFFFFF\">spare ammo</font> for all weapons"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Windfall'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Windfall_Deluxe'

	Name="Default__DKUpgrade_Skill_Windfall"
}
