class DKUpgrade_Skill_AdrenalineRush extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Pain is fuel
// Each time you take damage, gain a stack of Adrenaline
// Stacks increase attack speed and movement speed, decay over time

var config array<int> MaxStacks;
var config array<float> SpeedPerStack;
var config array<float> AttackSpeedPerStack;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MaxStacks[0] = 5;
		default.MaxStacks[1] = 8;
		default.SpeedPerStack[0] = 0.03f;
		default.SpeedPerStack[1] = 0.04f;
		default.AttackSpeedPerStack[0] = 0.04f;
		default.AttackSpeedPerStack[1] = 0.05f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_AdrenalineRush_Helper UPG;

	if (InDamage > 0 && OwnerPawn != None)
	{
		UPG = GetHelper(OwnerPawn, upgLevel);
		if (UPG != None)
			UPG.AddStack(default.MaxStacks[upgLevel - 1]);
	}
}

static simulated function ModifyMeleeAttackSpeed(out float InDuration, float DefaultDuration, int upgLevel, KFWeapon KFW)
{
	local DKUpgrade_Skill_AdrenalineRush_Helper UPG;

	if (KFW != None && KFW.Instigator != None)
	{
		UPG = GetHelperSimulated(KFPawn(KFW.Instigator));
		if (UPG != None && UPG.RepStacks > 0)
		{
			InDuration = InDuration / (1.0f + (default.AttackSpeedPerStack[upgLevel - 1] * float(UPG.RepStacks)));
		}
	}
}

static simulated function ModifySpeed(out float InSpeed, float DefaultSpeed, int upgLevel, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_AdrenalineRush_Helper UPG;

	if (OwnerPawn != None)
	{
		UPG = GetHelperSimulated(OwnerPawn);
		if (UPG != None && UPG.RepStacks > 0)
		{
			InSpeed += DefaultSpeed * default.SpeedPerStack[upgLevel - 1] * float(UPG.RepStacks);
		}
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_AdrenalineRush_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_AdrenalineRush_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
		{
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_AdrenalineRush_Helper', OwnerPawn);
			UPG.SetDeluxe(upgLevel > 1);
		}
	}
}

static function DKUpgrade_Skill_AdrenalineRush_Helper GetHelper(KFPawn OwnerPawn, int upgLevel)
{
	local DKUpgrade_Skill_AdrenalineRush_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_AdrenalineRush_Helper', UPG)
		{
			return UPG;
		}

		if (OwnerPawn.Role == Role_Authority)
		{
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_AdrenalineRush_Helper', OwnerPawn);
			UPG.SetDeluxe(upgLevel > 1);
		}
	}

	return UPG;
}

// For simulated (client-side) functions - don't spawn, just find
static simulated function DKUpgrade_Skill_AdrenalineRush_Helper GetHelperSimulated(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_AdrenalineRush_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_AdrenalineRush_Helper', UPG)
		{
			return UPG;
		}
	}

	return None;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_AdrenalineRush_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_AdrenalineRush_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_AdrenalineRush]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_AdrenalineRush"

	UpgradeName="Adrenaline Rush"

	UpgradeDescription(0)="<font color=\"#edb82a\">Adrenaline Rush</font> Taking damage grants <font color=\"#FFFFFF\">Adrenaline</font> stacks (max <font color=\"#FFFFFF\">5</font>). Per stack: <font color=\"#32CD32\">+3% Move Speed</font>, <font color=\"#FFD700\">+4% Attack Speed</font> Stacks decay over time. <font color=\"#AAAAAA\">Pain is fuel.</font>"
	UpgradeDescription(1)="<font color=\"#edb82a\">Adrenaline Rush</font> Taking damage grants <font color=\"#FFFFFF\">Adrenaline</font> stacks (max <font color=\"#FFFFFF\">8</font>). Per stack: <font color=\"#32CD32\">+4% Move Speed</font>, <font color=\"#FFD700\">+5% Attack Speed</font> Stacks decay over time. <font color=\"#AAAAAA\">Pain is fuel.</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AdrenalineRush'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AdrenalineRush_Deluxe'

	Name="Default__DKUpgrade_Skill_AdrenalineRush"
}
