// ===================================================================
// DKUpgrade_Perk_Haunted - The Watcher Easter Egg
// Theme: Something is watching... always watching...
// Color: Dark Purple/Black (RGB: 40, 0, 60)
// Unlock Requirement: Berserker Level 5 + Sharpshooter Level 5
// Activation: Haunted purchased + Support Level 5
// ===================================================================
class DKUpgrade_Perk_Haunted extends DKUpgrade_Perk
	config(ZedternalUnlimited);

// ===================================================================
// CONFIGURABLE UNLOCK/ACTIVATION CONDITIONS
// Change these to modify requirements
// ===================================================================

// Unlock conditions (to reveal Haunted in shop)
// These are handled by DKMutator.InitializeDefaultPerkRules()
// Current: Berserker 5 + Sharpshooter 5

// Activation conditions (to start The Watcher)
var class<KFPerk> ActivationPerkClass;    // The perk needed alongside Haunted
var config int ActivationPerkLevel;               // Level required for activation perk
var config string ActivationPerkName;             // String name for lookup

// Escalation settings
var config int KillsPerStage;                     // Kills needed to advance each stage
var config int MaxStage;                          // Maximum escalation stage (5)
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ActivationPerkLevel = 5;
		default.ActivationPerkName = "WMUpgrade_Perk_Support";
		default.KillsPerStage = 10;
		default.MaxStage = 5;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// ===================================================================
// THIS PERK GRANTS NO BONUSES
// Its only purpose is to enable The Watcher system
// ===================================================================

// ===================================================================
// Kill Tracking (for escalation)
// We hook ModifyDamageGiven just to track kills, not to modify damage
// ===================================================================
static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
	optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
	optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
	optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Perk_Haunted_Helper Helper;
	
	// We don't modify damage at all - just track kills
	if (DamageInstigator == None || DamageInstigator.Pawn == None)
		return;
	
	// Check if this damage would kill the target
	if (MyKFPM != None && (MyKFPM.Health - InDamage) <= 0)
	{
		Helper = GetHelper(DamageInstigator.Pawn);
		if (Helper != None)
		{
			Helper.OnKill();
		}
	}
}

// ===================================================================
// Helper Management
// ===================================================================
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Perk_Haunted_Helper Helper;
	local KFPawn_Human HumanPawn;
	
	HumanPawn = KFPawn_Human(OwnerPawn);
	if (HumanPawn == None)
		return;
	
	// Only create helper on server
	if (OwnerPawn.Role != ROLE_Authority)
		return;
	
	// Check if helper already exists
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Perk_Haunted_Helper', Helper)
	{
		Helper.SetUpgradeLevel(upgLevel);
		return;
	}
	
	// Spawn new helper
	Helper = OwnerPawn.Spawn(class'DKUpgrade_Perk_Haunted_Helper', OwnerPawn);
	if (Helper != None)
	{
		Helper.Initialize(HumanPawn, upgLevel);
		`log("Haunted: Spawned helper for" @ OwnerPawn.PlayerReplicationInfo.PlayerName);
	}
}

static function DKUpgrade_Perk_Haunted_Helper GetHelper(Pawn OwnerPawn)
{
	local DKUpgrade_Perk_Haunted_Helper Helper;
	
	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Perk_Haunted_Helper', Helper)
			return Helper;
	}
	
	return None;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Perk_Haunted_Helper Helper;
	
	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Perk_Haunted_Helper', Helper)
		{
			Helper.Cleanup();
			Helper.Destroy();
		}
	}
}

// ===================================================================
// Default Properties
// ===================================================================
defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Perk_Haunted]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Perk_Haunted"
    LocalizeDescriptionLineCount=4

	// Activation conditions (what triggers The Watcher after Haunted is purchased)
	ActivationPerkClass=class'KFPerk_Support'
	
	// Escalation settings
	
	// UI and description - Cryptic and mysterious
	upgradeName="???"
	
	// PerkBonus - None (this perk grants no bonuses)
	// Empty array = no bonus display
	
	// Cryptic descriptions
	upgradeDescription(0)="<font color=\"#400040\">...</font>"
	upgradeDescription(1)="<font color=\"#400040\">Something stirs in the darkness...</font>"
	upgradeDescription(2)="<font color=\"#400040\">You feel eyes upon you...</font>"
	upgradeDescription(3)="<font color=\"#400040\">It sees you now.</font>"
	
	// Icon references - You'll create these
	// For now using placeholder paths - update these with your actual icons
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_0'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_1'
	UpgradeIcon(2)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_2'
	UpgradeIcon(3)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_3'
	UpgradeIcon(4)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_4'
	UpgradeIcon(5)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_5'
	UpgradeIcon(6)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_6'
	UpgradeIcon(7)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_7'
	UpgradeIcon(8)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_8'
	UpgradeIcon(9)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_9'
	UpgradeIcon(10)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_10'
	UpgradeIcon(11)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_11'
	UpgradeIcon(12)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_12'
	UpgradeIcon(13)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_13'
	UpgradeIcon(14)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_14'
	UpgradeIcon(15)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_15'
	UpgradeIcon(16)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_16'
	UpgradeIcon(17)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_17'
	UpgradeIcon(18)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_18'
	UpgradeIcon(19)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_19'
	UpgradeIcon(20)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Haunted_Rank_20'

	Name="Default__DKUpgrade_Perk_Haunted"
}
