class DKUpgrade_Skill_FrostbiteArrows extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DamagePerStack;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamagePerStack[0] = 0.10f;
		default.DamagePerStack[1] = 0.15f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_FrostbiteArrows_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_FrostbiteArrows_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_FrostbiteArrows_Helper', OwnerPawn);
            UPG.bDeluxe = (upgLevel > 1);
            UPG.UpgradeLevel = upgLevel;
        }
    }
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_FrostbiteArrows_Helper UPG;
    local float DamageBonus;

    // Only apply to archery weapons
    if (IsArcheryWeapon(MyKFW) && DamageInstigator != None && DamageInstigator.Pawn != None && MyKFPM != None)
    {
        foreach DamageInstigator.Pawn.ChildActors(class'DKUpgrade_Skill_FrostbiteArrows_Helper', UPG)
        {
            DamageBonus = UPG.GetDamageBonusForTarget(MyKFPM);
            // Use += against DefaultDamage so this composes with any other damage
            // contributors instead of overwriting them. Old code did
            // `InDamage = DefaultDamage * (1+bonus)` which discarded any prior
            // contribution to InDamage from other skills/weapon upgrades.
            InDamage += Round(float(DefaultDamage) * DamageBonus);
            
            // Apply new frostbite stack after damage calculation
            UPG.ApplyFrostbiteStack(MyKFPM);
            break;
        }
    }
}

static function ModifySnarePower(out float InSnarePower, float DefaultSnarePower, int upgLevel, optional class<DamageType> DamageType, optional byte BodyPart)
{
    // Frostbite arrows always apply snare
    if (upgLevel > 0)
    {
        // Use += so we compose with any other snare contributors instead of
        // overwriting them. Old code did `InSnarePower = DefaultSnarePower + 0.3f`
        // which discarded any prior contribution to InSnarePower.
        InSnarePower += 0.3f; // Base snare power
    }
}

static function bool IsArcheryWeapon(KFWeapon KFW)
{
    return (KFWeap_Bow_Crossbow(KFW) != None || KFWeap_Bow_CompoundBow(KFW) != None || KFWeap_HRG_Crossboom(KFW) != None);
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_FrostbiteArrows_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_FrostbiteArrows_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_FrostbiteArrows]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_FrostbiteArrows"

    UpgradeName="Frostbite Arrows"
    upgradeDescription(0)="Your <font color=\"#77d914\">Bow and Crossbow</font> shots apply a stacking <font color=\"#87CEEB\">Slow Effect</font> that increases your <font color=\"#FFAA33\">Damage</font> against that target by <font color=\"#15d7fa\">10%</font> per stack (max 5 stacks)."
    upgradeDescription(1)="Your <font color=\"#77d914\">Bow and Crossbow</font> shots apply a stacking <font color=\"#87CEEB\">Slow Effect</font> that increases your <font color=\"#FFAA33\">Damage</font> against that target by <font color=\"#15d7fa\">15%</font> per stack (max 5 stacks)."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FrostbiteArrows'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FrostbiteArrows_Deluxe'

    Name="Default__DKUpgrade_Skill_FrostbiteArrows"
}
