// ===================================================================
// DKUpgrade_Skill_PyromaniacRush - Active ability: speed boost + fire immunity
// Standard: +10% speed + fire immunity for 10s
// Deluxe: +20% speed + fire immunity for 10s
// Cooldown: 60s after effect ends
// ===================================================================
class DKUpgrade_Skill_PyromaniacRush extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> SpeedBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.SpeedBonus[0] = 0.1f;
		default.SpeedBonus[1] = 0.2f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_PyromaniacRush_Helper Helper;
	local DKPlayerController DKPC;
	local bool bFound;
	
	if (KFPawn_Human(OwnerPawn) == None || OwnerPawn.Role != Role_Authority)
		return;
	
	DKPC = DKPlayerController(OwnerPawn.Controller);
	if (DKPC == None)
	{
		`log("DKUpgrade_Skill_PyromaniacRush: ERROR - Player does not have DKPlayerController!");
		return;
	}
	
	bFound = false;
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_PyromaniacRush_Helper', Helper)
	{
		bFound = true;
		Helper.SetTier(upgLevel);
		`log("DKUpgrade_Skill_PyromaniacRush: Updated existing helper to tier" @ upgLevel);
		break;
	}
	
	if (!bFound)
	{
		Helper = OwnerPawn.Spawn(class'DKUpgrade_Skill_PyromaniacRush_Helper', OwnerPawn);
		if (Helper != None)
		{
			Helper.Initialize(upgLevel, KFPawn_Human(OwnerPawn), DKPC);
			`log("DKUpgrade_Skill_PyromaniacRush: Spawned helper for" @ OwnerPawn.PlayerReplicationInfo.PlayerName);
		}
		else
		{
			`log("DKUpgrade_Skill_PyromaniacRush: ERROR - Failed to spawn helper!");
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_PyromaniacRush_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_PyromaniacRush_Helper', Helper)
	{
		Helper.Cleanup();
		Helper.Destroy();
		`log("DKUpgrade_Skill_PyromaniacRush: Cleaned up helper");
	}
}

// Apply speed bonus when active
static simulated function ModifySpeed(out float InSpeed, float DefaultSpeed, int upgLevel, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_PyromaniacRush_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_PyromaniacRush_Helper', Helper)
	{
		if (Helper.bActive)
		{
			InSpeed += DefaultSpeed * default.SpeedBonus[upgLevel - 1];
		}
		break;
	}
}

// Apply fire immunity when active
static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_PyromaniacRush_Helper Helper;
	
	if (OwnerPawn == None || DamageType == None)
		return;
	
	// Only apply to fire damage
	if (!ClassIsChildOf(DamageType, class'KFDT_Fire'))
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_PyromaniacRush_Helper', Helper)
	{
		if (Helper.bActive)
		{
			// Immune to fire damage
			InDamage = 0;
		}
		break;
	}
}

defaultproperties
{
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_PyromaniacRush]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_PyromaniacRush"

	UpgradeName="Pyromaniac Rush"
	
	upgradeDescription(0)="Unlocks <font color=\"#66cc00\">Pyromaniac Rush</font> active ability: <font color=\"#00ffff\">+10% speed</font> and <font color=\"#ff6600\">fire immunity</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	upgradeDescription(1)="Unlocks <font color=\"#66cc00\">Pyromaniac Rush (Deluxe)</font> active ability: <font color=\"#00ffff\">+20% speed</font> and <font color=\"#ff6600\">fire immunity</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PyromaniacRush'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PyromaniacRush_Deluxe'
	
	Name="Default__DKUpgrade_Skill_PyromaniacRush"
}