// ===================================================================
// DKUpgrade_Skill_WhisperOfMadness
//
// "Whisper of Madness"
// Every 3rd wave, the prophecy is completely hidden. You receive
// no information about the condition — just "???".
// Completing a hidden prophecy yields amplified rewards.
// Failing a hidden prophecy yields amplified (or normal) doom.
//
// Standard: 2x reward on hidden success, 1.5x doom on hidden failure
// Deluxe:   3x reward on hidden success, 1x doom on hidden failure
// ===================================================================
class DKUpgrade_Skill_WhisperOfMadness extends DKUpgrade_Skill;

// --- Helper spawning ---
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_WhisperOfMadness_Helper H;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == ROLE_Authority)
    {
        bFound = false;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_WhisperOfMadness_Helper', H)
        {
            bFound = true;
            H.Initialize(upgLevel);
            break;
        }

        if (!bFound)
        {
            H = OwnerPawn.Spawn(class'DKUpgrade_Skill_WhisperOfMadness_Helper', OwnerPawn);
            if (H != None)
                H.Initialize(upgLevel);
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_WhisperOfMadness_Helper H;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_WhisperOfMadness_Helper', H)
        {
            H.Cleanup();
            H.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_WhisperOfMadness]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_WhisperOfMadness"

    UpgradeName="Whisper of Madness"
    UpgradeDescription(0)="Every <font color=\"#ebc034\">3rd wave</font>, the prophecy is <font color=\"#ff0000\">completely hidden</font>. Complete it for <font color=\"#15d7fa\">2x reward</font>. Fail for <font color=\"#ff0000\">1.5x doom</font>."
    UpgradeDescription(1)="Every <font color=\"#ebc034\">3rd wave</font>, the prophecy is <font color=\"#ff0000\">completely hidden</font>. Complete it for <font color=\"#15d7fa\">3x reward</font>. Fail for <font color=\"#ff0000\">normal doom</font>."

    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_WhisperOfMadness_Deluxe'

    Name="Default__DKUpgrade_Skill_WhisperOfMadness"
}
