class DKUpgrade_Skill_PatientReload extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Theme: The patient hunter reloads methodically when motionless
var config array<float> ReloadRate;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ReloadRate[0] = 0.2f;
		default.ReloadRate[1] = 0.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function GetReloadRateScale(out float InReloadRateScale, int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	if (OwnerPawn != None && VSizeSq(OwnerPawn.Velocity) <= 0)
		InReloadRateScale = 1.0f / (1.0f / InReloadRateScale + default.ReloadRate[upgLevel - 1]);
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_PatientReload]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_PatientReload"

	UpgradeName="Patient Reload"
	UpgradeDescription(0)="<font color=\"#4682B4\">Patient Reload:</font> <font color=\"#FFFFFF\">20%</font> <font color=\"#87CEEB\">faster reload</font> while <font color=\"#F0F8FF\">standing still</font>"
	UpgradeDescription(1)="<font color=\"#4682B4\">Patient Reload:</font> <font color=\"#FFFFFF\">50%</font> <font color=\"#87CEEB\">faster reload</font> while <font color=\"#F0F8FF\">standing still</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PatientReload'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PatientReload_Deluxe'

	Name="Default__DKUpgrade_Skill_PatientReload"
}
