class DKUpgrade_Skill_Deadshot extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Damage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Damage[0] = 0.3f;
		default.Damage[1] = 0.6f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (HitZoneIdx == HZI_HEAD)
		InDamage += Round(float(DefaultDamage) * default.Damage[upgLevel - 1]);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Deadshot]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Deadshot"

    UpgradeName="Deadshot"
	upgradeDescription(0)="Increase <font color=\"#ff3399\">Headshot Damage</font> by <font color=\"#66cc00\">30%</font> for all weapons."
	upgradeDescription(1)="Increase <font color=\"#ff3399\">Headshot Damage</font> by <font color=\"#66cc00\">60%</font> for all weapons."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Deadshot'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Deadshot_Deluxe'
    Name="Default__DKUpgrade_Skill_Deadshot"
}