// ===================================================================
// DKUpgrade_Skill_SurplusForm
//
// "The body grows to accommodate its many shapes."
//
// Gain bonus weight capacity per active buff. Carry heavier loadouts
// as you accumulate forms. At full Mimicry (15 buffs), the bonus
// becomes massive — enabling loadouts normally impossible.
//
// TECHNICAL NOTE: ApplyWeightLimits doesn't receive OwnerPawn.
// We use a class-level cache updated by InitiateWeapon (which fires
// per-player on weapon pickup and after every buff roll via
// ForceWeaponRecalc -> UpdateWeaponMagAndCap). This works correctly
// on solo and listen servers. On dedicated servers with multiple
// Shapeshifters, the cache could briefly show another player's value
// between InitiateWeapon calls — acceptable trade-off given the mod's
// primary listen-server target.
//
// Standard: +1 weight per 2 active buffs (max +7 at full Mimicry)
// Deluxe:   +1 weight per active buff (max +15 at full Mimicry)
// ===================================================================
class DKUpgrade_Skill_SurplusForm extends DKUpgrade_Skill
    config(ZedternalReborn);

// Cache the computed weight bonus so ApplyWeightLimits can read it
// without needing OwnerPawn. Updated each time InitiateWeapon fires.
// Must be config to allow runtime writes via default. in static functions.
var config int CachedWeightBonus;

// Helper lookup - reuses the Shapeshifter perk's static GetHelper
static simulated function DKUpgrade_Perk_Shapeshifter_Helper GetShapeshifterHelper(Pawn OwnerPawn)
{
    return class'DKUpgrade_Perk_Shapeshifter'.static.GetHelper(OwnerPawn);
}

// Snapshot buff count into cached weight bonus
// Called on weapon pickup AND after every buff roll (via ForceWeaponRecalc)
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Perk_Shapeshifter_Helper Helper;
    local int BuffCount;

    if (OwnerPawn == None) return;

    Helper = GetShapeshifterHelper(OwnerPawn);
    if (Helper == None)
    {
        default.CachedWeightBonus = 0;
        return;
    }

    BuffCount = Helper.CountActiveBits(Helper.ReplicatedBuffMask);

    if (upgLevel > 1)
    {
        // Deluxe: +1 weight per active buff
        default.CachedWeightBonus = BuffCount;
    }
    else
    {
        // Standard: +1 weight per 2 active buffs (integer division)
        default.CachedWeightBonus = BuffCount / 2;
    }
}

// Apply cached weight bonus
static function ApplyWeightLimits(out int InWeightLimit, int DefaultWeightLimit, int upgLevel)
{
    InWeightLimit += default.CachedWeightBonus;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_SurplusForm]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_SurplusForm"

    UpgradeName="Surplus Form"
    UpgradeDescription(0)="<font color=\"#c77dff\">Surplus Form:</font> Gain <font color=\"#FFFFFF\">+1</font> <font color=\"#e0aaff\">weight capacity</font> per <font color=\"#FFFFFF\">2</font> active buffs (max <font color=\"#FFFFFF\">+7</font> at full Mimicry)"
    UpgradeDescription(1)="<font color=\"#c77dff\">Surplus Form:</font> Gain <font color=\"#FFFFFF\">+1</font> <font color=\"#e0aaff\">weight capacity</font> per active buff (max <font color=\"#FFFFFF\">+15</font> at full Mimicry)"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SurplusForm'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SurplusForm_Deluxe'

    Name="Default__DKUpgrade_Skill_SurplusForm"
}
