// ===================================================================
// DKUpgrade_Skill_Mitosis
// The hivemind's cellular division extends to ammunition -
// biomass consumed from kills is converted and channeled
// directly into the weapon's magazine, splitting and
// multiplying rounds from organic matter.
//
// Normal: Every 15 kills, instantly refill your current magazine
// Deluxe: Every 10 kills, instantly refill your current magazine
//
// BUGFIX 1: The kill quota is no longer consumed by a no-op refill.
// Previously the counter reset to 0 BEFORE the refill attempt, and
// the refill silently did nothing if the magazine was full, a melee
// weapon was held, or spare ammo was empty. With Hivemind's burst
// kills the trigger regularly landed right after a reload and
// evaporated. The counter now only resets when rounds actually moved;
// otherwise the trigger is banked and retried on the next kill.
//
// BUGFIX 2: The threshold is refreshed on every kill, so buying the
// deluxe tier mid-game takes effect immediately instead of being
// locked to the value captured when the helper first spawned.
// ===================================================================
class DKUpgrade_Skill_Mitosis extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<byte> KillThreshold;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.KillThreshold[0] = 15;
		default.KillThreshold[1] = 10;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// AddVampireHealth is called on every kill
static function AddVampireHealth(out int InHealth, int DefaultHealth, int upgLevel, KFPlayerController KFPC, class<DamageType> DT)
{
	local DKUpgrade_Skill_Mitosis_Helper UPG;

	if (KFPC == None || KFPC.Pawn == None || upgLevel < 1)
		return;

	UPG = GetHelper(KFPC.Pawn, upgLevel);
	if (UPG != None)
	{
		// Refresh every call so a mid-game deluxe purchase applies instantly
		UPG.bDeluxe = (upgLevel > 1);
		if (upgLevel - 1 < default.KillThreshold.Length)
			UPG.KillThreshold = default.KillThreshold[upgLevel - 1];

		UPG.OnKill();
	}
}

static function DKUpgrade_Skill_Mitosis_Helper GetHelper(Pawn OwnerPawn, int upgLevel)
{
	local DKUpgrade_Skill_Mitosis_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Mitosis_Helper', UPG)
		{
			return UPG;
		}

		// Should have one - spawn it
		UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_Mitosis_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_Mitosis_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Mitosis_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Mitosis]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Mitosis"

	UpgradeName="Mitosis"
	UpgradeDescription(0)="<font color=\"#9370DB\">Mitosis:</font> Every <font color=\"#FFFFFF\">15 kills</font>, <font color=\"#15d7fa\">instantly refill</font> your current magazine."
	UpgradeDescription(1)="<font color=\"#9370DB\">Mitosis:</font> Every <font color=\"#FFFFFF\">10 kills</font>, <font color=\"#15d7fa\">instantly refill</font> your current magazine."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Mitosis'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Mitosis_Deluxe'

	Name="Default__DKUpgrade_Skill_Mitosis"
}
