// ===================================================================
// DKUpgrade_Skill_SymbioticRestoration
// The hivemind's healing tendrils don't just mend flesh - they
// secrete a hardening resin that reinforces armor plating,
// knitting together what was broken.
//
// Normal: Healing a teammate also repairs 25% of heal amount as armor
// Deluxe: Healing a teammate also repairs 50% of heal amount as armor
// ===================================================================
class DKUpgrade_Skill_SymbioticRestoration extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> ArmorPercent;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ArmorPercent[0] = 0.25f;
		default.ArmorPercent[1] = 0.50f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function HealingDamage(int upgLevel, int HealAmount, KFPawn HealedPawn, KFPawn InstigatorPawn, class<DamageType> DamageType)
{
	local KFPawn_Human HealedHuman;
	local int ArmorRepair;

	if (HealAmount <= 0)
		return;

	HealedHuman = KFPawn_Human(HealedPawn);
	if (HealedHuman == None)
		return;

	// Only repair if armor is damaged
	if (HealedHuman.Armor < HealedHuman.MaxArmor)
	{
		ArmorRepair = Round(float(HealAmount) * default.ArmorPercent[upgLevel - 1]);
		if (ArmorRepair > 0)
		{
			HealedHuman.Armor = Min(HealedHuman.Armor + ArmorRepair, HealedHuman.MaxArmor);
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_SymbioticRestoration]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_SymbioticRestoration"

	UpgradeName="Symbiotic Restoration"
	UpgradeDescription(0)="Healing a teammate also repairs <font color=\"#4444ff\">25%</font> of the <font color=\"#42e087\">heal amount</font> as <font color=\"#4444ff\">armor</font>."
	UpgradeDescription(1)="Healing a teammate also repairs <font color=\"#4444ff\">50%</font> of the <font color=\"#42e087\">heal amount</font> as <font color=\"#4444ff\">armor</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SymbioticRestoration'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SymbioticRestoration_Deluxe'

	Name="Default__DKUpgrade_Skill_SymbioticRestoration"
}
