// ===================================================================
// DKUpgrade_Skill_WildHunt - The Wild Trophy
//
// Set phase: Every Nth trophy collected transforms into the optimal
// category — the one that participates in the most incomplete sets
// (weighted by tier).
//
// Stacking phase: Every Nth trophy collected generates a bonus
// duplicate — you get the original trophy AND a free copy of the
// same category. The hunt's bounty grows.
//
// Normal: Every 5th trophy | Deluxe: Every 3rd trophy
// ===================================================================
class DKUpgrade_Skill_WildHunt extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> TrophyInterval;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.TrophyInterval[0] = 5;
		default.TrophyInterval[1] = 3;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Perk_Predator_Helper H;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        H = class'DKUpgrade_Perk_Predator'.static.GetHelper(OwnerPawn);
        if (H != None)
        {
            H.SkillWildHuntInterval = default.TrophyInterval[upgLevel - 1];
            `log("[DK_PREDATOR] WildHunt: every" @ H.SkillWildHuntInterval $ "th trophy transforms/duplicates");
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_WildHunt]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_WildHunt"

    UpgradeName="Wild Hunt"
    UpgradeDescription(0)="<font color=\"#FFD700\">Wild Hunt:</font> Every <font color=\"#FFFFFF\">5th</font> trophy transforms into the <font color=\"#87CEEB\">optimal category</font> for set completion. During stacking: collect a <font color=\"#87CEEB\">bonus duplicate</font> instead"
    UpgradeDescription(1)="<font color=\"#FFD700\">Wild Hunt:</font> Every <font color=\"#FFFFFF\">3rd</font> trophy transforms into the <font color=\"#87CEEB\">optimal category</font> for set completion. During stacking: collect a <font color=\"#87CEEB\">bonus duplicate</font> instead"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_WildHunt'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_WildHunt_Deluxe'

    Name="Default__DKUpgrade_Skill_WildHunt"
}
