class DKUpgrade_Skill_Counterforce extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Turn their hits into yours
// Damage you take is stored and released on your next melee attack
// 10 second cooldown after releasing stored damage

var config array<float> ConversionRate;
var config array<int> MaxStoredDamage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ConversionRate[0] = 0.5f;
		default.ConversionRate[1] = 0.8f;
		default.MaxStoredDamage[0] = 200;
		default.MaxStoredDamage[1] = 350;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_Counterforce_Helper UPG;

	if (InDamage > 0 && OwnerPawn != None)
	{
		UPG = GetHelper(OwnerPawn);
		if (UPG != None && !UPG.bOnCooldown)
		{
			UPG.StoreDamage(Round(float(DefaultDamage) * default.ConversionRate[upgLevel - 1]), default.MaxStoredDamage[upgLevel - 1]);
		}
	}
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_Counterforce_Helper UPG;

	if (DamageType != None && static.IsMeleeDamageType(DamageType) && DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		UPG = GetHelper(KFPawn(DamageInstigator.Pawn));
		if (UPG != None && UPG.CurrentStoredDamage > 0 && !UPG.bOnCooldown)
		{
			InDamage += UPG.CurrentStoredDamage;
			UPG.ReleaseStoredDamage();
		}
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_Counterforce_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Counterforce_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			OwnerPawn.Spawn(class'DKUpgrade_Skill_Counterforce_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_Counterforce_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_Counterforce_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Counterforce_Helper', UPG)
		{
			return UPG;
		}

		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_Counterforce_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_Counterforce_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Counterforce_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Counterforce]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Counterforce"

	UpgradeName="Counterforce"

	UpgradeDescription(0)="<font color=\"#edb82a\">Counterforce</font> Damage you take is stored (<font color=\"#FF4500\">50%</font> conversion, max <font color=\"#FFFFFF\">200</font>). Your next <font color=\"#FF4500\">melee attack</font> releases all stored damage as bonus. <font color=\"#AAAAAA\">10 second cooldown after release.</font>"
	UpgradeDescription(1)="<font color=\"#edb82a\">Counterforce</font> Damage you take is stored (<font color=\"#FF4500\">80%</font> conversion, max <font color=\"#FFFFFF\">350</font>). Your next <font color=\"#FF4500\">melee attack</font> releases all stored damage as bonus. <font color=\"#AAAAAA\">10 second cooldown after release.</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Counterforce'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Counterforce_Deluxe'

	Name="Default__DKUpgrade_Skill_Counterforce"
}
