class DKUpgrade_Skill_Cryosynthesis extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> SpareAmmo;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.SpareAmmo[0] = 0.20f;
		default.SpareAmmo[1] = 0.40f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// BUGFIX: the grant previously went through KFInventoryManager.AddGrenades,
// which clamps to the perk's MaxGrenadeCount. Since WaveEnd fires at the
// wave boundary when players are typically at or near max grenades (or top
// up at the trader right after), the grant was silently absorbed by the cap
// and never visible. The count is now written directly so the bonus stacks
// ON TOP of the current amount, letting the player enter the next wave with
// grenades above the normal cap. GrenadeCount is replicated, so the HUD
// picks the change up automatically.
static function WaveEnd(int upgLevel, KFPlayerController KFPC)
{
	local KFPawn Player;
	local KFInventoryManager KFIM;
	local int NewCount;

	Player = KFPawn(KFPC.Pawn);
	if (Player == None || !Player.IsAliveAndWell())
		return;

	KFIM = KFInventoryManager(Player.InvManager);
	if (KFIM == None)
		return;

	if (upgLevel == 1)
		NewCount = int(KFIM.GrenadeCount) + 2;
	else
		NewCount = int(KFIM.GrenadeCount) + 4;

	KFIM.GrenadeCount = byte(Min(255, NewCount));
}

static simulated function ModifySpareAmmoAmount(out int InSpareAmmo, int DefaultSpareAmmo, int upgLevel, KFWeapon KFW, const optional out STraderItem TraderItem, optional bool bSecondary)
{
	if (!bSecondary)
	{
		InSpareAmmo += Round(float(DefaultSpareAmmo) * default.SpareAmmo[upgLevel - 1]);
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Cryosynthesis]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Cryosynthesis"

    UpgradeName="Cryosynthesis"
	upgradeDescription(0)="At the start of each wave, you gain <font color=\"#0bf1f1\">2 Grenades</font>. Your <font color=\"#15d7fa\">Spare Ammunition</font> is increased by <font color=\"#15d7fa\">20%</font>."
	upgradeDescription(1)="At the start of each wave, you gain <font color=\"#0bf1f1\">4 Grenades</font>. Your <font color=\"#15d7fa\">Spare Ammunition</font> is increased by <font color=\"#15d7fa\">40%</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Cryosynthesis'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Cryosynthesis_Deluxe'

	Name="Default__DKUpgrade_Skill_Cryosynthesis"
}
