class DKUpgrade_Skill_SoulOverflow extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Soul Overflow: Each kill channels soul energy into your weapon, restoring rounds
// to the current magazine from spare ammo. Uses the MagicBullet helper pattern.

var config array<int> Ammo;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Ammo[0] = 1;
		default.Ammo[1] = 3;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function AddVampireHealth(out int InHealth, int DefaultHealth, int upgLevel, KFPlayerController KFPC, class<DamageType> DT)
{
	local DKUpgrade_Skill_SoulOverflow_Helper UPG;

	UPG = GetHelper(KFPC.Pawn);
	if (UPG != None)
	{
		if (UPG.Player.WorldInfo.NetMode == NM_Standalone)
			UPG.StandaloneUpdateAmmo(default.Ammo[upgLevel - 1]);
		else
			UPG.ServerUpdateAmmo(default.Ammo[upgLevel - 1]);
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_SoulOverflow_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_SoulOverflow_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_SoulOverflow_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_SoulOverflow_Helper GetHelper(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_SoulOverflow_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_SoulOverflow_Helper', UPG)
		{
			return UPG;
		}

		UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_SoulOverflow_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_SoulOverflow_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_SoulOverflow_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_SoulOverflow]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_SoulOverflow"

	UpgradeName="Soul Overflow"
	UpgradeDescription(0)="<font color=\"#CC0000\">Soul Overflow:</font> Each kill restores <font color=\"#FFFFFF\">1</font> <font color=\"#66CCFF\">round</font> to your current magazine from spare ammo. Keep the reaping continuous."
	UpgradeDescription(1)="<font color=\"#CC0000\">Soul Overflow:</font> Each kill restores <font color=\"#FFFFFF\">3</font> <font color=\"#66CCFF\">rounds</font> to your current magazine from spare ammo. Keep the reaping continuous."

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SoulOverflow'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SoulOverflow_Deluxe'

	Name="Default__DKUpgrade_Skill_SoulOverflow"
}
