class DKUpgrade_Skill_ToxicAura extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> AuraRange;
var config array<int> AuraDamage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.AuraRange[0] = 300.0f;
		default.AuraRange[1] = 500.0f;
		default.AuraDamage[0] = 2;
		default.AuraDamage[1] = 4;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_ToxicAura_Helper AuraHelper;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ToxicAura_Helper', AuraHelper)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            AuraHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_ToxicAura_Helper', OwnerPawn);
            AuraHelper.UpgradeLevel = upgLevel;
        }
    }
}

static function DKUpgrade_Skill_ToxicAura_Helper GetHelper(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_ToxicAura_Helper AuraHelper;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ToxicAura_Helper', AuraHelper)
        {
            return AuraHelper;
        }

        // Create one if needed
        AuraHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_ToxicAura_Helper', OwnerPawn);
    }

    return AuraHelper;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_ToxicAura_Helper AuraHelper;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ToxicAura_Helper', AuraHelper)
        {
            AuraHelper.Destroy();
        }
    }
}

defaultproperties
{
    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_ToxicAura]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_ToxicAura"

    UpgradeName="Toxic Aura"
    UpgradeDescription(0)="<font color=\"#8B008B\">Toxic Aura:</font> Enemies within <font color=\"#FFFFFF\">3m</font> take <font color=\"#00FF00\">2 poison damage</font> per second."
    UpgradeDescription(1)="<font color=\"#8B008B\">Toxic Aura (Deluxe):</font> Enemies within <font color=\"#FFFFFF\">5m</font> take <font color=\"#00FF00\">4 poison damage</font> per second."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ToxicAura'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ToxicAura_Deluxe'
    
    Name="Default__DKUpgrade_Skill_ToxicAura"
}