class DKUpgrade_Skill_CurseOfStone extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> CurseChance;
var config array<float> CurseDamageMultiplier;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.CurseChance[0] = 0.03f;
		default.CurseChance[1] = 0.05f;
		default.CurseDamageMultiplier[0] = 1.0f;
		default.CurseDamageMultiplier[1] = 1.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_CurseOfStone_Helper CurseHelper;
    local float RandValue;
    local bool bShouldCurse, bIsCursed;
    
    if (DamageInstigator == None || DamageInstigator.Pawn == None || MyKFPM == None) return;
    
    // Get helper to manage curse effects
    CurseHelper = GetHelper(DamageInstigator.Pawn);
    if (CurseHelper == None) return;
    
    // Check if target is already cursed
    bIsCursed = CurseHelper.IsMonsterCursed(MyKFPM);
    
    // If cursed, apply double damage
    if (bIsCursed)
    {
        InDamage += Round(float(DefaultDamage) * default.CurseDamageMultiplier[upgLevel - 1]);
    }
    
    // Roll for curse chance on hit (only if not already cursed)
    if (!bIsCursed)
    {
        RandValue = FRand();
        bShouldCurse = (RandValue <= default.CurseChance[upgLevel - 1]);
        
        if (bShouldCurse)
        {
            CurseHelper.CurseMonster(MyKFPM, upgLevel);
        }
    }
    
    // Handle curse spreading on death (Deluxe version)
    if (upgLevel == 2 && InDamage >= MyKFPM.Health && bIsCursed)
    {
        CurseHelper.SpreadCurseOnDeath(MyKFPM);
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_CurseOfStone_Helper CurseHelper;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CurseOfStone_Helper', CurseHelper)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            CurseHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_CurseOfStone_Helper', OwnerPawn);
            CurseHelper.UpgradeLevel = upgLevel;
        }
    }
}

static function DKUpgrade_Skill_CurseOfStone_Helper GetHelper(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_CurseOfStone_Helper CurseHelper;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CurseOfStone_Helper', CurseHelper)
        {
            return CurseHelper;
        }

        // Create one if needed
        CurseHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_CurseOfStone_Helper', OwnerPawn);
    }

    return CurseHelper;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_CurseOfStone_Helper CurseHelper;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CurseOfStone_Helper', CurseHelper)
        {
            CurseHelper.Destroy();
        }
    }
}

defaultproperties
{
    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_CurseOfStone]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_CurseOfStone"

    UpgradeName="Curse of Stone"
    UpgradeDescription(0)="<font color=\"#8B008B\">Curse of Stone:</font> <font color=\"#FFFFFF\">3% chance</font> on hit to <font color=\"#FFD700\">curse</font> enemy - they take <font color=\"#FF6666\">double damage</font> from all sources for <font color=\"#FFFFFF\">5 seconds</font>."
    UpgradeDescription(1)="<font color=\"#8B008B\">Curse of Stone (Deluxe):</font> <font color=\"#FFFFFF\">5% chance</font> on hit to <font color=\"#FFD700\">curse</font> enemy - they take <font color=\"#FF6666\">double damage</font> from all sources for <font color=\"#FFFFFF\">5 seconds</font> + <font color=\"#FFD700\">cursed enemies spread curse</font> to nearby enemies on death."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CurseOfStone'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CurseOfStone_Deluxe'
    
    Name="Default__DKUpgrade_Skill_CurseOfStone"
}