class DKUpgrade_Skill_ArmorPiercingProtocol extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> PenetrationBonus;
var config array<float> LargeZedDamage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.PenetrationBonus[0] = 0.40f;
		default.PenetrationBonus[1] = 0.70f;
		default.LargeZedDamage[0] = 0.15f;
		default.LargeZedDamage[1] = 0.25f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function ModifyPenetration(out float InPenetration, float DefaultPenetration, int upgLevel, class<KFDamageType> DamageType, KFPawn OwnerPawn, optional bool bForce)
{
	local KFWeapon KFW;

	if (OwnerPawn == None)
		return;

	KFW = KFWeapon(OwnerPawn.Weapon);
	if (!IsRifleWeapon(KFW))
		return;

	InPenetration += DefaultPenetration * default.PenetrationBonus[upgLevel - 1];
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (MyKFPM == None || MyKFW == None)
		return;

	if (!IsRifleWeapon(MyKFW))
		return;

	if (!IsLargeZed(MyKFPM))
		return;

	InDamage += Round(float(DefaultDamage) * default.LargeZedDamage[upgLevel - 1]);
}

static function bool IsLargeZed(KFPawn_Monster KFPM)
{
	if (KFPM == None)
		return False;

	return KFPM.static.IsLargeZed() ||
		ClassIsChildOf(KFPM.Class, class'KFPawn_ZedScrake') ||
		ClassIsChildOf(KFPM.Class, class'KFPawn_ZedFleshpound');
}

static function bool IsRifleWeapon(KFWeapon KFW)
{
	if (KFW == None)
		return False;

	if (IsWeaponOnSpecificPerk(KFW, class'KFGame.KFPerk_Commando'))
	{
		return (KFW.InstantHitDamage[0] >= 35 ||
				KFW.default.FireInterval[0] >= 0.08);
	}

	return (InStr(PathName(KFW.Class), "Rifle") != INDEX_NONE ||
			InStr(PathName(KFW.Class), "rifle") != INDEX_NONE);
}

defaultproperties
{


    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_ArmorPiercingProtocol]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_ArmorPiercingProtocol"

	UpgradeName="Armor-Piercing Protocol"
	UpgradeDescription(0)="Rifle rounds gain <font color=\"#77d914\">+40%</font> <font color=\"#15d7fa\">penetration</font> and deal <font color=\"#77d914\">+15%</font> <font color=\"#15d7fa\">bonus damage</font> to <font color=\"#ff3399\">Large ZEDs</font>."
	UpgradeDescription(1)="Rifle rounds gain <font color=\"#77d914\">+70%</font> <font color=\"#15d7fa\">penetration</font> and deal <font color=\"#77d914\">+25%</font> <font color=\"#15d7fa\">bonus damage</font> to <font color=\"#ff3399\">Large ZEDs</font>."

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ArmorPiercingProtocol'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ArmorPiercingProtocol_Deluxe'

	Name="Default__DKUpgrade_Skill_ArmorPiercingProtocol"
}
