// ===================================================================
// DKUpgrade_Skill_DefiantStand
//
// "Defiant Stand"
// After suffering doom, enter a 20-second rage mode with massive
// combat bonuses.
//
// Standard: +25% damage, +20% DR, +15% speed for 20s
// Deluxe:   +30% damage, +25% DR, +20% speed for 20s
// ===================================================================
class DKUpgrade_Skill_DefiantStand extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config float DamageBonus;
var config float DamageBonusDeluxe;
var config float DRBonus;
var config float DRBonusDeluxe;
var config float SpeedBonus;
var config float SpeedBonusDeluxe;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageBonus = 0.25f;
		default.DamageBonusDeluxe = 0.30f;
		default.DRBonus = 0.20f;
		default.DRBonusDeluxe = 0.25f;
		default.SpeedBonus = 0.15f;
		default.SpeedBonusDeluxe = 0.20f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
    optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
    optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
    optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_DefiantStand_Helper H;

    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;

    foreach DamageInstigator.Pawn.ChildActors(class'DKUpgrade_Skill_DefiantStand_Helper', H)
    {
        if (H.bBuffActive)
        {
            if (upgLevel >= 2)
                InDamage += Round(float(DefaultDamage) * default.DamageBonusDeluxe);
            else
                InDamage += Round(float(DefaultDamage) * default.DamageBonus);
        }
        break;
    }
}

static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel,
    KFPawn OwnerPawn, optional class<DamageType> DamageType,
    optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_DefiantStand_Helper H;

    if (OwnerPawn == None)
        return;

    foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_DefiantStand_Helper', H)
    {
        if (H.bBuffActive)
        {
            if (upgLevel >= 2)
                InDamage -= Round(float(DefaultDamage) * default.DRBonusDeluxe);
            else
                InDamage -= Round(float(DefaultDamage) * default.DRBonus);

            if (InDamage < 0)
                InDamage = 0;
        }
        break;
    }
}

static simulated function ModifySpeed(out float InSpeed, float DefaultSpeed,
    int upgLevel, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_DefiantStand_Helper H;

    if (OwnerPawn == None)
        return;

    foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_DefiantStand_Helper', H)
    {
        if (H.bBuffActive)
        {
            if (upgLevel >= 2)
                InSpeed += DefaultSpeed * default.SpeedBonusDeluxe;
            else
                InSpeed += DefaultSpeed * default.SpeedBonus;
        }
        break;
    }
}

// --- Helper spawning ---
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_DefiantStand_Helper H;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == ROLE_Authority)
    {
        bFound = false;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_DefiantStand_Helper', H)
        {
            bFound = true;
            H.Initialize(upgLevel);
            break;
        }

        if (!bFound)
        {
            H = OwnerPawn.Spawn(class'DKUpgrade_Skill_DefiantStand_Helper', OwnerPawn);
            if (H != None)
                H.Initialize(upgLevel);
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_DefiantStand_Helper H;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_DefiantStand_Helper', H)
        {
            H.Cleanup();
            H.Destroy();
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_DefiantStand]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_DefiantStand"

    UpgradeName="Defiant Stand"
    UpgradeDescription(0)="After suffering <font color=\"#ff0000\">doom</font>, gain <font color=\"#15d7fa\">+25% damage</font>, <font color=\"#15d7fa\">+20% damage resistance</font>, and <font color=\"#15d7fa\">+15% speed</font> for <font color=\"#ebc034\">20 seconds</font>."
    UpgradeDescription(1)="After suffering <font color=\"#ff0000\">doom</font>, gain <font color=\"#15d7fa\">+30% damage</font>, <font color=\"#15d7fa\">+25% damage resistance</font>, and <font color=\"#15d7fa\">+20% speed</font> for <font color=\"#ebc034\">20 seconds</font>."

    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_DefiantStand_Deluxe'

    Name="Default__DKUpgrade_Skill_DefiantStand"
}
