class DKUpgrade_Skill_AvalancheProtocol extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> AvalancheDamage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.AvalancheDamage[0] = 5;
		default.AvalancheDamage[1] = 10;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_AvalancheProtocol_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_AvalancheProtocol_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_AvalancheProtocol_Helper', OwnerPawn);
            UPG.bDeluxe = (upgLevel > 1);
            UPG.UpgradeLevel = upgLevel;
        }
    }
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_AvalancheProtocol_Helper UPG;

    // Check if this damage will kill the target
    if (MyKFPM != None && MyKFPM.IsAliveAndWell() && 
        DamageInstigator != None && DamageInstigator.Pawn != None &&
        (MyKFPM.Health - InDamage) <= 0)
    {
        foreach DamageInstigator.Pawn.ChildActors(class'DKUpgrade_Skill_AvalancheProtocol_Helper', UPG)
        {
            UPG.OnEnemyKilled(MyKFPM);
            break;
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_AvalancheProtocol_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_AvalancheProtocol_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_AvalancheProtocol]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_AvalancheProtocol"

    UpgradeName="Avalanche Protocol"
    upgradeDescription(0)="Killing an enemy causes all nearby enemies (<font color=\"#77d914\">8m radius</font>) to take <font color=\"#15d7fa\">5 Damage</font> and become <font color=\"#87CEEB\">Slowed</font> for <font color=\"#FFAA33\">5 seconds</font>."
    upgradeDescription(1)="Killing an enemy causes all nearby enemies (<font color=\"#77d914\">8m radius</font>) to take <font color=\"#15d7fa\">10 Damage</font> and become <font color=\"#87CEEB\">Slowed</font> for <font color=\"#FFAA33\">5 seconds</font>."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AvalancheProtocol'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AvalancheProtocol_Deluxe'

    Name="Default__DKUpgrade_Skill_AvalancheProtocol"
}