// ===================================================================
// DKUpgrade_Skill_Hivesight
// The hivemind organism perceives threats through shared neural
// pathways - enemy vitals pulse in your vision and cloaked
// predators cannot hide from the swarm's compound awareness.
//
// Normal: See enemy health bars
// Deluxe: See enemy health bars + greatly extended cloak detection
// ===================================================================
class DKUpgrade_Skill_Hivesight extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> CloakDetectionBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.CloakDetectionBonus[0] = 0.5f;
		default.CloakDetectionBonus[1] = 2.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function bool CanSeeEnemyHealth(int upgLevel, KFPawn OwnerPawn)
{
	return True;
}

static simulated function ModifyCloakDetectionRange(out float InRange, float DefaultRange, int upgLevel)
{
	InRange += DefaultRange * default.CloakDetectionBonus[upgLevel - 1];
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Hivesight]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Hivesight"

	UpgradeName="Hivesight"
	UpgradeDescription(0)="See <font color=\"#a0c1cb\">enemy health bars</font>."
	UpgradeDescription(1)="See <font color=\"#a0c1cb\">enemy health bars</font> and detect cloaked ZEDs at greatly extended range."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Hivesight'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Hivesight_Deluxe'

	Name="Default__DKUpgrade_Skill_Hivesight"
}
