// ===================================================================
// DKUpgrade_Skill_AllIn - Gambit Skill
//
// "All In" - While a gambit is active, gain a scaling fire rate
// bonus based on progress toward completion.
// At 0% progress: +0% fire rate. At 100% progress: +25% fire rate.
//
// Standard: Fire rate bonus only.
// Deluxe:   Also grants scaling movement speed (up to +15%).
//
// Uses ModifyRateOfFire + ModifySpeed hooks, reads state from helper.
// ===================================================================
class DKUpgrade_Skill_AllIn extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Max fire rate bonus at 100% progress
var config float MaxFireRateBonus;

// Max movement speed bonus at 100% progress (deluxe only)
var config float MaxSpeedBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MaxFireRateBonus = 0.25f;
		default.MaxSpeedBonus = 0.15f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// ===================================================================
// FIRE RATE -- Scales with gambit progress
// ===================================================================

static simulated function ModifyRateOfFire(out float InRate, float DefaultRate, int upgLevel, KFWeapon KFW)
{
    local KFPawn OwnerPawn;
    local DKUpgrade_Perk_Gambit_Helper H;
    local float Progress, Bonus;

    if (KFW == None)
        return;

    OwnerPawn = KFPawn(KFW.Instigator);
    if (OwnerPawn == None)
        return;

    H = class'DKUpgrade_Perk_Gambit'.static.FindHelper(OwnerPawn);
    if (H == None || !H.RepActive || H.RepCompleted)
        return;

    Progress = H.GetProgressPercent();
    if (Progress <= 0.0f)
        return;

    // Scale fire rate bonus: 0% to MaxFireRateBonus based on progress
    Bonus = Progress * default.MaxFireRateBonus;

    // Reduce fire interval (lower InRate = faster firing)
    InRate *= 1.0f / (1.0f + Bonus);
}

// ===================================================================
// SPEED -- Scales with gambit progress (Deluxe only)
// ===================================================================

static simulated function ModifySpeed(out float InSpeed, float DefaultSpeed, int upgLevel, KFPawn OwnerPawn)
{
    local DKUpgrade_Perk_Gambit_Helper H;
    local float Progress, Bonus;

    // Deluxe only
    if (upgLevel < 2)
        return;

    if (OwnerPawn == None)
        return;

    H = class'DKUpgrade_Perk_Gambit'.static.FindHelper(OwnerPawn);
    if (H == None || !H.RepActive || H.RepCompleted)
        return;

    Progress = H.GetProgressPercent();
    if (Progress <= 0.0f)
        return;

    Bonus = Progress * default.MaxSpeedBonus;
    InSpeed += DefaultSpeed * Bonus;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_AllIn]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_AllIn"

    UpgradeName="All In"
    upgradeDescription(0)="While a gambit is active, gain up to <font color=\"#FFD700\">+25%</font> fire rate based on progress toward completion."
    upgradeDescription(1)="While a gambit is active, gain up to <font color=\"#FFD700\">+25%</font> fire rate and <font color=\"#FFD700\">+15%</font> movement speed based on progress."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AllIn'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AllIn_Deluxe'

    Name="Default__DKUpgrade_Skill_AllIn"
}
