// ===================================================================
// DKUpgrade_Skill_OverclockedForm
//
// "Push the body beyond its design tolerances."
//
// Increases all buff effectiveness but makes you take more damage.
// Glass cannon trade-off that becomes extremely powerful at Mimicry
// with many permanent buffs. The amplifier stacks multiplicatively
// with other skill multipliers (Flux State, Monomorph).
//
// Works through GetBuffEffectiveness() on the helper - the
// BuffAmplifier var multiplies all active buff values.
// The damage taken penalty is handled independently by this skill.
//
// Standard: +25% buff effectiveness, +10% damage taken
// Deluxe:   +50% buff effectiveness, +15% damage taken
// ===================================================================
class DKUpgrade_Skill_OverclockedForm extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Amplification;
var config array<float> DamagePenalty;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Amplification[0] = 0.25f;
		default.Amplification[1] = 0.50f;
		default.DamagePenalty[0] = 0.10f;
		default.DamagePenalty[1] = 0.15f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// Helper lookup - reuses the Shapeshifter perk's static GetHelper
static simulated function DKUpgrade_Perk_Shapeshifter_Helper GetShapeshifterHelper(Pawn OwnerPawn)
{
    return class'DKUpgrade_Perk_Shapeshifter'.static.GetHelper(OwnerPawn);
}

// Configure the helper's buff amplifier on weapon init (server-side)
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Perk_Shapeshifter_Helper Helper;

    if (OwnerPawn == None || OwnerPawn.Role != Role_Authority)
        return;

    Helper = GetShapeshifterHelper(OwnerPawn);
    if (Helper == None)
        return;

    Helper.BuffAmplifier = 1.0f + default.Amplification[upgLevel - 1];
    Helper.bNetDirty = true;
}

// Damage taken penalty - independent of helper system
static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    InDamage += Round(float(DefaultDamage) * default.DamagePenalty[upgLevel - 1]);
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_OverclockedForm]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_OverclockedForm"

    UpgradeName="Overclocked Form"
    UpgradeDescription(0)="<font color=\"#c77dff\">Overclocked Form:</font> All buff effectiveness increased by <font color=\"#FFFFFF\">25%</font>, but you take <font color=\"#FF6666\">+10%</font> <font color=\"#FF6666\">more damage</font>"
    UpgradeDescription(1)="<font color=\"#c77dff\">Overclocked Form:</font> All buff effectiveness increased by <font color=\"#FFFFFF\">50%</font>, but you take <font color=\"#FF6666\">+15%</font> <font color=\"#FF6666\">more damage</font>"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_OverclockedForm'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_OverclockedForm_Deluxe'

    Name="Default__DKUpgrade_Skill_OverclockedForm"
}
