// ===================================================================
// DKUpgrade_Skill_Soulbound — Artificer Skill
//
// "Your most-mastered weapon becomes your Soulbound weapon.
//  It gains massive bonus damage per milestone. All other weapons
//  gain a smaller bonus based on your Soulbound weapon's mastery."
//
// Works with ALL weapons (mastery-based, not Reforged-only).
// Requires Artificer perk to be active (reads its helper's MasteryData).
//
// Normal:  Soulbound: +5% damage per milestone. Others: +2% per milestone
// Deluxe:  Soulbound: +10% damage per milestone. Others: +4% per milestone
//
// The weapon with the highest MilestonesCompleted is the Soulbound.
// Ties go to whichever was mastered first (first in array).
//
// Hook: ModifyDamageGiven
// Helper: None (reads DKUpgrade_Perk_Artificer_Helper)
// ===================================================================
class DKUpgrade_Skill_Soulbound extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> SoulboundDamagePerMilestone;   // bonus for THE soulbound weapon
var config array<float> CrossDamagePerMilestone;        // bonus for all OTHER weapons
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.SoulboundDamagePerMilestone[0] = 0.05f;
		default.SoulboundDamagePerMilestone[1] = 0.10f;
		default.CrossDamagePerMilestone[0] = 0.02f;
		default.CrossDamagePerMilestone[1] = 0.04f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Perk_Artificer_Helper ArtHelper;
    local string CurrentNorm, SoulboundNorm;
    local int SoulboundMilestones;
    local float Bonus;

    if (DamageInstigator == None || DamageInstigator.Pawn == None || MyKFW == None)
        return;

    // Find Artificer helper on this player
    ArtHelper = FindArtificerHelper(DamageInstigator.Pawn);
    if (ArtHelper == None)
        return;

    // Determine the Soulbound weapon (highest milestones)
    FindSoulboundWeapon(ArtHelper, SoulboundNorm, SoulboundMilestones);
    if (SoulboundMilestones <= 0)
        return; // No mastery milestones yet — no bonus

    // Get current weapon's normalized name
    CurrentNorm = class'DKUpgrade_Perk_Artificer'.static.NormalizeWeaponName(string(MyKFW.Class.Name));

    // Apply appropriate bonus
    if (CurrentNorm ~= SoulboundNorm)
    {
        // This IS the Soulbound weapon — big bonus
        Bonus = float(SoulboundMilestones) * default.SoulboundDamagePerMilestone[upgLevel - 1];
    }
    else
    {
        // Other weapon — smaller cross-bonus from Soulbound mastery
        Bonus = float(SoulboundMilestones) * default.CrossDamagePerMilestone[upgLevel - 1];
    }

    if (Bonus > 0.f)
        InDamage += Round(float(DefaultDamage) * Bonus);
}

// ===================================================================
// ARTIFICER HELPER ACCESS
// ===================================================================

static function DKUpgrade_Perk_Artificer_Helper FindArtificerHelper(Pawn P)
{
    local DKUpgrade_Perk_Artificer_Helper H;

    if (P != None)
    {
        foreach P.ChildActors(class'DKUpgrade_Perk_Artificer_Helper', H)
        {
            return H;
        }
    }

    return None;
}

// Find the weapon with the most mastery milestones
static function FindSoulboundWeapon(DKUpgrade_Perk_Artificer_Helper ArtHelper, out string OutName, out int OutMilestones)
{
    local int i, BestMilestones;
    local string BestName;

    BestMilestones = 0;
    BestName = "";

    for (i = 0; i < ArtHelper.MasteryData.Length; ++i)
    {
        if (ArtHelper.MasteryData[i].MilestonesCompleted > BestMilestones)
        {
            BestMilestones = ArtHelper.MasteryData[i].MilestonesCompleted;
            BestName = ArtHelper.MasteryData[i].NormName;
        }
    }

    OutName = BestName;
    OutMilestones = BestMilestones;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Soulbound]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Soulbound"

    UpgradeName="Soulbound"
    UpgradeDescription(0)="Your most-mastered weapon gains <font color=\"#FFFFFF\">+5%</font> <font color=\"#FFD700\">damage per milestone</font>. Other weapons gain <font color=\"#FFFFFF\">+2%</font> per milestone"
    UpgradeDescription(1)="Your most-mastered weapon gains <font color=\"#FFFFFF\">+10%</font> <font color=\"#FFD700\">damage per milestone</font>. Other weapons gain <font color=\"#FFFFFF\">+4%</font> per milestone"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Soulbound'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Soulbound_Deluxe'

    Name="Default__DKUpgrade_Skill_Soulbound"
}
