class DKUpgrade_Skill_JuryRig extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// After switching weapons, your first few shots deal bonus damage
// Encourages rapid weapon rotation mid-fight

var config array<float> DamageBonus;   // Damage bonus per boosted shot
var config array<int> BonusShots;      // Number of boosted shots after switch
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageBonus[0] = 0.20f;
		default.DamageBonus[1] = 0.40f;
		default.BonusShots[0] = 3;
		default.BonusShots[1] = 5;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_JuryRig_Helper UPG;

	if (MyKFPM != None && DamageInstigator != None && DamageInstigator.Pawn != None && MyKFW != None)
	{
		UPG = GetHelper(DamageInstigator.Pawn);
		if (UPG != None)
		{
			// Check if weapon changed since last damage event
			if (UPG.LastWeapon != MyKFW)
			{
				UPG.LastWeapon = MyKFW;
				UPG.RemainingBonusShots = default.BonusShots[upgLevel - 1];
			}

			// Apply bonus damage if we have shots remaining
			if (UPG.RemainingBonusShots > 0)
			{
				InDamage += Round(float(DefaultDamage) * default.DamageBonus[upgLevel - 1]);

				// Only decrement once per frame (handles shotgun pellets)
				if (UPG.LastBonusShotTime != UPG.Player.WorldInfo.TimeSeconds)
				{
					UPG.LastBonusShotTime = UPG.Player.WorldInfo.TimeSeconds;
					UPG.RemainingBonusShots -= 1;
				}
			}
		}
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_JuryRig_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_JuryRig_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_JuryRig_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_JuryRig_Helper GetHelper(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_JuryRig_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_JuryRig_Helper', UPG)
		{
			return UPG;
		}

		UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_JuryRig_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_JuryRig_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_JuryRig_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_JuryRig]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_JuryRig"

	UpgradeName="Jury Rig"

	UpgradeDescription(0)="<font color=\"#DAA520\">Jury Rig:</font> First <font color=\"#FFFFFF\">3 shots</font> after switching weapons deal <font color=\"#FF4444\">+20%</font> <font color=\"#87CEEB\">damage</font>"
	UpgradeDescription(1)="<font color=\"#FFD700\">Jury Rig:</font> First <font color=\"#FFFFFF\">5 shots</font> after switching weapons deal <font color=\"#FF4444\">+40%</font> <font color=\"#87CEEB\">damage</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_JuryRig'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_JuryRig_Deluxe'

	Name="Default__DKUpgrade_Skill_JuryRig"
}
