// ===================================================================
// DKUpgrade_Skill_FluxState
//
// "In the space between moments, all forms exist at once."
//
// During ZED time, all buff effectiveness is amplified. The
// Shapeshifter becomes a ZED time monster, with every active buff
// hitting harder. Synergizes especially well with the Phantom buff
// (#14 ZED time fire rate) for devastating burst windows.
//
// Works through GetBuffEffectiveness() on the helper - the
// ZedTimeBuffMultiplier var is applied when WorldInfo.TimeDilation < 1.0.
// Stacks multiplicatively with other multipliers (Overclocked, Monomorph).
//
// Standard: +50% buff effectiveness during ZED time (1.5x)
// Deluxe:   +100% buff effectiveness during ZED time (2.0x)
// ===================================================================
class DKUpgrade_Skill_FluxState extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> ZedTimeAmplification;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ZedTimeAmplification[0] = 0.50f;
		default.ZedTimeAmplification[1] = 1.00f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// Helper lookup - reuses the Shapeshifter perk's static GetHelper
static simulated function DKUpgrade_Perk_Shapeshifter_Helper GetShapeshifterHelper(Pawn OwnerPawn)
{
    return class'DKUpgrade_Perk_Shapeshifter'.static.GetHelper(OwnerPawn);
}

// Configure the helper's ZED time multiplier on weapon init (server-side)
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Perk_Shapeshifter_Helper Helper;

    if (OwnerPawn == None || OwnerPawn.Role != Role_Authority)
        return;

    Helper = GetShapeshifterHelper(OwnerPawn);
    if (Helper == None)
        return;

    Helper.ZedTimeBuffMultiplier = 1.0f + default.ZedTimeAmplification[upgLevel - 1];
    Helper.bNetDirty = true;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_FluxState]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_FluxState"

    UpgradeName="Flux State"
    UpgradeDescription(0)="<font color=\"#c77dff\">Flux State:</font> During <font color=\"#e0aaff\">ZED time</font>, all buff effectiveness is increased by <font color=\"#FFFFFF\">50%</font>"
    UpgradeDescription(1)="<font color=\"#c77dff\">Flux State:</font> During <font color=\"#e0aaff\">ZED time</font>, all buff effectiveness is increased by <font color=\"#FFFFFF\">100%</font>"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FluxState'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FluxState_Deluxe'

    Name="Default__DKUpgrade_Skill_FluxState"
}
