class DKUpgrade_Skill_Backdraft extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> FireRate, SpecialRate;
var config array<float> ZedTimeExt;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.FireRate[0] = 0.5f;
		default.FireRate[1] = 0.8f;
		default.SpecialRate[0] = 0.2f;
		default.SpecialRate[1] = 0.35f;
		default.ZedTimeExt[0] = 0.0f;
		default.ZedTimeExt[1] = 0.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function bool IsUnAffectedByZedTime(int upgLevel, KFPawn OwnerPawn)
{
	return True;
}

static simulated function GetZedTimeModifier(out float InModifier, int upgLevel, KFWeapon KFW)
{
	local name StateName;

	if (KFW != None)
	{
		StateName = KFW.GetStateName();
		if (class'ZedternalReborn.WMWeaponStates'.static.IsWeaponAttackState(StateName))
		{
			if (KFWeap_MeleeBase(KFW) != None || KFW.default.MagazineCapacity[0] > 4)
				InModifier += default.FireRate[upgLevel - 1];
			else
				InModifier += default.SpecialRate[upgLevel - 1];
		}
	}
}

static simulated function GetZedTimeExtension(out float InExtension, float DefaultExtension, int upgLevel)
{
	InExtension += DefaultExtension * default.ZedTimeExt[upgLevel - 1];
}

static simulated function RevertUpgradeChanges(Pawn OwnerPawn)
{
	if (KFPawn_Human(OwnerPawn) != None)
		KFPawn_Human(OwnerPawn).bMovesFastInZedTime = False;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Backdraft]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Backdraft"

	UpgradeName="Backdraft"
	upgradeDescription(0)="You are <font color=\"#e80948\">unaffected by Zed Time</font>, moving and attacking at real-time speed."
	upgradeDescription(1)="You are <font color=\"#e80948\">unaffected by Zed Time</font>, moving and attacking at real-time speed. Extends <font color=\"#e80948\">Zed Time Duration</font> by <font color=\"#e85009\">50%</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Backdraft'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Backdraft_Deluxe'

	Name="Default__DKUpgrade_Skill_Backdraft"
}
