// ===================================================================
// DKUpgrade_Skill_VoidSustain
// Hollow Skill — unlocks the Void Sustain weapon upgrade in the trader.
// Void Sustain: chance on kill to instantly refill the magazine.
// Deluxe: higher proc chance.
// ===================================================================
class DKUpgrade_Skill_VoidSustain extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_VoidSustain]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_VoidSustain"

	UpgradeName="Void Sustain"
	UpgradeDescription(0)="Unlocks the <font color=\"#00CCFF\">Void Sustain</font> weapon upgrade in the trader for all your weapons. Void Sustain grants a chance on kill to <font color=\"#6B0099\">instantly refill the magazine</font>."
	UpgradeDescription(1)="Upgrades your <font color=\"#00CCFF\">Void Sustain</font> weapon upgrade to its <font color=\"#6B0099\">Deluxe</font> variant, increasing the proc chance."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_VoidSustain'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_VoidSustain_Deluxe'
	Name="Default__DKUpgrade_Skill_VoidSustain"
}
