class DKUpgrade_Skill_DesperateSymbiosis extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DamageBonus;
var config array<float> Penalty;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageBonus[0] = 0.40f;
		default.DamageBonus[1] = 0.65f;
		default.Penalty[0] = 0.15f;
		default.Penalty[1] = 0.10f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local KFPawn_Human OwnerPawn;
	local float HealthPercent;

	if (DamageInstigator == None || DamageInstigator.Pawn == None)
		return;

	OwnerPawn = KFPawn_Human(DamageInstigator.Pawn);
	if (OwnerPawn == None)
		return;

	HealthPercent = float(OwnerPawn.Health) / float(OwnerPawn.HealthMax);

	if (HealthPercent < 0.5f)
	{
     InDamage += Round(float(DefaultDamage) * (default.DamageBonus[upgLevel -1]));
	}
}

static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local KFPawn_Human HumanPawn;
	local float HealthPercent;

	if (OwnerPawn == None)
		return;

	HumanPawn = KFPawn_Human(OwnerPawn);
	if (HumanPawn == None)
		return;

	HealthPercent = float(HumanPawn.Health) / float(HumanPawn.HealthMax);

	if (HealthPercent > 0.75f)
	{
		InDamage += Round(float(InDamage) * (default.Penalty[upgLevel - 1]));
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_DesperateSymbiosis]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_DesperateSymbiosis"

	UpgradeName="Desperate Symbiosis"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_DesperateSymbiosis'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_DesperateSymbiosis_Deluxe'
	UpgradeDescription(0)="When below <font color='#FFD700'>50% health</font>, deal <font color='#00FF7F'>40%</font> more <font color='#9370DB'>damage</font> but take <font color='#FF6347'>15%</font> more <font color='#FF6347'>damage</font> when above <font color='#FFD700'>75% health</font>."
	UpgradeDescription(1)="When below <font color='#FFD700'>50% health</font>, deal <font color='#00FF7F'>65%</font> more <font color='#9370DB'>damage</font> but take <font color='#FF6347'>10%</font> more <font color='#FF6347'>damage</font> when above <font color='#FFD700'>75% health</font>."

	Name="Default__DKUpgrade_Skill_DesperateSymbiosis"
}