class DKUpgrade_Weapon_Hustler extends DKUpgrade_Weapon
    abstract
    hidecategories(Navigation,Movement,Collision,Navigation,Movement,Collision);

var int Dosh;

static function bool IsUpgradeCompatible(Class<KFWeapon> KFD)
{
    return true;
    //return ReturnValue;    
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional Class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    // End:0x106
    if((((MyKFPM != none) && MyKFPM.IsAliveAndWell()) && (MyKFPM.Health - InDamage) <= 0) && DamageInstigator != none)
    {
        KFPlayerReplicationInfo(DamageInstigator.PlayerReplicationInfo).AddDosh(default.Dosh * upgLevel);
    }
    //return;    
}

defaultproperties

{    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Weapon_Hustler]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Weapon_Hustler"

    Dosh=1
	WeaponBonus=(incValue=1, maxValue=-1)
	UpgradeName="Hustler"
	upgradeDescription(0)="Gain <font color=\"#77d914\">+%x%</font> <font color=\"#15d7fa\">dosh</font> for every kill."
}