// ===================================================================
// DKUpgrade_Skill_AceUpYourSleeve - Gambit Skill
//
// "Ace Up Your Sleeve" - After completing a gambit, the next N shots
// deal bonus damage.
//
// Standard: Next 10 shots deal +50% damage.
// Deluxe:   Next 15 shots deal +75% damage.
//
// ExtensionFuncInteger signals to helper (grants shots on completion).
// ModifyDamageGiven applies bonus and consumes shots.
// ===================================================================
class DKUpgrade_Skill_AceUpYourSleeve extends DKUpgrade_Skill;

// ===================================================================
// SIGNAL -- Tell helper this skill is active
// ===================================================================

static simulated function ExtensionFuncInteger(out int InValue, int DefaultValue, int upgLevel, string Identifier,
    KFWeapon MyKFW, KFPawn OwnerPawn, optional int InputInt, optional float InputFloat, optional name InputClassName,
    optional Object InputObject1, optional Object InputObject2, optional Object InputObject3)
{
    if (Identifier ~= "GambitAce")
        InValue = upgLevel;
}

// ===================================================================
// DAMAGE GIVEN -- Apply ace shot bonus and consume a charge
// ===================================================================

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
    optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
    optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
    optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Perk_Gambit_Helper H;
    local float BonusPct;

    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;

    H = class'DKUpgrade_Perk_Gambit'.static.GetHelper(DamageInstigator.Pawn);
    if (H == None || H.AceShots <= 0)
        return;

    // Consume one ace shot and get the bonus percentage
    BonusPct = H.ConsumeAceShot();
    if (BonusPct > 0.0f)
        InDamage += Round(float(DefaultDamage) * BonusPct);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_AceUpYourSleeve]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_AceUpYourSleeve"

    UpgradeName="Ace Up Your Sleeve"
    upgradeDescription(0)="After completing a gambit, your next <font color=\"#FFFFFF\">10 shots</font> deal <font color=\"#FFD700\">+50%</font> bonus damage."
    upgradeDescription(1)="After completing a gambit, your next <font color=\"#FFFFFF\">15 shots</font> deal <font color=\"#FFD700\">+75%</font> bonus damage."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AceUpYourSleeve'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AceUpYourSleeve_Deluxe'

    Name="Default__DKUpgrade_Skill_AceUpYourSleeve"
}
