class DKUpgrade_Weapon_DualHitman extends DKUpgrade_Weapon
    abstract
    hidecategories(Navigation,Movement,Collision,Navigation,Movement,Collision);

var float Damage, MagSize;

static function bool IsUpgradeCompatible(Class<KFWeapon> KFD)
{
    return true;
    //return ReturnValue;    
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional Class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    `log("[DK_WEAPUPG_HIT] DKUpgrade_Weapon_DualHitman.MDG upgLevel="$upgLevel$" InDmg="$InDamage$" DefDmg="$DefaultDamage$" Damage="$default.Damage$" MyKFW="$MyKFW);
    InDamage += Round((float(DefaultDamage) * default.Damage) * float(upgLevel));
    //return;    
}

static simulated function ModifyMagSizeAndNumber(out int InMagazineCapacity, int DefaultMagazineCapacity, int upgLevel, KFWeapon KFW, optional array< Class<KFPerk> > WeaponPerkClass, optional bool bSecondary, optional name WeaponClassName)
{
    `log("[DK_WEAPUPG_HIT] DKUpgrade_Weapon_DualHitman.MMSN upgLevel="$upgLevel$" InMag="$InMagazineCapacity$" DefMag="$DefaultMagazineCapacity$" MagSize="$default.MagSize$" KFW="$KFW);
    bSecondary = false;
    InMagazineCapacity += Round((float(DefaultMagazineCapacity) * default.MagSize) * float(upgLevel));
    //return;    
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Weapon_DualHitman]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Weapon_DualHitman"

    Damage=0.05000000
	MagSize=0.0500000
    WeaponBonus=(incValue=5,MaxValue=-1)
	UpgradeName="Dual Hitman"
    UpgradeDescription(0)="Increases your <font color=\"#15d7fa\">weapon damage</font> and <font color=\"#15d7fa\">magazine size</font> by <font color=\"#77d914\">+%x%%</font> per level."
}