// ===================================================================
// DKUpgrade_Skill_VolatileShift
//
// "The moment of transformation is the most dangerous."
//
// After buffs roll at wave start (or Mimicry gain), gain a temporary
// damage and movement speed boost. Rewards aggressive opening play
// during the transformation window.
//
// Standard: +15% damage, +10% move speed for 10s after roll
// Deluxe:   +30% damage, +15% move speed for 15s after roll
// ===================================================================
class DKUpgrade_Skill_VolatileShift extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DamageBonus;
var config array<float> SpeedBonus;
var config array<float> Duration;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageBonus[0] = 0.15f;
		default.DamageBonus[1] = 0.30f;
		default.SpeedBonus[0] = 0.10f;
		default.SpeedBonus[1] = 0.15f;
		default.Duration[0] = 10.0f;
		default.Duration[1] = 15.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// Helper lookup - reuses the Shapeshifter perk's static GetHelper
static simulated function DKUpgrade_Perk_Shapeshifter_Helper GetShapeshifterHelper(Pawn OwnerPawn)
{
    return class'DKUpgrade_Perk_Shapeshifter'.static.GetHelper(OwnerPawn);
}

// Check if we're within the Volatile Shift window
static simulated function bool IsInShiftWindow(DKUpgrade_Perk_Shapeshifter_Helper Helper, float WindowDuration)
{
    if (Helper == None || Helper.LastRollTimestamp <= 0.0f)
        return false;

    return (Helper.WorldInfo.TimeSeconds - Helper.LastRollTimestamp) < WindowDuration;
}

// #1 VOLATILE SHIFT: Damage bonus during transformation window
static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Perk_Shapeshifter_Helper Helper;

    if (MyKFPM == None || DamageInstigator == None || DamageInstigator.Pawn == None)
        return;

    Helper = GetShapeshifterHelper(DamageInstigator.Pawn);
    if (Helper == None)
        return;

    if (IsInShiftWindow(Helper, default.Duration[upgLevel - 1]))
        InDamage += Round(float(DefaultDamage) * default.DamageBonus[upgLevel - 1]);
}

// #2 VOLATILE SHIFT: Speed bonus during transformation window
static simulated function ModifySpeed(out float InSpeed, float DefaultSpeed, int upgLevel, KFPawn OwnerPawn)
{
    local DKUpgrade_Perk_Shapeshifter_Helper Helper;

    if (OwnerPawn == None) return;

    Helper = GetShapeshifterHelper(OwnerPawn);
    if (Helper == None) return;

    if (IsInShiftWindow(Helper, default.Duration[upgLevel - 1]))
        InSpeed += DefaultSpeed * default.SpeedBonus[upgLevel - 1];
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_VolatileShift]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_VolatileShift"

    UpgradeName="Volatile Shift"
    UpgradeDescription(0)="<font color=\"#c77dff\">Volatile Shift:</font> After buffs roll, gain <font color=\"#FFFFFF\">+15%</font> <font color=\"#e0aaff\">damage</font> and <font color=\"#FFFFFF\">+10%</font> <font color=\"#e0aaff\">move speed</font> for <font color=\"#FFFFFF\">10</font> seconds"
    UpgradeDescription(1)="<font color=\"#c77dff\">Volatile Shift:</font> After buffs roll, gain <font color=\"#FFFFFF\">+30%</font> <font color=\"#e0aaff\">damage</font> and <font color=\"#FFFFFF\">+15%</font> <font color=\"#e0aaff\">move speed</font> for <font color=\"#FFFFFF\">15</font> seconds"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_VolatileShift'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_VolatileShift_Deluxe'

    Name="Default__DKUpgrade_Skill_VolatileShift"
}
