class DKUpgrade_Skill_Firestorm extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Chance;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Chance[0] = 0.25f;
		default.Chance[1] = 0.50f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local rotator Rot;
	local vector Loc;

	if(((((((HitZoneIdx == 0) && MyKFPM != none) && KFPawn_ZedFleshpound(MyKFPM) != None) && MyKFPM.IsAliveAndWell()) && (MyKFPM.Health - InDamage) <= 0) && DamageInstigator != none) && (FRand() <= (default.Chance[upgLevel - 1])))
	{
		Rot = rotator(MyKFPM.Velocity);
		Loc = MyKFPM.Location;
		Loc.Z -= MyKFPM.GetCollisionHeight();
		Rot.Pitch = 0;
		   DamageInstigator.Spawn(class'ZedternalRBPerkpackage.DKProj_Firestorm', DamageInstigator, , Loc, Rot, , True);
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Firestorm]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Firestorm"

    UpgradeName="Firestorm"
	upgradeDescription(0)="Kills on <font color=\"#a0c1cb\">Fleshpounds</font> have a <font color=\"#15d7fa\">25% Chance</font> to cause a <font color=\"#0bf1f1\">Firestorm</font>."
	upgradeDescription(1)="Kills on <font color=\"#a0c1cb\">Fleshpounds</font> have a <font color=\"#15d7fa\">50% Chance</font> to cause a <font color=\"#0bf1f1\">massive Firestorm</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Firestorm'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Firestorm_Deluxe'

	Name="Default__DKUpgrade_Skill_Firestorm"
}