// ===================================================================
// DKUpgrade_Skill_Monomorph
//
// "One perfect form, honed to a razor's edge."
//
// When you have exactly ONE active buff (Ranks 1-9, before dual buffs
// unlock at Rank 10), that buff's effectiveness is amplified. Provides
// an early-game power spike that rewards commitment to a single form.
//
// Phases out naturally at Rank 10+ when dual buffs activate, though
// Mimicry's first wave at Rank 20 also starts with accumulated buffs.
// Creates an interesting build decision: the early game is stronger
// but the skill becomes dormant once dual buffs kick in.
//
// Works through GetBuffEffectiveness() on the helper - the
// SingleBuffAmplifier var is applied only when exactly 1 bit is set
// in ReplicatedBuffMask. Stacks multiplicatively with other multipliers.
//
// Standard: +50% single buff effectiveness (1.5x)
// Deluxe:   +100% single buff effectiveness (2.0x)
// ===================================================================
class DKUpgrade_Skill_Monomorph extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> SingleAmplification;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.SingleAmplification[0] = 0.50f;
		default.SingleAmplification[1] = 1.00f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// Helper lookup - reuses the Shapeshifter perk's static GetHelper
static simulated function DKUpgrade_Perk_Shapeshifter_Helper GetShapeshifterHelper(Pawn OwnerPawn)
{
    return class'DKUpgrade_Perk_Shapeshifter'.static.GetHelper(OwnerPawn);
}

// Configure the helper's single-buff amplifier on weapon init (server-side)
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Perk_Shapeshifter_Helper Helper;

    if (OwnerPawn == None || OwnerPawn.Role != Role_Authority)
        return;

    Helper = GetShapeshifterHelper(OwnerPawn);
    if (Helper == None)
        return;

    Helper.SingleBuffAmplifier = 1.0f + default.SingleAmplification[upgLevel - 1];
    Helper.bNetDirty = true;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Monomorph]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Monomorph"

    UpgradeName="Monomorph"
    UpgradeDescription(0)="<font color=\"#c77dff\">Monomorph:</font> When only <font color=\"#FFFFFF\">1</font> buff is active, its <font color=\"#e0aaff\">effectiveness</font> is increased by <font color=\"#FFFFFF\">50%</font>"
    UpgradeDescription(1)="<font color=\"#c77dff\">Monomorph:</font> When only <font color=\"#FFFFFF\">1</font> buff is active, its <font color=\"#e0aaff\">effectiveness</font> is increased by <font color=\"#FFFFFF\">100%</font>"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Monomorph'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Monomorph_Deluxe'

    Name="Default__DKUpgrade_Skill_Monomorph"
}
