// Sanctified Rounds
// After healing an ally, gain a temporary damage boost for 5 seconds
// Standard: +20% damage for 5s after healing
// Deluxe: +50% damage for 5s after healing
class DKUpgrade_Skill_SanctifiedRounds extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Damage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Damage[0] = 0.2f;
		default.Damage[1] = 0.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function HealingDamage(int upgLevel, int HealAmount, KFPawn HealedPawn, KFPawn InstigatorPawn, class<DamageType> DamageType)
{
	local DKUpgrade_Skill_SanctifiedRounds_Helper UPG;

	if (HealedPawn != None && InstigatorPawn != None && HealAmount > 0 && HealedPawn != InstigatorPawn)
	{
		UPG = GetHelper(InstigatorPawn);
		if (UPG != None)
			UPG.SetActive();
	}
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_SanctifiedRounds_Helper UPG;

	if (DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		UPG = GetHelper(KFPawn(DamageInstigator.Pawn));
		if (UPG != None && UPG.bActive)
			InDamage += Round(float(DefaultDamage) * default.Damage[upgLevel - 1]);
	}
}

static function DKUpgrade_Skill_SanctifiedRounds_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_SanctifiedRounds_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_SanctifiedRounds_Helper', UPG)
		{
			return UPG;
		}

		// Should have one
		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_SanctifiedRounds_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_SanctifiedRounds_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_SanctifiedRounds_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_SanctifiedRounds]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_SanctifiedRounds"

	UpgradeName="Sanctified Rounds"
	UpgradeDescription(0)="After healing an ally, gain <font color=\"#eeeeff\">20%</font> <font color=\"#ff4444\">bonus damage</font> for <font color=\"#eeeeff\">5</font> seconds"
	UpgradeDescription(1)="<font color=\"#ffd700\">Deluxe.</font> After healing an ally, gain <font color=\"#eeeeff\">50%</font> <font color=\"#ff4444\">bonus damage</font> for <font color=\"#eeeeff\">5</font> seconds"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SanctifiedRounds'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SanctifiedRounds_Deluxe'

	Name="Default__DKUpgrade_Skill_SanctifiedRounds"
}
