// ===================================================================
// DKUpgrade_Skill_Reclamation — Artificer Skill
//
// "Kills with ★ Reforged weapons reclaim life force from the fallen.
//  Recover health on kill. At full health, recover armor instead."
//
// Normal:  +2 HP per Reforged kill (+1 armor at full HP)
// Deluxe:  +4 HP per Reforged kill (+2 armor at full HP)
//
// Hook: ModifyDamageGiven (kill detection → helper does healing)
// Helper: DKUpgrade_Skill_Reclamation_Helper (kill dedup + heal logic)
// ===================================================================
class DKUpgrade_Skill_Reclamation extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> HealAmount;
var config array<int> ArmorAmount;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HealAmount[0] = 2;
		default.HealAmount[1] = 4;
		default.ArmorAmount[0] = 1;
		default.ArmorAmount[1] = 2;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_Reclamation_Helper H;

    if (DamageInstigator == None || DamageInstigator.Pawn == None || MyKFPM == None || MyKFW == None)
        return;

    // Only triggers with Reforged weapons
    if (!class'DKUpgrade_Perk_Artificer'.static.IsReforgedWeapon(MyKFW))
        return;

    // Check if this hit kills the target
    if (InDamage >= MyKFPM.Health)
    {
        H = GetHelper(DamageInstigator.Pawn, upgLevel);
        if (H != None)
            H.OnReforgedKill(MyKFPM, default.HealAmount[upgLevel - 1], default.ArmorAmount[upgLevel - 1]);
    }
}

// ===================================================================
// HELPER MANAGEMENT
// ===================================================================

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == ROLE_Authority)
        GetHelper(OwnerPawn, upgLevel);
}

static function DKUpgrade_Skill_Reclamation_Helper GetHelper(Pawn OwnerPawn, int upgLevel)
{
    local DKUpgrade_Skill_Reclamation_Helper H;

    if (KFPawn_Human(OwnerPawn) == None)
        return None;

    foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Reclamation_Helper', H)
    {
        H.UpgradeLevel = upgLevel;
        return H;
    }

    // Spawn if not found
    if (OwnerPawn.Role == ROLE_Authority)
    {
        H = OwnerPawn.Spawn(class'DKUpgrade_Skill_Reclamation_Helper', OwnerPawn);
        if (H != None)
            H.UpgradeLevel = upgLevel;
    }

    return H;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_Reclamation_Helper H;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Reclamation_Helper', H)
        {
            H.Destroy();
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Reclamation]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Reclamation"

    UpgradeName="Reclamation"
    UpgradeDescription(0)="Kills with <font color=\"#FFD700\"> Reforged</font> weapons restore <font color=\"#FFFFFF\">2 HP</font>. At full health, restore <font color=\"#FFFFFF\">1 armor</font> instead"
    UpgradeDescription(1)="Kills with <font color=\"#FFD700\"> Reforged</font> weapons restore <font color=\"#FFFFFF\">4 HP</font>. At full health, restore <font color=\"#FFFFFF\">2 armor</font> instead"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Reclamation'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Reclamation_Deluxe'

    Name="Default__DKUpgrade_Skill_Reclamation"
}
