// ===================================================================
// DKUpgrade_Skill_ExplosiveFury - Active ability: temporary explosive damage boost
// Standard: +30% explosive damage for 10s
// Deluxe: +50% explosive damage for 10s
// Cooldown: 60s after effect ends
// ===================================================================
class DKUpgrade_Skill_ExplosiveFury extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> ExplosiveDamageBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ExplosiveDamageBonus[0] = 0.3f;
		default.ExplosiveDamageBonus[1] = 0.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_ExplosiveFury_Helper Helper;
	local DKPlayerController DKPC;
	local bool bFound;
	
	if (KFPawn_Human(OwnerPawn) == None || OwnerPawn.Role != Role_Authority)
		return;
	
	DKPC = DKPlayerController(OwnerPawn.Controller);
	if (DKPC == None)
	{
		`log("DKUpgrade_Skill_ExplosiveFury: ERROR - Player does not have DKPlayerController!");
		return;
	}
	
	bFound = false;
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ExplosiveFury_Helper', Helper)
	{
		bFound = true;
		Helper.SetTier(upgLevel);
		`log("DKUpgrade_Skill_ExplosiveFury: Updated existing helper to tier" @ upgLevel);
		break;
	}
	
	if (!bFound)
	{
		Helper = OwnerPawn.Spawn(class'DKUpgrade_Skill_ExplosiveFury_Helper', OwnerPawn);
		if (Helper != None)
		{
			Helper.Initialize(upgLevel, KFPawn_Human(OwnerPawn), DKPC);
			`log("DKUpgrade_Skill_ExplosiveFury: Spawned helper for" @ OwnerPawn.PlayerReplicationInfo.PlayerName);
		}
		else
		{
			`log("DKUpgrade_Skill_ExplosiveFury: ERROR - Failed to spawn helper!");
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_ExplosiveFury_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ExplosiveFury_Helper', Helper)
	{
		Helper.Cleanup();
		Helper.Destroy();
		`log("DKUpgrade_Skill_ExplosiveFury: Cleaned up helper");
	}
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
	optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
	optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
	optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_ExplosiveFury_Helper Helper;
	local KFPawn OwnerPawn;
	
	if (DamageInstigator == None || DamageInstigator.Pawn == None)
		return;
	
	// Only apply to explosive damage
	if (DamageType == None || !ClassIsChildOf(DamageType, class'KFDT_Explosive'))
		return;
	
	OwnerPawn = KFPawn(DamageInstigator.Pawn);
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ExplosiveFury_Helper', Helper)
	{
		if (Helper.bActive)
		{
			InDamage += Round(float(DefaultDamage) * default.ExplosiveDamageBonus[upgLevel - 1]);
		}
		break;
	}
}

defaultproperties
{
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_ExplosiveFury]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_ExplosiveFury"

	UpgradeName="Explosive Fury"
	
	upgradeDescription(0)="Unlocks <font color=\"#66cc00\">Explosive Fury</font> active ability: <font color=\"#00ffff\">+30% explosive damage</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	upgradeDescription(1)="Unlocks <font color=\"#66cc00\">Explosive Fury (Deluxe)</font> active ability: <font color=\"#00ffff\">+50% explosive damage</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ExplosiveFury'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ExplosiveFury_Deluxe'
	
	Name="Default__DKUpgrade_Skill_ExplosiveFury"
}