// ===================================================================
// DKUpgrade_Skill_MountedTrophies - Wall of Champions
//
// Gain permanent Max HP and Max Armor each time a set is completed.
// Normal: +10 HP, +15 Armor per set | Deluxe: +20 HP, +30 Armor per set
//
// Synergy: Stacks with Trophy Hoarder (more sets = more HP/Armor).
// ===================================================================
class DKUpgrade_Skill_MountedTrophies extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> HPPerSet;
var config array<int> ArmorPerSet;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HPPerSet[0] = 10;
		default.HPPerSet[1] = 20;
		default.ArmorPerSet[0] = 15;
		default.ArmorPerSet[1] = 30;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Perk_Predator_Helper H;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        H = class'DKUpgrade_Perk_Predator'.static.GetHelper(OwnerPawn);
        if (H != None)
        {
            H.SkillMountedHP = default.HPPerSet[upgLevel - 1];
            H.SkillMountedArmor = default.ArmorPerSet[upgLevel - 1];
            `log("[DK_PREDATOR] MountedTrophies: +" $ H.SkillMountedHP $ " HP, +" $ H.SkillMountedArmor $ " Armor per set");
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_MountedTrophies]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_MountedTrophies"

    UpgradeName="Mounted Trophies"
    UpgradeDescription(0)="<font color=\"#FFD700\">Mounted Trophies:</font> <font color=\"#FFFFFF\">+10</font> <font color=\"#FF6666\">Max HP</font> and <font color=\"#FFFFFF\">+15</font> <font color=\"#87CEEB\">Max Armor</font> per completed set"
    UpgradeDescription(1)="<font color=\"#FFD700\">Mounted Trophies:</font> <font color=\"#FFFFFF\">+20</font> <font color=\"#FF6666\">Max HP</font> and <font color=\"#FFFFFF\">+30</font> <font color=\"#87CEEB\">Max Armor</font> per completed set"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_MountedTrophies'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_MountedTrophies_Deluxe'

    Name="Default__DKUpgrade_Skill_MountedTrophies"
}
