class DKUpgrade_Skill_GrimTithe extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Grim Tithe: The Reaper collects a toll from every soul claimed. Each kill during
// a wave accumulates dosh that is paid out as a lump sum when the wave ends.

var config array<int> DoshPerKill;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DoshPerKill[0] = 2;
		default.DoshPerKill[1] = 5;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function AddVampireHealth(out int InHealth, int DefaultHealth, int upgLevel, KFPlayerController KFPC, class<DamageType> DT)
{
	local DKUpgrade_Skill_GrimTithe_Helper UPG;

	if (KFPC != None && KFPC.Pawn != None)
	{
		UPG = GetHelper(KFPawn(KFPC.Pawn));
		if (UPG != None)
			UPG.AddKill();
	}
}

static function WaveEnd(int upgLevel, KFPlayerController KFPC)
{
	local DKUpgrade_Skill_GrimTithe_Helper UPG;
	local int Payout;

	if (KFPC != None && KFPC.Pawn != None)
	{
		UPG = GetHelper(KFPawn(KFPC.Pawn));
		if (UPG != None)
		{
			Payout = UPG.WaveKills * default.DoshPerKill[upgLevel - 1];
			if (Payout > 0)
				KFPlayerReplicationInfo(KFPC.PlayerReplicationInfo).AddDosh(Payout);
			UPG.ResetKills();
		}
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_GrimTithe_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_GrimTithe_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_GrimTithe_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_GrimTithe_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_GrimTithe_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_GrimTithe_Helper', UPG)
		{
			return UPG;
		}

		UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_GrimTithe_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_GrimTithe_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_GrimTithe_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_GrimTithe]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_GrimTithe"

	UpgradeName="Grim Tithe"
	UpgradeDescription(0)="<font color=\"#CC0000\">Grim Tithe:</font> Collect <font color=\"#FFFFFF\">2</font> <font color=\"#FFD700\">dosh</font> per kill, paid as a <font color=\"#FFAA00\">lump sum at wave end</font>. Death always collects its due."
	UpgradeDescription(1)="<font color=\"#CC0000\">Grim Tithe:</font> Collect <font color=\"#FFFFFF\">5</font> <font color=\"#FFD700\">dosh</font> per kill, paid as a <font color=\"#FFAA00\">lump sum at wave end</font>. Death always collects its due."

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_GrimTithe'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_GrimTithe_Deluxe'

	Name="Default__DKUpgrade_Skill_GrimTithe"
}
