class DKUpgrade_Skill_VenomExtraction extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> DamageBonus;
var config array<int> MaxStacks;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageBonus[0] = 0.1f;
		default.DamageBonus[1] = 0.2f;
		default.MaxStacks[0] = 1;
		default.MaxStacks[1] = 5;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_VenomExtraction_Helper VenomHelper;
    local float TotalDamageBonus;
    
    if (DamageInstigator == None || DamageInstigator.Pawn == None) return;
    
    // Get helper to check for active damage bonus
    VenomHelper = GetHelper(DamageInstigator.Pawn);
    if (VenomHelper != None && VenomHelper.CurrentStacks > 0)
    {
        // Apply damage bonus based on current stacks
        TotalDamageBonus = default.DamageBonus[upgLevel - 1] * VenomHelper.CurrentStacks;
        InDamage += Round(float(DefaultDamage) * TotalDamageBonus);
    }
    
    // Check if this kill should grant a venom stack (kill poisoned enemy)
    if (InDamage >= MyKFPM.Health && MyKFPM.bIsPoisoned && VenomHelper != None)
    {
        VenomHelper.AddVenomStack(upgLevel);
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_VenomExtraction_Helper VenomHelper;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_VenomExtraction_Helper', VenomHelper)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            VenomHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_VenomExtraction_Helper', OwnerPawn);
            VenomHelper.UpgradeLevel = upgLevel;
        }
    }
}

static function DKUpgrade_Skill_VenomExtraction_Helper GetHelper(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_VenomExtraction_Helper VenomHelper;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_VenomExtraction_Helper', VenomHelper)
        {
            return VenomHelper;
        }

        // Create one if needed
        VenomHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_VenomExtraction_Helper', OwnerPawn);
    }

    return VenomHelper;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_VenomExtraction_Helper VenomHelper;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_VenomExtraction_Helper', VenomHelper)
        {
            VenomHelper.Destroy();
        }
    }
}

defaultproperties
{
    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_VenomExtraction]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_VenomExtraction"

    UpgradeName="Venom Extraction"
    UpgradeDescription(0)="<font color=\"#8B008B\">Venom Extraction:</font> Killing <font color=\"#00FF00\">poisoned enemies</font> grants <font color=\"#FFFFFF\">+10% damage</font> for <font color=\"#FFFFFF\">10 seconds</font>."
    UpgradeDescription(1)="<font color=\"#8B008B\">Venom Extraction (Deluxe):</font> Killing <font color=\"#00FF00\">poisoned enemies</font> grants <font color=\"#FFFFFF\">+20% damage</font> for <font color=\"#FFFFFF\">10 seconds</font> + <font color=\"#FFD700\">stacks up to 5 times</font> (100% max)."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_VenomExtraction'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_VenomExtraction_Deluxe'
    
    Name="Default__DKUpgrade_Skill_VenomExtraction"
}