class DKUpgrade_Skill_BatteringRam extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Sprint IS your attack
// While sprinting: damage resistance. First melee within window of stopping sprint: huge damage multiplier.

var config array<float> SprintResistance;      // 20% / 30% resistance while sprinting
var config array<float> ChargeDamage;          // 2x / 3x first melee after sprint
var config array<float> ChargeWindow;          // 1.0s / 1.5s window after stopping sprint
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.SprintResistance[0] = 0.20f;
		default.SprintResistance[1] = 0.30f;
		default.ChargeDamage[0] = 2.0f;
		default.ChargeDamage[1] = 3.0f;
		default.ChargeWindow[0] = 1.0f;
		default.ChargeWindow[1] = 1.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	if (OwnerPawn != None && OwnerPawn.bIsSprinting)
	{
		InDamage -= Round(float(DefaultDamage) * default.SprintResistance[upgLevel - 1]);
		if (InDamage < 1)
			InDamage = 1;
	}
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_BatteringRam_Helper UPG;

	if (DamageType != None && static.IsMeleeDamageType(DamageType) && DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		UPG = GetHelper(KFPawn(DamageInstigator.Pawn));
		if (UPG != None && UPG.bChargeReady)
		{
			InDamage = Round(float(InDamage) * default.ChargeDamage[upgLevel - 1]);
			UPG.ConsumeCharge();
		}
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_BatteringRam_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_BatteringRam_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
		{
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_BatteringRam_Helper', OwnerPawn);
			UPG.StartTimer(upgLevel > 1);
		}
	}
}

static function DKUpgrade_Skill_BatteringRam_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_BatteringRam_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_BatteringRam_Helper', UPG)
		{
			return UPG;
		}

		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_BatteringRam_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_BatteringRam_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_BatteringRam_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_BatteringRam]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_BatteringRam"

	UpgradeName="Battering Ram"

	UpgradeDescription(0)="<font color=\"#edb82a\">Battering Ram</font> While <font color=\"#32CD32\">sprinting</font>: <font color=\"#4169E1\">+20% Damage Resistance</font> First melee within <font color=\"#FFFFFF\">1s</font> of stopping sprint: <font color=\"#FF4500\">2x Melee Damage</font> <font color=\"#AAAAAA\">Charge in. Swing hard.</font>"
	UpgradeDescription(1)="<font color=\"#edb82a\">Battering Ram</font> While <font color=\"#32CD32\">sprinting</font>: <font color=\"#4169E1\">+30% Damage Resistance</font> First melee within <font color=\"#FFFFFF\">1.5s</font> of stopping sprint: <font color=\"#FF4500\">3x Melee Damage</font> <font color=\"#AAAAAA\">Charge in. Swing hard.</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BatteringRam'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BatteringRam_Deluxe'

	Name="Default__DKUpgrade_Skill_BatteringRam"
}
