class DKUpgrade_Skill_Primed extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Damage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Damage[0] = 0.50f;
		default.Damage[1] = 1.00f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_Primed_Helper UPG;

	if (ClassIsChildOf(DamageType, class'KFDT_Ballistic') && DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		UPG = GetHelper(KFPawn(DamageInstigator.Pawn));
		if (UPG != None && UPG.bArmed)
		{
			InDamage += Round(float(DefaultDamage) * default.Damage[upgLevel - 1]);
			UPG.ConsumeShot();
		}
	}
}

// Reload detection: re-arm the buff when a reload occurs
static simulated function GetReloadRateScale(out float InReloadRateScale, int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_Primed_Helper UPG;

	if (OwnerPawn != None && OwnerPawn.Role == Role_Authority)
	{
		UPG = GetHelper(OwnerPawn);
		if (UPG != None)
			UPG.ArmShot();
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_Primed_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Primed_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_Primed_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_Primed_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_Primed_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Primed_Helper', UPG)
		{
			return UPG;
		}

		//Should have one
		UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_Primed_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_Primed_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Primed_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Primed]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Primed"

	UpgradeName="Primed"
	upgradeDescription(0)="Your <font color=\"#66cc00\">first shot</font> after <font color=\"#66cc00\">reloading</font> or <font color=\"#66cc00\">switching weapons</font> deals <font color=\"#ff3399\">50%</font> more <font color=\"#66cc00\">Damage</font>."
	upgradeDescription(1)="Your <font color=\"#66cc00\">first shot</font> after <font color=\"#66cc00\">reloading</font> or <font color=\"#66cc00\">switching weapons</font> deals <font color=\"#ff3399\">100%</font> more <font color=\"#66cc00\">Damage</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Primed'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Primed_Deluxe'
	Name="Default__DKUpgrade_Skill_Primed"
}
