// ===================================================================
// DKUpgrade_Skill_AgonizingPresence - Temporal Destabilization
// Theme: Your temporal field disrupts enemy nervous systems during
//        ZED Time. Increased stumble and knockdown power.
//        Deluxe: Knockdown bonus persists at half value outside ZED Time.
// Hooks: ModifyStumblePower, ModifyKnockdownPower (ZED Time gated)
// ===================================================================
class DKUpgrade_Skill_AgonizingPresence extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> StumbleBonus;
var config array<float> KnockdownBonus;
var config float KnockdownResidual;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.StumbleBonus[0] = 0.5f;
		default.StumbleBonus[1] = 1.0f;
		default.KnockdownBonus[0] = 0.5f;
		default.KnockdownBonus[1] = 1.0f;
		default.KnockdownResidual = 0.5f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyStumblePower(out float InStumblePower, float DefaultStumblePower, int upgLevel, optional KFPawn KFP, optional class<KFDamageType> DamageType, optional out float CooldownModifier, optional byte BodyPart, optional KFPawn OwnerPawn)
{
	// Stumble boost only during ZED Time
	if (OwnerPawn != None && OwnerPawn.WorldInfo.TimeDilation < 1.0)
		InStumblePower += DefaultStumblePower * default.StumbleBonus[upgLevel - 1];
}

static function ModifyKnockdownPower(out float InKnockdownPower, float DefaultKnockdownPower, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional byte BodyPart, optional bool bIsSprinting=False)
{
	if (OwnerPawn == None)
		return;

	if (OwnerPawn.WorldInfo.TimeDilation < 1.0)
	{
		// Full knockdown boost during ZED Time
		InKnockdownPower += DefaultKnockdownPower * default.KnockdownBonus[upgLevel - 1];
	}
	else if (upgLevel > 1)
	{
		// Deluxe: residual knockdown bonus outside ZED Time
		InKnockdownPower += DefaultKnockdownPower * default.KnockdownResidual;
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_AgonizingPresence]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_AgonizingPresence"

	UpgradeName="Agonizing Presence"
	upgradeDescription(0)="During <font color=\"#9632ff\">ZED Time</font>, your attacks have <font color=\"#d8b0ff\">+50%</font> <font color=\"#FFFFFF\">stumble</font> and <font color=\"#FFFFFF\">knockdown</font> power."
	upgradeDescription(1)="During <font color=\"#9632ff\">ZED Time</font>, your attacks have <font color=\"#d8b0ff\">+100%</font> <font color=\"#FFFFFF\">stumble</font> and <font color=\"#FFFFFF\">knockdown</font> power. Knockdown bonus persists at <font color=\"#d8b0ff\">+50%</font> outside ZED Time."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AgonizingPresence'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AgonizingPresence_Deluxe'

	Name="Default__DKUpgrade_Skill_AgonizingPresence"
}
