class DKUpgrade_Skill_SymbioticRounds extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> AmmoRecoveryChance;
var config array<float> CriticalScavengingChance;
var config array<int> BonusAmmoAmount;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.AmmoRecoveryChance[0] = 0.35f;
		default.AmmoRecoveryChance[1] = 0.50f;
		default.CriticalScavengingChance[0] = 0.15f;
		default.CriticalScavengingChance[1] = 0.25f;
		default.BonusAmmoAmount[0] = 2;
		default.BonusAmmoAmount[1] = 3;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local float RecoveryChance, CriticalChance;
    local int AmmoToRecover, MagRefund, SpareRefund;
    local bool bIsLargeZed;
    local DKPlayerController DKPC;
    
    // Only process headshot kills with rifle weapons
    if (MyKFPM == None || MyKFW == None || DamageInstigator == None || HitZoneIdx != HZI_HEAD)
        return;
        
    // Check if this will be a killing blow
    if (MyKFPM.Health > InDamage)
        return;
    
    // Check if weapon is a rifle
    if (!IsRifleWeapon(MyKFW))
        return;
    
    // Refunds route through the owning controller for reliable client-side
    // replication (a bare server-side ammo write does not reach a predicting
    // client on dedicated/remote).
    DKPC = DKPlayerController(DamageInstigator);
    if (DKPC == None)
        return;
    
    // Get chances based on upgrade level
    RecoveryChance = default.AmmoRecoveryChance[upgLevel - 1];
    CriticalChance = default.CriticalScavengingChance[upgLevel - 1];
    AmmoToRecover = default.BonusAmmoAmount[upgLevel - 1];
    
    // Apply low ammo bonus for level 2
    if (upgLevel == 2 && MyKFW.AmmoCount[0] < (MyKFW.MagazineCapacity[0] * 0.25f))
    {
        RecoveryChance += 0.15f;
    }
    
    // Basic ammo recovery (refund 1 round to magazine)
    if (FRand() < RecoveryChance)
        MagRefund = 1;
    
    // Critical scavenging for large zeds (bonus spare ammo)
    bIsLargeZed = IsLargeZed(MyKFPM);
    if (bIsLargeZed && FRand() < CriticalChance)
        SpareRefund = AmmoToRecover;
    
    // Single routed write so the magazine/spare changes actually land on the
    // owning client.
    if (MagRefund > 0 || SpareRefund > 0)
        DKPC.RefundWeaponAmmo(MyKFW, MagRefund, SpareRefund);
}

static function bool IsRifleWeapon(KFWeapon KFW)
{
    if (KFW == None)
        return False;
    
    // Match the "_Rifle_" class-name segment (KFWeap_Rifle_*, DKWeap_Rifle_*) so
    // this targets Sharpshooter rifles as the description states. The old bare
    // "Rifle" substring also matched KFWeap_AssaultRifle_* and friends.
    return InStr(PathName(KFW.Class), "_Rifle_") != INDEX_NONE;
}

static function bool IsLargeZed(KFPawn_Monster KFPM)
{
    if (KFPM == None)
        return False;
        
    return KFPM.static.IsLargeZed() || 
           ClassIsChildOf(KFPM.Class, class'KFPawn_ZedScrake') ||
           ClassIsChildOf(KFPM.Class, class'KFPawn_ZedFleshpound') ||
           ClassIsChildOf(KFPM.Class, class'KFPawn_ZedBloat') ||
           ClassIsChildOf(KFPM.Class, class'KFPawn_ZedSiren') ||
           ClassIsChildOf(KFPM.Class, class'KFPawn_ZedHusk');
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    // No helper class needed for this implementation
}

defaultproperties
{
    
    
    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_SymbioticRounds]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_SymbioticRounds"

    UpgradeName="SymbioticRounds"
    UpgradeDescription(0)="Rifle headshot kills have a <font color=\"#77d914\">35%</font> chance to refund <font color=\"#15d7fa\">1 round</font> to your magazine. <font color=\"#ff3399\">15%</font> chance for <font color=\"#77d914\">2 bonus spare ammo</font> on Medium and Large ZEDs."
    UpgradeDescription(1)="Rifle headshot kills have a <font color=\"#77d914\">50%</font> chance to refund <font color=\"#15d7fa\">1 round</font> to your magazine. <font color=\"#ff3399\">25%</font> chance for <font color=\"#77d914\">3 bonus spare ammo</font> on Medium and Large ZEDs. Gain <font color=\"#ffcc00\">15%</font> extra recovery chance when Magazine Capacity is below <font color=\"#ffcc00\">25%</font>."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SymbioticRounds'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SymbioticRounds_Deluxe'
    
    Name="Default__DKUpgrade_Skill_SymbioticRounds"
}