class DKUpgrade_Skill_SeethingSong extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Damage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Damage[0] = 0.20f;
		default.Damage[1] = 0.40f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}



static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
        if((((MyKFPM != None && KFPawn_ZedSiren(MyKFPM) != None) && MyKFPM.IsAliveAndWell()) && (MyKFPM.Health - InDamage) <= 0) && DamageInstigator != none)
		{
		   InDamage += Round(float(DefaultDamage) * (default.Damage[upgLevel - 1]));
        }
		//return; 
}

static simulated function bool ProjSirenResist(int upgLevel, KFPawn OwnerPawn)
{
	return True;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_SeethingSong]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_SeethingSong"

    UpgradeName="Seething Song"
	upgradeDescription(0)="You deal <font color=\"#e85009\">20%</font> more <font color=\"#e80948\">Damage to Sirens</font>. Your projectiles are <font color=\"#e85009\">immune</font> to  <font color=\"#e80948\">Siren Screams</font>."
	upgradeDescription(1)="You deal <font color=\"#e85009\">40%</font> more <font color=\"#e80948\">Damage to Sirens</font>. Your projectiles are <font color=\"#e85009\">immune</font> to  <font color=\"#e80948\">Siren Screams</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SeethingSong'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SeethingSong_Deluxe'

	Name="Default__DKUpgrade_Skill_SeethingSong"
}