// Adaptive Venom: Your Neurotoxin adapts to each ZED type.
// When damaging poisoned ZEDs, applies an ADDITIONAL DoT of a type they're weak to.
// Stacks with base Neurotoxin for double DoT pressure.
// ZED-class mapping:
//   Scrakes/Fleshpounds -> Fire DoT (weak to fire/explosives)
//   Husks              -> Bleeding DoT (already fire-resistant)
//   Bloats             -> Bleeding DoT (toxic-resistant)
//   Crawlers/Stalkers  -> Fire DoT (low HP, fire finishes fast)
//   Everything else    -> Enhanced Toxic DoT (stacking poison)
class DKUpgrade_Skill_AdaptiveVenom extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> AdaptiveDamage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.AdaptiveDamage[0] = 5;
		default.AdaptiveDamage[1] = 12;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local class<KFDamageType> AdaptiveDT;

	if (MyKFPM != None && DamageInstigator != None && (MyKFPM.bIsPoisoned || ZedHasToxicDoT(MyKFPM)))
	{
		AdaptiveDT = GetAdaptiveDamageType(MyKFPM);
		MyKFPM.ApplyDamageOverTime(default.AdaptiveDamage[upgLevel - 1], DamageInstigator, AdaptiveDT);
	}
}

static function class<KFDamageType> GetAdaptiveDamageType(KFPawn_Monster KFPM)
{
	// Large ZEDs: Fire is effective against Scrakes and Fleshpounds
	if (ClassIsChildOf(KFPM.Class, class'KFPawn_ZedScrake')
		|| ClassIsChildOf(KFPM.Class, class'KFPawn_ZedFleshpound'))
	{
		return class'KFDT_Fire';
	}

	// Husks are fire-resistant, use bleeding instead
	if (ClassIsChildOf(KFPM.Class, class'KFPawn_ZedHusk'))
	{
		return class'KFDT_Bleeding';
	}

	// Bloats are toxic-resistant, use bleeding
	if (ClassIsChildOf(KFPM.Class, class'KFPawn_ZedBloat'))
	{
		return class'KFDT_Bleeding';
	}

	// Crawlers and Stalkers: fire finishes them fast
	if (ClassIsChildOf(KFPM.Class, class'KFPawn_ZedCrawler')
		|| ClassIsChildOf(KFPM.Class, class'KFPawn_ZedStalker'))
	{
		return class'KFDT_Fire';
	}

	// Sirens: bleeding bypasses their resistances
	if (ClassIsChildOf(KFPM.Class, class'KFPawn_ZedSiren'))
	{
		return class'KFDT_Bleeding';
	}

	// Default: enhanced toxic (stacks with base Neurotoxin)
	return class'KFDT_Toxic';
}

// True if the zed currently has an active toxic damage-over-time. KF2's
// bIsPoisoned is the toxic *affliction* flag (the green-screen/panic state),
// which a light DoT may never push over threshold -- so this skill read false
// on zeds that were, in fact, taking poison damage. Scanning DamageOverTimeArray
// for a KFDT_Toxic DoT is the reliable "is poisoned" test. Mirrors the helper in
// Necrosis / Putrefaction / Venomweave.
static function bool ZedHasToxicDoT(KFPawn_Monster M)
{
	local int i;

	if (M == None)
		return false;

	for (i = 0; i < M.DamageOverTimeArray.Length; ++i)
	{
		if (M.DamageOverTimeArray[i].DamageType != None
			&& ClassIsChildOf(M.DamageOverTimeArray[i].DamageType, class'KFDT_Toxic'))
			return true;
	}

	return false;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_AdaptiveVenom]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_AdaptiveVenom"

	UpgradeDescription(0)="Your Neurotoxin <font color=\"#399c0e\">adapts</font>. Hits on <font color=\"#8fce00\">Poisoned</font> ZEDs apply an additional <font color=\"#399c0e\">5</font> adaptive DoT based on the ZED's weakness."
	UpgradeDescription(1)="Your Neurotoxin <font color=\"#399c0e\">adapts</font>. Hits on <font color=\"#8fce00\">Poisoned</font> ZEDs apply an additional <font color=\"#b346ea\">12</font> adaptive DoT based on the ZED's weakness."

	UpgradeName="Adaptive Venom"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AdaptiveVenom'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AdaptiveVenom_Deluxe'

	Name="Default__DKUpgrade_Skill_AdaptiveVenom"
}
