class DKUpgrade_Skill_CloseCall extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Damage;
var config array<float> Resistance;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Damage[0] = 0.30f;
		default.Damage[1] = 0.60f;
		default.Resistance[0] = 0.20f;
		default.Resistance[1] = 0.40f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_CloseCall_Helper UPG;

	if (DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		UPG = GetHelper(KFPawn(DamageInstigator.Pawn));
		if (UPG != None && UPG.bActive)
			InDamage += Round(float(DefaultDamage) * default.Damage[upgLevel - 1]);
	}
}

static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_CloseCall_Helper UPG;

	if (OwnerPawn != None)
	{
		UPG = GetHelper(OwnerPawn);
		if (UPG != None && UPG.bActive)
			InDamage -= Round(float(DefaultDamage) * default.Resistance[upgLevel - 1]);
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_CloseCall_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CloseCall_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_CloseCall_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_CloseCall_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_CloseCall_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CloseCall_Helper', UPG)
		{
			return UPG;
		}

		//Should have one
		UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_CloseCall_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_CloseCall_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CloseCall_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_CloseCall]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_CloseCall"

	UpgradeName="Close Call"
	upgradeDescription(0)="While below <font color=\"#be4d25\">25% Health</font>, deal <font color=\"#ff3399\">30%</font> more <font color=\"#66cc00\">Damage</font> and take <font color=\"#ff3399\">20%</font> <font color=\"#66cc00\">less Damage</font>."
	upgradeDescription(1)="While below <font color=\"#be4d25\">25% Health</font>, deal <font color=\"#ff3399\">60%</font> more <font color=\"#66cc00\">Damage</font> and take <font color=\"#ff3399\">40%</font> <font color=\"#66cc00\">less Damage</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CloseCall'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CloseCall_Deluxe'
	Name="Default__DKUpgrade_Skill_CloseCall"
}
