class DKUpgrade_Skill_NestOfVipers extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> TriggerTime;
var config array<float> CloudRange;
var config array<int> CloudDamage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.TriggerTime[0] = 5.0f;
		default.TriggerTime[1] = 3.0f;
		default.CloudRange[0] = 400.0f;
		default.CloudRange[1] = 600.0f;
		default.CloudDamage[0] = 3;
		default.CloudDamage[1] = 5;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_NestOfVipers_Helper ViperHelper;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_NestOfVipers_Helper', ViperHelper)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            ViperHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_NestOfVipers_Helper', OwnerPawn);
            ViperHelper.UpgradeLevel = upgLevel;
        }
    }
}

static function DKUpgrade_Skill_NestOfVipers_Helper GetHelper(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_NestOfVipers_Helper ViperHelper;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_NestOfVipers_Helper', ViperHelper)
        {
            return ViperHelper;
        }

        // Create one if needed
        ViperHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_NestOfVipers_Helper', OwnerPawn);
    }

    return ViperHelper;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_NestOfVipers_Helper ViperHelper;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_NestOfVipers_Helper', ViperHelper)
        {
            ViperHelper.Destroy();
        }
    }
}

defaultproperties
{
    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_NestOfVipers]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_NestOfVipers"

    UpgradeName="Nest of Vipers"
    UpgradeDescription(0)="<font color=\"#8B008B\">Nest of Vipers:</font> Standing still for <font color=\"#FFFFFF\">5+ seconds</font> creates <font color=\"#00FF00\">poison cloud</font> that damages enemies within <font color=\"#FFFFFF\">4m</font> for <font color=\"#FFFFFF\">3 damage/sec</font>."
    UpgradeDescription(1)="<font color=\"#8B008B\">Nest of Vipers (Deluxe):</font> Standing still for <font color=\"#FFFFFF\">3+ seconds</font> creates <font color=\"#00FF00\">poison cloud</font> that damages enemies within <font color=\"#FFFFFF\">6m</font> for <font color=\"#FFFFFF\">5 damage/sec</font> + <font color=\"#FFD700\">cloud follows you</font> for 10 seconds after moving."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_NestOfVipers'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_NestOfVipers_Deluxe'
    
    Name="Default__DKUpgrade_Skill_NestOfVipers"
}