// Putrefaction: Damage against poisoned ZEDs scales with their missing health.
// The lower the ZED's health, the more bonus damage you deal.
// Execute mechanic: spread poison, whittle down, then devastate in cleanup phase.
class DKUpgrade_Skill_Putrefaction extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Maximum bonus damage at 0% target health
var config array<float> MaxBonusDamage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MaxBonusDamage[0] = 0.50f;
		default.MaxBonusDamage[1] = 1.00f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local float MissingHealthPct, BonusMult;

	if (MyKFPM != None && (MyKFPM.bIsPoisoned || ZedHasToxicDoT(MyKFPM)) && MyKFPM.HealthMax > 0)
	{
		// Calculate missing health percentage (0.0 = full health, 1.0 = nearly dead)
		MissingHealthPct = 1.0f - (float(MyKFPM.Health) / float(MyKFPM.HealthMax));
		MissingHealthPct = FClamp(MissingHealthPct, 0.0f, 1.0f);

		// Bonus damage scales linearly with missing health
		BonusMult = MissingHealthPct * default.MaxBonusDamage[upgLevel - 1];
		InDamage += Round(float(DefaultDamage) * BonusMult);
	}
}

// See DKUpgrade_Skill_Necrosis.ZedHasToxicDoT. bIsPoisoned is the toxic
// affliction flag, which a light DoT may never trigger; scan the zed's
// active DoTs for a KFDT_Toxic entry so "poisoned" reflects real poison damage.
static function bool ZedHasToxicDoT(KFPawn_Monster M)
{
	local int i;

	if (M == None)
		return false;

	for (i = 0; i < M.DamageOverTimeArray.Length; ++i)
	{
		if (M.DamageOverTimeArray[i].DamageType != None
			&& ClassIsChildOf(M.DamageOverTimeArray[i].DamageType, class'KFDT_Toxic'))
			return true;
	}

	return false;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Putrefaction]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Putrefaction"

	// At 0% ZED health: +50% (L1) or +100% (L2) bonus damage
	// At 50% ZED health: +25% (L1) or +50% (L2) bonus damage

	UpgradeDescription(0)="Deal up to <font color=\"#399c0e\">50% bonus damage</font> to <font color=\"#8fce00\">Poisoned</font> ZEDs based on their <font color=\"#ff5050\">missing health</font>."
	UpgradeDescription(1)="Deal up to <font color=\"#b346ea\">100% bonus damage</font> to <font color=\"#8fce00\">Poisoned</font> ZEDs based on their <font color=\"#ff5050\">missing health</font>."

	UpgradeName="Putrefaction"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Putrefaction'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Putrefaction_Deluxe'

	Name="Default__DKUpgrade_Skill_Putrefaction"
}
