class DKUpgrade_Skill_CrowdSurge extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Kills make you faster and sharper
// Melee kills within a window stack movement speed
// At 3+ stacks: see cloaked Stalkers. At 5 stacks: faster weapon switch.

var config array<float> SpeedPerStack;         // +5% / +7% per kill stack
var config array<int> MaxStacks;               // 5 / 5
var config array<int> CloakedThreshold;        // 3 / 2 stacks to see cloaked
var config array<int> SwitchThreshold;         // 5 / 4 stacks for switch speed
var config array<float> SwitchSpeedBonus;      // 0.5 / 0.75 weapon switch bonus
var config array<float> StackDuration;         // 8s / 12s per stack
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.SpeedPerStack[0] = 0.05f;
		default.SpeedPerStack[1] = 0.07f;
		default.MaxStacks[0] = 5;
		default.MaxStacks[1] = 5;
		default.CloakedThreshold[0] = 3;
		default.CloakedThreshold[1] = 2;
		default.SwitchThreshold[0] = 5;
		default.SwitchThreshold[1] = 4;
		default.SwitchSpeedBonus[0] = 0.50f;
		default.SwitchSpeedBonus[1] = 0.75f;
		default.StackDuration[0] = 8.0f;
		default.StackDuration[1] = 12.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_CrowdSurge_Helper UPG;

	// Register melee kills
	if (DamageType != None && static.IsMeleeDamageType(DamageType)
		&& MyKFPM != None && MyKFPM.IsAliveAndWell() && (MyKFPM.Health - InDamage) <= 0
		&& DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		UPG = GetHelper(KFPawn(DamageInstigator.Pawn));
		if (UPG != None)
			UPG.AddStack(default.MaxStacks[upgLevel - 1], default.StackDuration[upgLevel - 1]);
	}
}

static simulated function ModifySpeed(out float InSpeed, float DefaultSpeed, int upgLevel, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_CrowdSurge_Helper UPG;

	if (OwnerPawn != None)
	{
		UPG = GetHelperSimulated(OwnerPawn);
		if (UPG != None && UPG.RepStacks > 0)
		{
			InSpeed += DefaultSpeed * default.SpeedPerStack[upgLevel - 1] * float(UPG.RepStacks);
		}
	}
}

static simulated function bool CanSeeCloaked(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_CrowdSurge_Helper UPG;

	if (OwnerPawn != None)
	{
		UPG = GetHelperSimulated(OwnerPawn);
		if (UPG != None && UPG.RepStacks >= default.CloakedThreshold[upgLevel - 1])
			return True;
	}

	return False;
}

static simulated function ModifyWeaponSwitchTime(out float InSwitchTime, float DefaultSwitchTime, int upgLevel, KFWeapon KFW)
{
	local DKUpgrade_Skill_CrowdSurge_Helper UPG;

	if (KFW != None && KFW.Instigator != None)
	{
		UPG = GetHelperSimulated(KFPawn(KFW.Instigator));
		if (UPG != None && UPG.RepStacks >= default.SwitchThreshold[upgLevel - 1])
		{
			InSwitchTime = DefaultSwitchTime / (DefaultSwitchTime / InSwitchTime + default.SwitchSpeedBonus[upgLevel - 1]);
		}
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_CrowdSurge_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CrowdSurge_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			OwnerPawn.Spawn(class'DKUpgrade_Skill_CrowdSurge_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_CrowdSurge_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_CrowdSurge_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CrowdSurge_Helper', UPG)
		{
			return UPG;
		}

		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_CrowdSurge_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DKUpgrade_Skill_CrowdSurge_Helper GetHelperSimulated(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_CrowdSurge_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CrowdSurge_Helper', UPG)
		{
			return UPG;
		}
	}

	return None;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_CrowdSurge_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_CrowdSurge_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_CrowdSurge]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_CrowdSurge"

	UpgradeName="Crowd Surge"

	UpgradeDescription(0)="<font color=\"#edb82a\">Crowd Surge</font> Melee kills grant speed stacks (max <font color=\"#FFFFFF\">5</font>, <font color=\"#AAAAAA\">8s each</font>). Per stack: <font color=\"#32CD32\">+5% Move Speed</font> At <font color=\"#FFD700\">3+</font> stacks: <font color=\"#87CEEB\">See cloaked enemies</font> At <font color=\"#FFD700\">5</font> stacks: <font color=\"#87CEEB\">Faster weapon switch</font>"
	UpgradeDescription(1)="<font color=\"#edb82a\">Crowd Surge</font> Melee kills grant speed stacks (max <font color=\"#FFFFFF\">5</font>, <font color=\"#AAAAAA\">12s each</font>). Per stack: <font color=\"#32CD32\">+7% Move Speed</font> At <font color=\"#FFD700\">2+</font> stacks: <font color=\"#87CEEB\">See cloaked enemies</font> At <font color=\"#FFD700\">4</font> stacks: <font color=\"#87CEEB\">Faster weapon switch</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CrowdSurge'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_CrowdSurge_Deluxe'

	Name="Default__DKUpgrade_Skill_CrowdSurge"
}
