class DKUpgrade_Skill_BugFixing extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> Damage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Damage[0] = 0.20f;
		default.Damage[1] = 0.40f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    if(KFAIController_ZedCrawler(InstigatedBy) != None)
    {
        InDamage -= Round(float(DefaultDamage) * default.Damage[upgLevel - 1]);    
    }
}

defaultproperties

{    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_BugFixing]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_BugFixing"

	UpgradeName="Bug Fixing"
    upgradeDescription(0)="You take <font color=\"#ff3399\">20%</font> less <font color=\"#7ed8d5\">Damage</font> from <font color=\"#f923be\">Crawlers</font>."
    upgradeDescription(1)="You take <font color=\"#ff3399\">40%</font> less <font color=\"#7ed8d5\">Damage</font> from <font color=\"#f923be\">Crawlers</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BugFixing'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BugFixing_Deluxe'
    Name="Default__DKUpgrade_Skill_BugFixing"
}
