class DKUpgrade_Skill_ShedSkin extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> DamageTrigger;
var config array<float> DamageResistance;
var config array<float> BuffDuration;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageTrigger[0] = 50;
		default.DamageTrigger[1] = 25;
		default.DamageResistance[0] = 0.5f;
		default.DamageResistance[1] = 0.75f;
		default.BuffDuration[0] = 8.0f;
		default.BuffDuration[1] = 12.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_ShedSkin_Helper ShedHelper;
    
    if (OwnerPawn == None) return;
    
    // Get helper to track damage and manage buff
    ShedHelper = GetHelper(OwnerPawn);
    if (ShedHelper != None)
    {
        // Track incoming damage for trigger detection
        ShedHelper.TrackDamage(InDamage, upgLevel);
        
        // Apply damage resistance if buff is active
        if (ShedHelper.bBuffActive)
        {
            InDamage = Round(float(InDamage) * (1.0f - default.DamageResistance[upgLevel - 1]));
        }
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_ShedSkin_Helper ShedHelper;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ShedSkin_Helper', ShedHelper)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            ShedHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_ShedSkin_Helper', OwnerPawn);
            ShedHelper.UpgradeLevel = upgLevel;
        }
    }
}

static function DKUpgrade_Skill_ShedSkin_Helper GetHelper(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_ShedSkin_Helper ShedHelper;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ShedSkin_Helper', ShedHelper)
        {
            return ShedHelper;
        }

        // Create one if needed
        ShedHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_ShedSkin_Helper', OwnerPawn);
    }

    return ShedHelper;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_ShedSkin_Helper ShedHelper;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_ShedSkin_Helper', ShedHelper)
        {
            ShedHelper.Destroy();
        }
    }
}

defaultproperties
{
    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_ShedSkin]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_ShedSkin"

    UpgradeName="Shed Skin"
    UpgradeDescription(0)="<font color=\"#8B008B\">Shed Skin:</font> After taking <font color=\"#FFFFFF\">50+</font> damage in <font color=\"#FFFFFF\">3 seconds</font>, gain <font color=\"#00FF00\">50% damage resistance</font> for <font color=\"#FFFFFF\">8 seconds</font> (30s cooldown)."
    UpgradeDescription(1)="<font color=\"#8B008B\">Shed Skin (Deluxe):</font> After taking <font color=\"#FFFFFF\">25+</font> damage in <font color=\"#FFFFFF\">3 seconds</font>, gain <font color=\"#00FF00\">75% damage resistance</font> for <font color=\"#FFFFFF\">12 seconds</font> (20s cooldown)."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ShedSkin'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ShedSkin_Deluxe'
    
    Name="Default__DKUpgrade_Skill_ShedSkin"
}