class DKUpgrade_Skill_Deadlock extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Refuse to die in the crowd
// If a killing blow is received while 3+ enemies are nearby: survive at 1 HP
// Gain 15 seconds of damage immunity. Once per wave.

var config array<int> MinEnemiesRequired;       // 3 / 2 enemies nearby to trigger
var config array<float> InvincibilityDuration;  // 15s / 15s
var const float NearbyRadius;            // 5 meters (squared)
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MinEnemiesRequired[0] = 3;
		default.MinEnemiesRequired[1] = 2;
		default.InvincibilityDuration[0] = 15.0f;
		default.InvincibilityDuration[1] = 15.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local DKUpgrade_Skill_Deadlock_Helper UPG;

	if (OwnerPawn != None && InDamage > 0)
	{
		UPG = GetHelper(OwnerPawn);
		if (UPG != None)
		{
			// If invincible, negate all damage
			if (UPG.bInvincible)
			{
				InDamage = 0;
				return;
			}

			// Check for lethal damage
			if (!UPG.bUsedThisWave && (OwnerPawn.Health - InDamage) <= 0)
			{
				// Check nearby enemy count
				if (UPG.CountNearbyEnemies() >= default.MinEnemiesRequired[upgLevel - 1])
				{
					// Survive at 1 HP
					InDamage = OwnerPawn.Health - 1;
					if (InDamage < 0)
						InDamage = 0;

					UPG.ActivateInvincibility(default.InvincibilityDuration[upgLevel - 1]);
				}
			}
		}
	}
}

static function WaveEnd(int upgLevel, KFPlayerController KFPC)
{
	local DKUpgrade_Skill_Deadlock_Helper UPG;

	if (KFPC != None && KFPC.Pawn != None)
	{
		UPG = GetHelper(KFPawn(KFPC.Pawn));
		if (UPG != None)
			UPG.ResetForWave();
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_Deadlock_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Deadlock_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			OwnerPawn.Spawn(class'DKUpgrade_Skill_Deadlock_Helper', OwnerPawn);
	}
}

static function DKUpgrade_Skill_Deadlock_Helper GetHelper(KFPawn OwnerPawn)
{
	local DKUpgrade_Skill_Deadlock_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Deadlock_Helper', UPG)
		{
			return UPG;
		}

		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_Deadlock_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local DKUpgrade_Skill_Deadlock_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_Deadlock_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Deadlock]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Deadlock"

	NearbyRadius=250000     // 500 UU = 5 meters, squared

	UpgradeName="Deadlock"

	UpgradeDescription(0)="<font color=\"#edb82a\">Deadlock</font> If you would die with <font color=\"#FFFFFF\">3+</font> enemies nearby: Survive at <font color=\"#DC143C\">1 HP</font> and become <font color=\"#FFD700\">invincible for 15s</font>. <font color=\"#AAAAAA\">Once per wave.</font>"
	UpgradeDescription(1)="<font color=\"#edb82a\">Deadlock</font> If you would die with <font color=\"#FFFFFF\">2+</font> enemies nearby: Survive at <font color=\"#DC143C\">1 HP</font> and become <font color=\"#FFD700\">invincible for 15s</font>. <font color=\"#AAAAAA\">Once per wave.</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Deadlock'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Deadlock_Deluxe'

	Name="Default__DKUpgrade_Skill_Deadlock"
}
