class DKUpgrade_Skill_LernaeanImmortality extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> InvulnDuration;
var config float DamageBoostMult;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.InvulnDuration[0] = 3.0f;
		default.InvulnDuration[1] = 5.0f;
		default.DamageBoostMult = 2.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_LernaeanImmortality_Helper UPG;
    
    if (OwnerPawn == None)
        return;
    
    UPG = GetHelper(OwnerPawn);
    if (UPG == None)
        return;
    
    // If invulnerable, negate all damage
    if (UPG.bInvulnerable)
    {
        InDamage = 0;
        return;
    }
    
    // Check if this would be lethal and we have a charge
    if (UPG.bChargeAvailable && (OwnerPawn.Health - InDamage) <= 0)
    {
        // Survive with 1 HP
        InDamage = OwnerPawn.Health - 1;
        
        // Trigger immortality effect
        UPG.TriggerImmortality(default.InvulnDuration[upgLevel - 1]);
    }
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_LernaeanImmortality_Helper UPG;
    
    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;
    
    UPG = GetHelper(DamageInstigator.Pawn);
    if (UPG == None)
        return;
    
    // Double damage during immortality window
    if (UPG.bDamageBoost)
    {
        InDamage = Round(float(InDamage) * default.DamageBoostMult);
    }
}

static function WaveEnd(int upgLevel, KFPlayerController KFPC)
{
    local DKUpgrade_Skill_LernaeanImmortality_Helper UPG;
    
    if (KFPC.Pawn != None)
    {
        UPG = GetHelper(KFPC.Pawn);
        if (UPG != None)
        {
            UPG.ResetCharge();
        }
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_LernaeanImmortality_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_LernaeanImmortality_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_LernaeanImmortality_Helper', OwnerPawn);
        }
    }
}

static function DKUpgrade_Skill_LernaeanImmortality_Helper GetHelper(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_LernaeanImmortality_Helper UPG;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_LernaeanImmortality_Helper', UPG)
        {
            return UPG;
        }

        // Should have one
        UPG = OwnerPawn.Spawn(class'DKUpgrade_Skill_LernaeanImmortality_Helper', OwnerPawn);
    }

    return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_LernaeanImmortality_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_LernaeanImmortality_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_LernaeanImmortality]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_LernaeanImmortality"

    UpgradeName="Lernaean Immortality"
    upgradeDescription(0)="<font color=\"#ffff00\">Once per wave</font>, survive <font color=\"#ff0000\">lethal damage</font> with <font color=\"#66cc00\">1 HP</font>, then gain <font color=\"#00ffff\">invulnerability</font> + <font color=\"#ff3399\">2x damage</font> for <font color=\"#ffff00\">3 seconds</font>."
    upgradeDescription(1)="<font color=\"#ffff00\">Once per wave</font>, survive <font color=\"#ff0000\">lethal damage</font> with <font color=\"#66cc00\">1 HP</font>, then gain <font color=\"#00ffff\">invulnerability</font> + <font color=\"#ff3399\">2x damage</font> for <font color=\"#ffff00\">5 seconds</font>."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_LernaeanImmortality'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_LernaeanImmortality_Deluxe'

    Name="Default__DKUpgrade_Skill_LernaeanImmortality"
}
