class DKUpgrade_Skill_GorgonsLegacy extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> TeamDamageBonus;
var config array<float> BuffDuration;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.TeamDamageBonus[0] = 0.25f;
		default.TeamDamageBonus[1] = 0.5f;
		default.BuffDuration[0] = 45.0f;
		default.BuffDuration[1] = 60.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local DKUpgrade_Skill_GorgonsLegacy_Helper LegacyHelper;
    
    if (DamageInstigator == None || DamageInstigator.Pawn == None) return;
    
    // Check if this player has the legacy buff active
    LegacyHelper = GetHelper(DamageInstigator.Pawn);
    if (LegacyHelper != None && LegacyHelper.bLegacyBuffActive)
    {
        // Apply damage bonus
        InDamage += Round(float(DefaultDamage) * default.TeamDamageBonus[upgLevel - 1]);
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local DKUpgrade_Skill_GorgonsLegacy_Helper LegacyHelper;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_GorgonsLegacy_Helper', LegacyHelper)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            LegacyHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_GorgonsLegacy_Helper', OwnerPawn);
            LegacyHelper.UpgradeLevel = upgLevel;
        }
    }
}

static function DKUpgrade_Skill_GorgonsLegacy_Helper GetHelper(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_GorgonsLegacy_Helper LegacyHelper;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_GorgonsLegacy_Helper', LegacyHelper)
        {
            return LegacyHelper;
        }

        // Create one if needed
        LegacyHelper = OwnerPawn.Spawn(class'DKUpgrade_Skill_GorgonsLegacy_Helper', OwnerPawn);
    }

    return LegacyHelper;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local DKUpgrade_Skill_GorgonsLegacy_Helper LegacyHelper;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'DKUpgrade_Skill_GorgonsLegacy_Helper', LegacyHelper)
        {
            LegacyHelper.Destroy();
        }
    }
}

// Static function to trigger legacy buff when a player with this skill dies
static function TriggerGorgonsLegacy(KFPawn_Human DyingPlayer, int SkillLevel)
{
    local WorldInfo WI;
    local KFPlayerController KFPC;
    local DKUpgrade_Skill_GorgonsLegacy_Helper LegacyHelper;
    
    if (DyingPlayer == None || DyingPlayer.WorldInfo == None) return;
    
    WI = DyingPlayer.WorldInfo;
    if (WI == None) return;
    
    // Apply legacy buff to all surviving teammates
    foreach WI.AllControllers(class'KFPlayerController', KFPC)
    {
        if (KFPC != None && KFPC != DyingPlayer.Controller && KFPC.Pawn != None && KFPC.Pawn.Health > 0)
        {
            LegacyHelper = GetHelper(KFPC.Pawn);
            if (LegacyHelper != None)
            {
                LegacyHelper.ActivateLegacyBuff(SkillLevel);
            }
        }
    }
}

defaultproperties
{
    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_GorgonsLegacy]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_GorgonsLegacy"

    UpgradeName="Gorgon's Legacy"
    UpgradeDescription(0)="<font color=\"#8B008B\">Gorgon's Legacy:</font> When you die, all teammates gain <font color=\"#66FF66\">+25% damage bonus</font> for <font color=\"#FFFFFF\">45 seconds</font>."
    UpgradeDescription(1)="<font color=\"#8B008B\">Gorgon's Legacy (Deluxe):</font> When you die, all teammates gain <font color=\"#66FF66\">+50% damage bonus</font> for <font color=\"#FFFFFF\">60 seconds</font> + <font color=\"#FFD700\">brief invincibility</font> when bonus activates."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_GorgonsLegacy'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_GorgonsLegacy_Deluxe'
    
    Name="Default__DKUpgrade_Skill_GorgonsLegacy"
}