class DKUpgrade_Skill_Territorial extends DKUpgrade_Skill
	config(ZedternalUnlimited);

// Theme: The Wendigo guards its den with fierce determination
var config array<float> Bonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Bonus[0] = 0.5f;
		default.Bonus[1] = 1.25f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function ModifyWeldingRate(out float InFastenRate, float DefaultFastenRate, out float InUnfastenRate, float DefaultUnfastenRate, int upgLevel)
{
	InFastenRate += DefaultFastenRate * default.Bonus[upgLevel - 1];
	InUnfastenRate += DefaultUnfastenRate * default.Bonus[upgLevel - 1];
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_Territorial]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_Territorial"

	UpgradeName="Territorial"
	UpgradeDescription(0)="<font color=\"#4682B4\">Territorial:</font> <font color=\"#FFFFFF\">50%</font> <font color=\"#87CEEB\">faster welding</font> and <font color=\"#F0F8FF\">unwelding</font> speed"
	UpgradeDescription(1)="<font color=\"#4682B4\">Territorial:</font> <font color=\"#FFFFFF\">125%</font> <font color=\"#87CEEB\">faster welding</font> and <font color=\"#F0F8FF\">unwelding</font> speed"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Territorial'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Territorial_Deluxe'

	Name="Default__DKUpgrade_Skill_Territorial"
}
