// ===================================================================
// DKUpgrade_Skill_ParasiticBloom
// When a large host falls, the hivemind's parasites burst forth
// in a cloud of restorative spores - teammates near the corpse
// are bathed in regenerative bio-matter.
//
// Normal: Killing a large zed heals all teammates within 10m for 20 HP
// Deluxe: Killing a large zed heals all teammates within 10m for 35 HP
//         and restores 10 armor
//
// BUGFIX: Armor is granted via KFPH.AddArmor() so it goes through the
// WMPawn_Human override into the real ZR armor pool (ZedternalArmor).
// Writing KFPH.Armor directly only poked the vanilla display byte,
// which ZR recomputes from ZedternalArmor and immediately wipes.
// ===================================================================
class DKUpgrade_Skill_ParasiticBloom extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<int> HealAmount;
var config int DeluxeArmorAmount;
var config float Radius;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HealAmount[0] = 20;
		default.HealAmount[1] = 35;
		default.DeluxeArmorAmount = 10;
		default.Radius = 1000.0f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local KFPawn_Human KFPH;
	local float DistSQ;

	// Check for a killing blow on a large zed or boss
	if (MyKFPM == None || DamageInstigator == None || DamageInstigator.Pawn == None)
		return;

	if (!(MyKFPM.static.IsLargeZed() || MyKFPM.static.IsABoss()))
		return;

	if (!MyKFPM.IsAliveAndWell() || (MyKFPM.Health - InDamage) > 0)
		return;

	// Iterate nearby teammates and heal them
	foreach DamageInstigator.Pawn.WorldInfo.AllPawns(class'KFPawn_Human', KFPH)
	{
		if (KFPH == None || !KFPH.IsAliveAndWell())
			continue;

		// Check distance from the dying zed
		DistSQ = VSizeSQ(KFPH.Location - MyKFPM.Location);
		if (DistSQ > default.Radius * default.Radius)
			continue;

		// Heal the teammate
		KFPH.HealDamage(default.HealAmount[upgLevel - 1], DamageInstigator, class'KFDT_Healing');

		// Deluxe: also restore armor. AddArmor virtual-dispatches into the
		// WMPawn_Human override, which adds to ZedternalArmor, clamps to
		// ZedternalMaxArmor and syncs the HUD display value.
		if (upgLevel > 1)
		{
			KFPH.AddArmor(default.DeluxeArmorAmount);
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_ParasiticBloom]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_ParasiticBloom"

	UpgradeName="Parasitic Bloom"
	UpgradeDescription(0)="Killing a <font color=\"#9370DB\">large zed</font> heals all teammates within <font color=\"#FFFFFF\">10m</font> for <font color=\"#42e087\">20 HP</font>."
	UpgradeDescription(1)="Killing a <font color=\"#9370DB\">large zed</font> heals all teammates within <font color=\"#FFFFFF\">10m</font> for <font color=\"#42e087\">35 HP</font> and restores <font color=\"#4444ff\">10 armor</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ParasiticBloom'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ParasiticBloom_Deluxe'

	Name="Default__DKUpgrade_Skill_ParasiticBloom"
}
