// ===================================================================
// DKUpgrade_Skill_NeuralFeedback
// Strike the hive and the hive strikes back - neural pathways
// channel pain into a corrosive bioelectric response that
// punishes anything foolish enough to attack the collective.
//
// Normal: Reflect 15% of damage taken back to the attacker
// Deluxe: Reflect 30% of damage taken back to the attacker
//         and heal yourself for 50% of the reflected amount
// ===================================================================
class DKUpgrade_Skill_NeuralFeedback extends DKUpgrade_Skill
	config(ZedternalUnlimited);

var config array<float> ReflectPercent;
var config float DeluxeHealPercent;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ReflectPercent[0] = 0.15f;
		default.ReflectPercent[1] = 0.30f;
		default.DeluxeHealPercent = 0.50f;

		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local int ReflectedDamage;

	if (InDamage <= 0)
		return;

	// Need a valid attacker that is a monster
	if (InstigatedBy == None || InstigatedBy.Pawn == None || KFPawn_Monster(InstigatedBy.Pawn) == None)
		return;

	// Make sure the attacker is alive
	if (!InstigatedBy.Pawn.IsAliveAndWell())
		return;

	// Calculate reflected damage
	ReflectedDamage = Round(float(DefaultDamage) * default.ReflectPercent[upgLevel - 1]);

	if (ReflectedDamage > 0)
	{
		// Deal damage back to the attacker
		InstigatedBy.Pawn.TakeDamage(ReflectedDamage, OwnerPawn.Controller, InstigatedBy.Pawn.Location, vect(0,0,0), class'KFDT_Toxic');

		// Deluxe: heal self for 50% of reflected damage
		if (upgLevel > 1 && OwnerPawn.Controller != None)
		{
			OwnerPawn.HealDamage(Round(float(ReflectedDamage) * default.DeluxeHealPercent), OwnerPawn.Controller, class'KFDT_Healing');
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKUpgrade_Skill_NeuralFeedback]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKUpgrade_Skill_NeuralFeedback"

	UpgradeName="Neural Feedback"
	UpgradeDescription(0)="Strike the hive and the <font color=\"#9370DB\">hive strikes back</font>. Reflect <font color=\"#FFFFFF\">15%</font> of damage taken back to the attacker as <font color=\"#8fce00\">toxic damage</font>."
	UpgradeDescription(1)="Strike the hive and the <font color=\"#9370DB\">hive strikes back</font>. Reflect <font color=\"#FFFFFF\">30%</font> of damage taken back as <font color=\"#8fce00\">toxic damage</font> and heal yourself for <font color=\"#42e087\">50%</font> of the reflected amount."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_NeuralFeedback'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_NeuralFeedback_Deluxe'

	Name="Default__DKUpgrade_Skill_NeuralFeedback"
}
