class DKWeaponUpg_Penetration extends DKUpgrade_Weapon
	abstract
	config(ZedternalUnlimited);

var config float PenBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 2)
	{
		default.PenBonus = 0.5f;
		default.MODEVERSION = 2;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	if (!KFW.default.bMeleeWeapon)
		return True;
	return False;
}

static simulated function ModifyPenetration(out float InPenetration, float DefaultPenetration, int upgLevel, class<KFDamageType> DamageType, KFPawn OwnerPawn, optional bool bForce)
{
	local float Val;
	Val = default.PenBonus;
	if (Val <= 0.f) Val = 0.5f;
	InPenetration += Val * upgLevel;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKWeaponUpg_Penetration]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKWeaponUpg_Penetration"

	UpgradeName="Armor Piercing"
	UpgradeDescription(0)="Increases your <font color=\"#15d7fa\">weapon penetration</font> by <font color=\"#77d914\">+%x%%</font> per level."
	WeaponBonus=(baseValue=0, incValue=50, maxValue=-1)
	Name="Default__DKWeaponUpg_Penetration"
}
