class DKWeaponUpg_Stun extends DKUpgrade_Weapon
	abstract
	config(ZedternalUnlimited);

var config float StunBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 2)
	{
		default.StunBonus = 0.2f;
		default.MODEVERSION = 2;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	return True;
}

static function ModifyStunPower(out float InStunPower, float DefaultStunPower, int upgLevel, optional class<DamageType> DamageType, optional byte HitZoneIdx)
{
	InStunPower += DefaultStunPower * default.StunBonus * upgLevel;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKWeaponUpg_Stun]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKWeaponUpg_Stun"

	UpgradeName="Concussive Impact"
	UpgradeDescription(0)="Increases your <font color=\"#15d7fa\">stun power</font> by <font color=\"#77d914\">+%x%%</font> per level."
	WeaponBonus=(baseValue=0, incValue=20, maxValue=-1)
	Name="Default__DKWeaponUpg_Stun"
}
