// Void Sight weapon upgrade — Deluxe tier
// +7% damage per level while aiming down sights.
// L1=7%, L5=35%, L10=70%
class DKWeaponUpg_VoidSight_Deluxe extends DKWeaponUpg_HollowBase
	abstract
	config(ZedternalUnlimited);

var config float ADSBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ADSBonus = 0.07f;
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	return True;
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (MyKFW == None)
		return;

	if (!MyKFW.bUsingSights)
		return;

	InDamage += Round(float(DefaultDamage) * default.ADSBonus * upgLevel);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKWeaponUpg_VoidSight_Deluxe]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKWeaponUpg_VoidSight_Deluxe"

	UpgradeName="Void Sight (Deluxe)"
	UpgradeDescription(0)="Deals <font color=\"#00CCFF\">+%x%%</font> additional damage while <font color=\"#6B0099\">aiming down sights</font> per level."
	WeaponBonus=(baseValue=0, incValue=7, maxValue=-1)
	RequiredSkillClassPath="ZedternalRBPerkpackage.DKUpgrade_Skill_VoidSight"
	bRequiresDeluxe=True
	Name="Default__DKWeaponUpg_VoidSight_Deluxe"
}
