// Hollow Caliber weapon upgrade — Deluxe tier
// +0.8% damage per level per permanently unlocked Hollow weapon.
// 10 unlocks + L10 = +80% bonus damage.
// 20 unlocks + L10 = +160% bonus damage.
class DKWeaponUpg_HollowCaliber_Deluxe extends DKWeaponUpg_HollowBase
	abstract
	config(ZedternalUnlimited);

var config float BonusPerLevelPerUnlock;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.BonusPerLevelPerUnlock = 0.008f;
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	return True;
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local DKUpgrade_Perk_Hollow_Helper HollowHelper;
	local int UnlockCount;
	local float Bonus;

	if (DamageInstigator == None || DamageInstigator.Pawn == None)
		return;

	foreach DamageInstigator.Pawn.ChildActors(class'DKUpgrade_Perk_Hollow_Helper', HollowHelper)
		break;
	if (HollowHelper == None)
		return;

	UnlockCount = HollowHelper.GetUnlockCount();
	if (UnlockCount <= 0)
		return;

	Bonus = float(UnlockCount) * default.BonusPerLevelPerUnlock * upgLevel;
	InDamage += Round(float(DefaultDamage) * Bonus);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKWeaponUpg_HollowCaliber_Deluxe]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKWeaponUpg_HollowCaliber_Deluxe"

	UpgradeName="Hollow Caliber (Deluxe)"
	UpgradeDescription(0)="Deals <font color=\"#00CCFF\">+0.8%</font> damage per level for each <font color=\"#6B0099\">permanently unlocked Hollow weapon</font> (currently lv. <font color=\"#00CCFF\">%x</font>)."
	WeaponBonus=(baseValue=0, incValue=1, maxValue=-1)
	RequiredSkillClassPath="ZedternalRBPerkpackage.DKUpgrade_Skill_HollowCaliber"
	bRequiresDeluxe=True
	Name="Default__DKWeaponUpg_HollowCaliber_Deluxe"
}
