class DKWeaponUpg_FleshpoundDamage extends DKUpgrade_Weapon
	abstract
	config(ZedternalUnlimited);

var config float DamageBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 2)
	{
		default.DamageBonus = 0.2f;
		default.MODEVERSION = 2;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	return True;
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (MyKFPM != None && KFPawn_ZedFleshpound(MyKFPM) != None)
		InDamage += Round(float(DefaultDamage) * default.DamageBonus * upgLevel);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKWeaponUpg_FleshpoundDamage]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKWeaponUpg_FleshpoundDamage"

	UpgradeName="Pound Breaker"
	UpgradeDescription(0)="Increases damage against <font color=\"#15d7fa\">Fleshpounds</font> by <font color=\"#77d914\">+%x%%</font> per level."
	WeaponBonus=(baseValue=0, incValue=20, maxValue=-1)
	Name="Default__DKWeaponUpg_FleshpoundDamage"
}
