// Void Infusion weapon upgrade — base tier
// +6% DoT scaler per level. Amplifies fire, poison, bleed, cryo ticks.
// L1=6%, L5=30%, L10=60%
class DKWeaponUpg_VoidInfusion extends DKWeaponUpg_HollowBase
	abstract
	config(ZedternalUnlimited);

var config float DoTBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DoTBonus = 0.06f;
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	return True;
}

static function ModifyDoTScaler(out float InDoTScaler, float DefaultDotScaler, int upgLevel, optional class<KFDamageType> KFDT, optional bool bNapalmInfected)
{
	InDoTScaler += DefaultDotScaler * default.DoTBonus * upgLevel;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKWeaponUpg_VoidInfusion]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKWeaponUpg_VoidInfusion"

	UpgradeName="Void Infusion"
	UpgradeDescription(0)="Increases your <font color=\"#6B0099\">damage-over-time</font> intensity by <font color=\"#00CCFF\">+%x%%</font> per level."
	WeaponBonus=(baseValue=0, incValue=6, maxValue=-1)
	RequiredSkillClassPath="ZedternalRBPerkpackage.DKUpgrade_Skill_VoidInfusion"
	bRequiresDeluxe=False
	Name="Default__DKWeaponUpg_VoidInfusion"
}
