// Void Reserves weapon upgrade — Deluxe tier
// +8% mag capacity AND +8% spare ammo per level.
// L1=8%, L5=40%, L10=80% on both stats.
class DKWeaponUpg_VoidReserves_Deluxe extends DKWeaponUpg_HollowBase
	abstract
	config(ZedternalUnlimited);

var config float BonusPerLevel;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.BonusPerLevel = 0.08f;
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	return True;
}

static simulated function ModifyMagSizeAndNumber(out int InMagazineCapacity, int DefaultMagazineCapacity, int upgLevel, KFWeapon KFW, optional array< Class<KFPerk> > WeaponPerkClass, optional bool bSecondary=False, optional name WeaponClassname)
{
	InMagazineCapacity += Round(float(DefaultMagazineCapacity) * default.BonusPerLevel * upgLevel);
}

static simulated function ModifySpareAmmoAmount(out int InSpareAmmo, int DefaultSpareAmmo, int upgLevel, KFWeapon KFW, optional const out STraderItem TraderItem, optional bool bSecondary=False)
{
	InSpareAmmo += Round(float(DefaultSpareAmmo) * default.BonusPerLevel * upgLevel);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKWeaponUpg_VoidReserves_Deluxe]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKWeaponUpg_VoidReserves_Deluxe"

	UpgradeName="Void Reserves (Deluxe)"
	UpgradeDescription(0)="Increases your <font color=\"#6B0099\">magazine capacity</font> and <font color=\"#6B0099\">spare ammo</font> by <font color=\"#00CCFF\">+%x%%</font> per level."
	WeaponBonus=(baseValue=0, incValue=8, maxValue=-1)
	RequiredSkillClassPath="ZedternalRBPerkpackage.DKUpgrade_Skill_VoidReserves"
	bRequiresDeluxe=True
	Name="Default__DKWeaponUpg_VoidReserves_Deluxe"
}
