class DKWeaponUpg_FireRate extends DKUpgrade_Weapon
	abstract
	config(ZedternalUnlimited);

var config float FireRateBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 2)
	{
		default.FireRateBonus = 0.1f;
		default.MODEVERSION = 2;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	if (!KFW.default.bMeleeWeapon)
		return True;
	return False;
}

static simulated function ModifyRateOfFire(out float InRate, float DefaultRate, int upgLevel, KFWeapon KFW)
{
	local float Val;
	Val = default.FireRateBonus;
	if (Val <= 0.f) Val = 0.1f;
	InRate = DefaultRate / (DefaultRate / InRate + Val * upgLevel);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKWeaponUpg_FireRate]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKWeaponUpg_FireRate"

	UpgradeName="Overclock"
	UpgradeDescription(0)="Increases your <font color=\"#15d7fa\">rate of fire</font> by <font color=\"#77d914\">+%x%%</font> per level."
	WeaponBonus=(baseValue=0, incValue=10, maxValue=-1)
	Name="Default__DKWeaponUpg_FireRate"
}
