class DKWeaponUpg_SpareAmmo extends DKUpgrade_Weapon
	abstract
	config(ZedternalUnlimited);

var config float AmmoBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 2)
	{
		default.AmmoBonus = 0.2f;
		default.MODEVERSION = 2;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	if (KFW.default.SpareAmmoCapacity[0] >= 8)
		return True;
	return False;
}

static simulated function ModifySpareAmmoAmount(out int InSpareAmmo, int DefaultSpareAmmo, int upgLevel, KFWeapon KFW, optional const out STraderItem TraderItem, optional bool bSecondary=False)
{
	local float Val;
	Val = default.AmmoBonus;
	if (Val <= 0.f) Val = 0.2f;
	InSpareAmmo += Round(float(DefaultSpareAmmo) * Val * upgLevel);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalRBPerkpackage.<langext>
    // Section: [DKWeaponUpg_SpareAmmo]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalRBPerkpackage"
    LocSection="DKWeaponUpg_SpareAmmo"

	UpgradeName="Deep Pockets"
	UpgradeDescription(0)="Increases your <font color=\"#15d7fa\">spare ammo</font> by <font color=\"#77d914\">+%x%%</font> per level."
	WeaponBonus=(baseValue=0, incValue=20, maxValue=-1)
	Name="Default__DKWeaponUpg_SpareAmmo"
}
