class ZTUpgrade_Skill_HoldTheLine extends ZTUpgrade_Skill config(ZedternalUnlimited);

// Stand your ground, become immovable
// While standing still or barely moving, gain huge damage and resistance bonuses
// Moving at full speed removes bonuses

var config array<float> MeleeDamageBonus;   // +30% / +50% melee damage
var config array<float> ResistanceBonus;    // +25% / +40% damage resistance
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MeleeDamageBonus[0] = 0.30f;
		default.MeleeDamageBonus[1] = 0.50f;
		default.ResistanceBonus[0] = 0.25f;
		default.ResistanceBonus[1] = 0.40f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.MeleeDamageBonus.Length = 2;
		default.MeleeDamageBonus[0] = 0.150000f;
		default.MeleeDamageBonus[1] = 0.300000f;
		default.ResistanceBonus.Length = 2;
		default.ResistanceBonus[0] = 0.080000f;
		default.ResistanceBonus[1] = 0.160000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local ZTUpgrade_Skill_HoldTheLine_Helper UPG;

	if (DamageType != None && static.IsMeleeDamageType(DamageType) && DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		UPG = GetHelper(KFPawn(DamageInstigator.Pawn));
		if (UPG != None && UPG.bHolding)
		{
			InDamage += Round(float(DefaultDamage) * default.MeleeDamageBonus[upgLevel - 1]);
		}
	}
}

static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local ZTUpgrade_Skill_HoldTheLine_Helper UPG;

	if (OwnerPawn != None)
	{
		UPG = GetHelper(OwnerPawn);
		if (UPG != None && UPG.bHolding)
		{
			InDamage -= Round(float(DefaultDamage) * default.ResistanceBonus[upgLevel - 1]);
			if (InDamage < 1)
				InDamage = 1;
		}
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_HoldTheLine_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_HoldTheLine_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
		{
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_HoldTheLine_Helper', OwnerPawn);
			UPG.SetDeluxe(upgLevel > 1);
		}
	}
}

static function ZTUpgrade_Skill_HoldTheLine_Helper GetHelper(KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_HoldTheLine_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_HoldTheLine_Helper', UPG)
		{
			return UPG;
		}

		if (OwnerPawn.Role == Role_Authority)
		{
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_HoldTheLine_Helper', OwnerPawn);
		}
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_HoldTheLine_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_HoldTheLine_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_HoldTheLine]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_HoldTheLine"

	UpgradeName="Hold the Line"

	UpgradeDescription(0)="<font color=\"#edb82a\">Hold the Line</font> While <font color=\"#87CEEB\">standing still</font>:  <font color=\"#FF4500\">+15% Melee Damage</font>  <font color=\"#4169E1\">+8% Damage Resistance</font> <font color=\"#AAAAAA\">Plant your feet and dare them to approach.</font>"
	UpgradeDescription(1)="<font color=\"#edb82a\">Hold the Line</font> While <font color=\"#87CEEB\">moving slowly</font>:  <font color=\"#FF4500\">+30% Melee Damage</font>  <font color=\"#4169E1\">+16% Damage Resistance</font> <font color=\"#AAAAAA\">Plant your feet and dare them to approach.</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HoldTheLine'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HoldTheLine_Deluxe'

	Name="Default__ZTUpgrade_Skill_HoldTheLine"
}
