// ===================================================================
// ZTUpgrade_Skill_Fatalist
//
// "Fatalist"
// Completing a prophecy condition type you've never completed before
// grants boosted reward. Encourages variety — as you check off
// more condition types, only rare/hard ones still give the bonus.
//
// Standard: 1.5x reward for first-time condition types
// Deluxe:   2.0x reward for first-time condition types
// ===================================================================
class ZTUpgrade_Skill_Fatalist extends ZTUpgrade_Skill;

// --- Helper spawning ---
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local ZTUpgrade_Skill_Fatalist_Helper H;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == ROLE_Authority)
    {
        bFound = false;
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Fatalist_Helper', H)
        {
            bFound = true;
            H.Initialize(upgLevel);
            break;
        }

        if (!bFound)
        {
            H = OwnerPawn.Spawn(class'ZTUpgrade_Skill_Fatalist_Helper', OwnerPawn);
            if (H != None)
                H.Initialize(upgLevel);
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_Fatalist_Helper H;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Fatalist_Helper', H)
        {
            H.Cleanup();
            H.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Fatalist]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Fatalist"

    UpgradeName="Fatalist"
    UpgradeDescription(0)="Completing a prophecy condition <font color=\"#77d914\">for the first time</font> grants <font color=\"#15d7fa\">1.5x reward</font>. Repeat conditions get normal reward."
    UpgradeDescription(1)="Completing a prophecy condition <font color=\"#77d914\">for the first time</font> grants <font color=\"#15d7fa\">2x reward</font>. Repeat conditions get normal reward."

    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Fatalist_Deluxe'

    Name="Default__ZTUpgrade_Skill_Fatalist"
}
