// ===================================================================
// ZTUpgrade_Skill_GeneticMemory
//
// "The first shape is always the deepest."
//
// The very first buff rolled in a game is imprinted permanently.
// Even after it's replaced by new rolls, a ghost of that original
// form lingers at reduced effectiveness. Your origin never fades.
//
// BEHAVIOR DETAILS:
// - FirstBuffIndex is locked on the first-ever RollNewBuffs call
//   (only when this skill is equipped and multiplier > 0).
// - The ghost bonus is ALWAYS ADDITIVE — it stacks on top of
//   normal effectiveness even when the buff is currently active.
//   Active buff = 1.0 + ghost. Inactive buff = 0.0 + ghost.
// - This means re-rolling your first buff or collecting it via
//   Mimicry gives it EXTRA power (1.15 / 1.30 base) permanently.
// - The skill never loses value — it's always doing something.
// - Ghost effectiveness stacks with other multipliers (Overclocked,
//   Flux State, Monomorph) just like any other base value.
//
// Standard: First buff permanently active at 15% effectiveness
// Deluxe:   First buff permanently active at 30% effectiveness
// ===================================================================
class ZTUpgrade_Skill_GeneticMemory extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> GhostPower;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.GhostPower[0] = 0.15f;
		default.GhostPower[1] = 0.30f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.GhostPower.Length = 2;
		default.GhostPower[0] = 0.150000f;
		default.GhostPower[1] = 0.300000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// Helper lookup - reuses the Shapeshifter perk's static GetHelper
static simulated function ZTUpgrade_Perk_Shapeshifter_Helper GetShapeshifterHelper(Pawn OwnerPawn)
{
    return class'ZTUpgrade_Perk_Shapeshifter'.static.GetHelper(OwnerPawn);
}

// Configure the helper's Genetic Memory multiplier on weapon init (server-side)
// FirstBuffIndex itself is set by RollNewBuffs when it detects the multiplier > 0
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local ZTUpgrade_Perk_Shapeshifter_Helper Helper;

    if (OwnerPawn == None || OwnerPawn.Role != Role_Authority)
        return;

    Helper = GetShapeshifterHelper(OwnerPawn);
    if (Helper == None)
        return;

    Helper.FirstBuffMultiplier = default.GhostPower[upgLevel - 1];
    Helper.bNetDirty = true;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_GeneticMemory]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_GeneticMemory"

    UpgradeName="Genetic Memory"
    UpgradeDescription(0)="Your <font color=\"#15d7fa\">First Buff</font> remains permanently active at <font color=\"#77d914\">15%</font> effectiveness."
    UpgradeDescription(1)="Your <font color=\"#15d7fa\">First Buff</font> remains permanently active at <font color=\"#77d914\">30%</font> effectiveness."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_GeneticMemory'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_GeneticMemory_Deluxe'

    Name="Default__ZTUpgrade_Skill_GeneticMemory"
}
