class ZTUpgrade_Skill_WintersSwiftness extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> MovementSpeed;
var config array<float> WeaponSwitchSpeed;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MovementSpeed[0] = 0.10f;
		default.MovementSpeed[1] = 0.20f;
		default.WeaponSwitchSpeed[0] = 0.5f;
		default.WeaponSwitchSpeed[1] = 0.4f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.MovementSpeed.Length = 2;
		default.MovementSpeed[0] = 0.100000f;
		default.MovementSpeed[1] = 0.200000f;
		default.WeaponSwitchSpeed.Length = 2;
		default.WeaponSwitchSpeed[0] = 0.500000f;
		default.WeaponSwitchSpeed[1] = 0.400000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function ModifySpeed(out float InSpeed, float DefaultSpeed, int upgLevel, KFPawn OwnerPawn)
{
    InSpeed = DefaultSpeed * (1.0f + default.MovementSpeed[upgLevel - 1]);
}

static simulated function ModifyWeaponSwitchTime(out float InSwitchTime, float DefaultSwitchTime, int upgLevel, KFWeapon KFW)
{
    InSwitchTime = DefaultSwitchTime * default.WeaponSwitchSpeed[upgLevel - 1];
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_WintersSwiftness]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_WintersSwiftness"

    UpgradeName="Winter's Swiftness"
    upgradeDescription(0)="Gain <font color=\"#87CEEB\">10%</font> <font color=\"#9966FF\">Movement Speed</font> and <font color=\"#15d7fa\">100%</font> <font color=\"#77d914\">Weapon Switch Speed</font>."
    upgradeDescription(1)="Gain <font color=\"#87CEEB\">20%</font> <font color=\"#9966FF\">Movement Speed</font> and <font color=\"#15d7fa\">150%</font> <font color=\"#77d914\">Weapon Switch Speed</font>."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_WintersSwiftness'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_WintersSwiftness_Deluxe'

    Name="Default__ZTUpgrade_Skill_WintersSwiftness"
}