class ZTUpgrade_Skill_Bloodthirst extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> MaxDamageBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MaxDamageBonus[0] = 0.50f;
		default.MaxDamageBonus[1] = 1.00f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.MaxDamageBonus.Length = 2;
		default.MaxDamageBonus[0] = 0.300000f;
		default.MaxDamageBonus[1] = 0.600000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local KFPawn_Human KFPH;
    local float HealthPercent;
    local float DamageBonus;
    
    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;
    
    KFPH = KFPawn_Human(DamageInstigator.Pawn);
    if (KFPH == None || !KFPH.IsAliveAndWell())
        return;
    
    // Calculate health percentage (0.0 = dead, 1.0 = full)
    HealthPercent = float(KFPH.Health) / float(KFPH.HealthMax);
    
    // Damage bonus scales inversely with health
    // At full health: 0% bonus, At 1 HP: MaxDamageBonus
    DamageBonus = (1.0f - HealthPercent) * default.MaxDamageBonus[upgLevel - 1];
    
    InDamage += Round(float(DefaultDamage) * DamageBonus);
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Bloodthirst]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Bloodthirst"

    UpgradeName="Bloodthirst"
    upgradeDescription(0)="Deal up to <font color=\"#ff3399\">+30%</font> bonus damage based on <font color=\"#ff0000\">missing health</font>. Lower HP = higher damage."
    upgradeDescription(1)="Deal up to <font color=\"#ff3399\">+60%</font> bonus damage based on <font color=\"#ff0000\">missing health</font>. Lower HP = higher damage."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Bloodthirst'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Bloodthirst_Deluxe'

    Name="Default__ZTUpgrade_Skill_Bloodthirst"
}
