// ===================================================================
// ZTUpgrade_Skill_PolymorphicSynthesis
//
// "The shifting body synthesizes power across its many forms."
//
// Cross-pollinates buff categories into unexpected resource bonuses:
// - Utility buffs (Speedfreak, Hoarder, Drumfire, Phantom) grant
//   bonus penetration — the shifting body phases through targets.
// - Offense buffs (Carnage, Executioner, Rampage, Crusher, Berserker)
//   grant bonus spare ammo — aggressive forms consume efficiently.
//
// Creates emergent synergies across buff categories and rewards
// diverse Mimicry collections from a completely different angle
// than Chimera Protocol (which gives flat damage).
//
// Standard: +1 penetration per active utility buff,
//           +8% spare ammo per active offense buff
// Deluxe:   +2 penetration per active utility buff,
//           +15% spare ammo per active offense buff
// ===================================================================
class ZTUpgrade_Skill_PolymorphicSynthesis extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> PenetrationPerUtilityBuff;
var config array<float> SpareAmmoPerOffenseBuff;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.PenetrationPerUtilityBuff[0] = 1.0f;
		default.PenetrationPerUtilityBuff[1] = 2.0f;
		default.SpareAmmoPerOffenseBuff[0] = 0.08f;
		default.SpareAmmoPerOffenseBuff[1] = 0.15f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.PenetrationPerUtilityBuff.Length = 2;
		default.PenetrationPerUtilityBuff[0] = 1.000000f;
		default.PenetrationPerUtilityBuff[1] = 2.000000f;
		default.SpareAmmoPerOffenseBuff.Length = 2;
		default.SpareAmmoPerOffenseBuff[0] = 0.080000f;
		default.SpareAmmoPerOffenseBuff[1] = 0.150000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// Helper lookup - reuses the Shapeshifter perk's static GetHelper
static simulated function ZTUpgrade_Perk_Shapeshifter_Helper GetShapeshifterHelper(Pawn OwnerPawn)
{
    return class'ZTUpgrade_Perk_Shapeshifter'.static.GetHelper(OwnerPawn);
}

// Resolve OwnerPawn from weapon (same pattern as main perk)
static simulated function KFPawn GetWeaponOwnerPawn(KFWeapon KFW)
{
    local KFPawn P;
    local Controller C;

    if (KFW == None)
        return None;

    P = KFPawn(KFW.Instigator);
    if (P != None) return P;

    P = KFPawn(KFW.Owner);
    if (P != None) return P;

    C = Controller(KFW.Owner);
    if (C != None)
    {
        P = KFPawn(C.Pawn);
        if (P != None) return P;
    }

    if (KFW.InvManager != None)
    {
        P = KFPawn(KFW.InvManager.Owner);
        if (P != None) return P;
    }

    return None;
}

// Penetration bonus from active utility buffs (bits 11-14)
static simulated function ModifyPenetration(out float InPenetration, float DefaultPenetration, int upgLevel, class<KFDamageType> DamageType, KFPawn OwnerPawn, optional bool bForce)
{
    local ZTUpgrade_Perk_Shapeshifter_Helper Helper;
    local int UtilityCount;

    if (OwnerPawn == None) return;

    Helper = GetShapeshifterHelper(OwnerPawn);
    if (Helper == None) return;

    // Count active utility buffs (bits 11-14: Speedfreak, Hoarder, Drumfire, Phantom)
    UtilityCount = Helper.CountBuffsInCategory(Helper.CATEGORY_UTILITY_MASK);
    if (UtilityCount > 0)
        InPenetration += default.PenetrationPerUtilityBuff[upgLevel - 1] * float(UtilityCount);
}

// Spare ammo bonus from active offense buffs (bits 0-4)
static simulated function ModifySpareAmmoAmount(out int InSpareAmmo, int DefaultSpareAmmo, int upgLevel, KFWeapon KFW, optional const out STraderItem TraderItem, optional bool bSecondary=False)
{
    local ZTUpgrade_Perk_Shapeshifter_Helper Helper;
    local KFPawn OwnerPawn;
    local int OffenseCount;

    OwnerPawn = GetWeaponOwnerPawn(KFW);
    if (OwnerPawn == None) return;

    Helper = GetShapeshifterHelper(OwnerPawn);
    if (Helper == None) return;

    // Count active offense buffs (bits 0-4: Carnage, Executioner, Rampage, Crusher, Berserker)
    OffenseCount = Helper.CountBuffsInCategory(Helper.CATEGORY_OFFENSE_MASK);
    if (OffenseCount > 0)
        InSpareAmmo += Round(float(DefaultSpareAmmo) * default.SpareAmmoPerOffenseBuff[upgLevel - 1] * float(OffenseCount));
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_PolymorphicSynthesis]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_PolymorphicSynthesis"

    UpgradeName="Polymorphic Synthesis"
    UpgradeDescription(0)="<font color=\"#c77dff\">Polymorphic Synthesis:</font> Active <font color=\"#e0aaff\">utility buffs</font> grant <font color=\"#FFFFFF\">+1</font> penetration each. Active <font color=\"#e0aaff\">offense buffs</font> grant <font color=\"#FFFFFF\">+8%</font> spare ammo each"
    UpgradeDescription(1)="<font color=\"#c77dff\">Polymorphic Synthesis:</font> Active <font color=\"#e0aaff\">utility buffs</font> grant <font color=\"#FFFFFF\">+2</font> penetration each. Active <font color=\"#e0aaff\">offense buffs</font> grant <font color=\"#FFFFFF\">+15%</font> spare ammo each"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PolymorphicSynthesis'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PolymorphicSynthesis_Deluxe'

    Name="Default__ZTUpgrade_Skill_PolymorphicSynthesis"
}
