// ===================================================================
// ZTUpgrade_Skill_EssenceDrain - Precision Sustains the Network
// Headshots on siphoned enemies deal significant bonus damage AND
// refresh the duration on ALL currently siphoned enemies. Rewards
// precision with both burst damage and sustained siphon uptime.
//
// Standard: +30% bonus headshot damage on siphoned, refresh siphons
// Deluxe:   +60% bonus headshot damage on siphoned, refresh siphons
//
// REQUIRES: ZTUpgrade_Perk_Parasite_Helper must expose:
//   - IsSiphoned(KFPawn_Monster) : bool
//   - RefreshAllSiphons() : void  (resets all siphon durations)
// ===================================================================
class ZTUpgrade_Skill_EssenceDrain extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> HeadshotBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HeadshotBonus[0] = 0.30f;
		default.HeadshotBonus[1] = 0.60f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.HeadshotBonus.Length = 2;
		default.HeadshotBonus[0] = 0.300000f;
		default.HeadshotBonus[1] = 0.600000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// ===================================================================
// Headshots on siphoned targets: bonus damage + refresh all siphons
// ===================================================================
static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
	optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
	optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
	optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local ZTUpgrade_Perk_Parasite_Helper ParasiteHelper;

	// Must be a headshot (HitZoneIdx 0 = head)
	if (HitZoneIdx != 0)
		return;

	if (DamageInstigator == None || DamageInstigator.Pawn == None || MyKFPM == None)
		return;

	ParasiteHelper = GetParasiteHelper(DamageInstigator.Pawn);
	if (ParasiteHelper == None)
		return;

	// Only applies to siphoned enemies
	if (!ParasiteHelper.IsSiphoned(MyKFPM))
		return;

	// Bonus headshot damage
	InDamage += Round(float(DefaultDamage) * default.HeadshotBonus[upgLevel - 1]);

	// Refresh ALL siphon durations
	ParasiteHelper.RefreshAllSiphons();
}

// ===================================================================
// Find Parasite Perk Helper
// ===================================================================
static function ZTUpgrade_Perk_Parasite_Helper GetParasiteHelper(Pawn OwnerPawn)
{
	local ZTUpgrade_Perk_Parasite_Helper PHelper;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Perk_Parasite_Helper', PHelper)
			return PHelper;
	}

	return None;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_EssenceDrain]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_EssenceDrain"

	UpgradeName="Essence Drain"
	UpgradeDescription(0)="<font color=\"#B40028\">Essence Drain:</font> Headshots on <font color=\"#FF6464\">siphoned</font> enemies deal <font color=\"#FFFFFF\">+30%</font> damage and <font color=\"#FFDC96\">refresh all siphon durations</font>"
	UpgradeDescription(1)="<font color=\"#FFD700\">[DELUXE]</font> <font color=\"#B40028\">Essence Drain:</font> Headshots on <font color=\"#FF6464\">siphoned</font> enemies deal <font color=\"#FFFFFF\">+60%</font> damage and <font color=\"#FFDC96\">refresh all siphon durations</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_EssenceDrain'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_EssenceDrain_Deluxe'

	Name="Default__ZTUpgrade_Skill_EssenceDrain"
}
