// ===================================================================
// ZTUpgrade_Skill_BloodBank - Stored Blood Shield
// Kills store blood points (capped). Stored blood absorbs damage
// before real HP is touched. Rewards sustained aggression with a
// secondary buffer that must be constantly replenished.
//
// Standard: +3 stored blood per kill, max 50, absorbs 60% of hit
// Deluxe:   +5 stored blood per kill, max 100, absorbs 80% of hit
// ===================================================================
class ZTUpgrade_Skill_BloodBank extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<int> BloodPerKill;
var config array<int> MaxStoredBlood;
var config array<float> AbsorptionRate;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.BloodPerKill[0] = 3;
		default.BloodPerKill[1] = 5;
		default.MaxStoredBlood[0] = 50;
		default.MaxStoredBlood[1] = 100;
		default.AbsorptionRate[0] = 0.60f;
		default.AbsorptionRate[1] = 0.80f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.BloodPerKill.Length = 2;
		default.BloodPerKill[0] = 2;
		default.BloodPerKill[1] = 3;
		default.MaxStoredBlood.Length = 2;
		default.MaxStoredBlood[0] = 25;
		default.MaxStoredBlood[1] = 50;
		default.AbsorptionRate.Length = 2;
		default.AbsorptionRate[0] = 0.200000f;
		default.AbsorptionRate[1] = 0.300000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// ===================================================================
// On Kill: Add stored blood via helper
// ===================================================================
static function AddVampireHealth(out int InHealth, int DefaultHealth, int upgLevel,
	KFPlayerController KFPC, class<DamageType> DT)
{
	local ZTUpgrade_Skill_BloodBank_Helper Helper;

	if (KFPC != None && KFPC.Pawn != None)
	{
		Helper = GetHelper(KFPC.Pawn);
		if (Helper != None)
			Helper.AddStoredBlood(default.BloodPerKill[upgLevel - 1], default.MaxStoredBlood[upgLevel - 1]);
	}
}

// ===================================================================
// On Damage Taken: Consume stored blood before real HP
// ===================================================================
static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel,
	KFPawn OwnerPawn, optional class<DamageType> DamageType,
	optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local ZTUpgrade_Skill_BloodBank_Helper Helper;
	local int Absorbed;

	if (OwnerPawn == None || InDamage <= 0)
		return;

	Helper = GetHelper(OwnerPawn);
	if (Helper != None && Helper.StoredBlood > 0)
	{
		// Calculate how much damage stored blood can absorb
		Absorbed = Min(Helper.StoredBlood, Round(float(InDamage) * default.AbsorptionRate[upgLevel - 1]));
		Helper.ConsumeStoredBlood(Absorbed);
		InDamage -= Absorbed;

		if (InDamage < 1)
			InDamage = 1;
	}
}

// ===================================================================
// Helper Management
// ===================================================================
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_BloodBank_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_BloodBank_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			OwnerPawn.Spawn(class'ZTUpgrade_Skill_BloodBank_Helper', OwnerPawn);
	}
}

static function ZTUpgrade_Skill_BloodBank_Helper GetHelper(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_BloodBank_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_BloodBank_Helper', UPG)
			return UPG;

		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_BloodBank_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_BloodBank_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_BloodBank_Helper', UPG)
			UPG.Destroy();
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_BloodBank]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_BloodBank"

	UpgradeName="Blood Bank"
	UpgradeDescription(0)="<font color=\"#B40028\">Blood Bank:</font> Kills store <font color=\"#FFFFFF\">2</font> blood (max <font color=\"#FFFFFF\">25</font>). Stored blood absorbs <font color=\"#FFFFFF\">20%</font> of incoming damage before your HP"
	UpgradeDescription(1)="<font color=\"#FFD700\">[DELUXE]</font> <font color=\"#B40028\">Blood Bank:</font> Kills store <font color=\"#FFFFFF\">3</font> blood (max <font color=\"#FFFFFF\">50</font>). Stored blood absorbs <font color=\"#FFFFFF\">20%</font> of incoming damage before your HP"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BloodBank'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BloodBank_Deluxe'

	Name="Default__ZTUpgrade_Skill_BloodBank"
}
