class ZTUpgrade_Skill_PredatorsFocus extends ZTUpgrade_Skill config(ZedternalUnlimited);

// Theme: The Wendigo's aim is perfectly still, like a predator frozen before the strike
var config array<float> Recoil;
var config float Bob;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Recoil[0] = 0.25f;
		default.Recoil[1] = 0.5f;
		default.Bob = 0.11f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Recoil.Length = 2;
		default.Recoil[0] = 0.250000f;
		default.Recoil[1] = 0.500000f;
		default.Bob = 0.110000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function ModifyRecoil(out float InRecoilModifier, float DefaultRecoilModifier, int upgLevel, KFWeapon KFW)
{
	if (KFW != None && KFW.bUsingSights)
		InRecoilModifier -= DefaultRecoilModifier * default.Recoil[upgLevel - 1];
}

static simulated function ModifyWeaponBopDampingPassive(out float bobDampFactor, int upgLevel)
{
	bobDampFactor += default.Bob;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_PredatorsFocus]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_PredatorsFocus"

	UpgradeName="Predator's Focus"
	UpgradeDescription(0)="<font color=\"#4682B4\">Predator's Focus:</font> <font color=\"#FFFFFF\">25%</font> <font color=\"#87CEEB\">less recoil</font> while <font color=\"#F0F8FF\">aiming down sights</font> and reduced weapon sway"
	UpgradeDescription(1)="<font color=\"#4682B4\">Predator's Focus:</font> <font color=\"#FFFFFF\">50%</font> <font color=\"#87CEEB\">less recoil</font> while <font color=\"#F0F8FF\">aiming down sights</font> and reduced weapon sway"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PredatorsFocus'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PredatorsFocus_Deluxe'

	Name="Default__ZTUpgrade_Skill_PredatorsFocus"
}
