Class ZTUpgrade_Perk_Frost extends ZTUpgrade_Perk
	config(ZedternalUnlimited);

var config float Chance;
var config float Damage;
var config float FreezeDuration;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Chance = 0.01f;
		default.Damage = 0.10f;
		default.FreezeDuration = 0.50f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Chance = 0.001000f;
		default.Damage = 0.012500f;
		default.FreezeDuration = 0.100000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}



static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local rotator Rot;
	local vector Loc;

	if (MyKFPM != None && DamageInstigator != None && (FRand() <= (default.Chance * upgLevel)))
	{
		Rot = rotator(MyKFPM.Velocity);
		Loc = MyKFPM.Location;
		Loc.Z -= MyKFPM.GetCollisionHeight();
		Rot.Pitch = 0;
		DamageInstigator.Spawn(class'ZedternalTempered.ZTProj_Avalanche', DamageInstigator, , Loc, Rot, , True);
	}
		
      if (DamageType != None && ClassIsChildOf(DamageType, class'KFDT_Freeze'))
	{
		InDamage += Round(float(DefaultDamage) * default.Damage * upgLevel);
	}
}

static function ModifyDoTScaler(out float InDoTScaler, float DefaultDotScaler, int upgLevel, optional class<KFDamageType> KFDT, optional bool bNapalmInfected)
{
	InDoTScaler += DefaultDotScaler * default.FreezeDuration * upgLevel;
}



defaultproperties
{
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Perks.UI_Perk_Frost_Rank_0'
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Perk_Frost]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Perk_Frost"
    LocalizeDescriptionLineCount=3

    UpgradeName="Frost"
	upgradeDescription(0)="All weapons have a <font color=\"#77d914\">%x%%</font> chance to cause an <font color=\"#0bf1f1\">Avalanche</font>."
	upgradeDescription(1)="Your <font color=\"#0bf1f1\">Freeze</font> effects deal <font color=\"#77d914\">%x%%</font> more damage."
	upgradeDescription(2)="Your <font color=\"#0bf1f1\">Freeze</font> effects last <font color=\"#77d914\">%x%%</font> longer."
	PerkBonus(0)=(baseValue=0, incValue=0, maxValue=-1)
	PerkBonus(1)=(baseValue=0, incValue=1, maxValue=-1)
	PerkBonus(2)=(baseValue=0, incValue=10, maxValue=-1)
	// Legacy (hand-made) artwork icons

	Name="Default__ZTUpgrade_Perk_Frost"
}