// ===================================================================
// ZTUpgrade_Skill_InfestedRounds
// Every bullet carries a payload of hivemind spores. On a killing
// blow, the host body ruptures in a shower of toxic bio-matter.
// Precision headshots trigger devastating eruptions; even body
// kills have a chance to burst.
//
// Normal: Headshot kills deal 50 AoE damage (3m radius)
//         Body kills have 25% chance for 25 damage (2m radius)
// Deluxe: Headshot kills deal 100 AoE damage (3m radius)
//         Body kills have 40% chance for 40 damage (2m radius)
// ===================================================================
class ZTUpgrade_Skill_InfestedRounds extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<int> HeadshotDamage;
var config array<int> BodyDamage;
var config array<float> BodyChance;
var config float HeadshotRadius;
var config float BodyRadius;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HeadshotDamage[0] = 50;
		default.HeadshotDamage[1] = 100;
		default.BodyDamage[0] = 25;
		default.BodyDamage[1] = 40;
		default.BodyChance[0] = 0.25f;
		default.BodyChance[1] = 0.40f;
		default.HeadshotRadius = 300.0f;
		default.BodyRadius = 200.0f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.HeadshotDamage.Length = 2;
		default.HeadshotDamage[0] = 50;
		default.HeadshotDamage[1] = 100;
		default.BodyDamage.Length = 2;
		default.BodyDamage[0] = 25;
		default.BodyDamage[1] = 40;
		default.BodyChance.Length = 2;
		default.BodyChance[0] = 0.250000f;
		default.BodyChance[1] = 0.400000f;
		default.HeadshotRadius = 300.000000f;
		default.BodyRadius = 200.000000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local KFPawn_Monster NearbyZed;
	local int AoEDamage;
	local float AoERadius;

	// Prevent recursive explosions: if this damage IS our AoE, skip
	if (ClassIsChildOf(DamageType, class'ZTDT_InfestedRounds'))
		return;

	// Check for a killing blow
	if (MyKFPM == None || DamageInstigator == None || DamageInstigator.Pawn == None)
		return;

	if (!MyKFPM.IsAliveAndWell() || (MyKFPM.Health - InDamage) > 0)
		return;

	// Determine AoE parameters based on hitzone
	if (HitZoneIdx == 0) // HZI_HEAD
	{
		// Headshot kill - always triggers
		AoEDamage = default.HeadshotDamage[upgLevel - 1];
		AoERadius = default.HeadshotRadius;
	}
	else
	{
		// Body kill - chance-based
		if (FRand() > default.BodyChance[upgLevel - 1])
			return;

		AoEDamage = default.BodyDamage[upgLevel - 1];
		AoERadius = default.BodyRadius;
	}

	// Apply AoE damage to nearby zeds
	foreach MyKFPM.CollidingActors(class'KFPawn_Monster', NearbyZed, AoERadius)
	{
		if (NearbyZed != MyKFPM && NearbyZed.IsAliveAndWell())
		{
			NearbyZed.TakeDamage(AoEDamage, DamageInstigator, NearbyZed.Location, vect(0,0,0), class'ZTDT_InfestedRounds');
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_InfestedRounds]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_InfestedRounds"

	UpgradeName="Infested Rounds"
	UpgradeDescription(0)="Headshot kills deal <font color=\"#15d7fa\">50 AoE damage</font> in a <font color=\"#FFFFFF\">3m radius</font>. Body kills have a <font color=\"#77d914\">25% chance</font> to deal <font color=\"#15d7fa\">25 damage</font> in a <font color=\"#FFFFFF\">2m radius</font>."
	UpgradeDescription(1)="Headshot kills deal <font color=\"#15d7fa\">100 AoE damage</font> in a <font color=\"#FFFFFF\">3m radius</font>. Body kills have a <font color=\"#77d914\">40% chance</font> to deal <font color=\"#15d7fa\">40 damage</font> in a <font color=\"#FFFFFF\">2m radius</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_InfestedRounds'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_InfestedRounds_Deluxe'

	Name="Default__ZTUpgrade_Skill_InfestedRounds"
}
