class ZTUpgrade_Skill_TimeSpiral extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> FireRate, SpecialRate;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.FireRate[0] = 0.1f;
		default.FireRate[1] = 0.2f;
		default.SpecialRate[0] = 0.4f;
		default.SpecialRate[1] = 0.8f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.FireRate.Length = 2;
		default.FireRate[0] = 0.100000f;
		default.FireRate[1] = 0.200000f;
		default.SpecialRate.Length = 2;
		default.SpecialRate[0] = 0.400000f;
		default.SpecialRate[1] = 0.400000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function bool GetIsUberAmmoActive(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	if (OwnerPawn != None && OwnerPawn.Controller != None)
		return OwnerPawn.Controller.WorldInfo.TimeDilation < 1.0f;
	else
		return False;
}

static simulated function GetZedTimeModifier(out float InModifier, int upgLevel, KFWeapon KFW)
{
	local name StateName;

	if (KFW != None)
	{
		StateName = KFW.GetStateName();
		if (class'ZedternalReborn.WMWeaponStates'.static.IsWeaponAttackState(StateName))
		{
			if (KFWeap_MeleeBase(KFW) != None || KFW.default.MagazineCapacity[0] > 4)
				InModifier += default.FireRate[upgLevel - 1];
			else
				InModifier += default.SpecialRate[upgLevel - 1];
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_TimeSpiral]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_TimeSpiral"

    UpgradeName="Time Spiral"
	upgradeDescription(0)="During <font color=\"#15d7fa\">ZED Time</font> you have <font color=\"#77d914\">infinite Ammo</font> and shoot slightly faster."
	upgradeDescription(1)="During <font color=\"#15d7fa\">ZED Time</font> you have <font color=\"#77d914\">infinite Ammo</font> and shoot significantly faster."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_TimeSpiral'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_TimeSpiral_Deluxe'

	Name="Default__ZTUpgrade_Skill_TimeSpiral"
}