// ===================================================================
// ZTUpgrade_Skill_TemporalAbsolution - Wound Rewind
// Theme: Rewind your body's state when ZED Time ends. Damage taken
//        during ZED Time is partially healed back.
// Hooks: InitiateWeapon/DeleteHelperClass (helper tracks HP across
//        ZED Time boundaries)
// ===================================================================
class ZTUpgrade_Skill_TemporalAbsolution extends ZTUpgrade_Skill;

// ===================================================================
// Helper Management
// ===================================================================
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_TemporalAbsolution_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_TemporalAbsolution_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
		{
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_TemporalAbsolution_Helper', OwnerPawn);
			if (UPG != None)
				UPG.Initialize(KFPawn_Human(OwnerPawn), upgLevel > 1);
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_TemporalAbsolution_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_TemporalAbsolution_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_TemporalAbsolution]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_TemporalAbsolution"

	UpgradeName="Temporal Absolution"
	upgradeDescription(0)="When <font color=\"#9632ff\">ZED Time</font> ends, heal back <font color=\"#d8b0ff\">35%</font> of damage taken during that instance."
	upgradeDescription(1)="When <font color=\"#9632ff\">ZED Time</font> ends, heal back <font color=\"#d8b0ff\">65%</font> of damage taken during that instance."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_TemporalAbsolution'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_TemporalAbsolution_Deluxe'

	Name="Default__ZTUpgrade_Skill_TemporalAbsolution"
}
