class ZTUpgrade_Skill_BargainHunter extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> Armor;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Armor[0] = 0.5f;
		default.Armor[1] = 1.0f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Armor.Length = 2;
		default.Armor[0] = 0.500000f;
		default.Armor[1] = 1.000000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function WaveEnd(int upgLevel, KFPlayerController KFPC)
{
	local ZTUpgrade_Skill_BargainHunter_Helper UPG;

	if (KFPC.Pawn != None)
	{
		UPG = GetHelper(KFPC.Pawn);
		if (UPG != None)
			UPG.GiveArmor(default.Armor[upgLevel - 1]);
	}
}

static function ZTUpgrade_Skill_BargainHunter_Helper GetHelper(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_BargainHunter_Helper UPG;

	if (WMPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_BargainHunter_Helper', UPG)
		{
			return UPG;
		}

		//Should have one
		UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_BargainHunter_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_BargainHunter_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_BargainHunter_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_BargainHunter]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_BargainHunter"

    UpgradeName="Bargain Hunter"
	UpgradeDescription(0)="Gain <font color=\"#ff3399\">50%</font> of your <font color=\"#66cc00\">Maximum Armor</font> back at the end of each wave."
	UpgradeDescription(1)="Gain <font color=\"#ff3399\">100%</font> of your <font color=\"#66cc00\">Maximum Armor</font> back at the end of each wave."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BargainHunter'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BargainHunter_Deluxe'

	Name="Default__ZTUpgrade_Skill_BargainHunter"
}
