// ===================================================================
// ZTUpgrade_Skill_Inferno - Active ability: ignite all enemies in line of sight
// Standard: 60 second cooldown
// Deluxe: 45 second cooldown, +50% fire damage
// ===================================================================
class ZTUpgrade_Skill_Inferno extends ZTUpgrade_Skill config(ZedternalUnlimited);

// Store cooldown values in defaultproperties
var config array<float> Cooldowns;
var config array<float> FireDamageBonuses;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Cooldowns[0] = 60.0f;
		default.Cooldowns[1] = 45.0f;
		default.FireDamageBonuses[0] = 0.0f;
		default.FireDamageBonuses[1] = 0.5f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Cooldowns.Length = 2;
		default.Cooldowns[0] = 60.000000f;
		default.Cooldowns[1] = 45.000000f;
		default.FireDamageBonuses.Length = 2;
		default.FireDamageBonuses[0] = 0.000000f;
		default.FireDamageBonuses[1] = 0.500000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// Fire damage bonus while Inferno is recharging (Deluxe). Implements the
// described mechanic: after casting, all fire-type damage the player deals
// is boosted for the duration of the cooldown. Bonus values are
// config-driven ([ZedternalTempered.ZTUpgrade_Skill_Inferno]
// FireDamageBonuses, index 0 = standard, 1 = deluxe; standard seeds 0.0).
static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local ZTUpgrade_Skill_Inferno_Helper Helper;
	local float Bonus;
	
	if (DamageInstigator == None || DamageInstigator.Pawn == None || DamageType == None)
		return;
	
	if (!ClassIsChildOf(DamageType, class'KFDT_Fire'))
		return;
	
	Bonus = default.FireDamageBonuses[Clamp(upgLevel, 1, default.FireDamageBonuses.Length) - 1];
	if (Bonus <= 0.0f)
		return;
	
	Helper = GetHelper(DamageInstigator.Pawn);
	if (Helper != None && Helper.bOnCooldown)
	{
		InDamage += Round(float(DefaultDamage) * Bonus);
	}
}

// Find the existing helper on a pawn (no spawn - the helper only exists
// while the skill is owned and registered).
static function ZTUpgrade_Skill_Inferno_Helper GetHelper(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_Inferno_Helper Helper;
	
	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Inferno_Helper', Helper)
		{
			return Helper;
		}
	}
	
	return None;
}

// Called when skill is purchased - spawn the helper
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_Inferno_Helper Helper;
	local ZTPlayerController DKPC;
	local bool bFound;
	
	if (KFPawn_Human(OwnerPawn) == None || OwnerPawn.Role != Role_Authority)
		return;
	
	DKPC = ZTPlayerController(OwnerPawn.Controller);
	if (DKPC == None)
	{
		`log("ZTUpgrade_Skill_Inferno: ERROR - Player does not have ZTPlayerController!");
		return;
	}
	
	// Check if helper already exists
	bFound = false;
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Inferno_Helper', Helper)
	{
		bFound = true;
		// Update to new tier if upgrading Standard -> Deluxe
		Helper.SetTier(upgLevel);
		`log("ZTUpgrade_Skill_Inferno: Updated existing helper to tier" @ upgLevel);
		break;
	}
	
	// Spawn new helper if not found
	if (!bFound)
	{
		Helper = OwnerPawn.Spawn(class'ZTUpgrade_Skill_Inferno_Helper', OwnerPawn);
		if (Helper != None)
		{
			Helper.Initialize(upgLevel, KFPawn_Human(OwnerPawn), DKPC);
			`log("ZTUpgrade_Skill_Inferno: Spawned helper for" @ OwnerPawn.PlayerReplicationInfo.PlayerName);
		}
		else
		{
			`log("ZTUpgrade_Skill_Inferno: ERROR - Failed to spawn helper!");
		}
	}
}

// Called when skill is removed - cleanup
static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_Inferno_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Inferno_Helper', Helper)
	{
		Helper.Cleanup();
		Helper.Destroy();
		`log("ZTUpgrade_Skill_Inferno: Cleaned up helper");
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Inferno]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Inferno"

	// Cooldown values stored in defaultproperties
	
	// Fire damage bonuses during Inferno
	
	UpgradeName="Inferno"
	
	upgradeDescription(0)="Unlocks <font color=\"#FF6400\">Inferno</font> active ability: Instantly set <font color=\"#FFB464\">all enemies in line of sight</font> on fire with a powerful DoT effect. Cooldown: <font color=\"#FF9900\">60 seconds</font>."
	
	upgradeDescription(1)="Unlocks <font color=\"#FF6400\">Inferno (Deluxe)</font> active ability: Instantly set <font color=\"#FFB464\">all enemies in line of sight</font> on fire with a powerful DoT effect. <font color=\"#FFFFFF\">+50%</font> fire damage while on cooldown. Cooldown: <font color=\"#FF9900\">45 seconds</font>."
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Inferno'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Inferno_Deluxe'
	
	Name="Default__ZTUpgrade_Skill_Inferno"
}
