class ZTUpgrade_Skill_DeadeyeMomentum extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> DamagePerStack;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamagePerStack[0] = 0.10f;
		default.DamagePerStack[1] = 0.20f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.DamagePerStack.Length = 2;
		default.DamagePerStack[0] = 0.050000f;
		default.DamagePerStack[1] = 0.100000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local ZTUpgrade_Skill_DeadeyeMomentum_Helper UPG;

	if (DamageInstigator != None && DamageInstigator.Pawn != None && MyKFPM != None)
	{
		UPG = GetHelper(KFPawn(DamageInstigator.Pawn));
		if (UPG != None)
		{
			// Apply current streak bonus
			if (UPG.Streak > 0)
				InDamage += Round(float(DefaultDamage) * default.DamagePerStack[upgLevel - 1] * float(UPG.Streak));

			// On kill: headshot increments streak, body shot resets it
			if ((MyKFPM.Health - InDamage) <= 0)
			{
				if (HitZoneIdx == HZI_HEAD)
					UPG.IncreaseCounter();
				else
					UPG.ResetCounter();
			}
		}
	}
}

static function ZTUpgrade_Skill_DeadeyeMomentum_Helper GetHelper(KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_DeadeyeMomentum_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_DeadeyeMomentum_Helper', UPG)
		{
			return UPG;
		}

		//Should have one
		UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_DeadeyeMomentum_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_DeadeyeMomentum_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_DeadeyeMomentum_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_DeadeyeMomentum]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_DeadeyeMomentum"

	UpgradeName="Deadeye Momentum"
	upgradeDescription(0)="Consecutive <font color=\"#66cc00\">Headshot Kills</font> grant <font color=\"#ff3399\">+5%</font> <font color=\"#66cc00\">Damage</font> per stack (max 5). <font color=\"#be4d25\">Non-headshot kills reset the streak</font>."
	upgradeDescription(1)="Consecutive <font color=\"#66cc00\">Headshot Kills</font> grant <font color=\"#ff3399\">+10%</font> <font color=\"#66cc00\">Damage</font> per stack (max 5). <font color=\"#be4d25\">Non-headshot kills reset the streak</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_DeadeyeMomentum'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_DeadeyeMomentum_Deluxe'
	Name="Default__ZTUpgrade_Skill_DeadeyeMomentum"
}
