class ZTUpgrade_Skill_HarshConditions extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> Chill;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Chill[0] = 0.25f;
		default.Chill[1] = 0.50f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Chill.Length = 2;
		default.Chill[0] = 0.150000f;
		default.Chill[1] = 0.300000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifySnarePower(out float InSnarePower, float DefaultSnarePower, int upgLevel, optional class<DamageType> DamageType, optional byte BodyPart)
{
	if (ClassIsChildOf(DamageType, class'KFDT_Freeze'))
	{
		InSnarePower += ((DefaultSnarePower) * default.Chill[upgLevel -1]);
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_HarshConditions]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_HarshConditions"

    UpgradeName="Harsh Conditions"
	upgradeDescription(0)="<font color=\"#0bf1f1\">Freeze Damage</font> slows ZEDs by <font color=\"#15d7fa\">25%</font>."
	upgradeDescription(1)="<font color=\"#0bf1f1\">Freeze Damage</font> slows ZEDs by <font color=\"#15d7fa\">50%</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HarshConditions'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HarshConditions_Deluxe'

	Name="Default__ZTUpgrade_Skill_HarshConditions"
}