class ZTUpgrade_Skill_Shifter extends ZTUpgrade_Skill;

static simulated function GetZedTimeExtension(out float InExtension, float DefaultExtension, int upgLevel)
{
    InExtension += float(Min(int(DefaultExtension * float(upgLevel * 10)), 40));
    //return;    
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Shifter]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Shifter"

    UpgradeName="Shifter"
	upgradeDescription(0)="You can extend <font color=\"#15d7fa\">ZED Time</font> <font color=\"#77d914\">10</font> additional times."
	upgradeDescription(1)="You can extend <font color=\"#15d7fa\">ZED Time</font> <font color=\"#77d914\">20</font> additional times."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Shifter'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Shifter_Deluxe'

	Name="Default__ZTUpgrade_Skill_Shifter"
}

