class ZTUpgrade_Skill_SymbioticEfficiency extends ZTUpgrade_Skill abstract config(ZedternalUnlimited);

var config array<float> ReloadBonus;
var config array<float> SwitchSpeedBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ReloadBonus[0] = 0.25f;
		default.ReloadBonus[1] = 0.40f;
		default.SwitchSpeedBonus[0] = 0.30f;
		default.SwitchSpeedBonus[1] = 0.50f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.ReloadBonus.Length = 2;
		default.ReloadBonus[0] = 0.125000f;
		default.ReloadBonus[1] = 0.200000f;
		default.SwitchSpeedBonus.Length = 2;
		default.SwitchSpeedBonus[0] = 0.300000f;
		default.SwitchSpeedBonus[1] = 0.500000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function GetReloadRateScale(out float InReloadRateScale, int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	// BUGFIX: InReloadRateScale is a TIME scale (smaller = faster). The old
	// code multiplied it UP, making reloads 25/40% SLOWER. Composed
	// harmonically like ZR's own reload skills.
	InReloadRateScale = 1.0f / (1.0f / InReloadRateScale + default.ReloadBonus[upgLevel - 1]);
}

static simulated function ModifyWeaponSwitchTime(out float InSwitchTime, float DefaultSwitchTime, int upgLevel, KFWeapon KFW)
{
	// BUGFIX: previously overwrote from DefaultSwitchTime, discarding every
	// other switch speed contributor. Divide the incoming value instead.
	InSwitchTime /= (1.0f + default.SwitchSpeedBonus[upgLevel - 1]);
}

defaultproperties
{
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_SymbioticEfficiency]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_SymbioticEfficiency"

	UpgradeName="Symbiotic Efficiency"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SymbioticEfficiency'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SymbioticEfficiency_Deluxe'
	UpgradeDescription(0)="The symbiote optimizes muscle memory and reflexes. <font color='#00FF7F'>12.5%</font> <font color='#9370DB'>reload speed</font> and <font color='#00FF7F'>30%</font> <font color='#9370DB'>weapon switch speed</font>."
	UpgradeDescription(1)="The symbiote maximizes muscle memory and reflexes. <font color='#00FF7F'>20%</font> <font color='#9370DB'>reload speed</font> and <font color='#00FF7F'>50%</font> <font color='#9370DB'>weapon switch speed</font>."
	
	Name="Default__ZTUpgrade_Skill_SymbioticEfficiency"
}