class ZTUpgrade_Skill_Fanatic extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<int> ExtraGrenades;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ExtraGrenades[0] = 5;
		default.ExtraGrenades[1] = 10;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.ExtraGrenades.Length = 2;
		default.ExtraGrenades[0] = 5;
		default.ExtraGrenades[1] = 10;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function ModifySpareGrenadeAmount(out int SpareGrenade, int DefaultSpareGrenade, int upgLevel)
{
	SpareGrenade += default.ExtraGrenades[upgLevel - 1];
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Fanatic]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Fanatic"

    upgradeName="Fanatic"
	upgradeDescription(0)="Increase <font color=\"#ff3399\">grenade capacity</font> by <font color=\"#66cc00\">5</font>."
	upgradeDescription(1)="Increase <font color=\"#ff3399\">grenade capacity</font> by <font color=\"#66cc00\">10</font>."
	upgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Fanatic'
	upgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Fanatic_Deluxe'

	Name="Default__ZTUpgrade_Skill_Fanatic"
}