class ZTUpgrade_Skill_BloodRush extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> Health;
var config array<float> RateOfFire;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Health[0] = 0.05f;
		default.Health[1] = 0.10f;
		default.RateOfFire[0] = 0.50f;
		default.RateOfFire[1] = 1.00f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Health.Length = 2;
		default.Health[0] = 0.300000f;
		default.Health[1] = 0.500000f;
		default.RateOfFire.Length = 2;
		default.RateOfFire[0] = 0.300000f;
		default.RateOfFire[1] = 0.500000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}



static function ModifyHealth(out int InHealth, int DefaultHealth, int upgLevel)
{
	InHealth -= (DefaultHealth * default.Health[upgLevel - 1]);
}

static simulated function ModifyRateOfFirePassive(out float rateOfFireFactor, int upgLevel)
{
	rateOfFireFactor = 1.0f / (1.0f / rateOfFireFactor + default.RateOfFire[upgLevel - 1]);
}

static simulated function ModifyMeleeAttackSpeedPassive(out float durationFactor, int upgLevel)
{
	durationFactor = 1.0f / (1.0f / durationFactor + default.RateOfFire[upgLevel - 1]);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_BloodRush]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_BloodRush"

    UpgradeName="Soul Stealer"
    upgradeDescription(0)="<font color=\"#962ab9\">Decrease</font> your <font color=\"#962ab9\">Maximum Health</font> by <font color=\"#cb1b43\">30</font>. Increase your <font color=\"#42e087\">Fire Rate</font> by <font color=\"#84d6d0\">30%</font> for all weapons."
    upgradeDescription(1)="<font color=\"#962ab9\">Decrease</font> your <font color=\"#962ab9\">Maximum Health</font> by <font color=\"#cb1b43\">50</font>. Increase your <font color=\"#42e087\">Fire Rate</font> by <font color=\"#84d6d0\">50%</font> for all weapons."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BloodRush'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BloodRush_Deluxe'
	Name="Default__ZTUpgrade_Skill_BloodRush" 
}