// ===================================================================
// ZTUpgrade_Skill_Overforge — Artificer Skill
//
// "Hits build Forge Heat stacks. At 10 stacks, your next hit
//  releases an Overforged Strike for massive bonus damage.
//  Switching weapons resets stacks."
//
// Works with ALL weapons.
//
// Normal:  10 hits → Overforged Strike = +100% bonus damage
// Deluxe:  10 hits → Overforged Strike = +200% bonus damage
//
// Hook: ModifyDamageGiven
// Helper: ZTUpgrade_Skill_Overforge_Helper (tracks hit stacks)
// ===================================================================
class ZTUpgrade_Skill_Overforge extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config int StackThreshold;
var config array<float> BurstDamage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.StackThreshold = 10;
		default.BurstDamage[0] = 1.00f;
		default.BurstDamage[1] = 2.00f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.StackThreshold = 10;
		default.BurstDamage.Length = 2;
		default.BurstDamage[0] = 1.000000f;
		default.BurstDamage[1] = 2.000000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local ZTUpgrade_Skill_Overforge_Helper H;

    if (DamageInstigator == None || DamageInstigator.Pawn == None || MyKFPM == None || MyKFW == None)
        return;

    H = GetHelper(DamageInstigator.Pawn, upgLevel);
    if (H == None)
        return;

    H.OnHit(MyKFW, InDamage, DefaultDamage, upgLevel);
}

// ===================================================================
// HELPER MANAGEMENT
// ===================================================================

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == ROLE_Authority)
        GetHelper(OwnerPawn, upgLevel);
}

static function ZTUpgrade_Skill_Overforge_Helper GetHelper(Pawn OwnerPawn, int upgLevel)
{
    local ZTUpgrade_Skill_Overforge_Helper H;

    if (KFPawn_Human(OwnerPawn) == None)
        return None;

    foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Overforge_Helper', H)
    {
        H.UpgradeLevel = upgLevel;
        return H;
    }

    // Spawn if not found
    if (OwnerPawn.Role == ROLE_Authority)
    {
        H = OwnerPawn.Spawn(class'ZTUpgrade_Skill_Overforge_Helper', OwnerPawn);
        if (H != None)
            H.UpgradeLevel = upgLevel;
    }

    return H;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_Overforge_Helper H;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Overforge_Helper', H)
        {
            H.Destroy();
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Overforge]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Overforge"

    UpgradeName="Overforge"
    UpgradeDescription(0)="Hits build <font color=\"#FFD700\">Forge Heat</font>. At <font color=\"#FFFFFF\">10 stacks</font>, deal <font color=\"#FFFFFF\">+100%</font> <font color=\"#FFD700\">Overforged Strike</font> damage"
    UpgradeDescription(1)="Hits build <font color=\"#FFD700\">Forge Heat</font>. At <font color=\"#FFFFFF\">10 stacks</font>, deal <font color=\"#FFFFFF\">+200%</font> <font color=\"#FFD700\">Overforged Strike</font> damage"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Overforge'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Overforge_Deluxe'

    Name="Default__ZTUpgrade_Skill_Overforge"
}
