// ===================================================================
// ZTUpgrade_Skill_BioelectricDischarge
// When the last round leaves the chamber, the hivemind channels
// accumulated bioelectric potential through the host's nervous
// system - releasing a devastating pulse that fries everything
// within arm's reach.
//
// Normal: Empty magazine triggers 5m electric pulse (50 damage)
//         10 second cooldown
// Deluxe: Empty magazine triggers 5m electric pulse (100 damage)
//         8 second cooldown
// ===================================================================
class ZTUpgrade_Skill_BioelectricDischarge extends ZTUpgrade_Skill;

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_BioelectricDischarge_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_BioelectricDischarge_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
		{
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_BioelectricDischarge_Helper', OwnerPawn);
			UPG.bDeluxe = (upgLevel > 1);
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_BioelectricDischarge_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_BioelectricDischarge_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_BioelectricDischarge]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_BioelectricDischarge"

	UpgradeName="Bioelectric Discharge"
	UpgradeDescription(0)="When your <font color=\"#FFFFFF\">magazine empties</font>, release a <font color=\"#15d7fa\">5m electric pulse</font> dealing <font color=\"#FFD700\">50 damage</font>. Cooldown: <font color=\"#FFFFFF\">10 seconds</font>."
	UpgradeDescription(1)="When your <font color=\"#FFFFFF\">magazine empties</font>, release a <font color=\"#15d7fa\">5m electric pulse</font> dealing <font color=\"#FFD700\">100 damage</font>. Cooldown: <font color=\"#FFFFFF\">8 seconds</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BioelectricDischarge'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BioelectricDischarge_Deluxe'

	Name="Default__ZTUpgrade_Skill_BioelectricDischarge"
}
