class ZTUpgrade_Skill_SoulChain extends ZTUpgrade_Skill config(ZedternalUnlimited);

// Soul Chain: Consecutive kills within a short window grant escalating damage bonuses.
// Each kill adds a stacking damage multiplier. All stacks reset after a few seconds of no kills.

var config array<float> DamagePerStack;
var config array<int> MaxStacks;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamagePerStack[0] = 0.05f;
		default.DamagePerStack[1] = 0.08f;
		default.MaxStacks[0] = 5;
		default.MaxStacks[1] = 8;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.DamagePerStack.Length = 2;
		default.DamagePerStack[0] = 0.050000f;
		default.DamagePerStack[1] = 0.080000f;
		default.MaxStacks.Length = 2;
		default.MaxStacks[0] = 5;
		default.MaxStacks[1] = 8;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local ZTUpgrade_Skill_SoulChain_Helper UPG;

	if (DamageInstigator != None && DamageInstigator.Pawn != None)
	{
		UPG = GetHelper(KFPawn(DamageInstigator.Pawn));
		if (UPG != None && UPG.CurrentStacks > 0)
			InDamage += Round(float(DefaultDamage) * default.DamagePerStack[upgLevel - 1] * UPG.CurrentStacks);
	}
}

static function AddVampireHealth(out int InHealth, int DefaultHealth, int upgLevel, KFPlayerController KFPC, class<DamageType> DT)
{
	local ZTUpgrade_Skill_SoulChain_Helper UPG;

	if (KFPC != None && KFPC.Pawn != None)
	{
		UPG = GetHelper(KFPawn(KFPC.Pawn));
		if (UPG != None)
			UPG.AddStack(default.MaxStacks[upgLevel - 1]);
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_SoulChain_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_SoulChain_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_SoulChain_Helper', OwnerPawn);
	}
}

static function ZTUpgrade_Skill_SoulChain_Helper GetHelper(KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_SoulChain_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_SoulChain_Helper', UPG)
		{
			return UPG;
		}

		UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_SoulChain_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_SoulChain_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_SoulChain_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_SoulChain]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_SoulChain"

	UpgradeName="Soul Chain"
	UpgradeDescription(0)="<font color=\"#CC0000\">Soul Chain:</font> Each kill within <font color=\"#FFAA00\">5 seconds</font> adds a stack. <font color=\"#FFFFFF\">+5%</font> <font color=\"#FF6666\">damage per stack</font> (max <font color=\"#FFFFFF\">5</font> stacks). Stacks reset after <font color=\"#FFAA00\">5s</font> without a kill."
	UpgradeDescription(1)="<font color=\"#CC0000\">Soul Chain:</font> Each kill within <font color=\"#FFAA00\">5 seconds</font> adds a stack. <font color=\"#FFFFFF\">+8%</font> <font color=\"#FF6666\">damage per stack</font> (max <font color=\"#FFFFFF\">8</font> stacks). Stacks reset after <font color=\"#FFAA00\">5s</font> without a kill."

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SoulChain'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SoulChain_Deluxe'

	Name="Default__ZTUpgrade_Skill_SoulChain"
}
