// ===================================================================
// ZTUpgrade_Skill_Bullseye - Active ability: Perfect Accuracy
// 10 seconds of near-zero recoil, spread, and weapon sway
// Cooldown: 60s after effect ends
// ===================================================================
class ZTUpgrade_Skill_Bullseye extends ZTUpgrade_Skill;

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_Bullseye_Helper Helper;
	local ZTPlayerController DKPC;
	local bool bFound;
	
	if (KFPawn_Human(OwnerPawn) == None || OwnerPawn.Role != Role_Authority)
		return;
	
	DKPC = ZTPlayerController(OwnerPawn.Controller);
	if (DKPC == None)
	{
		`log("[DK_BULLSEYE] ERROR - Player does not have ZTPlayerController!");
		return;
	}
	
	bFound = false;
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Bullseye_Helper', Helper)
	{
		bFound = true;
		Helper.SetTier(upgLevel);
		break;
	}
	
	if (!bFound)
	{
		Helper = OwnerPawn.Spawn(class'ZTUpgrade_Skill_Bullseye_Helper', OwnerPawn);
		if (Helper != None)
			Helper.Initialize(upgLevel, KFPawn_Human(OwnerPawn), DKPC);
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_Bullseye_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Bullseye_Helper', Helper)
	{
		Helper.Cleanup();
		Helper.Destroy();
	}
}

// Force recoil to zero when the active ability is up.
// Setting directly (rather than -= DefaultRecoilModifier) avoids going
// negative when other recoil-reducing skills are also active.
static simulated function ModifyRecoil(out float InRecoilModifier, float DefaultRecoilModifier, int upgLevel, KFWeapon KFW)
{
	local ZTUpgrade_Skill_Bullseye_Helper Helper;
	local KFPawn OwnerPawn;
	
	if (KFW == None)
		return;
	
	OwnerPawn = KFPawn(KFW.Owner);
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Bullseye_Helper', Helper)
	{
		if (Helper != None && Helper.bActive)
			InRecoilModifier = 0.0f;
		break;
	}
}

// Force spread to zero when active. Same rationale as ModifyRecoil.
static simulated function ModifySpread(out float InSpread, float DefaultSpread, int upgLevel, KFWeapon KFW)
{
	local ZTUpgrade_Skill_Bullseye_Helper Helper;
	local KFPawn OwnerPawn;
	
	if (KFW == None)
		return;
	
	OwnerPawn = KFPawn(KFW.Owner);
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Bullseye_Helper', Helper)
	{
		if (Helper != None && Helper.bActive)
			InSpread = 0.0f;
		break;
	}
}

// Greatly increase bob damping for steady aim when active
static simulated function ModifyWeaponBopDamping(out float InBobDamping, float DefaultBobDamping, int upgLevel, KFWeapon KFW)
{
	local ZTUpgrade_Skill_Bullseye_Helper Helper;
	local KFPawn OwnerPawn;
	
	if (KFW == None)
		return;
	
	OwnerPawn = KFPawn(KFW.Owner);
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Bullseye_Helper', Helper)
	{
		if (Helper != None && Helper.bActive)
			InBobDamping += 10.0f;
		break;
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Bullseye]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Bullseye"

	UpgradeName="Bullseye"
	
	upgradeDescription(0)="Unlocks <font color=\"#66cc00\">Bullseye</font> active ability: <font color=\"#00ffff\">PERFECT ACCURACY</font> for <font color=\"#ffaa33\">10 seconds</font>. No recoil, no spread, no weapon sway - your shots go exactly where you aim. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	upgradeDescription(1)="Unlocks <font color=\"#66cc00\">Bullseye</font> active ability: <font color=\"#00ffff\">PERFECT ACCURACY</font> for <font color=\"#ffaa33\">10 seconds</font>. No recoil, no spread, no weapon sway - your shots go exactly where you aim. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Bullseye'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Bullseye_Deluxe'
	
	Name="Default__ZTUpgrade_Skill_Bullseye"
}
