class ZTUpgrade_Skill_AspectOfSurtr extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> Damage;
var config array<float> Armor;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Damage[0] = 0.15f;
		default.Damage[1] = 0.30f;
		default.Armor[0] = 0.20f;
		default.Armor[1] = 0.40f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Damage.Length = 2;
		default.Damage[0] = 0.150000f;
		default.Damage[1] = 0.300000f;
		default.Armor.Length = 2;
		default.Armor[0] = 0.200000f;
		default.Armor[1] = 0.400000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (ClassIsChildOf(DamageType, class'KFDT_Fire'))
	{
      InDamage += Round(float(DefaultDamage) * default.Damage[upgLevel - 1]);
    }
}

static function ModifyArmor(out int MaxArmor, int DefaultArmor, int upgLevel)
{
	MaxArmor += Round(float(DefaultArmor) * default.Armor[upgLevel - 1]);
}


defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_AspectOfSurtr]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_AspectOfSurtr"

    UpgradeName="Aspect of Surtr"
	upgradeDescription(0)="Increase your <font color=\"#e80948\">Damage</font> with <font color=\"#e80948\">Fire</font> effects by <font color=\"#e85009\">15%</font> and your <font color=\"#e80948\">Maximum Armor</font> by <font color=\"#e85009\">20%</font>."
	upgradeDescription(1)="Increase your <font color=\"#e80948\">Damage</font> with <font color=\"#e80948\">Fire</font> effects by <font color=\"#e85009\">30%</font> and your <font color=\"#e80948\">Maximum Armor</font> by <font color=\"#e85009\">40%</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AspectOfSurtr'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AspectOfSurtr_Deluxe'

	Name="Default__ZTUpgrade_Skill_AspectOfSurtr"
}