// ===================================================================
// ZTUpgrade_Skill_ScavengersLuck - Active ability: instant reload + fire rate boost
// Standard: Instant reload + +30% fire rate for 10s
// Deluxe: Instant reload + +50% fire rate for 10s
// Cooldown: 60s after effect ends
// ===================================================================
class ZTUpgrade_Skill_ScavengersLuck extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> FireRateBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.FireRateBonus[0] = 0.3f;
		default.FireRateBonus[1] = 0.5f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.FireRateBonus.Length = 2;
		default.FireRateBonus[0] = 0.300000f;
		default.FireRateBonus[1] = 0.500000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_ScavengersLuck_Helper Helper;
	local ZTPlayerController DKPC;
	local bool bFound;
	
	if (KFPawn_Human(OwnerPawn) == None || OwnerPawn.Role != Role_Authority)
		return;
	
	DKPC = ZTPlayerController(OwnerPawn.Controller);
	if (DKPC == None)
	{
		`log("ZTUpgrade_Skill_ScavengersLuck: ERROR - Player does not have ZTPlayerController!");
		return;
	}
	
	bFound = false;
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_ScavengersLuck_Helper', Helper)
	{
		bFound = true;
		Helper.SetTier(upgLevel);
		`log("ZTUpgrade_Skill_ScavengersLuck: Updated existing helper to tier" @ upgLevel);
		break;
	}
	
	if (!bFound)
	{
		Helper = OwnerPawn.Spawn(class'ZTUpgrade_Skill_ScavengersLuck_Helper', OwnerPawn);
		if (Helper != None)
		{
			Helper.Initialize(upgLevel, KFPawn_Human(OwnerPawn), DKPC);
			`log("ZTUpgrade_Skill_ScavengersLuck: Spawned helper for" @ OwnerPawn.PlayerReplicationInfo.PlayerName);
		}
		else
		{
			`log("ZTUpgrade_Skill_ScavengersLuck: ERROR - Failed to spawn helper!");
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_ScavengersLuck_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_ScavengersLuck_Helper', Helper)
	{
		Helper.Cleanup();
		Helper.Destroy();
		`log("ZTUpgrade_Skill_ScavengersLuck: Cleaned up helper");
	}
}

static simulated function ModifyRateOfFire(out float InRate, float DefaultRate, int upgLevel, KFWeapon KFW)
{
	local ZTUpgrade_Skill_ScavengersLuck_Helper Helper;
	local KFPawn OwnerPawn;
	
	if (KFW == None || KFW.Owner == None)
		return;
	
	OwnerPawn = KFPawn(KFW.Owner);
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_ScavengersLuck_Helper', Helper)
	{
		if (Helper.bActive)
		{
			InRate += DefaultRate * default.FireRateBonus[upgLevel - 1];
		}
		break;
	}
}

defaultproperties
{
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_ScavengersLuck]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_ScavengersLuck"

	UpgradeName="Scavenger's Luck"
	
	upgradeDescription(0)="Unlocks <font color=\"#66cc00\">Scavenger's Luck</font> active ability: <font color=\"#00ffff\">Instant reload</font> + <font color=\"#00ffff\">+30% fire rate</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	upgradeDescription(1)="Unlocks <font color=\"#66cc00\">Scavenger's Luck (Deluxe)</font> active ability: <font color=\"#00ffff\">Instant reload</font> + <font color=\"#00ffff\">+50% fire rate</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ScavengersLuck'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ScavengersLuck_Deluxe'
	
	Name="Default__ZTUpgrade_Skill_ScavengersLuck"
}