class ZTUpgrade_Skill_AthenasWrath extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> DamageBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageBonus[0] = 0.5f;
		default.DamageBonus[1] = 0.75f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.DamageBonus.Length = 2;
		default.DamageBonus[0] = 0.500000f;
		default.DamageBonus[1] = 0.750000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local ZTUpgrade_Skill_AthenasWrath_Helper WrathHelper;
    local bool bShouldGetBonus;
    
    if (DamageInstigator == None || DamageInstigator.Pawn == None || MyKFPM == None) return;
    
    // Get helper to check for revenge targets
    WrathHelper = GetHelper(DamageInstigator.Pawn);
    if (WrathHelper == None) return;
    
    // Check if we should get damage bonus against this enemy
    bShouldGetBonus = WrathHelper.ShouldGetRevengeBonus(MyKFPM, upgLevel);
    
    if (bShouldGetBonus)
    {
        // Apply revenge damage bonus
        InDamage += Round(float(DefaultDamage) * default.DamageBonus[upgLevel - 1]);
    }
}

static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    local ZTUpgrade_Skill_AthenasWrath_Helper WrathHelper;
    local KFPawn_Monster AttackingMonster;
    
    if (OwnerPawn == None || InstigatedBy == None) return;
    
    // Track damage sources for revenge
    AttackingMonster = KFPawn_Monster(InstigatedBy.Pawn);
    if (AttackingMonster != None)
    {
        WrathHelper = GetHelper(OwnerPawn);
        if (WrathHelper != None)
        {
            WrathHelper.TrackAttacker(AttackingMonster, upgLevel);
        }
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local ZTUpgrade_Skill_AthenasWrath_Helper WrathHelper;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_AthenasWrath_Helper', WrathHelper)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            WrathHelper = OwnerPawn.Spawn(class'ZTUpgrade_Skill_AthenasWrath_Helper', OwnerPawn);
            WrathHelper.UpgradeLevel = upgLevel;
        }
    }
}

static function ZTUpgrade_Skill_AthenasWrath_Helper GetHelper(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_AthenasWrath_Helper WrathHelper;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_AthenasWrath_Helper', WrathHelper)
        {
            return WrathHelper;
        }

        // Create one if needed
        WrathHelper = OwnerPawn.Spawn(class'ZTUpgrade_Skill_AthenasWrath_Helper', OwnerPawn);
    }

    return WrathHelper;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_AthenasWrath_Helper WrathHelper;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_AthenasWrath_Helper', WrathHelper)
        {
            WrathHelper.Destroy();
        }
    }
}

defaultproperties
{
    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_AthenasWrath]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_AthenasWrath"

    UpgradeName="Athena's Wrath"
    UpgradeDescription(0)="<font color=\"#8B008B\">Athena's Wrath:</font> Deal <font color=\"#FFFFFF\">+50% damage</font> to enemies that have <font color=\"#FF6666\">damaged you</font> in the last <font color=\"#FFFFFF\">10 seconds</font>."
    UpgradeDescription(1)="<font color=\"#8B008B\">Athena's Wrath (Deluxe):</font> Deal <font color=\"#FFFFFF\">+75% damage</font> to enemies that have <font color=\"#FF6666\">damaged you</font> in the last <font color=\"#FFFFFF\">10 seconds</font> + extends to <font color=\"#FFD700\">enemies of the same type</font>."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AthenasWrath'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AthenasWrath_Deluxe'
    
    Name="Default__ZTUpgrade_Skill_AthenasWrath"
}