class ZTUpgrade_Skill_SymphonyOfSlaughter extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> SpeedBoost;
var config array<float> BoostDuration;
var config int KillsRequired;
var config float KillWindow;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.SpeedBoost[0] = 0.30f;
		default.SpeedBoost[1] = 0.50f;
		default.BoostDuration[0] = 5.0f;
		default.BoostDuration[1] = 8.0f;
		default.KillsRequired = 5;
		default.KillWindow = 10.0f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.SpeedBoost.Length = 2;
		default.SpeedBoost[0] = 0.300000f;
		default.SpeedBoost[1] = 0.500000f;
		default.BoostDuration.Length = 2;
		default.BoostDuration[0] = 5.000000f;
		default.BoostDuration[1] = 8.000000f;
		default.KillsRequired = 5;
		default.KillWindow = 10.000000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local ZTUpgrade_Skill_SymphonyOfSlaughter_Helper UPG;
    
    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;
    
    // Check if this will kill
    if (MyKFPM != None && MyKFPM.IsAliveAndWell() && (MyKFPM.Health - InDamage) <= 0)
    {
        UPG = GetHelper(DamageInstigator.Pawn);
        if (UPG != None)
        {
            UPG.RegisterKill(default.KillsRequired, default.KillWindow, default.SpeedBoost[upgLevel - 1], default.BoostDuration[upgLevel - 1]);
        }
    }
}

static simulated function ModifySpeed(out float InSpeed, float DefaultSpeed, int upgLevel, KFPawn OwnerPawn)
{
    local ZTUpgrade_Skill_SymphonyOfSlaughter_Helper UPG;
    
    if (OwnerPawn == None)
        return;
    
    UPG = GetHelper(OwnerPawn);
    if (UPG != None && UPG.bSpeedBoostActive)
    {
        InSpeed += DefaultSpeed * UPG.CurrentSpeedBoost;
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local ZTUpgrade_Skill_SymphonyOfSlaughter_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_SymphonyOfSlaughter_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_SymphonyOfSlaughter_Helper', OwnerPawn);
        }
    }
}

static function ZTUpgrade_Skill_SymphonyOfSlaughter_Helper GetHelper(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_SymphonyOfSlaughter_Helper UPG;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_SymphonyOfSlaughter_Helper', UPG)
        {
            return UPG;
        }

        // Should have one
        UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_SymphonyOfSlaughter_Helper', OwnerPawn);
    }

    return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_SymphonyOfSlaughter_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_SymphonyOfSlaughter_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_SymphonyOfSlaughter]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_SymphonyOfSlaughter"

    UpgradeName="Symphony of Slaughter"
    upgradeDescription(0)="<font color=\"#ffff00\">5 kills</font> within <font color=\"#aaaaaa\">10 seconds</font> grants <font color=\"#00ffff\">+30% movement speed</font> for <font color=\"#ffff00\">5 seconds</font>."
    upgradeDescription(1)="<font color=\"#ffff00\">5 kills</font> within <font color=\"#aaaaaa\">10 seconds</font> grants <font color=\"#00ffff\">+50% movement speed</font> for <font color=\"#ffff00\">8 seconds</font>."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SymphonyOfSlaughter'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SymphonyOfSlaughter_Deluxe'

    Name="Default__ZTUpgrade_Skill_SymphonyOfSlaughter"
}
