class ZTUpgrade_Weapon_Infiltrator extends ZTUpgrade_Weapon abstract hidecategories(Navigation,Movement,Collision,Navigation,Movement,Collision);

var float Damage;

static function bool IsUpgradeCompatible(Class<KFWeapon> KFD)
{
    return true;
    //return ReturnValue;    
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional Class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    // End:0x62
    if((MyKFPM != none) && KFPawn_ZedFleshpound(MyKFPM) != none)
    {
        InDamage += Round((float(DefaultDamage) * default.Damage) * float(upgLevel));        
    }
    else
        {
          // End:0xBB
          if((MyKFPM != none) && KFPawn_ZedFleshpoundMini(MyKFPM) != none)
        {
            InDamage += Round((float(DefaultDamage) * default.Damage) * float(upgLevel));
        }
		  
		  if((MyKFPM != none) && KFPawn_ZedScrake(MyKFPM) != none)
        {
           InDamage += Round((float(DefaultDamage) * default.Damage) * float(upgLevel));        
        }
           else
      {
        // End:0xBB
        if((MyKFPM != none) && WMPawn_ZedScrake_Tiny(MyKFPM) != none)
        {
            InDamage += Round((float(DefaultDamage) * default.Damage) * float(upgLevel));
        }
      }
    }
	 if((MyKFPM != none) && WMPawn_ZedPatriarch(MyKFPM) != none)
    {
        InDamage += Round((float(DefaultDamage) * default.Damage) * float(upgLevel));        
    }
    else
    {
        // End:0xBE
        if((MyKFPM != none) && WMPawn_ZedFleshpoundKing(MyKFPM) != none)
        {
            InDamage += Round((float(DefaultDamage) * default.Damage) * float(upgLevel));            
        }
        else
        {
            // End:0x11A
            if((MyKFPM != none) && WMPawn_ZedBloatKing(MyKFPM) != none)
            {
                InDamage += Round((float(DefaultDamage) * default.Damage) * float(upgLevel));                
            }
            else
            {
                // End:0x173
                if((MyKFPM != none) && WMPawn_ZedHans(MyKFPM) != none)
                {
                    InDamage += Round((float(DefaultDamage) * default.Damage) * float(upgLevel));
                }
            }
        }
    }
    //return;    
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Weapon_Infiltrator]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Weapon_Infiltrator"

    Damage=0.10000000
    WeaponBonus=(incValue=10,MaxValue=-1)
    upgradeName="Infiltrator"
    upgradeDescription(0)="Deals <font color=\"#77d914\">+%x%%</font> additional damage to <font color=\"#15d7fa\">Fleshpounds, Scrakes, and bosses</font> per level."
}