// ===================================================================
// ZTUpgrade_Skill_RaiseTheStakes - Gambit Skill
//
// "Raise the Stakes" - All gambit targets are increased, but all
// rewards are doubled.
//
// Standard: Targets +50%, rewards 2x.
// Deluxe:   Targets only +25%, rewards still 2x.
//
// Pure signal skill -- all logic lives in the Gambit Helper.
// ===================================================================
class ZTUpgrade_Skill_RaiseTheStakes extends ZTUpgrade_Skill;

// Signal presence to Gambit Helper via ExtensionFuncInteger
// Returns upgLevel (1=standard, 2=deluxe) when queried with "GambitRaiseTheStakes"
static simulated function ExtensionFuncInteger(out int InValue, int DefaultValue, int upgLevel, string Identifier,
    KFWeapon MyKFW, KFPawn OwnerPawn, optional int InputInt, optional float InputFloat, optional name InputClassName,
    optional Object InputObject1, optional Object InputObject2, optional Object InputObject3)
{
    if (Identifier ~= "GambitRaiseTheStakes")
        InValue = upgLevel;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_RaiseTheStakes]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_RaiseTheStakes"

    UpgradeName="Raise the Stakes"
    upgradeDescription(0)="All gambit targets are increased by <font color=\"#FF4444\">50%</font>, but all rewards are <font color=\"#FFD700\">doubled</font>."
    upgradeDescription(1)="All gambit targets are increased by only <font color=\"#FF4444\">25%</font>, but all rewards are <font color=\"#FFD700\">doubled</font>."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_RaiseTheStakes'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_RaiseTheStakes_Deluxe'

    Name="Default__ZTUpgrade_Skill_RaiseTheStakes"
}
