// ===================================================================
// ZTUpgrade_Skill_TheHouseAlwaysWins - Gambit Skill
//
// "The House Always Wins" - Each failed gambit reduces the next
// gambit's target by 20%, stacking up to a cap.
// Completing a gambit resets failure stacks to 0.
//
// Standard: Stacks up to 3x (60% easier).
// Deluxe:   Stacks up to 5x (100% easier -- guaranteed freebie).
//
// Pure signal skill -- all logic lives in the Gambit Helper.
// ===================================================================
class ZTUpgrade_Skill_TheHouseAlwaysWins extends ZTUpgrade_Skill;

// Signal presence to Gambit Helper via ExtensionFuncInteger
// Returns upgLevel (1=standard, 2=deluxe) when queried with "GambitHouseWins"
static simulated function ExtensionFuncInteger(out int InValue, int DefaultValue, int upgLevel, string Identifier,
    KFWeapon MyKFW, KFPawn OwnerPawn, optional int InputInt, optional float InputFloat, optional name InputClassName,
    optional Object InputObject1, optional Object InputObject2, optional Object InputObject3)
{
    if (Identifier ~= "GambitHouseWins")
        InValue = upgLevel;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_TheHouseAlwaysWins]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_TheHouseAlwaysWins"

    UpgradeName="The House Always Wins"
    upgradeDescription(0)="Each failed gambit reduces the next gambit's target by <font color=\"#FFD700\">20%</font>, stacking up to <font color=\"#FFFFFF\">3x</font> (<font color=\"#FFD700\">60%</font> easier)."
    upgradeDescription(1)="Each failed gambit reduces the next gambit's target by <font color=\"#FFD700\">20%</font>, stacking up to <font color=\"#FFFFFF\">5x</font> (<font color=\"#FFD700\">100%</font> easier)."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_TheHouseAlwaysWins'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_TheHouseAlwaysWins_Deluxe'

    Name="Default__ZTUpgrade_Skill_TheHouseAlwaysWins"
}
