// ===================================================================
// ZTUpgrade_Skill_ApexMark - The Boss's Blessing
//
// When you kill a Boss, ALL zeds have 100% trophy drop rate
// for a limited duration.
// Normal: 3 seconds | Deluxe: 5 seconds
//
// Boss kill → harvest window on surrounding trash.
// ===================================================================
class ZTUpgrade_Skill_ApexMark extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> Duration;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Duration[0] = 3.0f;
		default.Duration[1] = 5.0f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Duration.Length = 2;
		default.Duration[0] = 3.000000f;
		default.Duration[1] = 5.000000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local ZTUpgrade_Perk_Predator_Helper H;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        H = class'ZTUpgrade_Perk_Predator'.static.GetHelper(OwnerPawn);
        if (H != None)
        {
            H.SkillApexMarkDuration = default.Duration[upgLevel - 1];
            `log("[DK_PREDATOR] ApexMark: Boss kill = 100% drops for" @ H.SkillApexMarkDuration @ "seconds");
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_ApexMark]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_ApexMark"

    UpgradeName="Apex Mark"
    UpgradeDescription(0)="<font color=\"#FFD700\">Apex Mark:</font> Killing a <font color=\"#FF6666\">Boss</font> grants <font color=\"#FFFFFF\">100%</font> trophy drop rate on all zeds for <font color=\"#87CEEB\">3</font> seconds"
    UpgradeDescription(1)="<font color=\"#FFD700\">Apex Mark:</font> Killing a <font color=\"#FF6666\">Boss</font> grants <font color=\"#FFFFFF\">100%</font> trophy drop rate on all zeds for <font color=\"#87CEEB\">5</font> seconds"
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ApexMark'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ApexMark_Deluxe'

    Name="Default__ZTUpgrade_Skill_ApexMark"
}
