class ZTUpgrade_Skill_ChainFeed extends ZTUpgrade_Skill config(ZedternalUnlimited);

// Kills add +1 round directly to your current magazine, even beyond normal capacity
// Cap at 1.5x / 2.0x magazine capacity
// Rewards kill streaks with extended magazines - no spare ammo consumed

var config array<float> MagCapMultiplier;  // Maximum magazine multiplier (1.5x / 2.0x)
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MagCapMultiplier[0] = 1.5f;
		default.MagCapMultiplier[1] = 2.0f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.MagCapMultiplier.Length = 2;
		default.MagCapMultiplier[0] = 1.500000f;
		default.MagCapMultiplier[1] = 2.000000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function AddVampireHealth(out int InHealth, int DefaultHealth, int upgLevel, KFPlayerController KFPC, class<DamageType> DT)
{
	local ZTUpgrade_Skill_ChainFeed_Helper UPG;

	if (KFPC != None && KFPC.Pawn != None)
	{
		UPG = GetHelper(KFPC.Pawn);
		if (UPG != None)
		{
			if (UPG.Player.WorldInfo.NetMode == NM_Standalone)
				UPG.StandaloneAddAmmo(default.MagCapMultiplier[upgLevel - 1]);
			else
				UPG.ServerAddAmmo(default.MagCapMultiplier[upgLevel - 1]);
		}
	}
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_ChainFeed_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_ChainFeed_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_ChainFeed_Helper', OwnerPawn);
	}
}

static function ZTUpgrade_Skill_ChainFeed_Helper GetHelper(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_ChainFeed_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_ChainFeed_Helper', UPG)
		{
			return UPG;
		}

		// Should have one
		UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_ChainFeed_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_ChainFeed_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_ChainFeed_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_ChainFeed]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_ChainFeed"

	UpgradeName="Chain Feed"

	UpgradeDescription(0)="<font color=\"#DAA520\">Chain Feed:</font> Kills add <font color=\"#87CEEB\">+1 round</font> to your magazine, even <font color=\"#FFFFFF\">beyond capacity</font>. Max <font color=\"#FF4444\">150%</font> magazine"
	UpgradeDescription(1)="<font color=\"#FFD700\">Chain Feed:</font> Kills add <font color=\"#87CEEB\">+1 round</font> to your magazine, even <font color=\"#FFFFFF\">beyond capacity</font>. Max <font color=\"#FF4444\">200%</font> magazine"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ChainFeed'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ChainFeed_Deluxe'

	Name="Default__ZTUpgrade_Skill_ChainFeed"
}
