// ===================================================================
// ZTUpgrade_Skill_Bluff - Gambit Skill
//
// "Bluff" - When you would take fatal damage while a gambit is active,
// instead survive at 1 HP. The gambit is forfeited (no reward).
// Has a long cooldown.
//
// Standard: 90 second cooldown.
// Deluxe:   45 second cooldown + 2 seconds of damage immunity after trigger.
//
// ExtensionFuncInteger signals to helper (TriggerBluff checks level).
// ModifyDamageTaken intercepts lethal damage.
// ===================================================================
class ZTUpgrade_Skill_Bluff extends ZTUpgrade_Skill;

// ===================================================================
// SIGNAL -- Tell helper this skill is active
// ===================================================================

static simulated function ExtensionFuncInteger(out int InValue, int DefaultValue, int upgLevel, string Identifier,
    KFWeapon MyKFW, KFPawn OwnerPawn, optional int InputInt, optional float InputFloat, optional name InputClassName,
    optional Object InputObject1, optional Object InputObject2, optional Object InputObject3)
{
    if (Identifier ~= "GambitBluff")
        InValue = upgLevel;
}

// ===================================================================
// DAMAGE TAKEN -- Intercept lethal damage
// ===================================================================

static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel,
    KFPawn OwnerPawn, optional class<DamageType> DamageType,
    optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    local ZTUpgrade_Perk_Gambit_Helper H;

    if (OwnerPawn == None || InDamage <= 0)
        return;

    H = class'ZTUpgrade_Perk_Gambit'.static.GetHelper(OwnerPawn);
    if (H == None)
        return;

    // Deluxe: check for post-trigger damage immunity
    if (H.IsBluffImmune())
    {
        InDamage = 0;
        return;
    }

    // Check if this hit would be lethal
    if (InDamage >= OwnerPawn.Health)
    {
        // Attempt to trigger Bluff (checks cooldown, active gambit, etc.)
        if (H.TriggerBluff())
        {
            // Survived! Reduce damage to leave player at 1 HP
            InDamage = OwnerPawn.Health - 1;
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Bluff]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Bluff"

    UpgradeName="Bluff"
    upgradeDescription(0)="Survive fatal damage during an active gambit at <font color=\"#FFFFFF\">1 HP</font>. The gambit is forfeited. Cooldown: <font color=\"#FFD700\">90 seconds</font>."
    upgradeDescription(1)="Survive fatal damage during an active gambit at <font color=\"#FFFFFF\">1 HP</font> + <font color=\"#FFD700\">2s immunity</font>. Gambit forfeited. Cooldown: <font color=\"#FFD700\">45 seconds</font>."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Bluff'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Bluff_Deluxe'

    Name="Default__ZTUpgrade_Skill_Bluff"
}
