// ===================================================================
// ZTUpgrade_Skill_SeersFocus
//
// "Seer's Focus"
// While your prophecy is active and not yet failed, gain bonus
// damage and reload speed. The moment you fail, both vanish.
//
// Standard: +12% damage, +12% reload speed
// Deluxe:   +15% damage, +15% reload speed
// ===================================================================
class ZTUpgrade_Skill_SeersFocus extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config float DamageBonus;            // Standard: 12%
var config float DamageBonusDeluxe;      // Deluxe: 15%
var config float ReloadBonus;            // Standard: 12%
var config float ReloadBonusDeluxe;      // Deluxe: 15%
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageBonus = 0.12f;
		default.DamageBonusDeluxe = 0.15f;
		default.ReloadBonus = 0.12f;
		default.ReloadBonusDeluxe = 0.15f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.DamageBonus = 0.120000f;
		default.DamageBonusDeluxe = 0.150000f;
		default.ReloadBonus = 0.060000f;
		default.ReloadBonusDeluxe = 0.075000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
    optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
    optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
    optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local ZTUpgrade_Perk_Omen_Helper OH;

    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;

    foreach DamageInstigator.Pawn.ChildActors(class'ZTUpgrade_Perk_Omen_Helper', OH)
    {
        if (OH.bProphecyActive && !OH.bProphecyFailed)
        {
            if (upgLevel >= 2)
                InDamage += Round(float(DefaultDamage) * default.DamageBonusDeluxe);
            else
                InDamage += Round(float(DefaultDamage) * default.DamageBonus);
        }
        break;
    }
}

static simulated function GetReloadRateScale(out float InReloadRateScale,
    int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local ZTUpgrade_Perk_Omen_Helper OH;

    if (OwnerPawn == None)
        return;

    foreach OwnerPawn.ChildActors(class'ZTUpgrade_Perk_Omen_Helper', OH)
    {
        if (OH.bProphecyActive && !OH.bProphecyFailed)
        {
            if (upgLevel >= 2)
                InReloadRateScale -= default.ReloadBonusDeluxe;
            else
                InReloadRateScale -= default.ReloadBonus;
        }
        break;
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_SeersFocus]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_SeersFocus"

    UpgradeName="Seer's Focus"
    UpgradeDescription(0)="While your <font color=\"#77d914\">prophecy is active</font> and not failed, gain <font color=\"#15d7fa\">+6% damage</font> and <font color=\"#15d7fa\">+6% reload speed</font>."
    UpgradeDescription(1)="While your <font color=\"#77d914\">prophecy is active</font> and not failed, gain <font color=\"#15d7fa\">+7.5% damage</font> and <font color=\"#15d7fa\">+7.5% reload speed</font>."

    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SeersFocus_Deluxe'

    Name="Default__ZTUpgrade_Skill_SeersFocus"
}
