class ZTUpgrade_Skill_AshenBulwark extends ZTUpgrade_Skill config(ZedternalUnlimited);

// Ashen Bulwark: Reduces fire, toxic, and sonic damage taken.
// Standard: -30% fire/toxic/sonic damage taken.
// Deluxe:   -65% fire/toxic/sonic damage taken.

var config array<float> Resistance;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Resistance[0] = 0.3f;
		default.Resistance[1] = 0.65f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Resistance.Length = 2;
		default.Resistance[0] = 0.100000f;
		default.Resistance[1] = 0.200000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	if (DamageType != None)
	{
		if (ClassIsChildOf(DamageType, class'KFDT_Fire') || ClassIsChildOf(DamageType, class'KFDT_Toxic') || ClassIsChildOf(DamageType, class'KFDT_Sonic'))
			InDamage -= Round(float(DefaultDamage) * default.Resistance[upgLevel - 1]);
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_AshenBulwark]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_AshenBulwark"

	UpgradeName="AshenBulwark"
	upgradeDescription(0)="Take <font color=\"#84d6d0\">10%</font> less damage from <font color=\"#42e087\">fire</font>, <font color=\"#42e087\">toxic</font>, and <font color=\"#42e087\">sonic</font> attacks."
	upgradeDescription(1)="Take <font color=\"#84d6d0\">20%</font> less damage from <font color=\"#42e087\">fire</font>, <font color=\"#42e087\">toxic</font>, and <font color=\"#42e087\">sonic</font> attacks."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AshenBulwark'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AshenBulwark_Deluxe'

	Name="Default__ZTUpgrade_Skill_AshenBulwark"
}
