// ===================================================================
// ZTUpgrade_Skill_TwistOfFate
//
// "Twist of Fate"
// When a prophecy completes, flip a coin.
// Heads: reward is DOUBLED. Tails: you get NOTHING (no doom).
//
// Standard: 50/50 chance
// Deluxe:   55/45 chance (favors double)
// ===================================================================
class ZTUpgrade_Skill_TwistOfFate extends ZTUpgrade_Skill;

// --- Helper spawning ---
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local ZTUpgrade_Skill_TwistOfFate_Helper H;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == ROLE_Authority)
    {
        bFound = false;
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_TwistOfFate_Helper', H)
        {
            bFound = true;
            H.Initialize(upgLevel);
            break;
        }

        if (!bFound)
        {
            H = OwnerPawn.Spawn(class'ZTUpgrade_Skill_TwistOfFate_Helper', OwnerPawn);
            if (H != None)
                H.Initialize(upgLevel);
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_TwistOfFate_Helper H;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_TwistOfFate_Helper', H)
        {
            H.Cleanup();
            H.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_TwistOfFate]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_TwistOfFate"

    UpgradeName="Twist of Fate"
    UpgradeDescription(0)="When a prophecy completes, <font color=\"#ebc034\">flip a coin</font>. <font color=\"#15d7fa\">50% chance: reward DOUBLED</font>. <font color=\"#ff0000\">50% chance: NOTHING</font>."
    UpgradeDescription(1)="When a prophecy completes, <font color=\"#ebc034\">flip a coin</font>. <font color=\"#15d7fa\">55% chance: reward DOUBLED</font>. <font color=\"#ff0000\">45% chance: NOTHING</font>."

    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_TwistOfFate_Deluxe'

    Name="Default__ZTUpgrade_Skill_TwistOfFate"
}
