class ZTUpgrade_Skill_HuntersInstinct extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> MarkRadius;
var config array<float> MarkDuration;
var config array<float> DamageBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MarkRadius[0] = 800.0f;
		default.MarkRadius[1] = 1200.0f;
		default.MarkDuration[0] = 6.0f;
		default.MarkDuration[1] = 8.0f;
		default.DamageBonus[0] = 0.30f;
		default.DamageBonus[1] = 0.40f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.MarkRadius.Length = 2;
		default.MarkRadius[0] = 800.000000f;
		default.MarkRadius[1] = 1200.000000f;
		default.MarkDuration.Length = 2;
		default.MarkDuration[0] = 6.000000f;
		default.MarkDuration[1] = 8.000000f;
		default.DamageBonus.Length = 2;
		default.DamageBonus[0] = 0.300000f;
		default.DamageBonus[1] = 0.400000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local ZTUpgrade_Skill_HuntersInstinct_Helper Helper;

    if (MyKFPM == None || DamageInstigator == None || DamageInstigator.Pawn == None)
        return;

    Helper = GetHelper(DamageInstigator.Pawn);
    if (Helper == None)
        return;

    // Marked zeds take bonus damage from ALL sources (any weapon), per
    // description. The old code gated this behind IsRifleWeapon AND a kill
    // check, so the bonus essentially never fired in practice (only on rifle
    // killing blows, and it had no visible effect on a dying zed).
    if (Helper.IsZedMarked(MyKFPM))
    {
        InDamage += Round(float(DefaultDamage) * default.DamageBonus[upgLevel - 1]);
    }

    // Marking only happens on RIFLE kills. Use post-bonus InDamage so the
    // marked-zed bonus itself can be the killing blow that propagates marks.
    if (MyKFW != None && IsRifleWeapon(MyKFW)
        && MyKFPM.IsAliveAndWell() && (MyKFPM.Health - InDamage) <= 0)
    {
        Helper.MarkNearbyZeds(MyKFPM.Location,
            default.MarkRadius[upgLevel - 1],
            default.MarkDuration[upgLevel - 1]);
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    // Helper must exist regardless of currently-equipped weapon, because the
    // damage bonus applies to ALL weapons and is read on every hit. Old code
    // only created the helper when the equipped weapon was a rifle, which
    // meant non-rifle equipped → no helper → bonus never applied.
    if (OwnerPawn != None && OwnerPawn.Role == Role_Authority)
        CreateHelper(OwnerPawn);
}

static function ZTUpgrade_Skill_HuntersInstinct_Helper GetHelper(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_HuntersInstinct_Helper Helper;

    if (OwnerPawn == None)
        return None;

    foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_HuntersInstinct_Helper', Helper)
    {
        return Helper;
    }

    return None;
}

static function ZTUpgrade_Skill_HuntersInstinct_Helper CreateHelper(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_HuntersInstinct_Helper Helper;

    if (OwnerPawn == None)
        return None;

    Helper = GetHelper(OwnerPawn);
    if (Helper == None && OwnerPawn.Role == Role_Authority)
    {
        Helper = OwnerPawn.Spawn(class'ZTUpgrade_Skill_HuntersInstinct_Helper', OwnerPawn);
    }

    return Helper;
}

static function bool IsRifleWeapon(KFWeapon KFW)
{
    if (KFW == None)
        return False;

    // Check if weapon is in the assault rifle category (Commando weapons)
    if (IsWeaponOnSpecificPerk(KFW, class'KFGame.KFPerk_Commando'))
    {
        // Exclude SMGs and other non-rifle weapons by checking damage characteristics
        return (KFW.InstantHitDamage[0] >= 35 ||
                KFW.default.FireInterval[0] >= 0.08);
    }

    // Also include weapons that might be rifle-like but under other categories
    return (InStr(PathName(KFW.Class), "Rifle") != INDEX_NONE ||
            InStr(PathName(KFW.Class), "rifle") != INDEX_NONE);
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_HuntersInstinct_Helper Helper;

    Helper = GetHelper(OwnerPawn);
    if (Helper != None)
    {
        Helper.Destroy();
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_HuntersInstinct]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_HuntersInstinct"

    UpgradeName="Hunter's Instinct"
    UpgradeDescription(0)="Rifle kills mark nearby zeds within <font color=\"#15d7fa\">8 meters</font> for <font color=\"#ff3399\">6 seconds</font>. Marked zeds take <font color=\"#77d914\">+30%</font> damage from all sources."
    UpgradeDescription(1)="Rifle kills mark nearby zeds within <font color=\"#15d7fa\">12 meters</font> for <font color=\"#ff3399\">8 seconds</font>. Marked zeds take <font color=\"#77d914\">+40%</font> damage from all sources."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HuntersInstinct'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HuntersInstinct_Deluxe'
    
    Name="Default__ZTUpgrade_Skill_HuntersInstinct"
}
