// ===================================================================
// ZTUpgrade_Skill_PhantomPain - Damage Echo Time Bomb
// Theme: Accumulated damage during ZED time detonates as AoE on end
// ===================================================================
class ZTUpgrade_Skill_PhantomPain extends ZTUpgrade_Skill;

// Track damage dealt during ZED time via helper
static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
	optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
	optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
	optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local KFPawn OwnerPawn;
	local ZTUpgrade_Skill_PhantomPain_Helper Helper;

	if (DamageInstigator == None || DamageInstigator.Pawn == None)
		return;

	OwnerPawn = KFPawn(DamageInstigator.Pawn);
	if (OwnerPawn == None)
		return;

	// Only accumulate during ZED time
	if (OwnerPawn.WorldInfo.TimeDilation >= 1.0)
		return;

	Helper = GetHelper(OwnerPawn);
	if (Helper != None && MyKFPM != None)
		Helper.AccumulateDamage(InDamage, MyKFPM.Location);
}

// ===================================================================
// Helper Management
// ===================================================================
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_PhantomPain_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_PhantomPain_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
		{
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_PhantomPain_Helper', OwnerPawn);
			if (UPG != None)
				UPG.Initialize(KFPawn_Human(OwnerPawn), upgLevel > 1);
		}
	}
}

static function ZTUpgrade_Skill_PhantomPain_Helper GetHelper(KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_PhantomPain_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_PhantomPain_Helper', UPG)
		{
			return UPG;
		}
	}

	return None;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_PhantomPain_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_PhantomPain_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_PhantomPain]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_PhantomPain"

	UpgradeName="Phantom Pain"
	upgradeDescription(0)="Damage dealt during <font color=\"#9632ff\">ZED Time</font> is accumulated. When ZED Time ends, release <font color=\"#d8b0ff\">10%</font> of accumulated damage as an <font color=\"#FFFFFF\">AoE explosion</font> (10m radius)."
	upgradeDescription(1)="Damage dealt during <font color=\"#9632ff\">ZED Time</font> is accumulated. When ZED Time ends, release <font color=\"#d8b0ff\">20%</font> of accumulated damage as <font color=\"#FFFFFF\">two AoE explosions</font>  one on you, one on the last enemy hit."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PhantomPain'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_PhantomPain_Deluxe'

	Name="Default__ZTUpgrade_Skill_PhantomPain"
}
