class ZTUpgrade_Skill_Timewalk extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> FireRate, SpecialRate;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.FireRate[0] = 0.1f;
		default.FireRate[1] = 0.2f;
		default.SpecialRate[0] = 0.5f;
		default.SpecialRate[1] = 1.0f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.FireRate.Length = 2;
		default.FireRate[0] = 0.100000f;
		default.FireRate[1] = 0.200000f;
		default.SpecialRate.Length = 2;
		default.SpecialRate[0] = 0.250000f;
		default.SpecialRate[1] = 0.500000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function bool IsUnAffectedByZedTime(int upgLevel, KFPawn OwnerPawn)
{
	return True;
}

static simulated function GetZedTimeModifier(out float InModifier, int upgLevel, KFWeapon KFW)
{
	local name StateName;

	if (KFW != None)
	{
		StateName = KFW.GetStateName();
		if (class'ZedternalReborn.WMWeaponStates'.static.IsWeaponAttackState(StateName))
		{
			if (KFWeap_MeleeBase(KFW) != None || KFW.default.MagazineCapacity[0] > 4)
				InModifier += default.FireRate[upgLevel - 1];
			else
				InModifier += default.SpecialRate[upgLevel - 1];
		}
	}
}

static simulated function RevertUpgradeChanges(Pawn OwnerPawn)
{
	if (KFPawn_Human(OwnerPawn) != None)
			KFPawn_Human(OwnerPawn).bMovesFastInZedTime = False;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Timewalk]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Timewalk"

    UpgradeName="Timewalk"
	upgradeDescription(0)="During <font color=\"#15d7fa\">ZED Time</font> you move <font color=\"#77d914\">25%</font> faster."
	upgradeDescription(1)="During <font color=\"#15d7fa\">ZED Time</font> you move <font color=\"#77d914\">50%</font> faster."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Timewalk'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Timewalk_Deluxe'

	Name="Default__ZTUpgrade_Skill_Timewalk"
}

