// ===================================================================
// ZTUpgrade_Skill_ProphetsMomentum
//
// "Prophet's Momentum"
// Each consecutively completed prophecy grants a stacking damage bonus.
// Any doom resets the streak to zero.
//
// Standard: +4% damage per streak
// Deluxe:   +5% damage per streak
// ===================================================================
class ZTUpgrade_Skill_ProphetsMomentum extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config float DamagePerStreak;        // Standard: 4%
var config float DamagePerStreakDeluxe;   // Deluxe: 5%
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamagePerStreak = 0.04f;
		default.DamagePerStreakDeluxe = 0.05f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.DamagePerStreak = 0.040000f;
		default.DamagePerStreakDeluxe = 0.050000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
    optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
    optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
    optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local ZTUpgrade_Skill_ProphetsMomentum_Helper H;
    local float BonusPerStreak;

    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;

    foreach DamageInstigator.Pawn.ChildActors(class'ZTUpgrade_Skill_ProphetsMomentum_Helper', H)
    {
        if (H.StreakCount > 0)
        {
            if (upgLevel >= 2)
                BonusPerStreak = default.DamagePerStreakDeluxe;
            else
                BonusPerStreak = default.DamagePerStreak;

            InDamage += Round(float(DefaultDamage) * BonusPerStreak * float(H.StreakCount));
        }
        break;
    }
}

// --- Helper spawning (standard pattern) ---
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local ZTUpgrade_Skill_ProphetsMomentum_Helper H;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == ROLE_Authority)
    {
        bFound = false;
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_ProphetsMomentum_Helper', H)
        {
            bFound = true;
            H.Initialize(upgLevel);
            break;
        }

        if (!bFound)
        {
            H = OwnerPawn.Spawn(class'ZTUpgrade_Skill_ProphetsMomentum_Helper', OwnerPawn);
            if (H != None)
                H.Initialize(upgLevel);
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_ProphetsMomentum_Helper H;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_ProphetsMomentum_Helper', H)
        {
            H.Cleanup();
            H.Destroy();
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_ProphetsMomentum]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_ProphetsMomentum"

    UpgradeName="Prophet's Momentum"
    UpgradeDescription(0)="Each <font color=\"#77d914\">consecutive prophecy completion</font> grants <font color=\"#15d7fa\">+4% damage</font>. Any doom <font color=\"#ff0000\">resets the streak</font>."
    UpgradeDescription(1)="Each <font color=\"#77d914\">consecutive prophecy completion</font> grants <font color=\"#15d7fa\">+5% damage</font>. Any doom <font color=\"#ff0000\">resets the streak</font>."

    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ProphetsMomentum_Deluxe'

    Name="Default__ZTUpgrade_Skill_ProphetsMomentum"
}
