class ZTUpgrade_Skill_SearingFocus extends ZTUpgrade_Skill config(ZedternalUnlimited);

// Searing Focus: Reduces weapon recoil and spread.
// Standard: -20% recoil, -15% spread.
// Deluxe:   -50% recoil, -40% spread.

var config array<float> Recoil;
var config array<float> Spread;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Recoil[0] = 0.2f;
		default.Recoil[1] = 0.5f;
		default.Spread[0] = 0.15f;
		default.Spread[1] = 0.4f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Recoil.Length = 2;
		default.Recoil[0] = 0.200000f;
		default.Recoil[1] = 0.500000f;
		default.Spread.Length = 2;
		default.Spread[0] = 0.150000f;
		default.Spread[1] = 0.400000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function ModifyRecoil(out float InRecoilModifier, float DefaultRecoilModifier, int upgLevel, KFWeapon KFW)
{
	if (KFW != None)
		InRecoilModifier -= DefaultRecoilModifier * default.Recoil[upgLevel - 1];
}

static simulated function ModifySpread(out float InSpreadModifier, float DefaultSpreadModifier, int upgLevel, KFWeapon KFW)
{
	if (KFW != None)
		InSpreadModifier -= DefaultSpreadModifier * default.Spread[upgLevel - 1];
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_SearingFocus]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_SearingFocus"

	UpgradeName="SearingFocus"
	upgradeDescription(0)="<font color=\"#42e087\">Reduce</font> <font color=\"#42e087\">weapon recoil</font> by <font color=\"#84d6d0\">20%</font> and <font color=\"#42e087\">spread</font> by <font color=\"#84d6d0\">15%</font>."
	upgradeDescription(1)="<font color=\"#42e087\">Reduce</font> <font color=\"#42e087\">weapon recoil</font> by <font color=\"#84d6d0\">50%</font> and <font color=\"#42e087\">spread</font> by <font color=\"#84d6d0\">40%</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SearingFocus'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_SearingFocus_Deluxe'

	Name="Default__ZTUpgrade_Skill_SearingFocus"
}
