class ZTUpgrade_Skill_NarrowEscape extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> Chance;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Chance[0] = 0.01f;
		default.Chance[1] = 0.02f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Chance.Length = 2;
		default.Chance[0] = 0.010000f;
		default.Chance[1] = 0.020000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional Class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	if(FRand() <= (default.Chance[upgLevel - 1]))
		{
		InDamage = 0;
        }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_NarrowEscape]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_NarrowEscape"

    UpgradeName="Narrow Escape"
	upgradeDescription(0)="<font color=\"#ff3399\">Incoming Damage</font> has a <font color=\"#66cc00\">1%</font> chance to be reduced to <font color=\"#be4d25\">0</font>."
	upgradeDescription(1)="<font color=\"#ff3399\">Incoming Damage</font> has a <font color=\"#66cc00\">2%</font> chance to be reduced to <font color=\"#be4d25\">0</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_NarrowEscape'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_NarrowEscape_Deluxe'
    Name="Default__ZTUpgrade_Skill_NarrowEscape"
}