// Venomous Riposte: Taking damage releases a toxic shockwave that poisons nearby ZEDs.
// Has a cooldown between activations.
// Pattern based on ColdRiposte.
class ZTUpgrade_Skill_VenomousRiposte extends ZTUpgrade_Skill;

static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local ZTUpgrade_Skill_VenomousRiposte_Helper UPG;

	if (InDamage > 0)
	{
		UPG = GetHelper(OwnerPawn, upgLevel);
		if (UPG != None && UPG.bReady)
			UPG.PoisonBurst();
	}
}

static function ZTUpgrade_Skill_VenomousRiposte_Helper GetHelper(KFPawn OwnerPawn, int upgLevel)
{
	local ZTUpgrade_Skill_VenomousRiposte_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_VenomousRiposte_Helper', UPG)
		{
			return UPG;
		}

		UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_VenomousRiposte_Helper', OwnerPawn);
		UPG.bDeluxe = (upgLevel > 1);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_VenomousRiposte_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_VenomousRiposte_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_VenomousRiposte]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_VenomousRiposte"

	UpgradeDescription(0)="Taking damage releases a <font color=\"#399c0e\">toxic shockwave</font> that <font color=\"#8fce00\">Poisons</font> nearby ZEDs. <font color=\"#ebd402\">20 second cooldown</font>."
	UpgradeDescription(1)="Taking damage releases a <font color=\"#b346ea\">toxic shockwave</font> that <font color=\"#8fce00\">Poisons</font> nearby ZEDs with <font color=\"#b346ea\">increased range and damage</font>. <font color=\"#ebd402\">20 second cooldown</font>."

	UpgradeName="Venomous Riposte"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_VenomousRiposte'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_VenomousRiposte_Deluxe'

	Name="Default__ZTUpgrade_Skill_VenomousRiposte"
}
