// ===================================================================
// ZTUpgrade_Skill_QuickDraw - Active ability: temporary fire rate boost
// Standard: +40% fire rate for 10s
// Deluxe: +60% fire rate for 10s
// Cooldown: 60s after effect ends
// ===================================================================
class ZTUpgrade_Skill_QuickDraw extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> FireRateBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.FireRateBonus[0] = 0.4f;
		default.FireRateBonus[1] = 0.6f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.FireRateBonus.Length = 2;
		default.FireRateBonus[0] = 0.400000f;
		default.FireRateBonus[1] = 0.600000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_QuickDraw_Helper Helper;
	local ZTPlayerController DKPC;
	local bool bFound;
	
	if (KFPawn_Human(OwnerPawn) == None || OwnerPawn.Role != Role_Authority)
		return;
	
	DKPC = ZTPlayerController(OwnerPawn.Controller);
	if (DKPC == None)
	{
		`log("ZTUpgrade_Skill_QuickDraw: ERROR - Player does not have ZTPlayerController!");
		return;
	}
	
	bFound = false;
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_QuickDraw_Helper', Helper)
	{
		bFound = true;
		Helper.SetTier(upgLevel);
		`log("ZTUpgrade_Skill_QuickDraw: Updated existing helper to tier" @ upgLevel);
		break;
	}
	
	if (!bFound)
	{
		Helper = OwnerPawn.Spawn(class'ZTUpgrade_Skill_QuickDraw_Helper', OwnerPawn);
		if (Helper != None)
		{
			Helper.Initialize(upgLevel, KFPawn_Human(OwnerPawn), DKPC);
			`log("ZTUpgrade_Skill_QuickDraw: Spawned helper for" @ OwnerPawn.PlayerReplicationInfo.PlayerName);
		}
		else
		{
			`log("ZTUpgrade_Skill_QuickDraw: ERROR - Failed to spawn helper!");
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_QuickDraw_Helper Helper;
	
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_QuickDraw_Helper', Helper)
	{
		Helper.Cleanup();
		Helper.Destroy();
		`log("ZTUpgrade_Skill_QuickDraw: Cleaned up helper");
	}
}

static simulated function ModifyRateOfFire(out float InRate, float DefaultRate, int upgLevel, KFWeapon KFW)
{
	local ZTUpgrade_Skill_QuickDraw_Helper Helper;
	local KFPawn OwnerPawn;
	
	if (KFW == None || KFW.Owner == None)
		return;
	
	OwnerPawn = KFPawn(KFW.Owner);
	if (OwnerPawn == None)
		return;
	
	foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_QuickDraw_Helper', Helper)
	{
		if (Helper.bActive)
		{
			InRate += DefaultRate * default.FireRateBonus[upgLevel - 1];
		}
		break;
	}
}

defaultproperties
{
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_QuickDraw]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_QuickDraw"

	UpgradeName="Quick Draw"
	
	upgradeDescription(0)="Unlocks <font color=\"#66cc00\">Quick Draw</font> active ability: <font color=\"#00ffff\">+40% fire rate</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	upgradeDescription(1)="Unlocks <font color=\"#66cc00\">Quick Draw (Deluxe)</font> active ability: <font color=\"#00ffff\">+60% fire rate</font> for <font color=\"#ffaa33\">10 seconds</font>. Cooldown: <font color=\"#ff9900\">60 seconds</font>."
	
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_QuickDraw'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_QuickDraw_Deluxe'
	
	Name="Default__ZTUpgrade_Skill_QuickDraw"
}