// ===================================================================
// ZTUpgrade_Skill_Transfusion - Selfless Vampirism
// Killing a siphoned enemy sends a healing pulse to all teammates
// within range. You push forward and kill for your team's benefit.
//
// Standard: 8 HP heal to teammates within 8m on siphoned kill
// Deluxe:   18 HP heal to teammates within 12m on siphoned kill
//
// REQUIRES: ZTUpgrade_Perk_Parasite_Helper must expose:
//   - IsSiphoned(KFPawn_Monster) : bool
// ===================================================================
class ZTUpgrade_Skill_Transfusion extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<int> TeamHealAmount;
var config array<float> HealRadius;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.TeamHealAmount[0] = 8;
		default.TeamHealAmount[1] = 18;
		default.HealRadius[0] = 800.0f;
		default.HealRadius[1] = 1200.0f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.TeamHealAmount.Length = 2;
		default.TeamHealAmount[0] = 8;
		default.TeamHealAmount[1] = 18;
		default.HealRadius.Length = 2;
		default.HealRadius[0] = 800.000000f;
		default.HealRadius[1] = 1200.000000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// ===================================================================
// On Damage: Detect killing blow on siphoned enemy, heal team
// ===================================================================
static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel,
	optional Actor DamageCauser, optional KFPawn_Monster MyKFPM,
	optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType,
	optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	local ZTUpgrade_Perk_Parasite_Helper ParasiteHelper;
	local KFPawn_Human KFPH;
	local float RadiusSq;

	if (DamageInstigator == None || DamageInstigator.Pawn == None || MyKFPM == None)
		return;

	// Check if this is a killing blow
	if (MyKFPM.Health - InDamage > 0)
		return;

	ParasiteHelper = GetParasiteHelper(DamageInstigator.Pawn);
	if (ParasiteHelper == None)
		return;

	// Only triggers on siphoned enemies
	if (!ParasiteHelper.IsSiphoned(MyKFPM))
		return;

	// Heal all teammates within radius
	RadiusSq = default.HealRadius[upgLevel - 1] ** 2;

	foreach DamageInstigator.Pawn.WorldInfo.AllPawns(class'KFPawn_Human', KFPH)
	{
		// Don't heal self
		if (KFPH == DamageInstigator.Pawn)
			continue;

		// Check alive
		if (KFPH.Health <= 0 || !KFPH.IsAliveAndWell())
			continue;

		// Check range
		if (VSizeSq(KFPH.Location - DamageInstigator.Pawn.Location) <= RadiusSq)
		{
			KFPH.HealDamage(default.TeamHealAmount[upgLevel - 1], DamageInstigator, class'KFDT_Healing');
		}
	}
}

// ===================================================================
// Find Parasite Perk Helper
// ===================================================================
static function ZTUpgrade_Perk_Parasite_Helper GetParasiteHelper(Pawn OwnerPawn)
{
	local ZTUpgrade_Perk_Parasite_Helper PHelper;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Perk_Parasite_Helper', PHelper)
			return PHelper;
	}

	return None;
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Transfusion]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Transfusion"

	UpgradeName="Transfusion"
	UpgradeDescription(0)="<font color=\"#B40028\">Transfusion:</font> Killing <font color=\"#FF6464\">siphoned</font> enemies heals all teammates within <font color=\"#FFFFFF\">8m</font> for <font color=\"#FFFFFF\">8</font> HP"
	UpgradeDescription(1)="<font color=\"#FFD700\">[DELUXE]</font> <font color=\"#B40028\">Transfusion:</font> Killing <font color=\"#FF6464\">siphoned</font> enemies heals all teammates within <font color=\"#FFFFFF\">12m</font> for <font color=\"#FFFFFF\">18</font> HP"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Transfusion'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Transfusion_Deluxe'

	Name="Default__ZTUpgrade_Skill_Transfusion"
}
