// Unwavering Faith
// You cannot be grabbed by Clots
// Standard & Deluxe: Immune to Clot grab
class ZTUpgrade_Skill_UnwaveringFaith extends ZTUpgrade_Skill;

static function bool CanNotBeGrabbed(int upgLevel, KFPawn OwnerPawn)
{
	return True;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_UnwaveringFaith]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_UnwaveringFaith"

	UpgradeName="Unwavering Faith"
	UpgradeDescription(0)="You <font color=\"#eeeeff\">cannot be grabbed</font> by Clots"
	UpgradeDescription(1)="<font color=\"#ffd700\">Deluxe.</font> You <font color=\"#eeeeff\">cannot be grabbed</font> by Clots"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_UnwaveringFaith'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_UnwaveringFaith_Deluxe'

	Name="Default__ZTUpgrade_Skill_UnwaveringFaith"
}
