// ===================================================================
// ZTUpgrade_Skill_Contagion - Infectious Siphon
// Siphoned enemies passively spread siphon to nearby non-siphoned
// enemies through proximity. The infection spreads through the horde
// naturally. Let enemies cluster before engaging.
//
// Standard: 3m spread radius, checks every 2 seconds
// Deluxe:   5m spread radius, checks every 1.5 seconds
//
// All logic handled by helper class that runs periodic proximity
// checks against the Parasite perk helper's siphon list.
//
// REQUIRES: ZTUpgrade_Perk_Parasite_Helper must expose:
//   - GetSiphonedEnemies(out array<KFPawn_Monster>) : void
//   - IsSiphoned(KFPawn_Monster) : bool
//   - ApplySiphonToTarget(KFPawn_Monster) : void
//   - GetSiphonedEnemyCount() : int
//   - GetMaxSiphons() : int
// ===================================================================
class ZTUpgrade_Skill_Contagion extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> SpreadRadius;
var config array<float> SpreadInterval;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.SpreadRadius[0] = 300.0f;
		default.SpreadRadius[1] = 500.0f;
		default.SpreadInterval[0] = 2.0f;
		default.SpreadInterval[1] = 1.5f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.SpreadRadius.Length = 2;
		default.SpreadRadius[0] = 150.000000f;
		default.SpreadRadius[1] = 250.000000f;
		default.SpreadInterval.Length = 2;
		default.SpreadInterval[0] = 2.000000f;
		default.SpreadInterval[1] = 1.500000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// ===================================================================
// Helper Management
// ===================================================================
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_Contagion_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Contagion_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
		{
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_Contagion_Helper', OwnerPawn);
			if (UPG != None)
			{
				UPG.SpreadRadius = default.SpreadRadius[upgLevel - 1];
				UPG.SpreadInterval = default.SpreadInterval[upgLevel - 1];
				UPG.StartSpreadTimer();
			}
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_Contagion_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_Contagion_Helper', UPG)
			UPG.Destroy();
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Contagion]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Contagion"

	UpgradeName="Contagion"
	UpgradeDescription(0)="<font color=\"#B40028\">Contagion:</font> <font color=\"#FF6464\">Siphoned</font> enemies passively spread siphon to non-siphoned enemies within <font color=\"#FFFFFF\">1.5m</font> every <font color=\"#FFFFFF\">2s</font>"
	UpgradeDescription(1)="<font color=\"#FFD700\">[DELUXE]</font> <font color=\"#B40028\">Contagion:</font> <font color=\"#FF6464\">Siphoned</font> enemies passively spread siphon to non-siphoned enemies within <font color=\"#FFFFFF\">2.5m</font> every <font color=\"#FFFFFF\">1.5s</font>"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Contagion'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Contagion_Deluxe'

	Name="Default__ZTUpgrade_Skill_Contagion"
}
