// ===================================================================
// ZTUpgrade_Skill_BloodTithe
//
// "Blood Tithe"
// At wave start, sacrifice 10 HP. If you complete the prophecy,
// gain permanent max HP.
//
// Standard: sacrifice 10, gain +15 max HP on success (net +5)
// Deluxe:   sacrifice 10, gain +20 max HP on success (net +10)
// ===================================================================
class ZTUpgrade_Skill_BloodTithe extends ZTUpgrade_Skill;

// --- Helper spawning ---
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local ZTUpgrade_Skill_BloodTithe_Helper H;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == ROLE_Authority)
    {
        bFound = false;
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_BloodTithe_Helper', H)
        {
            bFound = true;
            H.Initialize(upgLevel);
            break;
        }

        if (!bFound)
        {
            H = OwnerPawn.Spawn(class'ZTUpgrade_Skill_BloodTithe_Helper', OwnerPawn);
            if (H != None)
                H.Initialize(upgLevel);
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_BloodTithe_Helper H;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_BloodTithe_Helper', H)
        {
            H.Cleanup();
            H.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_BloodTithe]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_BloodTithe"

    UpgradeName="Blood Tithe"
    UpgradeDescription(0)="At wave start, <font color=\"#ff0000\">sacrifice 10 HP</font>. Complete the prophecy to gain <font color=\"#15d7fa\">+15 permanent max HP</font> <font color=\"#77d914\">(net +5)</font>."
    UpgradeDescription(1)="At wave start, <font color=\"#ff0000\">sacrifice 10 HP</font>. Complete the prophecy to gain <font color=\"#15d7fa\">+20 permanent max HP</font> <font color=\"#77d914\">(net +10)</font>."

    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_BloodTithe_Deluxe'

    Name="Default__ZTUpgrade_Skill_BloodTithe"
}
