class ZTUpgrade_Skill_FireEater extends ZTUpgrade_Skill config(ZedternalUnlimited);

// Fire Eater: Increases healing received from all sources.
// Standard: +25% healing received.
// Deluxe:   +60% healing received.

var config array<float> Healing;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Healing[0] = 0.25f;
		default.Healing[1] = 0.6f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Healing.Length = 2;
		default.Healing[0] = 0.150000f;
		default.Healing[1] = 0.300000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyHealAmount(out float InHealAmount, float DefaultHealAmount, int upgLevel)
{
	InHealAmount += DefaultHealAmount * default.Healing[upgLevel - 1];
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_FireEater]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_FireEater"

	UpgradeName="FireEater"
	upgradeDescription(0)="<font color=\"#42e087\">Increase</font> <font color=\"#42e087\">healing received</font> from all sources by <font color=\"#84d6d0\">15%</font>."
	upgradeDescription(1)="<font color=\"#42e087\">Increase</font> <font color=\"#42e087\">healing received</font> from all sources by <font color=\"#84d6d0\">30%</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FireEater'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FireEater_Deluxe'

	Name="Default__ZTUpgrade_Skill_FireEater"
}
