class ZTUpgrade_Skill_Firefighter extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<int> Dosh;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Dosh[0] = 3;
		default.Dosh[1] = 6;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Dosh.Length = 2;
		default.Dosh[0] = 2;
		default.Dosh[1] = 3;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
        if((((MyKFPM != None && KFPawn_ZedHusk(MyKFPM) != None) && MyKFPM.IsAliveAndWell()) && (MyKFPM.Health - InDamage) <= 0) && DamageInstigator != none)
		{
		KFPlayerReplicationInfo(DamageInstigator.PlayerReplicationInfo).AddDosh(default.Dosh[upgLevel - 1]);
        }
		//return; 
}

defaultproperties

{    
	
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Firefighter]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Firefighter"

	UpgradeName="Firefighter"
	upgradeDescription(0)="Gain <font color=\"#ff3399\">2</font> extra dosh for every <font color=\"#66cc00\">Husk</font> you kill."
    upgradeDescription(1)="Gain <font color=\"#ff3399\">3</font> extra dosh for every <font color=\"#66cc00\">Husk</font> you kill."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Firefighter'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Firefighter_Deluxe'
    Name="Default__ZTUpgrade_Skill_Firefighter"
}