// ===================================================================
// ZTUpgrade_Skill_LifeTap - Siphon-Powered Healing
// Your medic dart/syringe recharge rate scales with your current
// siphon count. More siphoned enemies = faster healing dart recharge.
//
// Uses a replicated helper to pass siphon count to the client,
// then ModifyHealerRechargeTime reads it via GetALocalPlayerController.
//
// Standard: -6% recharge time per siphoned enemy (max 8 = -48%)
// Deluxe:   -10% recharge time per siphoned enemy (max 8 = -80%)
//
// REQUIRES: ZTUpgrade_Perk_Parasite_Helper must expose:
//   - GetSiphonedEnemyCount() : int
// ===================================================================
class ZTUpgrade_Skill_LifeTap extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> RechargeReductionPerSiphon;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.RechargeReductionPerSiphon[0] = 0.06f;
		default.RechargeReductionPerSiphon[1] = 0.10f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.RechargeReductionPerSiphon.Length = 2;
		default.RechargeReductionPerSiphon[0] = 0.060000f;
		default.RechargeReductionPerSiphon[1] = 0.100000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// ===================================================================
// Reduce healer recharge time based on replicated siphon count
// ===================================================================
static simulated function ModifyHealerRechargeTime(out float InRechargeTime, float DefaultRechargeTime, int upgLevel)
{
	local PlayerController PC;
	local ZTUpgrade_Skill_LifeTap_Helper Helper;
	local float Reduction;

	PC = class'WorldInfo'.static.GetWorldInfo().GetALocalPlayerController();
	if (PC == None || PC.Pawn == None)
		return;

	foreach PC.Pawn.ChildActors(class'ZTUpgrade_Skill_LifeTap_Helper', Helper)
	{
		if (Helper.ReplicatedSiphonCount > 0)
		{
			Reduction = default.RechargeReductionPerSiphon[upgLevel - 1] * float(Helper.ReplicatedSiphonCount);
			Reduction = FMin(Reduction, 0.85f);
			InRechargeTime *= (1.0f - Reduction);
		}
		break;
	}
}

// ===================================================================
// Helper Management
// ===================================================================
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_LifeTap_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_LifeTap_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			OwnerPawn.Spawn(class'ZTUpgrade_Skill_LifeTap_Helper', OwnerPawn);
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_LifeTap_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_LifeTap_Helper', UPG)
			UPG.Destroy();
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_LifeTap]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_LifeTap"

	UpgradeName="Life Tap"
	UpgradeDescription(0)="<font color=\"#B40028\">Life Tap:</font> <font color=\"#FFFFFF\">-6%</font> medic dart recharge per <font color=\"#FF6464\">siphoned</font> enemy (up to <font color=\"#FFFFFF\">-48%</font> at 8 siphons)"
	UpgradeDescription(1)="<font color=\"#FFD700\">[DELUXE]</font> <font color=\"#B40028\">Life Tap:</font> <font color=\"#FFFFFF\">-10%</font> medic dart recharge per <font color=\"#FF6464\">siphoned</font> enemy (up to <font color=\"#FFFFFF\">-80%</font> at 8 siphons)"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_LifeTap'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_LifeTap_Deluxe'

	Name="Default__ZTUpgrade_Skill_LifeTap"
}
