class ZTUpgrade_Skill_Heatstroke extends ZTUpgrade_Skill config(ZedternalUnlimited);

var const class<KFDamageType> DKDT;

var config array<float> DamageInc;
var config array<float> DamageFactor;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageInc[0] = 0.10f;
		default.DamageInc[1] = 0.20f;
		default.DamageFactor[0] = 0.10f;
		default.DamageFactor[1] = 0.20f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.DamageInc.Length = 2;
		default.DamageInc[0] = 0.100000f;
		default.DamageInc[1] = 0.200000f;
		default.DamageFactor.Length = 2;
		default.DamageFactor[0] = 0.100000f;
		default.DamageFactor[1] = 0.200000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (DamageType != None && DamageType != default.DKDT && DamageInstigator != None && MyKFPM != None)
    {
	  MyKFPM.ApplyDamageOverTime(int(float(DefaultDamage) * default.DamageFactor[upgLevel - 1]), DamageInstigator, default.DKDT);
	}
	// FIXED: Added missing closing parenthesis
	if (ClassIsChildOf(DamageType, class'KFDT_Fire'))
	{
	InDamage += Round(float(DefaultDamage) * (default.DamageInc[upgLevel - 1]));
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Heatstroke]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Heatstroke"

    DKDT=class'ZedternalTempered.ZTDT_Heatstroke'
    UpgradeName="Heatstroke"
	upgradeDescription(0)="All weapons apply <font color=\"e80948\">Heatstroke</font>, burning ZEDs and dealing <font color=\"#e85009\">minor Fire Damage</font>. You deal <font color=\"#e85009\">10%</font> more <font color=\"#e80948\">Fire Damage</font>."
	upgradeDescription(1)="All weapons apply <font color=\"e80948\">Heatstroke</font>, severely burning ZEDs and dealing <font color=\"#e85009\">major Fire Damage</font>. You deal <font color=\"#e85009\">20%</font> more <font color=\"#e80948\">Fire Damage</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Heatstroke'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Heatstroke_Deluxe'

	Name="Default__ZTUpgrade_Skill_Heatstroke"
}