// Divine Fortitude
// Increases both max health and max armor
// Standard: +10% health, +10% armor
// Deluxe: +25% health, +25% armor
class ZTUpgrade_Skill_DivineFortitude extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> HealthBonus, ArmorBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.HealthBonus[0] = 0.1f;
		default.HealthBonus[1] = 0.25f;
		default.ArmorBonus[0] = 0.1f;
		default.ArmorBonus[1] = 0.25f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.HealthBonus.Length = 2;
		default.HealthBonus[0] = 0.100000f;
		default.HealthBonus[1] = 0.250000f;
		default.ArmorBonus.Length = 2;
		default.ArmorBonus[0] = 0.100000f;
		default.ArmorBonus[1] = 0.250000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyHealth(out int InHealth, int DefaultHealth, int upgLevel)
{
	InHealth += Round(float(DefaultHealth) * default.HealthBonus[upgLevel - 1]);
}

static function ModifyArmor(out int MaxArmor, int DefaultArmor, int upgLevel)
{
	MaxArmor += Round(float(DefaultArmor) * default.ArmorBonus[upgLevel - 1]);
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_DivineFortitude]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_DivineFortitude"

	UpgradeName="Divine Fortitude"
	UpgradeDescription(0)="Increase <font color=\"#ff6666\">Max Health</font> and <font color=\"#4444ff\">Max Armor</font> by <font color=\"#eeeeff\">10%</font>"
	UpgradeDescription(1)="<font color=\"#ffd700\">Deluxe.</font> Increase <font color=\"#ff6666\">Max Health</font> and <font color=\"#4444ff\">Max Armor</font> by <font color=\"#eeeeff\">25%</font>"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_DivineFortitude'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_DivineFortitude_Deluxe'

	Name="Default__ZTUpgrade_Skill_DivineFortitude"
}
