class ZTUpgrade_Skill_IceArmor extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<int> ArmorBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ArmorBonus[0] = 10;
		default.ArmorBonus[1] = 20;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.ArmorBonus.Length = 2;
		default.ArmorBonus[0] = 10;
		default.ArmorBonus[1] = 20;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local ZTUpgrade_Skill_IceArmor_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_IceArmor_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_IceArmor_Helper', OwnerPawn);
            UPG.bDeluxe = (upgLevel > 1);
            UPG.UpgradeLevel = upgLevel;
        }
    }
}

static function ModifyArmor(out int InArmor, int DefaultArmor, int upgLevel)
{
    InArmor += default.ArmorBonus[upgLevel - 1];
}

static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    local ZTUpgrade_Skill_IceArmor_Helper UPG;

    if (OwnerPawn != None && InDamage > 0)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_IceArmor_Helper', UPG)
        {
            UPG.OnDamageTaken();
            break;
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_IceArmor_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_IceArmor_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_IceArmor]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_IceArmor"

    UpgradeName="Ice Armor"
    upgradeDescription(0)="Gain <font color=\"#87CEEB\">10</font> additional <font color=\"#77d914\">Armor Points</font> that regenerate <font color=\"#15d7fa\">1 point</font> every <font color=\"#FFAA33\">3 seconds</font> out of combat."
    upgradeDescription(1)="Gain <font color=\"#87CEEB\">20</font> additional <font color=\"#77d914\">Armor Points</font> that regenerate <font color=\"#15d7fa\">1 point</font> every <font color=\"#FFAA33\">3 seconds</font> out of combat."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_IceArmor'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_IceArmor_Deluxe'

    Name="Default__ZTUpgrade_Skill_IceArmor"
}