class ZTUpgrade_Skill_AdrenalineReload extends ZTUpgrade_Skill config(ZedternalUnlimited);

// Taking damage triggers an adrenaline rush: faster reload and movement
// Rewards aggressive/risky play and helps recover from bad positioning

var config array<float> ReloadBonus;  // Reload speed bonus during boost
var config array<float> SpeedBonus;   // Movement speed bonus during boost
var config array<float> BoostDuration;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ReloadBonus[0] = 0.30f;
		default.ReloadBonus[1] = 0.60f;
		default.SpeedBonus[0] = 0.10f;
		default.SpeedBonus[1] = 0.20f;
		default.BoostDuration[0] = 4.0f;
		default.BoostDuration[1] = 6.0f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.ReloadBonus.Length = 2;
		default.ReloadBonus[0] = 0.150000f;
		default.ReloadBonus[1] = 0.300000f;
		default.SpeedBonus.Length = 2;
		default.SpeedBonus[0] = 0.100000f;
		default.SpeedBonus[1] = 0.200000f;
		default.BoostDuration.Length = 2;
		default.BoostDuration[0] = 4.000000f;
		default.BoostDuration[1] = 6.000000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
	local ZTUpgrade_Skill_AdrenalineReload_Helper UPG;

	if (OwnerPawn != None && InDamage > 0)
	{
		UPG = GetHelper(OwnerPawn);
		if (UPG != None)
			UPG.ActivateBoost(default.BoostDuration[upgLevel - 1]);
	}
}

static simulated function GetReloadRateScale(out float InReloadRateScale, int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_AdrenalineReload_Helper UPG;

	UPG = GetHelper(OwnerPawn);
	if (UPG != None && UPG.bBoosted)
		InReloadRateScale = 1.0f / (1.0f / InReloadRateScale + default.ReloadBonus[upgLevel - 1]);
}

static simulated function ModifySpeed(out float InSpeed, float DefaultSpeed, int upgLevel, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_AdrenalineReload_Helper UPG;

	UPG = GetHelper(OwnerPawn);
	if (UPG != None && UPG.bBoosted)
		InSpeed += DefaultSpeed * default.SpeedBonus[upgLevel - 1];
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_AdrenalineReload_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_AdrenalineReload_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_AdrenalineReload_Helper', OwnerPawn);
	}
}

static simulated function ZTUpgrade_Skill_AdrenalineReload_Helper GetHelper(KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_AdrenalineReload_Helper UPG;

	if (KFPawn_Human(OwnerPawn) != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_AdrenalineReload_Helper', UPG)
		{
			return UPG;
		}

		if (OwnerPawn.Role == Role_Authority)
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_AdrenalineReload_Helper', OwnerPawn);
	}

	return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_AdrenalineReload_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_AdrenalineReload_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_AdrenalineReload]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_AdrenalineReload"

	UpgradeName="Adrenaline Reload"

	UpgradeDescription(0)="<font color=\"#DAA520\">Adrenaline Reload:</font> Taking damage grants <font color=\"#87CEEB\">+15% reload speed</font> and <font color=\"#87CEEB\">+10% movement speed</font> for <font color=\"#FFFFFF\">4</font> seconds"
	UpgradeDescription(1)="<font color=\"#FFD700\">Adrenaline Reload:</font> Taking damage grants <font color=\"#87CEEB\">+30% reload speed</font> and <font color=\"#87CEEB\">+20% movement speed</font> for <font color=\"#FFFFFF\">6</font> seconds"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AdrenalineReload'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AdrenalineReload_Deluxe'

	Name="Default__ZTUpgrade_Skill_AdrenalineReload"
}
