class ZTUpgrade_Skill_OdeToGreed extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> Health;
var config array<int> Dosh;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Health[0] = 0.25f;
		default.Health[1] = 0.50f;
		default.Dosh[0] = 250;
		default.Dosh[1] = 500;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Health.Length = 2;
		default.Health[0] = 0.500000f;
		default.Health[1] = 0.800000f;
		default.Dosh.Length = 2;
		default.Dosh[0] = 250;
		default.Dosh[1] = 400;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}




static function WaveEnd(int upgLevel, KFPlayerController KFPC)
{
    if(KFPC != none)
    {
        KFPlayerReplicationInfo(KFPC.PlayerReplicationInfo).AddDosh(default.Dosh[upgLevel - 1]);
    }
}

static function ModifyHealth(out int InHealth, int DefaultHealth, int upgLevel)
{
	InHealth -= (DefaultHealth * default.Health[upgLevel - 1]);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_OdeToGreed]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_OdeToGreed"

    UpgradeName="Ode to Greed"
	upgradeDescription(0)="<font color=\"#962ab9\">Decrease</font> your <font color=\"#962ab9\">Maximum Health</font> by <font color=\"#cb1b43\">50</font>. At the start of each wave you gain <font color=\"#84d6d0\">250 Dosh</font>."
	upgradeDescription(1)="<font color=\"#962ab9\">Decrease</font> your <font color=\"#962ab9\">Maximum Health</font> by <font color=\"#cb1b43\">80</font>. At the start of each wave you gain <font color=\"#84d6d0\">400 Dosh</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_OdeToGreed'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_OdeToGreed_Deluxe'
	Name="Default__ZTUpgrade_Skill_OdeToGreed"
}