class ZTUpgrade_Skill_FiredUp extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> ReloadRate;
var config array<float> MagSize;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ReloadRate[0] = 0.15f;
		default.ReloadRate[1] = 0.30f;
		default.MagSize[0] = 0.40f;
		default.MagSize[1] = 0.60f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.ReloadRate.Length = 2;
		default.ReloadRate[0] = 0.075000f;
		default.ReloadRate[1] = 0.150000f;
		default.MagSize.Length = 2;
		default.MagSize[0] = 0.400000f;
		default.MagSize[1] = 0.600000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function GetReloadRateScale( out float InReloadRateScale, int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	InReloadRateScale = 1.f / (1.f/InReloadRateScale + (default.ReloadRate[upgLevel - 1]));
}


static simulated function ModifyMagSizeAndNumber( out int InMagazineCapacity, int DefaultMagazineCapacity, int upgLevel, KFWeapon KFW, optional array< Class<KFPerk> > WeaponPerkClass, optional bool bSecondary=false, optional name WeaponClassname )
{
	InMagazineCapacity += Round(float(DefaultMagazineCapacity) * (default.MagSize[upgLevel - 1]));
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_FiredUp]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_FiredUp"

    UpgradeName="Fired Up"
	upgradeDescription(0)="Increase your <font color=\"e80948\">Reload Speed</font> by <font color=\"#e85009\">7.5%</font> and your <font color=\"e80948\">Magazine Size</font> by <font color=\"#e85009\">40%</font>."
	upgradeDescription(1)="Increase your <font color=\"e80948\">Reload Speed</font> by <font color=\"#e85009\">15%</font> and your <font color=\"e80948\">Magazine Size</font> by <font color=\"#e85009\">60%</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FiredUp'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_FiredUp_Deluxe'

	Name="Default__ZTUpgrade_Skill_FiredUp"
}