// ===================================================================
// ZTUpgrade_Skill_RegenerativeMembrane
// The hivemind's outer membrane pulses with restorative enzymes
// when the host stands still - a living cocoon that knits wounds
// shut. But break the trance, and the membrane needs time to
// re-form before it can heal again.
//
// Normal: Heal 1 HP/sec while stationary.
//         Moving after healing triggers 60 second cooldown.
// Deluxe: Heal 2 HP/sec + 1 armor/sec while stationary.
//         Moving after healing triggers 60 second cooldown.
// ===================================================================
class ZTUpgrade_Skill_RegenerativeMembrane extends ZTUpgrade_Skill;

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_RegenerativeMembrane_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_RegenerativeMembrane_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
		{
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_RegenerativeMembrane_Helper', OwnerPawn);
			UPG.bDeluxe = (upgLevel > 1);
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_RegenerativeMembrane_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_RegenerativeMembrane_Helper', UPG)
		{
			UPG.Destroy();
		}
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_RegenerativeMembrane]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_RegenerativeMembrane"

	UpgradeName="Regenerative Membrane"
	UpgradeDescription(0)="Heal <font color=\"#42e087\">1 HP/sec</font> while <font color=\"#F0F8FF\">standing still</font>. Moving after healing triggers a <font color=\"#FFAA00\">60 second cooldown</font>."
	UpgradeDescription(1)="Heal <font color=\"#42e087\">2 HP/sec</font> and <font color=\"#4444ff\">1 armor/sec</font> while <font color=\"#F0F8FF\">standing still</font>. Moving after healing triggers a <font color=\"#FFAA00\">60 second cooldown</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_RegenerativeMembrane'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_RegenerativeMembrane_Deluxe'

	Name="Default__ZTUpgrade_Skill_RegenerativeMembrane"
}
