class ZTUpgrade_Skill_ThickSkin extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> Damage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Damage[0] = 0.20f;
		default.Damage[1] = 0.40f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Damage.Length = 2;
		default.Damage[0] = 0.100000f;
		default.Damage[1] = 0.200000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageTaken(out int InDamage, int DefaultDamage, int upgLevel, KFPawn OwnerPawn, optional class<DamageType> DamageType, optional Controller InstigatedBy, optional KFWeapon MyKFW)
{
    if(KFAIController_ZedBloat(InstigatedBy) != None)
    {
        InDamage -= Round(float(DefaultDamage) * default.Damage[upgLevel - 1]);    
    }
}

defaultproperties

{    
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_ThickSkin]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_ThickSkin"

	UpgradeName="Thick Skin"
    upgradeDescription(0)="You take <font color=\"#ff3399\">10%</font> less <font color=\"#7ed8d5\">Damage</font> from <font color=\"#f923be\">Bloats</font>."
    upgradeDescription(1)="You take <font color=\"#ff3399\">20%</font> less <font color=\"#7ed8d5\">Damage</font> from <font color=\"#f923be\">Bloats</font>."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ThickSkin'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_ThickSkin_Deluxe'
    Name="Default__ZTUpgrade_Skill_ThickSkin"
}
