// ===================================================================
// ZTUpgrade_Skill_LeechField - Stationary Drain Aura
// Standing still for 2+ seconds creates a damage aura around you.
// Enemies inside take tick damage and you heal from it. Moving
// cancels the field. Holdout-style defensive vampire turret.
//
// Standard: 6m radius, 8 damage/tick (1s), heal 50% of damage dealt
// Deluxe:   8m radius, 15 damage/tick (1s), heal 100% of damage dealt
//
// All logic handled by helper class.
// ===================================================================
class ZTUpgrade_Skill_LeechField extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> FieldRadius;
var config array<int> DamagePerTick;
var config array<float> HealPercent;
var config float StationaryDelay;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.FieldRadius[0] = 600.0f;
		default.FieldRadius[1] = 800.0f;
		default.DamagePerTick[0] = 8;
		default.DamagePerTick[1] = 15;
		default.HealPercent[0] = 0.50f;
		default.HealPercent[1] = 1.00f;
		default.StationaryDelay = 2.0f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.FieldRadius.Length = 2;
		default.FieldRadius[0] = 300.000000f;
		default.FieldRadius[1] = 400.000000f;
		default.DamagePerTick.Length = 2;
		default.DamagePerTick[0] = 8;
		default.DamagePerTick[1] = 15;
		default.HealPercent.Length = 2;
		default.HealPercent[0] = 0.500000f;
		default.HealPercent[1] = 1.000000f;
		default.StationaryDelay = 2.000000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


// ===================================================================
// Helper Management
// ===================================================================
static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
	local ZTUpgrade_Skill_LeechField_Helper UPG;
	local bool bFound;

	if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
	{
		bFound = False;
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_LeechField_Helper', UPG)
		{
			bFound = True;
			break;
		}

		if (!bFound)
		{
			UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_LeechField_Helper', OwnerPawn);
			if (UPG != None)
			{
				UPG.FieldRadius = default.FieldRadius[upgLevel - 1];
				UPG.DamagePerTick = default.DamagePerTick[upgLevel - 1];
				UPG.HealPercent = default.HealPercent[upgLevel - 1];
				UPG.StationaryDelay = default.StationaryDelay;
			}
		}
	}
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
	local ZTUpgrade_Skill_LeechField_Helper UPG;

	if (OwnerPawn != None)
	{
		foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_LeechField_Helper', UPG)
			UPG.Destroy();
	}
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_LeechField]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_LeechField"

	UpgradeName="Leech Field"
	UpgradeDescription(0)="<font color=\"#B40028\">Leech Field:</font> Stand still <font color=\"#FFFFFF\">2s</font> to create a <font color=\"#FFFFFF\">3m</font> drain aura. Enemies take <font color=\"#FFFFFF\">8</font> damage/s. You heal for <font color=\"#FFFFFF\">50%</font> of damage dealt. Moving cancels"
	UpgradeDescription(1)="<font color=\"#FFD700\">[DELUXE]</font> <font color=\"#B40028\">Leech Field:</font> Stand still <font color=\"#FFFFFF\">2s</font> to create an <font color=\"#FFFFFF\">4m</font> drain aura. Enemies take <font color=\"#FFFFFF\">15</font> damage/s. You heal for <font color=\"#FFFFFF\">100%</font>. Moving cancels"

	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_LeechField'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_LeechField_Deluxe'

	Name="Default__ZTUpgrade_Skill_LeechField"
}
