class ZTUpgrade_Skill_HuntDown extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> DamagePerStack;
var config int MaxStacks;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamagePerStack[0] = 0.05f;
		default.DamagePerStack[1] = 0.10f;
		default.MaxStacks = 5;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.DamagePerStack.Length = 2;
		default.DamagePerStack[0] = 0.030000f;
		default.DamagePerStack[1] = 0.050000f;
		default.MaxStacks = 5;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local ZTUpgrade_Skill_HuntDown_Helper UPG;
    local int CurrentStacks;
    
    if (DamageInstigator == None || DamageInstigator.Pawn == None)
        return;
    
    if (MyKFPM == None)
        return;
    
    UPG = GetHelper(DamageInstigator.Pawn);
    if (UPG == None)
        return;
    
    // Register the hit and get current stack count
    CurrentStacks = UPG.RegisterHit(MyKFPM, default.MaxStacks);
    
    // Apply damage bonus based on stacks (stacks from previous hits, not this one)
    if (CurrentStacks > 0)
    {
        InDamage += Round(float(DefaultDamage) * default.DamagePerStack[upgLevel - 1] * float(CurrentStacks));
    }
}

static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local ZTUpgrade_Skill_HuntDown_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_HuntDown_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_HuntDown_Helper', OwnerPawn);
        }
    }
}

static function ZTUpgrade_Skill_HuntDown_Helper GetHelper(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_HuntDown_Helper UPG;

    if (KFPawn_Human(OwnerPawn) != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_HuntDown_Helper', UPG)
        {
            return UPG;
        }

        // Should have one
        UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_HuntDown_Helper', OwnerPawn);
    }

    return UPG;
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_HuntDown_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_HuntDown_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{

    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_HuntDown]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_HuntDown"

    UpgradeName="Hunt Down"
    upgradeDescription(0)="Consecutive hits on the <font color=\"#ff3399\">same enemy</font> deal <font color=\"#66cc00\">+3%</font> more damage per hit. Max <font color=\"#ffff00\">3</font> stacks (<font color=\"#ff3399\">+25%</font>)."
    upgradeDescription(1)="Consecutive hits on the <font color=\"#ff3399\">same enemy</font> deal <font color=\"#66cc00\">+5%</font> more damage per hit. Max <font color=\"#ffff00\">5</font> stacks (<font color=\"#ff3399\">+50%</font>)."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HuntDown'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_HuntDown_Deluxe'

    Name="Default__ZTUpgrade_Skill_HuntDown"
}
