class ZTUpgrade_Skill_Permafrost extends ZTUpgrade_Skill config(ZedternalUnlimited);

// Theme: "Permafrost" - The stillness of absolute zero steadies your aim
// Reduces weapon recoil and spread for improved precision

var config array<float> Recoil;
var config array<float> Spread;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.Recoil[0] = 0.30f;
		default.Recoil[1] = 0.60f;
		default.Spread[0] = 0.30f;
		default.Spread[1] = 0.60f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.Recoil.Length = 2;
		default.Recoil[0] = 0.300000f;
		default.Recoil[1] = 0.600000f;
		default.Spread.Length = 2;
		default.Spread[0] = 0.300000f;
		default.Spread[1] = 0.600000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function ModifyRecoil(out float InRecoilModifier, float DefaultRecoilModifier, int upgLevel, KFWeapon KFW)
{
    InRecoilModifier -= DefaultRecoilModifier * default.Recoil[upgLevel - 1];
}

static simulated function ModifySpread(out float InSpreadModifier, float DefaultSpreadModifier, int upgLevel, KFWeapon KFW)
{
    InSpreadModifier -= DefaultSpreadModifier * default.Spread[upgLevel - 1];
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Permafrost]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Permafrost"

    UpgradeName="Permafrost"
    upgradeDescription(0)="The stillness of absolute zero steadies your aim. Reduce <font color=\"#87CEEB\">Recoil</font> and <font color=\"#15d7fa\">Weapon Spread</font> by <font color=\"#77d914\">30%</font>."
    upgradeDescription(1)="The stillness of absolute zero steadies your aim. Reduce <font color=\"#87CEEB\">Recoil</font> and <font color=\"#15d7fa\">Weapon Spread</font> by <font color=\"#77d914\">60%</font>."
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Permafrost'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Permafrost_Deluxe'

    Name="Default__ZTUpgrade_Skill_Permafrost"
}
