class ZTUpgrade_Skill_AssetLiquidation extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config array<float> DamagePercentage;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamagePercentage[0] = 0.01f;
		default.DamagePercentage[1] = 0.02f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.DamagePercentage.Length = 2;
		default.DamagePercentage[0] = 0.010000f;
		default.DamagePercentage[1] = 0.020000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static simulated function InitiateWeapon(int upgLevel, KFWeapon KFW, KFPawn OwnerPawn)
{
    local ZTUpgrade_Skill_AssetLiquidation_Helper UPG;
    local bool bFound;

    if (KFPawn_Human(OwnerPawn) != None && OwnerPawn.Role == Role_Authority)
    {
        bFound = False;
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_AssetLiquidation_Helper', UPG)
        {
            bFound = True;
            break;
        }

        if (!bFound)
        {
            UPG = OwnerPawn.Spawn(class'ZTUpgrade_Skill_AssetLiquidation_Helper', OwnerPawn);
            UPG.bDeluxe = (upgLevel > 1);
            UPG.UpgradeLevel = upgLevel;
        }
    }
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
    local ZTUpgrade_Skill_AssetLiquidation_Helper UPG;
    local int TrackedDamage;

    // Track damage dealt with weapons. Cap the tracked amount to the zed's CURRENT
    // health: real "damage dealt" can never exceed what the target had. This closes the
    // InstaKill special-wave exploit -- that wave forces every hit's InDamage to
    // 9,999,999, which otherwise accumulated into millions of liquidation dosh -- while
    // leaving normal sub-lethal hits unchanged, since the cap only binds on overkill.
    if (MyKFW != None && MyKFPM != None && DamageInstigator != None && DamageInstigator.Pawn != None)
    {
        TrackedDamage = Min(InDamage, MyKFPM.Health);
        if (TrackedDamage > 0)
        {
            foreach DamageInstigator.Pawn.ChildActors(class'ZTUpgrade_Skill_AssetLiquidation_Helper', UPG)
            {
                UPG.TrackWeaponDamage(MyKFW, TrackedDamage);
                break;
            }
        }
    }
}

static simulated function DeleteHelperClass(Pawn OwnerPawn)
{
    local ZTUpgrade_Skill_AssetLiquidation_Helper UPG;

    if (OwnerPawn != None)
    {
        foreach OwnerPawn.ChildActors(class'ZTUpgrade_Skill_AssetLiquidation_Helper', UPG)
        {
            UPG.Destroy();
        }
    }
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_AssetLiquidation]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_AssetLiquidation"

    UpgradeName="Asset Liquidation"
    
    upgradeDescription(0)="Selling a weapon grants dosh equal to <font color=\"#ffaa33\">1%</font> of <font color=\"#ff6600\">damage dealt</font> with it this wave."
    upgradeDescription(1)="Selling a weapon grants dosh equal to <font color=\"#ffaa33\">2%</font> of <font color=\"#ff6600\">damage dealt</font> with it this wave."
    
    UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AssetLiquidation'
    UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_AssetLiquidation_Deluxe'

    Name="Default__ZTUpgrade_Skill_AssetLiquidation"
}