class ZTUpgrade_Skill_Blaze extends ZTUpgrade_Skill config(ZedternalUnlimited);


var config array<float> DamageInc;
var config array<float> SpareAmmo;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DamageInc[0] = 0.30f;
		default.DamageInc[1] = 0.50f;
		default.SpareAmmo[0] = 0.40f;
		default.SpareAmmo[1] = 0.80f;

		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.DamageInc.Length = 2;
		default.DamageInc[0] = 0.300000f;
		default.DamageInc[1] = 0.500000f;
		default.SpareAmmo.Length = 2;
		default.SpareAmmo[0] = 0.400000f;
		default.SpareAmmo[1] = 0.800000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}


static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (IsWeaponOnSpecificPerk(MyKFW, class'KFGame.KFPerk_Firebug') || IsDamageTypeOnSpecificPerk(DamageType, class'KFGame.KFPerk_Firebug'))
		InDamage += Round(float(DefaultDamage) * (default.DamageInc[upgLevel - 1]));
}

static simulated function ModifySpareAmmoAmount( out int InSpareAmmo, int DefaultSpareAmmo, int upgLevel, KFWeapon KFW, optional const out STraderItem TraderItem, optional bool bSecondary=false )
{
		InSpareAmmo += Round(float(DefaultSpareAmmo) * (default.SpareAmmo[upgLevel - 1]));
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Blaze]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Blaze"

    UpgradeName="Blaze"
	upgradeDescription(0)="You deal <font color=\"#e85009\">30%</font> more Damage with <font color=\"#e80948\">Firebug Weapons</font>. Increase your <font color=\"#e80948\">SpareAmmo</font> by <font color=\"#e85009\">40%.</font>"
	upgradeDescription(1)="You deal <font color=\"#e85009\">50%</font> more Damage with <font color=\"#e80948\">Firebug Weapons</font>. Increase your <font color=\"#e80948\">SpareAmmo</font> by <font color=\"#e85009\">80%.</font>"
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Blaze'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Blaze_Deluxe'

	Name="Default__ZTUpgrade_Skill_Blaze"
}