// ===================================================================
// ZTUpgrade_Skill_Headhunter
// Hollow Skill — unlocks the Headhunter weapon upgrade in the trader.
// Headhunter: bonus headshot damage.
// Deluxe: stronger variant.
// ===================================================================
class ZTUpgrade_Skill_Headhunter extends ZTUpgrade_Skill config(ZedternalUnlimited);

var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTUpgrade_Skill_Headhunter]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTUpgrade_Skill_Headhunter"

	UpgradeName="Headhunter"
	UpgradeDescription(0)="Unlocks the <font color=\"#00CCFF\">Headhunter</font> weapon upgrade in the trader for all your weapons. Headhunter deals bonus <font color=\"#6B0099\">headshot damage</font>."
	UpgradeDescription(1)="Upgrades your <font color=\"#00CCFF\">Headhunter</font> weapon upgrade to its <font color=\"#6B0099\">Deluxe</font> variant, increasing its potency."
	UpgradeIcon(0)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Headhunter'
	UpgradeIcon(1)=Texture2D'ZedternalRBPerkpackage_Resources.Skills.UI_Skill_Headhunter_Deluxe'
	Name="Default__ZTUpgrade_Skill_Headhunter"
}
