// Void Infusion weapon upgrade — Deluxe tier
// +9% DoT scaler per level.
// L1=9%, L5=45%, L10=90%
class ZTWeaponUpg_VoidInfusion_Deluxe extends ZTWeaponUpg_HollowBase abstract config(ZedternalUnlimited);

var config float DoTBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.DoTBonus = 0.09f;
		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.DoTBonus = 0.090000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	return True;
}

static function ModifyDoTScaler(out float InDoTScaler, float DefaultDotScaler, int upgLevel, optional class<KFDamageType> KFDT, optional bool bNapalmInfected)
{
	InDoTScaler += DefaultDotScaler * default.DoTBonus * upgLevel;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTWeaponUpg_VoidInfusion_Deluxe]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTWeaponUpg_VoidInfusion_Deluxe"

	UpgradeName="Void Infusion (Deluxe)"
	UpgradeDescription(0)="Increases your <font color=\"#6B0099\">damage-over-time</font> intensity by <font color=\"#00CCFF\">+%x%%</font> per level."
	WeaponBonus=(baseValue=0, incValue=9, maxValue=-1)
	RequiredSkillClassPath="ZedternalTempered.ZTUpgrade_Skill_VoidInfusion"
	bRequiresDeluxe=True
	Name="Default__ZTWeaponUpg_VoidInfusion_Deluxe"
}
