class ZTWeaponUpg_HeadshotDamage extends ZTUpgrade_Weapon abstract config(ZedternalUnlimited);

var config float DamageBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 2)
	{
		default.DamageBonus = 0.2f;
		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.DamageBonus = 0.200000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 2;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	if (KFW.default.bMeleeWeapon)
		return False;
	return True;
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (MyKFPM != None && HitZoneIdx == 0)
		InDamage += Round(float(DefaultDamage) * default.DamageBonus * upgLevel);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTWeaponUpg_HeadshotDamage]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTWeaponUpg_HeadshotDamage"

	UpgradeName="Crackshot"
	UpgradeDescription(0)="Increases your <font color=\"#15d7fa\">headshot damage</font> by <font color=\"#77d914\">+%x%%</font> per level."
	WeaponBonus=(baseValue=0, incValue=20, maxValue=-1)
	Name="Default__ZTWeaponUpg_HeadshotDamage"
}
