class ZTWeaponUpg_Damage extends ZTUpgrade_Weapon abstract config(ZedternalUnlimited);

var config float DamageBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 2)
	{
		default.DamageBonus = 0.1f;
		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.DamageBonus = 0.100000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 2;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	return True;
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	`log("[DK_WEAPUPG_HIT] ZTWeaponUpg_Damage upgLevel="$upgLevel$" InDamage="$InDamage$" DefaultDamage="$DefaultDamage$" DamageBonus="$default.DamageBonus$" MyKFW="$MyKFW);
	InDamage += Round(float(DefaultDamage) * default.DamageBonus * upgLevel);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTWeaponUpg_Damage]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTWeaponUpg_Damage"

	UpgradeName="Sharpened Edge"
	UpgradeDescription(0)="Increases your <font color=\"#15d7fa\">weapon damage</font> by <font color=\"#77d914\">+%x%%</font> per level."
	WeaponBonus=(baseValue=0, incValue=10, maxValue=-1)
	Name="Default__ZTWeaponUpg_Damage"
}
