class ZTWeaponUpg_SpareAmmoSmall extends ZTUpgrade_Weapon abstract config(ZedternalUnlimited);

var config int AmmoFlat;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 2)
	{
		default.AmmoFlat = 2;
		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.AmmoFlat = 2;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 2;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	if (KFW.default.SpareAmmoCapacity[0] > 0 && KFW.default.SpareAmmoCapacity[0] < 8)
		return True;
	return False;
}

static simulated function ModifySpareAmmoAmount(out int InSpareAmmo, int DefaultSpareAmmo, int upgLevel, KFWeapon KFW, optional const out STraderItem TraderItem, optional bool bSecondary=False)
{
	local int Val;
	Val = default.AmmoFlat;
	if (Val <= 0) Val = 2;
	InSpareAmmo += Val * upgLevel;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTWeaponUpg_SpareAmmoSmall]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTWeaponUpg_SpareAmmoSmall"

	UpgradeName="Scavenger"
	UpgradeDescription(0)="Adds <font color=\"#77d914\">+%x</font> rounds to your <font color=\"#15d7fa\">spare ammo</font> per level. (small-capacity weapons)"
	WeaponBonus=(baseValue=0, incValue=2, maxValue=-1)
	Name="Default__ZTWeaponUpg_SpareAmmoSmall"
}
