class ZTWeaponUpg_Heal extends ZTUpgrade_Weapon abstract config(ZedternalUnlimited);

var config float HealBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 2)
	{
		default.HealBonus = 0.2f;
		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.HealBonus = 0.200000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 2;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	if (class<KFWeap_MedicBase>(KFW) != None)
		return True;
	return False;
}

static function ModifyHealAmount(out float InHealAmount, float DefaultHealAmount, int upgLevel)
{
	InHealAmount += DefaultHealAmount * default.HealBonus * upgLevel;
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTWeaponUpg_Heal]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTWeaponUpg_Heal"

	UpgradeName="Combat Medic"
	UpgradeDescription(0)="Increases the <font color=\"#15d7fa\">healing amount</font> of your medic weapon by <font color=\"#77d914\">+%x%%</font> per level."
	WeaponBonus=(baseValue=0, incValue=20, maxValue=-1)
	Name="Default__ZTWeaponUpg_Heal"
}
