// Void Sight weapon upgrade — base tier
// +4% damage per level while aiming down sights.
// L1=4%, L5=20%, L10=40%
class ZTWeaponUpg_VoidSight extends ZTWeaponUpg_HollowBase abstract config(ZedternalUnlimited);

var config float ADSBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.ADSBonus = 0.04f;
		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.ADSBonus = 0.040000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	return True;
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (MyKFW == None)
		return;

	if (!MyKFW.bUsingSights)
		return;

	InDamage += Round(float(DefaultDamage) * default.ADSBonus * upgLevel);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTWeaponUpg_VoidSight]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTWeaponUpg_VoidSight"

	UpgradeName="Void Sight"
	UpgradeDescription(0)="Deals <font color=\"#00CCFF\">+%x%%</font> additional damage while <font color=\"#6B0099\">aiming down sights</font> per level."
	WeaponBonus=(baseValue=0, incValue=4, maxValue=-1)
	RequiredSkillClassPath="ZedternalTempered.ZTUpgrade_Skill_VoidSight"
	bRequiresDeluxe=False
	Name="Default__ZTWeaponUpg_VoidSight"
}
