// Reaper's Edge weapon upgrade — Deluxe tier
// +5% bonus damage vs bosses per level.
// L1=5%, L5=25%, L10=50%
class ZTWeaponUpg_ReapersEdge_Deluxe extends ZTWeaponUpg_HollowBase abstract config(ZedternalUnlimited);

var config float BossBonus;
var config int MODEVERSION;

static function UpdateConfig()
{
	if (default.MODEVERSION < 1)
	{
		default.BossBonus = 0.05f;
		// BEGIN TEMPERED INI DEFAULTS (generated; do not edit by hand)
		default.BossBonus = 0.050000f;
		// END TEMPERED INI DEFAULTS
		default.MODEVERSION = 1;
		static.StaticSaveConfig();
	}
}

static function bool IsUpgradeCompatible(class<KFWeapon> KFW)
{
	return True;
}

static function ModifyDamageGiven(out int InDamage, int DefaultDamage, int upgLevel, optional Actor DamageCauser, optional KFPawn_Monster MyKFPM, optional KFPlayerController DamageInstigator, optional class<KFDamageType> DamageType, optional int HitZoneIdx, optional KFWeapon MyKFW)
{
	if (MyKFPM == None)
		return;

	if (!MyKFPM.Class.static.IsABoss())
		return;

	InDamage += Round(float(DefaultDamage) * default.BossBonus * upgLevel);
}

defaultproperties
{
    // --- Localization (auto-generated by mass_localize_dk_upgrades.py) ---
    // Strings live in KFGame/Localization/<lang>/ZedternalTempered.<langext>
    // Section: [ZTWeaponUpg_ReapersEdge_Deluxe]  -- see DKUpgrade_* base class for details.
    bShouldLocalize=True
    LocPackage="ZedternalTempered"
    LocSection="ZTWeaponUpg_ReapersEdge_Deluxe"

	UpgradeName="Reaper's Edge (Deluxe)"
	UpgradeDescription(0)="Deals <font color=\"#00CCFF\">+%x%%</font> additional damage to <font color=\"#6B0099\">bosses</font> per level."
	WeaponBonus=(baseValue=0, incValue=5, maxValue=-1)
	RequiredSkillClassPath="ZedternalTempered.ZTUpgrade_Skill_ReapersEdge"
	bRequiresDeluxe=True
	Name="Default__ZTWeaponUpg_ReapersEdge_Deluxe"
}
